### ISSUE TITLE
出现了报错

### ISSUE THREAD

**Issue by Xxxxhl** [PaddlePaddle/PaddleX#1000]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本
1.2.8
**问题描述**  
一训练就报错
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
RuntimeError: Failed to load model file , please make sure model file is saved with the following APIs: save_params, save_persistables, save_vars

**Comment by lailuboy** [comment]
出现这个错误外没有其他错误信息的话，一般是显存不够，可以调小batch_size参数重试
