### ISSUE TITLE
C++部署有把预测结果标记到图像的方法吗

### ISSUE THREAD

**Issue by BuLuoPiaoYu** [PaddlePaddle/PaddleX#1001]
找到下面这个方法，好像用不了，参数类型不对
![image](https://user-images.githubusercontent.com/54087448/127594907-1a89ea15-0a9d-45d1-b11d-6fa95b1cc279.png)

**Comment by lailuboy** [comment]
就是上面的方法，类型的话要与接口的类型一致

**Comment by FlyingQianMM** [comment]
1. 参照下面的代码
![image](https://user-images.githubusercontent.com/22235422/127948596-3189f232-2079-488b-a7e0-a425f5ac95c4.png)
将可视化的头文件include到自己的代码中
2. 目前我们给出的CMakeList.txt中时默认没有编译visualize的h和cpp文件， 需要自行在cmakelist里面加一下
![image](https://user-images.githubusercontent.com/22235422/127948459-147a3eab-4014-4120-8487-454c2bffe937.png) 
参考已给出的Cmakelist加下可视化代码所在的utils目录：
```
aux_source_directory(${PROJECT_ROOT_DIR}/model_deploy/utils/src DETECTOR_SRC)
```
3. 重新编辑即可
