### ISSUE TITLE
部署模型如何包含argmax算子？？现在部署的模型貌似不包含argmax。。。。。

### ISSUE THREAD

**Issue by lmmir** [PaddlePaddle/PaddleX#1002]
问题类型：模型部署
**问题描述**  

========================  

部署模型如何包含argmax算子？？现在部署的模型貌似不包含argmax。。。。。
部署模型如何包含argmax算子？？现在部署的模型貌似不包含argmax。。。。。
部署模型如何包含argmax算子？？现在部署的模型貌似不包含argmax。。。。。

**Comment by lailuboy** [comment]
是什么模型？如果模型中包含该算子，在训练后导出的部署模型中会包含。

**Comment by lmmir** [comment]
deeplabv3p

**Comment by lmmir** [comment]
> 是什么模型？如果模型中包含该算子，在训练后导出的部署模型中会包含。

deeplabv3p

**Comment by FlyingQianMM** [comment]
请问是paddlex训练导出的deeplabv3p吗？如果是paddlex的，默认都是加入argmax算子的，见 https://github.com/PaddlePaddle/PaddleX/blob/f2fce32bbf696da0e87071ca401530be9cf6a375/paddlex/cv/models/segmenter.py#L104

**Comment by lmmir** [comment]
> 请问是paddlex训练导出的deeplabv3p吗？如果是paddlex的，默认都是加入argmax算子的，见
> 
> https://github.com/PaddlePaddle/PaddleX/blob/f2fce32bbf696da0e87071ca401530be9cf6a375/paddlex/cv/models/segmenter.py#L104

但我模型在paddlelite里使用 推理的数据不是0或者1

**Comment by lmmir** [comment]
> 请问是paddlex训练导出的deeplabv3p吗？如果是paddlex的，默认都是加入argmax算子的，见
> 
> https://github.com/PaddlePaddle/PaddleX/blob/f2fce32bbf696da0e87071ca401530be9cf6a375/paddlex/cv/models/segmenter.py#L104

你引用的 是代码里实现了argmax ，我的意思是模型里直接包含argmax，推理得到数据就是经过argmax算子处理过的，而不是predict后再进行argmax计算。

**Comment by heliqi** [comment]
你用的paddlex是哪个版本？

**Comment by lmmir** [comment]
> 你用的paddlex是哪个版本？

2.0.0rc3
![image](https://user-images.githubusercontent.com/6245182/127957469-7119eeb5-838f-4524-9e52-d352edeebb1d.png)

**Comment by heliqi** [comment]
2.0导出的seg模型得到的结果是经过argmax的。
1.你先试试用paddle加载模型看结果是否是0 1 
2.你用visualDL可视化直接看看模型最后是否有argmax

**Comment by lmmir** [comment]
> 2.0导出的seg模型得到的结果是经过argmax的。
> 1.你先试试用paddle加载模型看结果是否是0 1
> 2.你用visualDL可视化直接看看模型最后是否有argmax


visualDL可视化没看到有argmax 
![model pdmodel](https://user-images.githubusercontent.com/6245182/128126616-3abee0e4-f0f0-4452-b0d4-ffc5bb3624e7.png)

**Comment by FlyingQianMM** [comment]
抱歉前面说错了，导出后的模型没有argmax。没有默认支持argmax的原因是，有些任务例如人像分割需要原始的logit，您在使用paddlelite部署时可以先在后处理加一个argmax操作，我们再评估下要不要默认加入argmax。
