### ISSUE TITLE
PaddleX GUI 的实现？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleX#1007]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
您使用的PaddleX GUI版本
1.1.7
**问题描述**  
想了解PaddleX GUI的具体实现

===================================  

您好，我试用了PaddleX GUI版本，效果很不错，并且能在我的 GTX750Ti 上跑模型训练，tql！请问GUI的代码开源了吗？
PaddleX GUI是用C#实现的吗，是否可以理解为界面参数实际上是传递给python训练代码的？如果方便能否给一个技术实现的具体路线呢？
非常感谢！

**Comment by geoexploring** [comment]
发现一个小问题：
假设已经下载了果蔬分类的样例数据集，
再另外要做一个新的猫狗识别的图像分类项目，则在第一步创建数据集时没法加载猫狗识别数据集，而一直显示果蔬分类数据集，
需要删除果蔬分类数据集后，才能创建猫狗识别数据集。
在两台电脑上都发现有这个问题。

**Comment by lailuboy** [comment]
可以创建多数据集和选择对应的，前提创建的数据集要导入和校验成功，并成功划分好才会在创建项目的下拉列表中可以选择。
GUI不是C#实现的，是基于wxwidget实现的。GUI最终是传递参数给python代码进行训练的。就是API训练时使用的接口。

**Comment by geoexploring** [comment]
@lailuboy, 谢谢解答，明白了！
