### ISSUE TITLE
paddle on ROS

### ISSUE THREAD

**Issue by Feng1909** [PaddlePaddle/PaddleX#1009]
问题类型：模型部署
Can you provide some examples by C++ on ROS platform? Our team want to deploy ppyolo-tiny on ROS and see if it's faster than yolov4-tiny. Thanks for your work, it's an amazing tool.

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by FlyingQianMM** [comment]
paddlex支持ppyolo-tiny的C++部署，参考我们给出的代码 https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp 将其集成入ros下的c++项目中即可。
