### ISSUE TITLE
模型训练完成后output文件夹输出的vdlrecords.xxx.log是什么编码?

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleX#1010]
问题类型：其它  

**PaddleX版本**  
您使用的PaddleX版本
2.0.0rc3

**问题描述**  
output输出的vdlrecords.xxx.log是什么编码?

========================

请问模型训练完成后output文件夹输出的vdlrecords.xxx.log是什么编码呢?
我的输出是乱码,如下:
![Screenshot_2](https://user-images.githubusercontent.com/58645709/127800150-219f281a-813a-4f04-973e-55b1d56596b5.png)

另外,这个log并不像PaddleX GUI输出的日志那么友好,也许可以改进.

谢谢!

**Comment by yzl19940819** [comment]
您好  VDL的日志文件的是二进制文件。详细使用请参考https://github.com/PaddlePaddle/PaddleDetection/issues/3791

**Comment by geoexploring** [comment]
@yzl19940819 ,谢谢!
按照您给出的链接里的解决方案, 我在AI Studio notebook里按照下面的代码运行:
```python
from visualdl import LogReader

reader = LogReader(file_path='output/mobilenetv3_large_ssld/vdl_log/vdlrecords.1627805693.log')
data = reader.get_data('scalar', 'loss')
print(data)
```
没有任何反应,请问是什么问题呢?
谢谢!

**Comment by YixinKristy** [comment]
您好，由于aistudio目前小故障，导致已集成的vdl暂时停止使用，所以需要您手动安装visualdl，因此首先请您确保您的visualdl在aistudio上安装成功，安装命令如下：
!pip install --upgrade visualdl

接着您再使用logreader接口进行尝试，确保文件路径无误，应该就没问题了

**Comment by geoexploring** [comment]
@YixinKristy, 谢谢!
按照您给的解决方案试了一下, 还是不行, 可能需要等aistudio好了才行.

另外, 请问PaddleX GUI的底层训练代码是完全基于PaddleX实现的吗?
我发现基于GUI训练出来的结果, 和我基于PaddleX写的代码运行结果很不一样, 具体请见[测试PaddleX GUI训练结果是否和基于PaddleX的代码一致](https://aistudio.baidu.com/aistudio/projectdetail/2248091).
不确定是不是我代码的问题, 头秃.
谢谢

**Comment by yzl19940819** [comment]
您好，您可以在本地pip安装一下paddlex，下载好vdl的文件，看看效果。
GUI和代码的训练结果区别我看一下

**Comment by geoexploring** [comment]
@yzl19940819 ，改了基于PaddleX写的代码的学习率之后（从0.025到0.00625）就能得到很好的结果。但是在GUI里，0.025的学习率也能得到很好的结果。所以GUI的训练代码和简单的基于PaddleX写的代码是不一致的？

**Comment by geoexploring** [comment]
PaddleX GUI 的PaddleX版本是1.2.8，1.2.8的PaddleX底层是Paddle的静态图版本，
而我写的基于PaddleX实现的代码是2.0.0rc4，2.0.0rc4的PaddleX对应的是Paddle的动态图版本。
可能这是两者的最大区别。

本地pip安装了paddlex和vdl，vdl依然无法通过代码的方式显示，可能要等修复好以后才行。
