### ISSUE TITLE
请问在2.0中是否去掉了 pdx.deploy.Predictor 没有找到命令

### ISSUE THREAD

**Issue by duolabmeng6** [PaddlePaddle/PaddleX#1014]
问题类型：模型部署

```
model = pdx.deploy.Predictor(r'./model_target/inference_model', use_gpu=False)
```
报错了 找不到部署的函数 版本是 `PaddleX-2.0.0rc4`
```
AttributeError: module 'paddlex' has no attribute 'deploy'

```

文档

https://paddlex.readthedocs.io/zh_CN/release-1.3/deploy/server/python.html#id2

**Comment by jiangjiajun** [comment]
目前2.0版本没有提供，提供了`paddlex.load_model`

**Comment by duolabmeng6** [comment]
> 目前2.0版本没有提供，提供了`paddlex.load_model`

请教一下  `load_model` 

如何设置不使用GPU 使用 CPU 推理 

我在源码中没搜索到 所以想问一下~

**Comment by jiangjiajun** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device 可以使用这个接口

**Comment by duolabmeng6** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/set_device_cn.html#set-device 可以使用这个接口

原来如此 感谢大佬~爱你么么哒

**Comment by pphgood** [comment]
> 目前2.0版本没有提供，提供了`paddlex.load_model`
2.4版本paddlex.load_mode也没有了，请问换成什么函数了
