### ISSUE TITLE
module 'paddlex' has no attribute 'models'

### ISSUE THREAD

**Issue by MangoloD** [PaddlePaddle/PaddleX#1016]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本
2.0
**问题描述**  
module 'paddlex' has no attribute 'models'
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
我将'models'改为'cls'可以正常调用模型

**Comment by andyz168** [comment]
在 PaddleX 2.0 版本中，paddlex.models 模块被移除了，取而代之的是 paddlex.cv.models 模块。因此，在 PaddleX 2.0 或更高版本中，您需要将您的代码中的 paddlex.models 改为 paddlex.cv.models 才能正常运行。请尝试修改您的代码并再次运行。
