### ISSUE TITLE
paddlex2.0rc3及以上版本是不是不支持hub serving的方式

### ISSUE THREAD

**Issue by ztc125521** [PaddlePaddle/PaddleX#1023]
问题类型：模型部署
**问题描述**  
采用paddle hub serving需要start的时候出现 self.model = pdx.deploy.Predictor(self.default_pretrained_model_path,
AttributeError: module 'paddlex' has no attribute 'deploy'这个错误。
========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by wsyjwps1983** [comment]
paddlex --export_inference 做模型转换时也失败，直接把best_model的模型文件给copy过来了
paddlex版本为2.0.0rc3

**Comment by FlyingQianMM** [comment]
2.0不支持hub serving哈

**Comment by ahbyqq** [comment]
> 2.0不支持hub serving哈

请问paddlex2.1.0训练出的ppyolov2模型能在paddlehub serving部署吗？
