### ISSUE TITLE
工业表计读数问题

### ISSUE THREAD

**Issue by luwang1103** [PaddlePaddle/PaddleX#1030]
问题类型：其它  

**PaddleX版本**  
您使用的PaddleX版本

**问题描述**  
![image](https://user-images.githubusercontent.com/38969132/128802599-8633223f-2a5c-4f1c-8919-7716d7977aa9.png)

========================
我想测试该项目，但是出现了报错，我想知道这是什么问题呢？
请在这里描述您的问题

**Comment by FlyingQianMM** [comment]
可以在第247行打印下batch是否为空。另外，表计检测案例在2.0里面做了重构，建议使用2.0下的 https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/meter_reader
