### ISSUE TITLE
paddleX GUI版本导入数据问题

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleX#1033]
**PaddleX版本**  
您使用的PaddleX版本

数据类型：请说明你的数据类型，如图像分类、目标检测、实例分割或语义分割

我使用的是Windows版本的PaddleX GUI1.1.7。在进行目标检测任务时，在https://github.com/PaddlePaddle/PaddleX/blob/master/DataAnnotation/AnnotationNote/2_%5B%E7%9B%AE%E6%A0%87%E6%A3%80%E6%B5%8B%5D%E5%8F%8A%5B%E5%AE%9E%E4%BE%8B%E5%88%86%E5%89%B2%5D%E6%95%B0%E6%8D%AE%E6%A0%87%E6%B3%A8.md
中，提示使用LabelMe进行标注，但LabelMe标注得到的数据是json，但在PaddleX GUI中创建数据集时，提示标注必须是xml文件，请问这种情况如何处理。

**Comment by lishuai903** [comment]
看你这个链接的目标检测结构是xml形式
**参考以下代码，用时需要部分路径修改：**
`import json
import os

from tqdm import tqdm
from xmltodict import unparse

BBOX_OFFSET = 0

src_base = os.path.join("meter_det", "annotations")
dst_base = os.path.join("data", "VOCdevkitCOCO", "VOCCOCO")

dst_dirs = {x: os.path.join(dst_base, x) for x in ["Annotations", "ImageSets", "JPEGImages"]}
dst_dirs['ImageSets'] = os.path.join(dst_dirs['ImageSets'], "Main")
for k, d in dst_dirs.items():
    os.makedirs(d, exist_ok=True)


def base_dict(filename, width, height, depth=3):
    return {
        "annotation": {
            "filename": os.path.split(filename)[-1],
            "folder": "VOCCOCO", "segmented": "0", "owner": {"name": "unknown"},
            "source": {'database': "The COCO 2017 database", 'annotation': "COCO 2017", "image": "unknown"},
            "size": {'width': width, 'height': height, "depth": depth},
            "object": []
        }
    }


def base_object(size_info, name, bbox):
    x1, y1, w, h = bbox
    x2, y2 = x1 + w, y1 + h

    width = size_info['width']
    height = size_info['height']

    x1 = max(x1, 0) + BBOX_OFFSET
    y1 = max(y1, 0) + BBOX_OFFSET
    x2 = min(x2, width - 1) + BBOX_OFFSET
    y2 = min(y2, height - 1) + BBOX_OFFSET

    return {
        'name': name, 'pose': 'Unspecified', 'truncated': '0', 'difficult': '0',
        'bndbox': {'xmin': x1, 'ymin': y1, 'xmax': x2, 'ymax': y2}
    }


sets = {
    "trainval": os.path.join(src_base, "instance_train.json"),
    "test": os.path.join(src_base, "instance_test.json"),
}

cate = {x['id']: x['name'] for x in json.load(open(sets["test"]))['categories']}

for stage, filename in sets.items():
    print("Parse", filename)
    data = json.load(open(filename))

    images = {}
    for im in tqdm(data["images"], "Parse Images"):
        img = base_dict(im['file_name'], im['width'], im['height'], 3)
        images[im["id"]] = img

    for an in tqdm(data["annotations"], "Parse Annotations"):
        ann = base_object(images[an['image_id']]['annotation']["size"], cate[an['category_id']], an['bbox'])
        images[an['image_id']]['annotation']['object'].append(ann)

    for k, im in tqdm(images.items(), "Write Annotations"):
        im['annotation']['object'] = im['annotation']['object'] or [None]
        a=im['annotation']['filename'][:-4]
        unparse(im,
                open(os.path.join(dst_dirs["Annotations"], "{}.xml".format(str(a))), "w"),
                full_document=False, pretty=True)

    print("Write image sets")
    with open(os.path.join(dst_dirs["ImageSets"], "{}.txt".format(stage)), "w") as f:
        f.writelines(list(map(lambda x: str(x).zfill(12) + "\n", images.keys())))

    print("OK")`

**Comment by FlyingQianMM** [comment]
paddlex有提供数据转换的api，看下文档 

![image](https://user-images.githubusercontent.com/22235422/128960234-ea74940c-8935-47f5-8f91-005ea805f8bc.png)

https://github.com/PaddlePaddle/PaddleX#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
