### ISSUE TITLE
paddlex能转onnx嘛

### ISSUE THREAD

**Issue by ztc125521** [PaddlePaddle/PaddleX#1034]
问题类型：模型部署
**问题描述**  

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by heliqi** [comment]
可以使用paddle2onnx把模型转成onnx格式。由于导出模型带前后处理，建议使用paddle x的cpp部署，支持trt和triton。具体文档可看paddle/deploy/cpp下的readme
