### ISSUE TITLE
SFnet c++无法推理

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleX#1035]
PaddleSeg的SFnet训练之后用python代码推理效果如下
![6032167a496464ba123e50f62d5972b](https://user-images.githubusercontent.com/88479008/128961814-8df520e7-bee8-48b1-91dc-361cfce48eb8.png)

将模型导出为静态图模型
用C++范例报如下问题
![4980ca9cbca0f13e0e1cb4f0aab84a2](https://user-images.githubusercontent.com/88479008/128961879-fd02ac42-316f-43c4-8fa8-03659ee49429.png)
W0810 16:36:00.829313  2724 operator.cc:242] elementwise_add raises an exception struct dnnl::error, could not create a descriptor for a binary operation primitive

但是用PaddleSeg模型部署提供的范例模型，C++推理是正常的

这个是什么问题呢？

**Comment by FlyingQianMM** [comment]
能否提供下模型和测试图片让我们复现下？

**Comment by 534114658** [comment]
用PaddleSeg的SFnet预训练模型导出为静态图模型，用C++推理报一样的错
是C++还没支持吗 ？

你可以尝试下PaddleSeg的SFnet的预训练模型及图片，效果一样

**Comment by FlyingQianMM** [comment]
好的，我们复现下，尽快定位问题

**Comment by FlyingQianMM** [comment]
请问你模型导出时安装的paddle版本时多少呢？目前C++预测时使用的预测库是2.1.0版本的，你可以先换成paddlepaddle_gpu==2.1.0重新导出下模型，再试下C++预测

**Comment by 534114658** [comment]
![image](https://user-images.githubusercontent.com/88479008/129340006-7b96feee-9798-4b23-a203-251efa1b6647.png)
用  python -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple  命令安装的
必须是  paddlepaddle_gpu==2.1.0   是吧

**Comment by FlyingQianMM** [comment]
使用gpu预测的话，命令要将use_gpu设置为true，https://github.com/PaddlePaddle/PaddleX/blob/ed3159fcc87b8e0fbd3213040d6c8951266e0e01/deploy/cpp/demo/model_infer.cpp#L26

**Comment by 534114658** [comment]
已解决   use_gpu设置为true就可以正常运行了

为什么c++其他分割模型use_gpu设置为false可以运行？

**Comment by FlyingQianMM** [comment]
设置为false是使用cpu预测，目前有点问题，我们正在测试定位。

**Comment by FlyingQianMM** [comment]
使用cpu预测需要使用develop版本的预测库才能正常运行。
