### ISSUE TITLE
paddleX语义分割如何处理超过255类标签的数据

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleX#1038]
paddleX语义分割是否支持处理超过255类标签的数据，或者是否可以支持.npy格式的标注数据？

**Comment by FlyingQianMM** [comment]
目前不支持超过255类标签的标注数据，标注数据仅是png格式的。

能否问下具体的应用场景是什么样子的，会有超过255类的分割类别？

**Comment by fanweiya** [comment]
细胞分割

**Comment by FlyingQianMM** [comment]
可以先使用develop开发模式完成该项任务，需要更改代码的地方：

1. 读取label改成直接读取npy格式，具体改这一行 https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/transforms/operators.py#L170
2. 现在损失函数计算的ignore_idx默认是255，即255的地方不参与计算损失函数，该参数说明在https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/paddleseg/models/losses/cross_entropy_loss.py#L37，在 https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/models/segmenter.py#L143 这行设置`ignore_idx`即可
3. 卸载之前安装的paddlex，然后安装刚修改好的paddlex，具体见 https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85
