### ISSUE TITLE
Eval阶段出现错误ValueError: could not broadcast input array from shape

### ISSUE THREAD

**Issue by weypro** [PaddlePaddle/PaddleX#1039]
问题类型：模型训练  

**PaddleX版本**  
2.0.0

**问题描述**  
自建数据集，训练过程正常，在eval阶段出现ValueError: could not broadcast input array from shape...（shape参数不尽相同）  
问题项目及数据集已公开，https://aistudio.baidu.com/aistudio/projectdetail/2277943  
COCO格式和VOC格式都是该错误，用opencv/pil打开后保存（确保是三通道）无效。
恳请大佬帮忙

**Comment by FlyingQianMM** [comment]
paddlex已经升级至动态图2.0版本，你目前使用的还是静态图版本的paddlex，可以试下将paddlex更新至2.0.0rc4
```
pip install paddlex==2.0.0rc4 -U
```
运行下我们给出的tutorial看能够正常运行 https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train
如果tutorial可以正常运行，而你的数据集无法正常运行的话，请贴一下全部的日志。

**Comment by weypro** [comment]
感谢大佬，更新版本后问题解决
