### ISSUE TITLE
Normal模式下保存的模型，怎样直接加载预测？

### ISSUE THREAD

**Issue by legendxty** [PaddlePaddle/PaddleX#104]
我在aistudio上面加载模型预测的方式是：通过新建模型后，调用model的train接口，设置num_epochs=0，pretrain_weights='./output/faster_rcnn_r50_fpn/best_model'，然后进行predict。
而把模型文件下载到本地windows系统中，在本地进行预测时，有没有更直接的方法？

**Comment by jiangjiajun** [comment]
> 我在aistudio上面加载模型预测的方式是：通过新建模型后，调用model的train接口，设置num_epochs=0，pretrain_weights='./output/faster_rcnn_r50_fpn/best_model'，然后进行predict。
> 而把模型文件下载到本地windows系统中，在本地进行预测时，有没有更直接的方法？

使用paddlex加载即可（注意先安装好paddlepaddle或者paddlepaddle-gpu 1.8.0及以上版本）
```
pip install paddlex -i https://mirror.baidu.com/pypi/simple
```

模型加载及预测
```
import paddlex as pdx
model = pdx.load_model('./output/faster_rcnn_r50_fpn/best_model')
result = model.predict('test.jpg')
```
如若你的检测或分割模型，还可以调用[visualize接口](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/visualize.md)，如下
```
pdx.det.visualize('test.jpg', result, save_dir='./')
# 或pdx.seg.visualize('test.jpg', result, save_dir='./')
```
