### ISSUE TITLE
为什么在linux环境中不支持链接tensorrt的静态库？

### ISSUE THREAD

**Issue by wikiwen** [PaddlePaddle/PaddleX#1041]
问题类型：模型部署
**问题描述**  
在c++的部署代码中，我注意到在win32中默认链接tensorrt和cuda的静态库，而在非win32的系统中默认链接动态库。请问为什么不支持在linux环境中链接tensorrt的静态库呢？

具体代码见[位置](https://github.com/PaddlePaddle/PaddleX/blob/619cdba9b9f4972270929906f90c57396ae00afa/deploy/cpp/tools/build_pipeline/CMakeLists.txt#L154)

**Comment by heliqi** [comment]
是支持编译静态库的，只是我们更推荐在linux上进行动态编译。
如果你有需要的话，把WITH_STATIC以及对应所有动态库名字改成静态库即可
