### ISSUE TITLE
关于目标检测yolov3_mobilenetv3裁剪了模型反而体积增大的问题

### ISSUE THREAD

**Issue by smallwhi** [PaddlePaddle/PaddleX#1044]
模型刚训练完，导出成hub部署模型体积只有80MB，再做完裁剪训练体积增大到了700多MB
![image](https://user-images.githubusercontent.com/66171021/129465060-fe751efb-d26d-453a-9d92-9a8a93dfa341.png)

**Comment by FlyingQianMM** [comment]
该问题与 #910  相似

模型剪裁之后得到的model.pdparams参数文件可能会出现体积不变或者变大的情况，因为该参数文件中不仅包含模型推理时所需的参数（已剪裁），还包含了与完成剪裁相关的参数，但是此时剪裁过的模型flops已经减少了。如果需要进一步得到推理时所需的参数文件，需要将模型导出，具体可以参考我们的[模型导出文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/export_model.md)。
