### ISSUE TITLE
paddlex2.0导出onnx后还需要自行编写数据的前处理和后处理是吗？

### ISSUE THREAD

**Issue by ztc125521** [PaddlePaddle/PaddleX#1045]
问题类型：模型部署
**问题描述**  

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by heliqi** [comment]
是的， 如果是c++的话，  你也可以参照我们的triton 、 tensorrt 引擎 加入onnx runtime引擎。
