### ISSUE TITLE
GUI应该增加“部署模型导出”

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1051]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
RC2

**问题描述**  

===================================  

GUI 应该增加“部署模型导出”

不然每次还要手动的输出命令

paddlex --export_inference --model_dir=./xiaoduxiong_epoch_12 --save_dir=./inference_model

**Comment by BuLuoPiaoYu** [comment]
> 问题类型：PaddleX可视化客户端
> 
> **PaddleX GUI版本**
> RC2
> 
> **问题描述**
> 
> ===================================
> 
> GUI 应该增加“部署模型导出”
> 
> 不然每次还要手动的输出命令
> 
> paddlex --export_inference --model_dir=./xiaoduxiong_epoch_12 --save_dir=./inference_model

发布模型就是了

**Comment by monkeycc** [comment]
C++部署调用   就要手动  转换模型才可以  直接发布的只能在python中调用

**Comment by BuLuoPiaoYu** [comment]
> C++部署调用 就要手动 转换模型才可以 直接发布的只能在python中调用

不会啊，你发布完是这样的吗，我在C++都是调的这些文件啊

![image](https://user-images.githubusercontent.com/54087448/129998664-f28627d0-648f-45f2-8702-bd14b69bb9ae.png)

**Comment by heliqi** [comment]
如果是最新的 rc2版本GUI， 发布模型就是导出，可以在C++部署的。 导出的模型如上图
