### ISSUE TITLE
PPyolo  c++推理报错

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleX#1056]
生成的推理文件如下：

mode: fluid
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 128
  - 1280
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
label_list:
- person
- bicycle

报错内容为：

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 3-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 160, 4, 4], input[1]'s shape = [1, 1, 4, 40].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:4 != inputs_dims[i][j]:40.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/concat_op.h:63)

这是什么问题？

**Comment by heliqi** [comment]
你好， 麻烦贴下更完整的报错信息 。
另外提供下运行时相关的信息： 模型是哪个套件导出、套件版本是多少、 预测库是哪个版本？

**Comment by 534114658** [comment]
![image](https://user-images.githubusercontent.com/88479008/130206540-b6dc51c2-b26a-4fe3-8e36-7348bbd1e86b.png)
主要是 target_size: 这个参数
如果训练为608 或者512 c++推理正常的

指定尺寸训练出的模型在c++推理报错
但是指定尺寸训练的模型用python可以正常推理

以上已经是全部报错信息

训练是PaddleDetection-release-2.2
c++   是PaddleX-develop的最新版本

**Comment by heliqi** [comment]
能提供你指定PaddleDetection 模型尺寸 并导出的脚本么？ 或者提供导出的模型也可以 ？  
方便我们复现

**Comment by 534114658** [comment]
![image](https://user-images.githubusercontent.com/88479008/130310029-efe7258f-fdd2-46de-b220-086143d8abe3.png)
keep_ratio: false改为keep_ratio: true 就可以正常推理

但是结果和python不一样

python结果如下：
![image](https://user-images.githubusercontent.com/88479008/130310069-7b326657-af8c-40ef-a9d7-6ab37aaf390e.png)
c++结果如下：
![image](https://user-images.githubusercontent.com/88479008/130310086-4fd396d4-ed85-4c8e-b436-ade8343d84f9.png)
打印 c++   图片的resize 结果为117  *1280   模型配置的是128*1280  所以结果出现了偏差
需要怎么样更改配置？

是否可以提供邮箱？   发送模型及图片

**Comment by FlyingQianMM** [comment]
YOLO系列的模型，target_size必须长和宽相等呢，现在你设置的是128x1280，所以出现了上述报错信息
