### ISSUE TITLE
paddle模型训练异常终止

### ISSUE THREAD

**Issue by wenyansha** [PaddlePaddle/PaddleX#1060]
问题类型：模型训练  

**PaddleX版本**  
paddlex_gui_win10_v1.1.8

**问题描述**  

====================  
利用paddlex可视化界面开始模型训练，数据均为系统提供的样例数据，开始模型训练还未有**%的进度条就显示训练终止，查看err.log、out.log、paddlex.log均没有报错信息。所有类型的模型样例都测试了，均终止训练。不知道是什么原因，或者paddlex对安装环境有没有要求

**Comment by FlyingQianMM** [comment]
1. 训练终止是在下载完预训练模型之后终止的吗？
2. CUDA、CUDNN、显卡驱动目前是什么版本

**Comment by wenyansha** [comment]
> 
> 
>     1. 训练终止是在下载完预训练模型之后终止的吗？
> 
>     2. CUDA、CUDNN、显卡驱动目前是什么版本

我重新安装了CUDA11.2+CUDNN8.1.1后大部分模型可以使用了，但在实例分割项目中backnone选择Xception**时，仍然会有之前的问题，想问下部分模型不可用与什么有关，有没有关于不同模型的说明呀。训练终止在下载完预训练模型之后，显卡是NVIDIA GeoForce GTX 1050。

**Comment by FlyingQianMM** [comment]
你用的是2.0的GUI吗？以前1.x的GUI还没有出现过部分模型不可用的现象

**Comment by wenyansha** [comment]
> 
> 
> 你用的是2.0的GUI吗？以前1.x的GUI还没有出现过部分模型不可用的现象

是说PaddleX的版本吗，我用的是1.1.7版本的，我们用了几台电脑在测，有的电脑可以用Xception的模型，有的电脑就不行

**Comment by FlyingQianMM** [comment]
PaddleX有GUI和API两种使用方式，如果是用GUI的话，目前已经升级到2.0了，需要CUDA11.2+CUDNN8才能使用，可以试试

GUI（CUDA11.2/CUDNN8）：
windows: https://bj.bcebos.com/paddlex/PaddleX_30X0/PaddleX2.0.0rc2_windows10.zip
ubuntu: https://bj.bcebos.com/paddlex/2.0//paddlex_gui_ubuntu1804_amd64_v2.0.0rc2.tar.gz

GUI中的模型在API中都有，也可以使用API进行开发，具体可以看下PaddleX 2.0文档 https://github.com/PaddlePaddle/PaddleX#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3

**Comment by wenyansha** [comment]
> 
> 
> PaddleX有GUI和API两种使用方式，如果是用GUI的话，目前已经升级到2.0了，需要CUDA11.2+CUDNN8才能使用，可以试试
> 
> GUI（CUDA11.2/CUDNN8）：
> windows: https://bj.bcebos.com/paddlex/PaddleX_30X0/PaddleX2.0.0rc2_windows10.zip
> ubuntu: https://bj.bcebos.com/paddlex/2.0//paddlex_gui_ubuntu1804_amd64_v2.0.0rc2.tar.gz
> 
> GUI中的模型在API中都有，也可以使用API进行开发，具体可以看下PaddleX 2.0文档 https://github.com/PaddlePaddle/PaddleX#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3

好的，谢谢
