### ISSUE TITLE
openvino  推理DeeplabV3p报错

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleX#1073]
DeeplabV3p是由PaddleSeg模块训练
DeeplabV3p转openvino成功
openvino windows编译也是成功的
运行提示如下错误：
![image](https://user-images.githubusercontent.com/88479008/130890876-1e333d09-ee88-4b5e-a6f9-e1a265b03c2a.png)

cfg_file文件如下
![image](https://user-images.githubusercontent.com/88479008/130890972-d34af54b-c572-43d9-bc4d-c4fe082e1a3d.png)

**Comment by FlyingQianMM** [comment]
有没有指定--model_type=seg?

**Comment by 534114658** [comment]
指定了

C++的openvino代码是PaddleX动态图最新版
seg的模型是PaddleSeg模块训练   openvino模型由PaddleX的openvino模块命令转化而来

**Comment by FlyingQianMM** [comment]
> openvino模型由PaddleX的openvino模块命令转化而来

这个是用的PaddleX 静态图版本的命令吧？咱们动态图的openvino转换脚本还没ready。

你可以试下如果不转openvino，直接用paddle inference部署，能否正常解析这个yml文件

**Comment by 534114658** [comment]
好的
