### ISSUE TITLE
openvino  如何调用GPU（核显）？

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleX#1083]
在openvino的c++代码里面可选设备只有CPU和VPU
如下图：
![image](https://user-images.githubusercontent.com/88479008/131308413-c5acc2dd-dd0e-487a-8ff2-e9d534ab428b.png)
在openvino里面是可以配置GPU（核显）的
如下图：
![49923ae1131194ea5d3a60732328ae5](https://user-images.githubusercontent.com/88479008/131309415-825db8f0-9758-4a48-bc12-2687170218ea.png)

这边需要怎么配置？

**Comment by FlyingQianMM** [comment]
PaddleX的openvino部署目前只做了cpu和vpu的适配。如果是要用GPU部署，可以先用Paddle原生的推理引擎，这样也省去了转onnx的步骤。

另外您之前有使用过openvino gpu部署么，预测性能怎么样呢？

**Comment by 534114658** [comment]
正在看openvino的demo

在网上看了一篇帖子
连接：https://blog.csdn.net/beingod0/article/details/102911569
硬件如下
![image](https://user-images.githubusercontent.com/88479008/131427462-3e5da6a3-1659-463d-a120-ff2feb365838.png)
cpu处理
![image](https://user-images.githubusercontent.com/88479008/131427500-d490f007-3a9a-4ff4-8409-0c7505ede737.png)
核显处理
![image](https://user-images.githubusercontent.com/88479008/131427522-23ee7cf8-ab2c-42f2-8754-662dda1153a5.png)
在需要使用openvino的环境下   还是很有优势的
特别是11代cpu

openvino官网的数据
![b6620c1909ef202b846f59dee26a2ff](https://user-images.githubusercontent.com/88479008/131427881-fa67b36c-4016-4d72-9c75-37289394f7ce.png)

**Comment by FlyingQianMM** [comment]
了解，GPU推理还是比CPU快的。

1. 使用GPU推理，之前有试过用Paddle预测库或者tensorrt测试过不？如果是用的英伟达的显卡，会有进一步加速，可以先试下，看下性能是否满足您当前的需求。

2. 关于Openvino的GPU推理我们之前没有测试过。关于Openvino引擎参数设置都在 https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/model_deploy/engine/src/openvino_engine.cpp ，您可以先看下device是否可以改成GPU，感觉是可以的，需要对一下openvino的细节。

3.  1和2测试性能时，可以做好设备和相关性能数据的记录。有问题再反馈给我们

**Comment by 534114658** [comment]
使用GPU推理没问题

![image](https://user-images.githubusercontent.com/88479008/131436493-e49630eb-334b-4111-b153-5caa13eba226.png)
动态图的openvino没调通（动态图的openvino可以正常使用了吗？）
静态图的指定设备不是openvino_engine.cpp

**Comment by 534114658** [comment]
动态图的openvino什么时候可以使用？

**Comment by 534114658** [comment]
11代核显相对于cpu在分割模型预计加速25%
