### ISSUE TITLE
编译C++的代码失败，出现“cc1plus: error: too many filenames given”的错误

### ISSUE THREAD

**Issue by zhangzscn** [PaddlePaddle/PaddleX#1091]
问题类型：模型部署
**问题描述**  

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

环境：
Ubuntu 20.04
Gcc 9.3.0
Opencv 4.5.3

编译的paddle_inference信息:
GIT COMMIT ID: e04b66f2d272d68f77dcd94cb2956938475411d8
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
CUDA version: 11.4
CUDNN version: v8.2
CXX compiler version: 9.3.0

编译PaddleX的cpp文件夹时Cmake的设置：
WITH_MKL:ON
其他为OFF

编译输出错误如下：
[ 11%] Built target ext-yaml-cpp
[ 12%] Building CXX object demo/CMakeFiles/batch_infer.dir/batch_infer.cpp.o
[ 15%] Building CXX object demo/CMakeFiles/model_infer.dir/model_infer.cpp.o
[ 15%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/common/src/base_preprocess.cpp.o
[ 16%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/common/src/base_preprocess.cpp.o
[ 18%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/common/src/model_factory.cpp.o
[ 21%] Building CXX object demo/CMakeFiles/multi_gpu_model_infer.dir/multi_gpu_model_infer.cpp.o
[ 21%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/common/src/model_factory.cpp.o
[ 22%] Building CXX object demo/CMakeFiles/multi_gpu_model_infer.dir/__/model_deploy/common/src/base_preprocess.cpp.o
[ 26%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/common/src/transforms.cpp.o
[ 26%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/common/src/paddle_deploy.cpp.o
[ 26%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/common/src/paddle_deploy.cpp.o
[ 28%] Building CXX object demo/CMakeFiles/multi_gpu_model_infer.dir/__/model_deploy/common/src/model_factory.cpp.o
[ 29%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/utils/src/bbox_utils.cpp.o
[ 32%] Building CXX object demo/CMakeFiles/multi_gpu_model_infer.dir/__/model_deploy/common/src/paddle_deploy.cpp.o
[ 33%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/utils/src/bbox_utils.cpp.o
[ 33%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/common/src/transforms.cpp.o
cc1plus: error: too many filenames given.  Type cc1plus --help for usage
cc1plus: error: too many filenames given.  Type cc1plus --help for usage

试过PaddleX的2.0.0rc0，1.3.0，都会出现这个cc1plus: error: too many filenames given. 的问题，麻烦帮忙看看怎么解决？

**Comment by FlyingQianMM** [comment]
这个看起来是gcc的问题。

编译paddle inference的时候需要对CMAKE_CXX_FLAGS https://github.com/PaddlePaddle/Paddle/blob/develop/CMakeLists.txt#L173 小改：
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=deprecated-declarations -Wno-deprecated-declarations -Wno-error=pessimizing-move -Wno-terminate")
```

麻烦@heliqi 跟进下这个问题吧

**Comment by zhangzscn** [comment]
把Cmake的版本从3.20.1降低到3.16.0也可以解决这个问题

**Comment by liaozihang** [comment]
编译选项加 -O3 试试

**Comment by bigbosscyb** [comment]
我的是因为库文件和头文件目录里面有中文
