### ISSUE TITLE
paddlegui使用文档为空呀 

### ISSUE THREAD

**Issue by super3kl** [PaddlePaddle/PaddleX#110]
https://paddlex.readthedocs.io/zh_CN/latest/paddlex_gui/download.html
https://paddlex.readthedocs.io/zh_CN/latest/paddlex_gui/how_to_use.html

**Comment by jiangjiajun** [comment]
> https://paddlex.readthedocs.io/zh_CN/latest/paddlex_gui/download.html
> https://paddlex.readthedocs.io/zh_CN/latest/paddlex_gui/how_to_use.html

谢谢反馈，PaddleX GUI的使用文档我们会尽快在这两天内补充上去。

**Comment by haha911** [comment]
这两个链接怎么打不开？

**Comment by jiangjiajun** [comment]
> 这两个链接怎么打不开？

https://paddlex.readthedocs.io/zh_CN/develop/gui
