### ISSUE TITLE
请教PaddleX使用Python开发的优势

### ISSUE THREAD

**Issue by wenmingwei** [PaddlePaddle/PaddleX#1110]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  

还在调研中

**问题描述**  

我们想对PaddleX进行一些功能扩展，但是python工程师比较珍贵。
想咨询一下，PaddleX使用Python开发相对于其他语言（golang、java）有哪些优势吗？
当初大佬们选用Python开发PaddleX的原因是什么啊？
非常感谢

===================================

**Comment by lailuboy** [comment]
Python虽然是脚本语言，但上手非常快，开发效率也非常高。并且拥有非常强大的第三方库（特别是一些科学计算和人工智能相关库，与这些库最开始的研究者是高校学者和科研机构研究者也有关），目前是深度学习和人工智能工程师首选的语言。
模型训练阶段是离线的，目前深度学习框架训练接口大部分都是通过Python接口方式提供（框架实现采用C++），所以同时兼顾了模型开发效率和模型训练速度问题。PaddleX的模型训练模块和接口基于Python能与框架能更好兼容且技术栈也相同。在部署阶段支持用其他语言，如C/C++/C#/Golang和Java这些第三方语言。如果有其他语言经历，转Python也非常快。
