### ISSUE TITLE
运行官方demo 报错

### ISSUE THREAD

**Issue by BlackAcer09** [PaddlePaddle/PaddleX#1126]
问题类型：模型部署
**问题描述**  
PaddleXManufacture/demo/build/pipeline_infer

按照官方文档配置 cuda cudnn 和TR https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/deploy/cpp/docs/manufacture_sdk

编译成功，但运行失败报错：
./pipeline_infer: error while loading shared libraries: libyaml-cpp.so.0.6: cannot open shared object file: No such file or directory

确认在PaddleXManufacture/third_party/yaml-cpp/lib 路径下包含此文件libyaml-cpp.so.0.6

ubuntu18.04 
cmake version 3.21.2

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

cmakelists.txt
```
cmake_minimum_required(VERSION 3.0)
project(PaddleDeploy CXX C)

SET(USER_KEY, "Hello World")
MESSAGE(WARNING "this var key =${USER_KEY}")

option(WITH_MKL        "Compile demo with MKL/OpenBlas support,defaultuseMKL."          ON)
option(WITH_GPU        "Compile demo with GPU/CPU, default use CPU."                    ON)
option(WITH_STATIC_LIB "Compile demo with static/shared library, default use static."   OFF)
option(WITH_TENSORRT "Compile demo with TensorRT."   OFF)

SET(TENSORRT_DIR "" CACHE PATH "~/ProgramFiles/tensorrt_tar/TensorRT-7.2.3.4")
SET(OPENCV_DIR "" CACHE PATH "/usr/local/lib")
SET(CUDA_LIB "" CACHE PATH "/usr/local/cuda/lib64")
SET(CUDNN_LIB "" CACHE PATH "/usr/local/cuda/lib64")
SET(PADDLEX_DIR "" CACHE PATH "/home/leo/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture")

find_package(OpenCV REQUIRED)

# paddlex

find_package(PaddleXManufacture REQUIRED PATHS /home/leo/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/share NO_DEFAULT_PATH)
include_directories(${PaddleXManufacture_INCLUDE_DIRS})
set(DEPS ${DEPS} ${PaddleXManufacture_LIBS})
message("paddlexpipeline-------:${PaddleXManufacture_INCLUDE_DIRS}")
# OPENCV
message("opencv-------:${WITH_TENSORRT} ${TENSORRT_DIR}")
if (WIN32)
  find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/build/ NO_DEFAULT_PATH)
  unset(OpenCV_DIR CACHE)
else ()
  find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/share/OpenCV NO_DEFAULT_PATH)
endif ()

set(DEPS ${DEPS} ${OpenCV_LIBS})
include_directories(${OpenCV_INCLUDE_DIRS})

# GPU TensorRT
if(WITH_GPU)
  if(NOT WIN32)
    if (NOT DEFINED CUDNN_LIB)
      message(FATAL_ERROR "please set CUDNN_LIB with -DCUDNN_LIB=/path/cudnn/")
    endif()
    message("libcudart:${CUDA_LIB}")
    set(DEPS ${DEPS} ${CUDA_LIB}libcudart${CMAKE_SHARED_LIBRARY_SUFFIX})
    set(DEPS ${DEPS} ${CUDNN_LIB}libcudnn${CMAKE_SHARED_LIBRARY_SUFFIX})

    if (WITH_TENSORRT)
      include_directories("${TENSORRT_DIR}/include")
      link_directories("${TENSORRT_DIR}/lib")

      set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/libnvinfer${CMAKE_SHARED_LIBRARY_SUFFIX})
      set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/libnvinfer_plugin${CMAKE_SHARED_LIBRARY_SUFFIX})
    endif()

  else()
    set(DEPS ${DEPS} ${CUDA_LIB}/cudart${CMAKE_STATIC_LIBRARY_SUFFIX} )
    set(DEPS ${DEPS} ${CUDA_LIB}/cublas${CMAKE_STATIC_LIBRARY_SUFFIX} )
    set(DEPS ${DEPS} ${CUDA_LIB}/cudnn${CMAKE_STATIC_LIBRARY_SUFFIX})

    if (WITH_TENSORRT)
      include_directories("${TENSORRT_DIR}/include")
      link_directories("${TENSORRT_DIR}/lib")

      set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/nvinfer${CMAKE_STATIC_LIBRARY_SUFFIX})
      set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/nvinfer_plugin${CMAKE_STATIC_LIBRARY_SUFFIX})
      set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/myelin64_1${CMAKE_STATIC_LIBRARY_SUFFIX})
    endif()
  endif()
endif()

macro(safe_set_static_flag)
    foreach(flag_var
        CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
      if(${flag_var} MATCHES "/MD")
        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
      endif(${flag_var} MATCHES "/MD")
    endforeach(flag_var)
endmacro()

if (WIN32)
    add_definitions("/DGOOGLE_GLOG_DLL_DECL=")
    find_package(OpenMP REQUIRED)
    if (OPENMP_FOUND)
        message("OPENMP FOUND")
        set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} ${OpenMP_C_FLAGS}")
        set(CMAKE_C_FLAGS_RELEASE  "${CMAKE_C_FLAGS_RELEASE} ${OpenMP_C_FLAGS}")
        set(CMAKE_CXX_FLAGS_DEBUG  "${CMAKE_CXX_FLAGS_DEBUG} ${OpenMP_CXX_FLAGS}")
        set(CMAKE_CXX_FLAGS_RELEASE   "${CMAKE_CXX_FLAGS_RELEASE} ${OpenMP_CXX_FLAGS}")
    endif()
    set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} /bigobj /MTd")
    set(CMAKE_C_FLAGS_RELEASE  "${CMAKE_C_FLAGS_RELEASE} /bigobj /MT")
    set(CMAKE_CXX_FLAGS_DEBUG  "${CMAKE_CXX_FLAGS_DEBUG} /bigobj /MTd")
    set(CMAKE_CXX_FLAGS_RELEASE   "${CMAKE_CXX_FLAGS_RELEASE} /bigobj /MT")
    if (WITH_STATIC_LIB)
        safe_set_static_flag()
        add_definitions(-DSTATIC_LIB)
    endif()
else()
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g  -fopenmp -std=c++11")
    # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -o3 -fopenmp -std=c++11")
    set(CMAKE_STATIC_LIBRARY_PREFIX "")
    set(EXTERNAL_LIB "-ldl -lrt -lgomp -lz -lm -lpthread")
    set(DEPS ${DEPS} ${EXTERNAL_LIB})
endif()

message("--DEPS-----:${DEPS}")



add_executable(pipeline_infer pipeline_infer.cpp)
target_link_libraries(pipeline_infer ${DEPS})

if(WIN32)
  add_custom_command(TARGET pipeline_infer POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/mklml/lib/mklml.dll ${CMAKE_BINARY_DIR}/
    COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/mklml/lib/libiomp5md.dll ${CMAKE_BINARY_DIR}/
    COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/mkldnn/lib/mkldnn.dll  ${CMAKE_BINARY_DIR}/
    COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/lib/PaddleXManufacture.dll ${CMAKE_BINARY_DIR}/
    COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/paddle/lib/paddle_inference.dll ${CMAKE_BINARY_DIR}/

    )
  if (WITH_TENSORRT)
    add_custom_command(TARGET pipeline_infer POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy ${TENSORRT_DIR}/lib/nvinfer.dll ${CMAKE_BINARY_DIR}/
      COMMAND ${CMAKE_COMMAND} -E copy ${TENSORRT_DIR}/lib/nvinfer_plugin.dll ${CMAKE_BINARY_DIR}/
      COMMAND ${CMAKE_COMMAND} -E copy ${TENSORRT_DIR}/lib/myelin64_1.dll ${CMAKE_BINARY_DIR}/
    )
  endif()
endif()
```

**Comment by heliqi** [comment]
把这个libyaml-cpp.so.0.6 拷贝到编译目录，或者将该目录加入环境变量试试

**Comment by FlyingQianMM** [comment]
试下把CMakeList.txt中原本的`find_package(PaddleXManufacture REQUIRED PATHS ${PADDLEX_DIR}/share NO_DEFAULT_PATH)`
改成：
```
find_package(PaddleXManufacture REQUIRED PATHS ${PADDLEX_DIR}/share/PaddleXManufacture NO_DEFAULT_PATH)
```

**Comment by BlackAcer09** [comment]
> 把这个libyaml-cpp.so.0.6 拷贝到编译目录，或者将该目录加入环境变量试试


必须把所有第三方的so路径加入环境变量才能运行demo
.bashrc 中加入以下内容

```
export LD_LIBRARY_PATH=~/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/third_party/yaml-cpp/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/third_party/mkldnn/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/third_party/mklml/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```

**Comment by BlackAcer09** [comment]
> 试下把CMakeList.txt中原本的`find_package(PaddleXManufacture REQUIRED PATHS ${PADDLEX_DIR}/share NO_DEFAULT_PATH)`
> 改成：
> 
> ```
> find_package(PaddleXManufacture REQUIRED PATHS ${PADDLEX_DIR}/share/PaddleXManufacture NO_DEFAULT_PATH)
> ```




改find package这个方法没有效果

**Comment by BlackAcer09** [comment]
> 问题类型：模型部署
> **问题描述**
> PaddleXManufacture/demo/build/pipeline_infer
> 
> 按照官方文档配置 cuda cudnn 和TR https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/deploy/cpp/docs/manufacture_sdk
> 
> 编译成功，但运行失败报错：
> ./pipeline_infer: error while loading shared libraries: libyaml-cpp.so.0.6: cannot open shared object file: No such file or directory
> 
> 确认在PaddleXManufacture/third_party/yaml-cpp/lib 路径下包含此文件libyaml-cpp.so.0.6
> 
> ubuntu18.04
> cmake version 3.21.2
> 
> 请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。
> 
> cmakelists.txt
> 
> ```
> cmake_minimum_required(VERSION 3.0)
> project(PaddleDeploy CXX C)
> 
> SET(USER_KEY, "Hello World")
> MESSAGE(WARNING "this var key =${USER_KEY}")
> 
> option(WITH_MKL        "Compile demo with MKL/OpenBlas support,defaultuseMKL."          ON)
> option(WITH_GPU        "Compile demo with GPU/CPU, default use CPU."                    ON)
> option(WITH_STATIC_LIB "Compile demo with static/shared library, default use static."   OFF)
> option(WITH_TENSORRT "Compile demo with TensorRT."   OFF)
> 
> SET(TENSORRT_DIR "" CACHE PATH "~/ProgramFiles/tensorrt_tar/TensorRT-7.2.3.4")
> SET(OPENCV_DIR "" CACHE PATH "/usr/local/lib")
> SET(CUDA_LIB "" CACHE PATH "/usr/local/cuda/lib64")
> SET(CUDNN_LIB "" CACHE PATH "/usr/local/cuda/lib64")
> SET(PADDLEX_DIR "" CACHE PATH "/home/leo/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture")
> 
> find_package(OpenCV REQUIRED)
> 
> # paddlex
> 
> find_package(PaddleXManufacture REQUIRED PATHS /home/leo/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/share NO_DEFAULT_PATH)
> include_directories(${PaddleXManufacture_INCLUDE_DIRS})
> set(DEPS ${DEPS} ${PaddleXManufacture_LIBS})
> message("paddlexpipeline-------:${PaddleXManufacture_INCLUDE_DIRS}")
> # OPENCV
> message("opencv-------:${WITH_TENSORRT} ${TENSORRT_DIR}")
> if (WIN32)
>   find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/build/ NO_DEFAULT_PATH)
>   unset(OpenCV_DIR CACHE)
> else ()
>   find_package(OpenCV REQUIRED PATHS ${OPENCV_DIR}/share/OpenCV NO_DEFAULT_PATH)
> endif ()
> 
> set(DEPS ${DEPS} ${OpenCV_LIBS})
> include_directories(${OpenCV_INCLUDE_DIRS})
> 
> # GPU TensorRT
> if(WITH_GPU)
>   if(NOT WIN32)
>     if (NOT DEFINED CUDNN_LIB)
>       message(FATAL_ERROR "please set CUDNN_LIB with -DCUDNN_LIB=/path/cudnn/")
>     endif()
>     message("libcudart:${CUDA_LIB}")
>     set(DEPS ${DEPS} ${CUDA_LIB}libcudart${CMAKE_SHARED_LIBRARY_SUFFIX})
>     set(DEPS ${DEPS} ${CUDNN_LIB}libcudnn${CMAKE_SHARED_LIBRARY_SUFFIX})
> 
>     if (WITH_TENSORRT)
>       include_directories("${TENSORRT_DIR}/include")
>       link_directories("${TENSORRT_DIR}/lib")
> 
>       set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/libnvinfer${CMAKE_SHARED_LIBRARY_SUFFIX})
>       set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/libnvinfer_plugin${CMAKE_SHARED_LIBRARY_SUFFIX})
>     endif()
> 
>   else()
>     set(DEPS ${DEPS} ${CUDA_LIB}/cudart${CMAKE_STATIC_LIBRARY_SUFFIX} )
>     set(DEPS ${DEPS} ${CUDA_LIB}/cublas${CMAKE_STATIC_LIBRARY_SUFFIX} )
>     set(DEPS ${DEPS} ${CUDA_LIB}/cudnn${CMAKE_STATIC_LIBRARY_SUFFIX})
> 
>     if (WITH_TENSORRT)
>       include_directories("${TENSORRT_DIR}/include")
>       link_directories("${TENSORRT_DIR}/lib")
> 
>       set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/nvinfer${CMAKE_STATIC_LIBRARY_SUFFIX})
>       set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/nvinfer_plugin${CMAKE_STATIC_LIBRARY_SUFFIX})
>       set(DEPS ${DEPS} ${TENSORRT_DIR}/lib/myelin64_1${CMAKE_STATIC_LIBRARY_SUFFIX})
>     endif()
>   endif()
> endif()
> 
> macro(safe_set_static_flag)
>     foreach(flag_var
>         CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
>         CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
>       if(${flag_var} MATCHES "/MD")
>         string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
>       endif(${flag_var} MATCHES "/MD")
>     endforeach(flag_var)
> endmacro()
> 
> if (WIN32)
>     add_definitions("/DGOOGLE_GLOG_DLL_DECL=")
>     find_package(OpenMP REQUIRED)
>     if (OPENMP_FOUND)
>         message("OPENMP FOUND")
>         set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} ${OpenMP_C_FLAGS}")
>         set(CMAKE_C_FLAGS_RELEASE  "${CMAKE_C_FLAGS_RELEASE} ${OpenMP_C_FLAGS}")
>         set(CMAKE_CXX_FLAGS_DEBUG  "${CMAKE_CXX_FLAGS_DEBUG} ${OpenMP_CXX_FLAGS}")
>         set(CMAKE_CXX_FLAGS_RELEASE   "${CMAKE_CXX_FLAGS_RELEASE} ${OpenMP_CXX_FLAGS}")
>     endif()
>     set(CMAKE_C_FLAGS_DEBUG   "${CMAKE_C_FLAGS_DEBUG} /bigobj /MTd")
>     set(CMAKE_C_FLAGS_RELEASE  "${CMAKE_C_FLAGS_RELEASE} /bigobj /MT")
>     set(CMAKE_CXX_FLAGS_DEBUG  "${CMAKE_CXX_FLAGS_DEBUG} /bigobj /MTd")
>     set(CMAKE_CXX_FLAGS_RELEASE   "${CMAKE_CXX_FLAGS_RELEASE} /bigobj /MT")
>     if (WITH_STATIC_LIB)
>         safe_set_static_flag()
>         add_definitions(-DSTATIC_LIB)
>     endif()
> else()
>    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g  -fopenmp -std=c++11")
>     # set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -o3 -fopenmp -std=c++11")
>     set(CMAKE_STATIC_LIBRARY_PREFIX "")
>     set(EXTERNAL_LIB "-ldl -lrt -lgomp -lz -lm -lpthread")
>     set(DEPS ${DEPS} ${EXTERNAL_LIB})
> endif()
> 
> message("--DEPS-----:${DEPS}")
> 
> 
> 
> add_executable(pipeline_infer pipeline_infer.cpp)
> target_link_libraries(pipeline_infer ${DEPS})
> 
> if(WIN32)
>   add_custom_command(TARGET pipeline_infer POST_BUILD
>     COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/mklml/lib/mklml.dll ${CMAKE_BINARY_DIR}/
>     COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/mklml/lib/libiomp5md.dll ${CMAKE_BINARY_DIR}/
>     COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/mkldnn/lib/mkldnn.dll  ${CMAKE_BINARY_DIR}/
>     COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/lib/PaddleXManufacture.dll ${CMAKE_BINARY_DIR}/
>     COMMAND ${CMAKE_COMMAND} -E copy ${PADDLEX_DIR}/third_party/paddle/lib/paddle_inference.dll ${CMAKE_BINARY_DIR}/
> 
>     )
>   if (WITH_TENSORRT)
>     add_custom_command(TARGET pipeline_infer POST_BUILD
>       COMMAND ${CMAKE_COMMAND} -E copy ${TENSORRT_DIR}/lib/nvinfer.dll ${CMAKE_BINARY_DIR}/
>       COMMAND ${CMAKE_COMMAND} -E copy ${TENSORRT_DIR}/lib/nvinfer_plugin.dll ${CMAKE_BINARY_DIR}/
>       COMMAND ${CMAKE_COMMAND} -E copy ${TENSORRT_DIR}/lib/myelin64_1.dll ${CMAKE_BINARY_DIR}/
>     )
>   endif()
> endif()
> ```

cmake 内容做了一点修改，具体看上边cmake内容，否则无法编译，另外
必须把所有第三方的so路径加入环境变量才能运行demo
.bashrc 中加入以下内容后 source 一下

```
export LD_LIBRARY_PATH=~/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/third_party/yaml-cpp/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/third_party/mkldnn/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=~/WorkSpace/Cpp/Code/cmakeTT/PaddleXManufacture/third_party/mklml/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
```
