### ISSUE TITLE
GUI无法下载样例和模型文件

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleX#1128]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
您使用的PaddleX GUI版本
我下载了这个issue中的2.0.0版本GUI，
https://github.com/PaddlePaddle/PaddleX/issues/1108#issuecomment-914877486
**问题描述**  

===================================  
我现在无法下载样例工程，训练自己的图像时，也无法下载模型。网络没有问题，如果我使用1.1.7，就可以完全正常的使用

**Comment by heliqi** [comment]
试试2.0版本的GUI看看：
windows: https://bj.bcebos.com/paddlex/2.0/PaddleX2.0.0_windows10.rar
linux: https://bj.bcebos.com/paddlex/2.0/PaddleX2.0.0_ubuntu1804_amd64.tar.gz

**Comment by gaooolianggg** [comment]
@heliqi 换了2.0.0仍然是同样的问题。我原来使用了1.1.7，在windows和Ubuntu18.04都使用了。我发现，windows系统中把原来的workspace删掉，就可以了。但Ubuntu这样操作后仍然不行

**Comment by FlyingQianMM** [comment]
试下更换下工作目录
