### ISSUE TITLE
请问最新版的GUI在哪里下载

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleX#1129]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
您使用的PaddleX GUI版本

**问题描述**  

===================================  
官网目前下载的还是1.1.7版本

**Comment by geoexploring** [comment]
转自PaddleX QQ 群消息
>  PaddleX2.0 GUI正式版发布了——
Windows：https://bj.bcebos.com/paddlex/2.0/PaddleX2.0.0_windows10.rar
Linux：https://bj.bcebos.com/paddlex/2.0/PaddleX2.0.0_ubuntu1804_amd64.tar.gz
同时API也已经发布2.0.0正式版，可通过pip install paddlex==2.0.0安装。
2.0版本使用文档见GitHub：https://github.com/PaddlePaddle/PaddleX

**Comment by heliqi** [comment]
不好意思，路径如上， 官网文档正在更新中。
