### ISSUE TITLE
2.0.0版训练的权重测试发现score结果不正常

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#1130]
问题类型：模型部署
部署测试发现分割结果也就是data的结果正常，但是置信度score的结果不正常，显示在图上发现是一条一条的竖线组成的

**Comment by heliqi** [comment]
请问是什么模型？ 是用paddlex导出的么？ data结果正常，是指 label_map 是对的?

**Comment by aiwenzhu** [comment]
> 请问是什么模型？ 是用paddlex导出的么？ data结果正常，是指 label_map 是对的?
是用paddlex导出的，deeplabv3p模型，对就是label_map正常，score_map不正常，老版本是都正常的，我在paddlex微信交流11群里发图片@你一下

**Comment by heliqi** [comment]
新版本lebal_map的维度是H * W，直接对应图片。 但是 score_map是 H*W*C的维度， 其中C是类别数， 需要处理下取出最大的score才能放到原图上
