### ISSUE TITLE
GUI能不能增加一键清理，硬盘占用太多了

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1139]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
2.00

**问题描述**  

===================================  

GUI能不能增加一键清理，硬盘占用太多了

每一轮或者每N轮就会保存一次模型

项目多的话 硬盘空间完全不够用

能不能在 项目 里面  增加清理模型
只保存想要的轮次模型  然后其他的轮次模型  全部删除

![微信截图_20210914093651](https://user-images.githubusercontent.com/6490927/133180273-1058ce02-43c9-4918-8fca-56b12d29710a.png)

**Comment by FlyingQianMM** [comment]
> 只保存想要的轮次模型 然后其他的轮次模型 全部删除

当前可以先手动选择想要的模型再删除其他的呢
