### ISSUE TITLE
gui安装问题

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleX#1143]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
您使用的PaddleX GUI版本

**问题描述**  

===================================  

我分别在windows和Ubuntu18上使用了GUI2.0.0. 我发现windows上我安装的coda版本是10.2，但paddleGUI打开后，显示的CUDA版本是11.2，但我的Ubuntu系统安装的是10.2，打开GUI则显示CUDA版本N/A，请问，使用GUI是不是只要安装好驱动就行，还是必须要安装适合的CUDA版本。
在一个就是，我的Ubuntu不能下载样例和模型，而使用1.1.7则没有这样的问题。

**Comment by heliqi** [comment]
显示N/A可能是你的GPU环境不匹配，未识别到显卡。 新版本的cuda是打包的11.2版本， 建议检查下驱动是否支持该版本，可以升级下驱动试试
