### ISSUE TITLE
训练报错 ：Exception: warmup_steps should less than 240

### ISSUE THREAD

**Issue by legendxty** [PaddlePaddle/PaddleX#115]
代码如下：
model = pdx.det.FasterRCNN(num_classes=num_classes, backbone='ResNet18')
model.train(
    num_epochs=240,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    learning_rate=0.0025,
    lr_decay_epochs=[40, 120],
    save_interval_epochs=2,
    save_dir='output/faster_rcnn_r50_fpn')
报错：Exception: warmup_steps should less than 240
报错很多次了，每次都改半天，忍不了了，请问num_epochs和lr_decay_epochs这俩参数怎么设置？

**Comment by jiangjiajun** [comment]
> 代码如下：
> model = pdx.det.FasterRCNN(num_classes=num_classes, backbone='ResNet18')
> model.train(
> num_epochs=240,
> train_dataset=train_dataset,
> train_batch_size=8,
> eval_dataset=eval_dataset,
> learning_rate=0.0025,
> lr_decay_epochs=[40, 120],
> save_interval_epochs=2,
> save_dir='output/faster_rcnn_r50_fpn')
> 报错：Exception: warmup_steps should less than 240
> 报错很多次了，每次都改半天，忍不了了，请问num_epochs和lr_decay_epochs这俩参数怎么设置？

非常不好意思给你带来了不好的体验，当前会出这个错误的原因是由于我们在参数检查中，加了如下的判断
warmup_steps需要小于 lr_decay_epochs[0] * num_steps_each_epoch， 这么做的原因是确保warmup会在学习率的第一次衰减前结束。

在你的这个代码中 lr_decay_epochs[0] = 40， 而num_steps_each_epoch等于 训练样本数/batch_size， warmup_steps你在接口中没有配置，则使用的是默认值500， 你可以在train接口中重新指定一下warmup_steps参数

我会重新调整一下这里的提示信息，避免带来无意义的报错信息，谢谢~

**Comment by jiangjiajun** [comment]
新增错误提示，同时已添加相应文档说明。 https://paddlex.readthedocs.io/zh_CN/develop/appendix/parameters.html#id2
