### ISSUE TITLE
结果bbox_map和可视化图中的AP为什么不同？

### ISSUE THREAD

**Issue by yuyifan-lab** [PaddlePaddle/PaddleX#1151]
问题类型：其它  

**PaddleX版本**  
您使用的PaddleX版本

**问题描述**  
![image](https://user-images.githubusercontent.com/85004561/133920937-48721261-c2ca-4e84-a371-66de610bbcc7.png)
![image](https://user-images.githubusercontent.com/85004561/133920949-48f8f38b-9e29-4ef6-9327-83ba2ae13a7a.png)

========================

请在这里描述您的问题
图一的bbox_map=83.327，图二的单独的AP=86.48,。
只有一种类型，为什么会出现最终不一样的结果？

**Comment by will-jl944** [comment]
评估使用的是voc metric吗？`draw_pr_curve`使用的是coco metric。二者计算方式不同。可参考[文档](https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/docs/apis/models/detection.md#train)按照你的需求设置评估使用的metric。
