### ISSUE TITLE
模型转换为openvino模型仅支持PaddleX训练的吗

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleX#1159]
请问模型转换为openvino模型仅支持PaddleX训练的吗？ppocr训练的模型可以转换吗

**Comment by will-jl944** [comment]
目前仅支持paddlex、paddledetection、paddleseg、paddleclas训练的模型，不支持ppocr的。

**Comment by Dandelion111** [comment]
> 目前仅支持paddlex、paddledetection、paddleseg、paddleclas训练的模型，不支持ppocr的。

好的，谢谢回复，未来有支持ppocr的打算吗请问？

**Comment by FlyingQianMM** [comment]
暂时没有适配的计划，你也可以参考目前我们的教程进行适配ocr的模型
