### ISSUE TITLE
PaddleX_onnx_TensorRT部署报错

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleX#1162]
问题类型：模型部署
**问题描述**  
模型训练工具：PaddleSeg
模型类别：ocrnet_hrnetw18
转onnx工具：Paddle2ONNX

按照PaddleX_onnx_TensorRT部署步骤转换ONNX模型，正常转换
![image](https://user-images.githubusercontent.com/88479008/134789800-f92fa4fc-27a5-4314-9f29-b2725cdb1630.png)

生成c++程序正常

用的是PaddleSeg_ocrnet_hrnetw18,根据范例修改配置文件
![image](https://user-images.githubusercontent.com/88479008/134789859-c4e1bab0-73e0-4f61-b4c2-c3547a52fb4c.png)

c++推理报错
![image](https://user-images.githubusercontent.com/88479008/134789945-28e8309b-d65e-4828-9c87-22d0216fcb46.png)

应该是input_- name: "x"不对？  还是其他的问题？
input_- name该怎么输入？在哪可以查看及查询？

**Comment by heliqi** [comment]
你用visualdl看看ocrnet_hrnetw18的网络结构， 查看输入输出的name和shape， 确认下是否跟上面的配置一样。 文档中的seg模型是paddlex导出的DeepLabv3p模型为例的，可能seg套件导出的名字、形状变了

**Comment by 534114658** [comment]
查看onnx属性如下
![image](https://user-images.githubusercontent.com/88479008/134799295-56f469c0-e13d-4279-bf79-c184bf14773a.png)

名称对的上   配置文件如下：
![image](https://user-images.githubusercontent.com/88479008/134799329-326da79b-8bf1-418c-b5e8-fb8a7f7d3ca4.png)

是哪里配置的问题吗？

**Comment by heliqi** [comment]
配置看起来没问题， 你能把模型发我邮箱么？我晚上debug后给你反馈

heliqi@baidu.com

**Comment by 534114658** [comment]
模型、配置文件及图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月26日(星期天) 下午5:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] PaddleX_onnx_TensorRT部署报错 (#1162)





 
你能把模型发我邮箱么？我晚上debug后给你反馈
 
***@***.***
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


从QQ邮箱发来的超大附件

model_1.onnx (46.50M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=746561306d9672cf5794b42f1663571d0c5500050200535718560309074e510750074c090452571f565758555500570001000209306f655f5a01045c6f524b5d5b0b19300d&t=exs_ftn_download&code=5ea00ce2




deploy1.yaml (405B, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7364343353989b9d5095e12c1e66564d54575006010552071f0504035e4b50560757190a0953064f035d040a5c50525b50000d56386a64065714585c41574a1b5309583305&t=exs_ftn_download&code=2d438fdb




9.png (367.0K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5b61663053729bc90390b32f4736531957540252570707504c045607581b550f02564b095402001b52510253040e0052500350066133610f4f110857610b&t=exs_ftn_download&code=aaf0a6a6

**Comment by 534114658** [comment]
已发

**Comment by heliqi** [comment]
已收到

**Comment by 534114658** [comment]
有发现是什么问题吗？

**Comment by 534114658** [comment]
有发现是什么问题吗？

**Comment by 534114658** [comment]
环境：cuda10.2_cudnn7.6_avx_mkl_trt7
在使用TensorRT 7.0会报上面的错
![image](https://user-images.githubusercontent.com/88479008/135371768-4bb96639-cbfe-470f-9717-f7929ab2c113.png)
但是只有TensorRT 7.0才支持cuda10.2_cudnn7.6，其他版本的TensorRT支持的cudnn不是cudnn7.6

例如改用TensorRT 7.2.3（支持的是cudnn8.1）
不会报input_- name的问题
而是报如下错误
![image](https://user-images.githubusercontent.com/88479008/135372959-b9f25a46-22c3-4ca5-a482-f96747304417.png)


这个到底是版本问题还是  这块的程序问题？

**Comment by heliqi** [comment]
应该是版本问题， 我们这边测试是在docker环境，没有问题。 
直接拉的容器是：nvcr.io/nvidia/tensorrt:<20.11>-py3 ,   对应的nvidia官网文档是： https://docs.nvidia.com/deeplearning/tensorrt/container-release-notes/rel_20-11.html#rel_20-11

TensorRT版本为 7.2.1
NVIDIA CUDA 11.1.0 including cuBLAS 11.2.1.
NVIDIA cuDNN 8.0.4

trt部署的例子在这个部署文档：
https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/deploy/cpp/docs/compile/tensorrt/trt.md
