### ISSUE TITLE
多线程部署后影响预测速度

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleX#1168]
问题类型：模型部署
**问题描述**  
我使用paddle2.1.2，显卡2080，cuda10.2.c#部署完成后测试分割模型预测速度大概20ms，但是如果我使用多个线程同时加载多个模型进行预测（暂时测试了4个线程），每个线程的预测速度明显下降，到了100ms左右，感觉随着线程增加速度是逐渐下降的，请问有办法解决吗？
======================
========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by Code-WHappy** [comment]
目标模型是两个线程不同时调用同一个模型推理失败。你试试两个线程不同时调用seg模型推理看行不行？

**Comment by FlyingQianMM** [comment]
在同一张卡上，多个线程分别加载不同的模型进行预测，相当于在同一张卡上同时有好几个模型在预测，相比于单模型，是会变慢的
