### ISSUE TITLE
No module named 'nltk'

### ISSUE THREAD

**Issue by jjchen460287** [PaddlePaddle/PaddleX#1171]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本
2.0
**问题描述**  
No module named 'nltk'

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
小白一枚，第一次使用paddlex  出现错误No module named 'nltk'
[err.log](https://github.com/PaddlePaddle/PaddleX/files/7235960/err.log)

**Comment by yzl19940819** [comment]
https://blog.csdn.net/qq_33432841/article/details/103789082 
这个回答参考一下？

**Comment by jjchen460287** [comment]
> https://blog.csdn.net/qq_33432841/article/details/103789082
> 这个回答参考一下？

成功安装之后  还是报 No module named 'nltk'这个错误

**Comment by FlyingQianMM** [comment]
请用当前python环境下的pip安装nltk：
```
python -m pip install nltk
```
