### ISSUE TITLE
语义分割做转换的时候报错paddlex --data_conversion --source labelme --to SEG

### ISSUE THREAD

**Issue by ZhangJR01** [PaddlePaddle/PaddleX#1173]
**PaddleX版本**  
您使用的PaddleX版本
2.0
数据类型：请说明你的数据类型，如图像分类、目标检测、实例分割或语义分割
语义分割

![image](https://user-images.githubusercontent.com/69112783/135068784-2d68c36d-ebf5-4f17-a7ee-7f5fec0b4155.png)
![image](https://user-images.githubusercontent.com/69112783/135069301-ff7e5c17-2194-483f-b274-0d3baca4e107.png)
![image](https://user-images.githubusercontent.com/69112783/135069359-a9eb5592-11ef-4c0e-baf0-b9d955ce78a6.png)
![image](https://user-images.githubusercontent.com/69112783/135069432-659b67f4-7f04-4948-a17c-69064765bd69.png)

**Comment by FlyingQianMM** [comment]
没看到报错信息在哪里
