### ISSUE TITLE
TensorRT加载模型预测不支持FP16

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleX#1175]
问题类型：模型部署
PaddleSeg推理开启trt
![image](https://user-images.githubusercontent.com/88479008/135212139-b1d52bd4-3e94-48d8-8db8-1062baccc577.png)
设置FP32  和不启用trt推理速度差不多

设置FP16  提示硬件不支持

![image](https://user-images.githubusercontent.com/88479008/135212334-06c9aec3-9402-4667-a146-ca4e238e501e.png)

请问市面上哪些显卡支持FP16？
我用的是1080TI

**Comment by 534114658** [comment]
找了1块2080TI
推理用的是TensorRT加载模型预测
模型使用的是DeepLabV3P_ResNet18_vd
FP16推理时间：15ms
FP32推理时间：18ms
加速不多

而且只有DeepLabV3P_ResNet18_vd   如下设置就可以使用
      engine_config.min_input_shape["x"] = {1, 3, 100, 100};
      engine_config.max_input_shape["x"] = {1, 3, 2000, 2000};
      engine_config.optim_input_shape["x"] = {1, 3, 1024, 1024};

其他模型添加了程序爆出来的input_shape   又会报   永无止境，无限循环。。。

不好用，，

而且每个模型报的都不一样，总不能针对每个模型来写一个推理程序吧，实用性太差

模型都是百度自家的，推理的时候需要哪些input_shape   自家应该知道啊

**Comment by heliqi** [comment]
目前推理引擎使用TensorRT是稍微麻烦点，近期推理引擎团队正在大力解决。
TensorRT是第三方没完全开源的推理引擎，不完全支持所有的模型。 所以paddle模型使用tensorrt时，只能把部分子图切割给trt运行， 导致每个子图的输入都需要设置。

具体原理可以参考官网文档的“四：Paddle-TRT子图运行原理”部分： https://paddleinference.paddlepaddle.org.cn/optimize/paddle_trt.html
