### ISSUE TITLE
C# demo 调试时出现错误

### ISSUE THREAD

**Issue by carychai** [PaddlePaddle/PaddleX#1177]
问题类型：模型部署
**问题描述**  
编译model_infer.dll成功后，用提供的c#专案调试时，运行到InitModel时报错，提示：“试图加载格式不正确的程序”
========================  
使用CPU预测
模型来自paddlex的样例训练而来
![1](https://user-images.githubusercontent.com/26074835/135228062-9ee57c2c-8a18-490f-9f61-4221942c1465.png)
![2](https://user-images.githubusercontent.com/26074835/135228088-701c28f8-1ab3-47f6-a275-e64b05639c54.png)

**Comment by FlyingQianMM** [comment]
> 使用CPU预测

使用GPU可以正常运行么？

**Comment by carychai** [comment]
> > 使用CPU预测
> 
> 使用GPU可以正常运行么？

**Comment by carychai** [comment]
不小心点Closed，我再开一个

**Comment by carychai** [comment]
> # 问题类型：模型部署
> **问题描述**
> 编译model_infer.dll成功后，用提供的c#专案调试时，运行到InitModel时报错，提示：“试图加载格式不正确的程序”
> 使用CPU预测 模型来自paddlex的样例训练而来 ![1](https://user-images.githubusercontent.com/26074835/135228062-9ee57c2c-8a18-490f-9f61-4221942c1465.png) ![2](https://user-images.githubusercontent.com/26074835/135228088-701c28f8-1ab3-47f6-a275-e64b05639c54.png)

**Comment by carychai** [comment]
> > 使用CPU预测
> 
> 使用GPU可以正常运行么？

没有GPU

**Comment by FlyingQianMM** [comment]
看下代码 有没有use_gpu=False的相关设置吧

**Comment by heliqi** [comment]
注意报错提示！ 检查下输入的模型文件、模型参数文件、配置文件路径是否对

如果输入的模型没问题， 可以把具体的异常打印出来， 或者把try去掉看看具体的报错是啥。
