### ISSUE TITLE
模型部署的安全性

### ISSUE THREAD

**Issue by JWLe666** [PaddlePaddle/PaddleX#1178]
如何让模型只能是我自己的程序才能调用，其他的程序或者代码不能调用。
加密模型或者模型加权限等方法，大家都可以说说。
最好有代码和对应的说明。

**Comment by FlyingQianMM** [comment]
只要密钥不给别人，别人就解密不了模型。
部署文档：https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/deploy/cpp
![image](https://user-images.githubusercontent.com/22235422/135289573-531d2443-11b8-45d0-88c0-bc74209674da.png)

**Comment by JWLe666** [comment]
如果不用部署的方式也能加密吗，比如这样pdx.deploy.Predictor(r'inference_model_yolov3', use_gpu=True) 直接调用也能吗

**Comment by heliqi** [comment]
如果不用部署的方式， 想加密解密模型就需要你查看我们的cpp部署源码， 把解密部分的接口单独剥离出来
有一定cpp功底，应该是没问题的

**Comment by JWLe666** [comment]
好的 谢谢

**Comment by JWLe666** [comment]
有个问题  我的paddlex是1.2版本   这个版本的解密是exe  我要怎么单独拿出来呢

**Comment by FlyingQianMM** [comment]
目前加密算法未开源，只提供了sdk。可以参考我们链接加密sdk的方法，自行将加密sdk的使用方式进行剥离。

**Comment by loveanao** [comment]
> 
很期望能使用这种，简便的方式来解密加密文档
pdx.deploy.Predictor(r'inference_model_yolov3', use_gpu=True, keys)
