### ISSUE TITLE
labelme 标注数据转换为voc或者coco出现错误

### ISSUE THREAD

**Issue by QIANXUNZDL123** [PaddlePaddle/PaddleX#1180]
paddlex:2.0.0rc3

数据类型：转换为目标检测数据集

git文档上转换指令为：paddlex --data_conversion --source labelme --to PascalVOC --pics ./pics --annotations ./annotations --save_dir ./converted_dataset_dir   其中--to 存在  ImageNet（图像分类）、PascalVOC（目标检测），MSCOCO（实例分割，也可用于目标检测）和SEG(语义分割)
但是在根据改命令转换成voc或者coco数据集都会有问题。如下所示：
![1](https://user-images.githubusercontent.com/46549527/135418993-08b0f06e-154e-4c1d-a8ad-c1bb1597bf51.png)
直接报不支持 MSCOCO或者PascalVOC
但是将--to改为 COCO或者VOC虽然也会报错 但是可以生成数据集

![图片](https://user-images.githubusercontent.com/46549527/135419296-63d539ab-23b7-440c-9e5e-69427211caf4.png)

主要是你们convert.py脚本下被你们写成这样了 
![图片](https://user-images.githubusercontent.com/46549527/135419423-2363c372-f353-4ace-a303-2b024139fa62.png)

convert.py脚本下to  是 voc   coco   并不是你们文档里面写的PascalVOC和MSCOCO  分割还是可以得，，可能你们需要修改下文档或者更改下。。。。。。。

**Comment by will-jl944** [comment]
此问题已在PaddleX 2.0正式版修复，可以通过`pip install paddlex -U`升级
