### ISSUE TITLE
padllex2.0

### ISSUE THREAD

**Issue by jjchen460287** [PaddlePaddle/PaddleX#1181]
问题类型：模型训练  
palllex2.0  paddlepaddle 2.1.3 
进行行人检测模型训练报错

Your running script needs PaddleX<2.0.0, please refer to https://github.com/PaddlePaddle/PaddleX/tree/release/2.0-rc/tutorials/train#%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7 to solve this issue.

请问我需要安装低版本paddlex吗？

**Comment by FlyingQianMM** [comment]
是的 这个链接有提示您安装1.3.11版本的paddlex 或者使用 2.0的训练代码
