### ISSUE TITLE
gui版本打不开 

### ISSUE THREAD

**Issue by 854619267** [PaddlePaddle/PaddleX#1184]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
1.1.7

**问题描述**  

===================================  
一直卡在这个画面    但是之前可以正常使用

![image](https://user-images.githubusercontent.com/3395480/136139613-45abb2f3-035f-426c-bc43-4f5dd3061ac4.png)

**Comment by jiangjiajun** [comment]
你可以尝试删除用户主目录下的~/.paddlex，再打开试试
