### ISSUE TITLE
mv: cannot stat 'check.py': No such file or directory

### ISSUE THREAD

**Issue by gznc-lhl** [PaddlePaddle/PaddleX#1186]
问题类型：其它  

**PaddleX版本**  
paddlex2.0.0

**问题描述**  

========================

mv: cannot stat 'check.py': No such file or directory
公共场所吸烟检测项目中缺少这个文件

**Comment by FlyingQianMM** [comment]
公共场所吸烟检测项目 这个具体是什么项目呢？

**Comment by gznc-lhl** [comment]
> 
> 
> 公共场所吸烟检测项目 这个具体是什么项目呢？

aistudio上面的一个项目

**Comment by FlyingQianMM** [comment]
> mv: cannot stat 'check.py': No such file or directory

这个报错看起来与PaddleX没有关系，请检查下该项目中该文件是否存在
