### ISSUE TITLE
paddlex1.2 模型部署编译问题

### ISSUE THREAD

**Issue by JWLe666** [PaddlePaddle/PaddleX#1189]
我是根据这个教程来弄的https://github.com/PaddlePaddle/PaddleX/blob/release/1.2/docs/deploy/server/cpp/windows.md
到 点击生成->全部生成 就报错

![image](https://user-images.githubusercontent.com/49588285/136553651-7df49da1-d01e-44f8-8856-ff8581c3cea7.png)

**Comment by FlyingQianMM** [comment]
看报错信息提醒缺少模型解密的lib，看下教程下载对应的加密sdk并指定对应的路径。不需要模型加密解密的话，就设置成False

**Comment by JWLe666** [comment]
好了  可以了   谢谢

**Comment by JWLe666** [comment]
这个报错是解决了   但又有新的报错
![image](https://user-images.githubusercontent.com/49588285/136648846-ee42b77a-2bcc-489f-a203-3874260fc8be.png)
![image](https://user-images.githubusercontent.com/49588285/136648873-4ec65040-c52e-41b0-a1fe-80df949de546.png)
