### ISSUE TITLE
paddlex模型库中没有PPYOLOTiny

### ISSUE THREAD

**Issue by AdobeDW** [PaddlePaddle/PaddleX#1190]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本
PaddleX-release-2.0.0
**问题描述**  
1、使用PaddelX训练PPYOLOTiny模型出错，提示paddlex.de没有ppyolo tiny属性，我查了一下paddlex模型库，目标检测里只有PPYOLO，没有ppyolo tiny模型。
2、求助！！！我使用paddleX训练是为了得到model.yml文件，以便去加载，因为可视化裁剪模型的裁剪率必须加载模型model.yml，但是我用paddleDetection训练的模型导出后只有infer_cfg.yml文件，没有model.yml，请问有什么办法吗？困扰我几天了，感谢帮助！
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
使用PaddelX训练PPYOLOTiny模型提示：
Traceback (most recent call last):
  File "PaddleX/tutorials/train/object_detection/ppyolotiny.py", line 43, in <module>
    model = pdx.det.PPYOLOTiny(num_classes=num_classes)
AttributeError: module 'paddlex.det' has no attribute 'PPYOLOTiny'

**Comment by lleesg** [comment]
有ppyolo tiny模型：pdx.det.PPYOLOTiny
可以load模型后，用model.train训练一轮，生成model.yml，然后按需手动修改model.yml即可
