### ISSUE TITLE
模型恢复训练失败，optimizer显示参数未找到。

### ISSUE THREAD

**Issue by JKsang** [PaddlePaddle/PaddleX#1193]
问题类型：模型训练  

**PaddleX版本**  
PaddleX==2.0.0

**问题描述**  

====================  
![image](https://user-images.githubusercontent.com/48127870/136650561-e1f38a6b-506a-4d12-bafb-345599d2efc6.png)
![image](https://user-images.githubusercontent.com/48127870/136650498-34bcab71-11b4-4bf5-b19f-27f09103b124.png)

**Comment by will-jl944** [comment]
问题已修复，感谢反馈。

更新PaddleX的方法请参考[教程](https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85)。
