### ISSUE TITLE
paddlex1.2 模型部署编译问题2

### ISSUE THREAD

**Issue by JWLe666** [PaddlePaddle/PaddleX#1199]
我是根据这个教程来弄的https://github.com/PaddlePaddle/PaddleX/blob/release/1.2/docs/deploy/server/cpp/windows.md
在最后一步 点击生成->全部生成  报错
![image](https://user-images.githubusercontent.com/49588285/136737364-d572eed9-4c8b-478b-8fc3-92a99ed8669b.png)
![image](https://user-images.githubusercontent.com/49588285/136737386-831454c6-b490-4b67-a767-02fde0d36454.png)

## 环境
1. PaddlePaddle版本号2.1.1.post110、PaddleX版本号1.2、Python版本号3.8
3. Windows10
4. 使用的CUDA/cuDNN的版本号是11.1

**Comment by FlyingQianMM** [comment]
![image](https://user-images.githubusercontent.com/22235422/136753302-6505a6bb-7dac-43c2-807b-62d14a52a197.png)
你下载推理引擎paddleinference预编译包的版本号是多少？你的cuda是11.1，1.2版本下的还没有适配cuda 11.1的paddle inference

要么就把训练和部署都升级到2.0来

**Comment by JWLe666** [comment]
我换cuda10.2了  用这个paddleinference预编译包
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows
![image](https://user-images.githubusercontent.com/49588285/136945021-d5c2ca69-7a3e-4dd6-97e6-3a2058bc2f2e.png)
报错的数量少 多了，但还是报错
![image](https://user-images.githubusercontent.com/49588285/136945156-a8f324a4-b428-49db-8988-522642a648ab.png)
![image](https://user-images.githubusercontent.com/49588285/136945238-fdeca1d2-03dd-44fb-8367-f7910cddb35d.png)

**Comment by heliqi** [comment]
虽然你换了2.0+的预测库，但是你的c++代码还是旧的(从报错内容可以看出)。 先下载github上最新代码进行编译 ，比如最新代码目录为：https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/deploy/cpp

**Comment by JWLe666** [comment]
我现在换PaddleX-release-2.0.0了 编译过程中有提醒，但没有中断  显示 全部生成 已成功。并没有生成出来文件
![image](https://user-images.githubusercontent.com/49588285/137095905-6693025f-b820-4e7e-be97-e4dd20c2db96.png)
![image](https://user-images.githubusercontent.com/49588285/137095999-3ed77656-ec53-4bf3-aa85-92648ea4fea8.png)
![image](https://user-images.githubusercontent.com/49588285/137096050-76ff1882-c69e-4a61-91d1-a4c77673a474.png)
我一开始是在弄加密的 但报错了  我就先试试不加密 行不行 结果就出现上面的情况了
加密编译的报错
![image](https://user-images.githubusercontent.com/49588285/137102247-2e89dcd7-3237-404f-b1ac-ffcc7215b5e7.png)

**Comment by heliqi** [comment]
显示生成成功已经编译生成完毕了，生成的exe在 out目录下

**Comment by JWLe666** [comment]
真没有
![image](https://user-images.githubusercontent.com/49588285/137441074-4d767be1-23a7-416e-8662-665c319bb2c5.png)
![image](https://user-images.githubusercontent.com/49588285/137441094-7f4fc11f-10a7-4747-a756-aeab3570da12.png)

**Comment by JWLe666** [comment]
大佬  要不在官方q群 教教我
