### ISSUE TITLE
文档中的API和代码不对应

### ISSUE THREAD

**Issue by chk218** [PaddlePaddle/PaddleX#12]
文档中是：https://paddlex.readthedocs.io/zh_CN/latest/apis/datasets.html#cocodetection
`paddlex.datasets.COCODetection`

而代码中却是：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/datasets/__init__.py
`paddlex.datasets.CocoDetection`

**Comment by jiangjiajun** [comment]
> 文档中是：https://paddlex.readthedocs.io/zh_CN/latest/apis/datasets.html#cocodetection
> `paddlex.datasets.COCODetection`
> 
> 而代码中却是：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/datasets/__init__.py
> `paddlex.datasets.CocoDetection`
确实是文档有误，会立即修复，谢谢反馈!

**Comment by chk218** [comment]
> 文档中是：https://paddlex.readthedocs.io/zh_CN/latest/apis/datasets.html#cocodetection
> `paddlex.datasets.COCODetection`
> 
> 而代码中却是：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/cv/datasets/__init__.py
> `paddlex.datasets.CocoDetection`
