### ISSUE TITLE
GUI版本有没有模型量化的功能？

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleX#1203]
用的是2.0.0的GUI版本，有裁剪，但是没有找到量化的功能。是不是量化只能在API里实现，有序有没有加入GUI的计划呀？

**Comment by heliqi** [comment]
是的，目前量化只能用API的方式。

**Comment by CashBai** [comment]
> 是的，目前量化只能用API的方式。

后续会增加近GUI内吗？

**Comment by heliqi** [comment]
后续会增加进GUI内。 需要等paddleslim那边发布新版本，解决兼容性问题，可能要等一段时间
