### ISSUE TITLE
C++部署遇到的问题解决方案

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1204]
最新的Cuda11.0  C++预测库

需要将lib的cudnn.lib放到cuda的lib中，

也需要将bin文件夹中的dll
放到cuda的bin中才可以运行。

**Comment by heliqi** [comment]
这个是搭建GPU环境必须的操作， cudnn安装就是将下载的bin和lib文件分别拷贝到cuda对应目录中。 百度搜cudnn安装， 应该有很多文章介绍
