### ISSUE TITLE
paddlex二次开发

### ISSUE THREAD

**Issue by liangruofei** [PaddlePaddle/PaddleX#1205]
各位大佬：
       想对paddlex的GUI进行二次开发，删除一些不需要的应用功能，做成一个简化版进行展示，请问，paddlex支持吗，支持的话，在哪快有入口提供了接口，感谢！！！

**Comment by lailuboy** [comment]
具体详细需求能再更细一些吗，我们看怎么能帮助到您。目前PaddleX有提供RESTful方式以及HTML开源示例代码，看是否满足(https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/static/paddlex_restful/restful/templates/paddlex_restful_demo.html)。
