### ISSUE TITLE
paddlex read_meter segmentation problem

### ISSUE THREAD

**Issue by xywlpo** [PaddlePaddle/PaddleX#1206]
您好，我在使用paddlex的read_meter例子的时候，使用您提供的预训练好的模型进行推理试验，图片使用的是您提供的测试集，发现检测模型可以正常定位，但是分割模型无法分割刻度和指针，请问是什么原因？下面是原图的识别结果
![visualize_1634281873605](https://user-images.githubusercontent.com/728405/137447545-2966fdba-b378-4d01-882d-d0827e0b33f1.jpg)
下面是其中一个表计的分割结果，其中黑色为背景0，灰色为指针1，刻度我设置250像素值
![seg](https://user-images.githubusercontent.com/728405/137447655-0dbbbeea-2ecd-4645-a509-def8d6b0a0b7.jpg)
模型文件采用的是：是否跟动态图模型或静态图模型有关，但是我没有找到其他的模型文件下载地址
![截屏2021-10-15 下午3 19 40](https://user-images.githubusercontent.com/728405/137447917-81403a9d-ea03-4204-beca-9c8ae40c6dcc.png)
当前的paddlepaddle采用2.1.3版本，paddlex采用的是2.0.0版本，非常感谢您的解答

**Comment by FlyingQianMM** [comment]
麻烦给下运行命令，我们复现下

**Comment by fengqinglun** [comment]
我也是出现了同样的问题

**Comment by fengqinglun** [comment]
python reader_infer.py --det_model_dir output/ppyolov2_r50vd_dcn/best_model --seg_model_dir output/deeplabv3p_r50vd/best_model/ --image meter_det/test/20190822_105.jpg

**Comment by FlyingQianMM** [comment]
了解，我们尽快复现定位问题

**Comment by FlyingQianMM** [comment]
该问题已经修复，见pr https://github.com/PaddlePaddle/PaddleX/pull/1222

使用最新的代码，可参考文档[PaddleX develop安装](https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/docs/install.md#paddlex-develop%E5%AE%89%E8%A3%85)

**Comment by fengqinglun** [comment]
thx
