### ISSUE TITLE
model_infer.dll生成问题&调用问题

### ISSUE THREAD

**Issue by jimmytyt** [PaddlePaddle/PaddleX#1207]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？
否
    * 您是否在demo基础上修改代码内容？还请您提供运行的代码
否
2. c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？
可运行，但编译出来的model_infer.dll调用失败（其中编译生成dll时，模式为X64-release，cmakelists.txt中122行代码修改为add_library(model_infer SHARED ./model_infer.cpp ${SRC} ${ENGINE_SRC} ${DETECTOR_SRC} ${ENCRYPTION_SRC})，否则无法编译得到.DLL）。
    * 您是否在demo基础上修改代码内容？还请您提供运行的代码
否
    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？
还未
3. 您使用的**模型**和**数据集**是？
paddleX桌面版训练得到的分类模型
4. 请提供您出现的报错信息及相关log

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号
PP2.1.3；PX2.0；PYTHON3.8
2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号
PaddleInference 10.2
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows
4. 请问您使用的CUDA/cuDNN的版本号是？
10.2/7.6

**Comment by heliqi** [comment]
具体的报错信息是？

**Comment by jimmytyt** [comment]
![image](https://user-images.githubusercontent.com/18440163/137835167-982edd5f-d397-4bb2-8eec-9b2b6c684fe2.png)
上图是调用InitModel()前；
以下是调用时报错结果（错误没有被catch到）：
“WinFormsApp_final.exe”(CoreCLR: DefaultDomain): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Private.CoreLib.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“E:\PaddleX\examples\C#_deploy\C#\bin\x64\Debug\net5.0-windows\WinFormsApp_final.dll”。已加载符号。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\System.Windows.Forms.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\System.Windows.Forms.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.InteropServices.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Drawing.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Collections.Specialized.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\System.Drawing.Common.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Threading.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Diagnostics.TraceSource.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Collections.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\Microsoft.Win32.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.EventBasedAsync.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Threading.Thread.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\Accessibility.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.Extensions.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Memory.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\Microsoft.Win32.SystemEvents.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\zh-Hans\System.Windows.Forms.resources.dll”。模块已生成，不包含符号。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.TypeConverter.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Buffers.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ObjectModel.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Linq.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Private.Uri.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Collections.NonGeneric.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.Serialization.Formatters.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.CompilerServices.Unsafe.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.IO.FileSystem.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
程序“[24712] WinFormsApp_final.exe”已退出，返回值为 -529697949 (0xe06d7363) 'Microsoft C++ Exception'。

**Comment by jimmytyt** [comment]
> 具体的报错信息是？
![image](https://user-images.githubusercontent.com/18440163/137838419-4532196f-c2e1-4abc-9c9a-72d08b54a6ba.png)
上图是调用InitModel()前；
以下是调用时报错结果（错误没有被catch到）：
“WinFormsApp_final.exe”(CoreCLR: DefaultDomain): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Private.CoreLib.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“E:\PaddleX\examples\C#_deploy\C#\bin\x64\Debug\net5.0-windows\WinFormsApp_final.dll”。已加载符号。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\System.Windows.Forms.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\System.Windows.Forms.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.InteropServices.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Drawing.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Collections.Specialized.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\System.Drawing.Common.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Threading.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Diagnostics.TraceSource.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Collections.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\Microsoft.Win32.Primitives.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.EventBasedAsync.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Threading.Thread.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\Accessibility.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.Extensions.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Memory.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\Microsoft.Win32.SystemEvents.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.11\zh-Hans\System.Windows.Forms.resources.dll”。模块已生成，不包含符号。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.TypeConverter.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ComponentModel.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Buffers.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.ObjectModel.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Linq.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Private.Uri.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Collections.NonGeneric.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.Serialization.Formatters.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.Runtime.CompilerServices.Unsafe.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.11\System.IO.FileSystem.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“WinFormsApp_final.exe”(CoreCLR: clrhost): 已加载“D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
程序“[24712] WinFormsApp_final.exe”已退出，返回值为 -529697949 (0xe06d7363) 'Microsoft C++ Exception'。

**Comment by heliqi** [comment]
调用initmodel就报错了？你是paddlex导出的模型还是paddle clas导出的模型。如果是paddlex导出，model_type传paddlex。

可以增加断点，或者日志来定位具体在c++哪里报错

**Comment by jimmytyt** [comment]
> 调用initmodel就报错了？你是paddlex导出的模型还是paddle clas导出的模型。如果是paddlex导出，model_type传paddlex。
> 
> 可以增加断点，或者日志来定位具体在c++哪里报错

是的，调用initmodel就报错了。是paddlex导出的模型。下面两个文件需要有什么修改吗（比如model_type）？
![image](https://user-images.githubusercontent.com/18440163/137851603-9d7e9ab6-3824-453f-9dfd-6b899598013e.png)
![image](https://user-images.githubusercontent.com/18440163/137851706-f0b9b26c-c651-4455-b4cb-f16a825b3f04.png)

我的断点就是打在initmodel()处，执行该行代码会需要几秒钟，然后直接程序终止界面退出，输出：。。。。程序“[24712] WinFormsApp_final.exe”已退出，返回值为 -529697949 (0xe06d7363) 'Microsoft C++ Exception'。

**Comment by heliqi** [comment]
不是改这个配置文件， 是你图片中的InitModel中的model_type参数需要改为paddlex。

**Comment by jimmytyt** [comment]
> 不是改这个配置文件， 是你图片中的InitModel中的model_type参数需要改为paddlex。

![image](https://user-images.githubusercontent.com/18440163/137853121-5e12c2cd-fb4b-4245-a219-03de43825ffe.png)
InitModel中的model_type就是paddlex。
另外，这个界面会产生 WinFormsApp_final.dll？

**Comment by jimmytyt** [comment]
> 不是改这个配置文件， 是你图片中的InitModel中的model_type参数需要改为paddlex。

![image](https://user-images.githubusercontent.com/18440163/137880469-4a407ac1-2ff0-4b55-af92-c31281f792d6.png)
引发异常的是 WinFormsApp_final.dll？为啥不是.exe呢？
![image](https://user-images.githubusercontent.com/18440163/137880766-bc7988c0-628c-4cbb-8a7e-79bf086f2ca8.png)
项目属性配置的是.exe呀，奇怪了。

**Comment by heliqi** [comment]
1. 你最开始截图中的model_type参数确实是clas，不是paddlex
2. 没有c++的报错信、日志等信息，没法帮你定位。
    以下两种方法建议选一个：
    a. 直接编译c++的demo，然后用demo对模型进行推理预测， 这个是有日志和相关报错信息的。如果c++没问题再编译成dll，给C#调用
    b. 如果只想编译dll给c#，那你需要在各个地方增加打印， debug下看看报错是哪哪一句导致的。 
       InitModel还不够，得定位到InitModel里边哪里的问题。

**Comment by jimmytyt** [comment]
> 1. 你最开始截图中的model_type参数确实是clas，不是paddlex
> 2. 没有c++的报错信、日志等信息，没法帮你定位。
>    以下两种方法建议选一个：
>    a. 直接编译c++的demo，然后用demo对模型进行推理预测， 这个是有日志和相关报错信息的。如果c++没问题再编译成dll，给C#调用
>    b. 如果只想编译dll给c#，那你需要在各个地方增加打印， debug下看看报错是哪哪一句导致的。
>    InitModel还不够，得定位到InitModel里边哪里的问题。

发现了一个问题**You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.**
在用cmake生成工程的时候已经指定了TensorRT路径，这里提示未发现，是需要把TensorRT的那些文件放到C#工程里吗？

**Comment by jimmytyt** [comment]
原因找到了，CUDA版本问题，我这里有10.1和10.2，默认选择了10.1，改成10.2就OK了。
![image](https://user-images.githubusercontent.com/18440163/138070964-7fed0b78-a4b0-4e7f-9a03-9bf9d087f02a.png)

**Comment by Weituo666** [comment]
> 原因找到了，CUDA版本问题，我这里有10.1和10.2，默认选择了10.1，改成10.2就OK了。 ![image](https://user-images.githubusercontent.com/18440163/138070964-7fed0b78-a4b0-4e7f-9a03-9bf9d087f02a.png)

你好，请问怎么更改版本呢。我遇到了和你一样的问题
