### ISSUE TITLE
不同API推理速度问题

### ISSUE THREAD

**Issue by careylipu** [PaddlePaddle/PaddleX#1209]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题

在AI Studio GPU 环境下 ，不算模型加载时间，推理速度 代码1每帧0点几秒，代码2每帧3-4秒，另外Hub Convert 产生的模型通过Serving部署成API，推理速度每张照片也要3-4秒。请问是什么原因，谢谢！

代码1：
model = pdx.load_model('work/predict/ppyolov2_r50vd_dcn/inference_model')
result = model.predict(frame)    

代码2：
predictor = pdx.deploy.Predictor('work/predict/ppyolov2_r50vd_dcn/inference_model')
result = predictor.predict(frame)

**Comment by will-jl944** [comment]
代码`1`仅用于验证模型效果，在GPU环境下会默认使用GPU，但并未提供任何加速手段。

代码`2`用于模型部署，默认使用CPU，可以通过设置`use_gpu=True`使用GPU，同时也提供了MKL、TensorRT等加速手段供选择，详见[文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/python_deploy.md)。

PaddleX的PaddleHub Serving部署目前仅支持CPU，后续将支持GPU以及各种加速手段的接口。

综上，追求性能的情况下建议使用代码`2`，或者[C++部署](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp#readme)。

**Comment by careylipu** [comment]
谢谢
