### ISSUE TITLE
examples/meter_reader/train_segmentation.py 不支持多gpu训练模式

### ISSUE THREAD

**Issue by Amanda-Barbara** [PaddlePaddle/PaddleX#1210]
你好，我在examples/meter_reader/train_segmentation.py代码的第一行添加了
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1' # 同时使用第0、1、3号GPU卡进行训练
```
但是在训练的过程中并没有启动多个GPU，还是默认的启动设备号为0的gpu进行训练，想请教一下该如何修改，谢谢。

**Comment by will-jl944** [comment]
请参考[训练文档](https://github.com/PaddlePaddle/PaddleX/tree/release/2.0.0/tutorials/train#%E5%BC%80%E5%A7%8B%E8%AE%AD%E7%BB%83)。

**Comment by Amanda-Barbara** [comment]
@will-jl944 好的，多谢指点。
