### ISSUE TITLE
BML CodeLab官方环境报错：CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by careylipu** [PaddlePaddle/PaddleX#1211]
## 描述问题

环境：百度官方 AI Studio BML CodeLab GPU:v100 16G显存
Python: 3.7.4
框架版本:PaddlePaddle 2.1.2
PaddleX:2.0.0

今天测试推理报错，同样的代码昨天天还可以，请问是官方 Codelab镜像模板问题吗

报错如下：
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:99)

**Comment by careylipu** [comment]
aistudio@jupyter-599111-2395150:~/PaddleX$ nvidia-smi
Wed Oct 20 15:25:41 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   34C    P0    38W / 300W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
aistudio@jupyter-599111-2395150:~/PaddleX$

**Comment by FlyingQianMM** [comment]
看起来是驱动版本过低，可至 AI Studio BML CodeLab反馈下

**Comment by careylipu** [comment]
现在需要自己重新安装 一边 PaddlePandle-gpu框架，才能运行。默认的报错。麻烦你替我给 AI Studio BML CodeLab反馈一下。
