### ISSUE TITLE
C++部署，检测目标框会偏移

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1214]
安装Windows预测库  

预测库(2.1.1版本)
cuda11.0_cudnn8_avx_mkl_trt7 

预测之后

预测的时候  框  会偏移到 目标的上方
不会对齐

这种我应该联系谁  需要发送模型和图片给你们吗

**Comment by FlyingQianMM** [comment]
预测结果可视化参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)

预测结果我们也测试过可视化，不会出现这种偏移到目标上方的明显误差
