### ISSUE TITLE
有没有PaddleX 2.0.0版本 关于自动超参数寻优的API

### ISSUE THREAD

**Issue by oruchimaru420** [PaddlePaddle/PaddleX#1216]
## 描述问题
我想使用PaddleX来进行语义分割的自动超参数寻优，请问有没有相关的API具有该功能？
烦请给出相关的链接或API函数名
非常感谢！

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
Yes
2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
Yes
3. 您使用的数据集是？
自定义数据集
4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddlepaddle-gpu==2.1.3post110
paddlex==2.0.0
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Win10
3. 请问您使用的Python版本是？
Python 3.7
5. 请问您使用的CUDA/cuDNN的版本号是？
CUDA 11.0

**Comment by FlyingQianMM** [comment]
PaddleX目前没有自动超参数寻优功能
