### ISSUE TITLE
预览测试图片中，中文显示成问号

### ISSUE THREAD

**Issue by lx1054331851** [PaddlePaddle/PaddleX#1217]
## 复现
![image](https://user-images.githubusercontent.com/12423206/138622038-f510caf0-f9b8-4a8f-bbc1-530d64487ffe.png)

2. 请提供您使用的GUI版本号
![image](https://user-images.githubusercontent.com/12423206/138622087-cbb5c49a-bab7-4a1c-9e2c-aad20d9cdad2.png)

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
win11

**Comment by yzl19940819** [comment]
您好，标签使用最好使用英文。

**Comment by lx1054331851** [comment]
好的，谢谢！
