### ISSUE TITLE
安全漏洞（Security Vulnerability）

### ISSUE THREAD

**Issue by haby0** [PaddlePaddle/PaddleX#1218]
请问报告安全漏洞的联系人是谁？谢谢！

What would be the right contact to report a security vulnerabilty? thanks!

**Comment by yzl19940819** [comment]
你好，我是PaddleX的产品经理，具体的安全漏洞是？可微信联系 17854262968

**Comment by FlyingQianMM** [comment]
目前我们提供的restful api示例了前后端解耦的一种使用方式，您可根据实际的部署场景再行自定义修改下。您提到的安全问体，目前可以再限制下只能读取图像文件以及当前用户目录

**Comment by haby0** [comment]
> 目前我们提供的restful api示例了前后端解耦的一种使用方式，您可根据实际的部署场景再行自定义修改下。

我不使用`PaddleX`，只是发现了安全问题。

> 您提到的安全问体，目前可以再限制下只能读取图像文件以及当前用户目录。

你们会修复这个安全问题是吗？

**Comment by FlyingQianMM** [comment]
感谢您指出问题。另外想问下，您了解PaddleX restful api是出于什么使用场景？

**Comment by haby0** [comment]
> 感谢您指出问题。另外想问下，您了解PaddleX restful api是出于什么使用场景？

你可以联系@yzl19940819 ，hi上联系（沟通更快速），谢谢
