### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#1219]
在实际项目中由于推理图片小且很多，paddlex无法同时推理多张图片(好像也可以设置多张推理，但测试发现时间并没有减少），相对而言，pytorch在部署的时候可以设置较大的batchsize同时推理多张图(感觉是GPU并行？），算下来推理时间成多倍的减少，paddlex是否可以在这方面进行改进，谢谢

**Comment by FlyingQianMM** [comment]
多卡多模推理可以看下 https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/deploy/cpp/docs/demo/multi_gpu_model_infer.md

![image](https://user-images.githubusercontent.com/22235422/138647648-5376be20-8789-4798-b3b8-fdb903e51ff1.png)
