### ISSUE TITLE
pycharm客户端闪退

### ISSUE THREAD

**Issue by Amanda-Barbara** [PaddlePaddle/PaddleX#1221]
使用pycharm调试或运行paddlex代码，不管调整显存或者内存的大小以及修改进程数worker的大小，终止时pycharm客户端会闪退，想请教一下是什么原因，谢谢！

**Comment by FlyingQianMM** [comment]
直接在终端运行呢？

**Comment by Amanda-Barbara** [comment]
@FlyingQianMM 终端运行是可以的，但是想用pycharm进行调试，其他的工程都可以在pycharm运行或者调试时终止而不会闪退，

**Comment by FlyingQianMM** [comment]
建议基于终端进行调试，可采用加打印的方式。
