### ISSUE TITLE
 PaddleX训练好的模型支持在百度EdgeBoard硬件上部署推理吗？

### ISSUE THREAD

**Issue by careylipu** [PaddlePaddle/PaddleX#1223]
PaddleX训练好的模型支持在百度EdgeBoard硬件上部署推理吗？

**Comment by FlyingQianMM** [comment]
大部分飞桨模型都是支持的，包括图像分类、分割，目标检测的YOLO系列，具体支持的模型列表可以咨询下[EdgeBoard](https://ai.baidu.com/tech/hardware/deepkit)

**Comment by careylipu** [comment]
请问Jetson 平台如何部署模型，github文档里没有这方面的内容
