### ISSUE TITLE
环境问题：import paddlex as pdx 总是报错 

### ISSUE THREAD

**Issue by he655** [PaddlePaddle/PaddleX#1224]
报错内容：
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/parallel.py:119: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
---------------------------------------------------------------------------ModuleNotFoundError                       Traceback (most recent call last)<ipython-input-2-17e5292c8539> in <module>
----> 1 import paddlex as pdx
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/__init__.py in <module>
     18 init_parallel_env()
     19 
---> 20 from . import cv
     21 from . import seg
     22 from . import cls
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from . import models
     16 from . import transforms
     17 from . import datasets
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/__init__.py in <module>
     13 # limitations under the License.
     14 
---> 15 from .segmenter import *
     16 from .classifier import *
     17 from .detector import *
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/segmenter.py in <module>
     23 import paddlex.paddleseg as paddleseg
     24 import paddlex
---> 25 from paddlex.cv.transforms import arrange_transforms
     26 from paddlex.utils import get_single_card_bs, DisablePrint
     27 import paddlex.utils.logging as logging
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/transforms/__init__.py in <module>
     14 
     15 from .operators import *
---> 16 from .batch_operators import BatchRandomResize, BatchRandomResizeByShort, _BatchPadding
     17 from paddlex.cv import transforms as T
     18 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/transforms/batch_operators.py in <module>
     20 except Exception:
     21     from collections import Sequence
---> 22 from paddle.fluid.dataloader.collate import default_collate_fn
     23 from .operators import Transform, Resize, ResizeByShort, _Permute, interp_dict
     24 from .box_utils import jaccard_overlap
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

注：
1.PaddlePaddle版本为2.0.2  
2.python版本为3.7  
3.PaddleX版本为2.0.0
4.Windows平台运行
5.使用的CPU

**Comment by geoexploring** [comment]
我也遇见同样的问题，也就是在AI Studio里创建新项目时，`! pip install paddlex==2.0.0`后`import paddlex as pdx`，会出现上述问题。

但是当我Fork一个新项目（比如[PaddleX2.0快速上手-DeepLabV3+语义分割](https://aistudio.baidu.com/aistudio/projectdetail/2160249?channelType=0&channel=0)）后，运行该项目中的上述步骤（`! pip install paddlex==2.0.0`和`import paddlex as pdx`），则不会出现上述问题

**Comment by FlyingQianMM** [comment]
请检查下当前的python环境下安装的paddle是否是>=2.0版本的

**Comment by will-jl944** [comment]
paddlepaddle版本需要>=2.1.2才可以使用paddlex 2.0.0

**Comment by Kenkaowei** [comment]
请问这个问题咋解决？我也是遇到这个问题

**Comment by Kenkaowei** [comment]
> paddlepaddle版本需要>=2.1.2才可以使用paddlex 2.0.0

还是不行哈
