### ISSUE TITLE
使用tenosrrt_infer推理报错。

### ISSUE THREAD

**Issue by lpt-hub** [PaddlePaddle/PaddleX#1225]
环境：win10,cuda11,paddleseg2.3,paddlex2.0,bisenetv2

模型导出命令：python export.py --config configs\quick_start/bisenet_optic_disc_512x512_1k-100000.yml --model_path output\best_model\model.pdparams --input_shape 1 3 1024 1024 --save_dir output

推理命令：tensorrt_infer.exe --model_filename=model/model.pdmodel --params_filename=model/model.pdiparams --cfg_file=model/deploy.yaml --image=Z:\Member_dir\lpt\paddle\dataset\saveImg/1.jpg --model_type=seg

报错报错情况：
![image](https://user-images.githubusercontent.com/63625557/139169762-9b5d37e5-b4ef-4086-9792-6a0cc1c7ae99.png)

**Comment by heliqi** [comment]
请把报错前面一起截全给我看看

你是用paddle seg导出的模型？

**Comment by lpt-hub** [comment]
> 请把报错前面一起截全给我看看
> 
> 你是用paddle seg导出的模型？

是的，用paddleseg的export导出模型的。
报错截图：
![github](https://user-images.githubusercontent.com/63625557/139178464-f49f78c6-cff3-4873-a464-81aa5e7b846b.jpg)

**Comment by lpt-hub** [comment]
模型的输入输出：
![image](https://user-images.githubusercontent.com/63625557/139181508-e22e41f2-dc27-4b17-afd4-1d90e34e62e1.png)

**Comment by lpt-hub** [comment]
![image](https://user-images.githubusercontent.com/63625557/139181682-d75d96f8-7ddd-4886-902d-7c983575c9f7.png)

**Comment by heliqi** [comment]
1.除了输入x节点的shape，你应该手动填写了其他四个节点的max min optim input_shape（可以三个先填一样的，跑通后再支持范围的shape）。请对照可视化软件中shape信息，看填写是否正确。 一般报错都是填写问题

2.cuda11 cudnn8对应的trt应该是7.2（inference包里有个version.txt文件，里边也有版本信息），检查下trt版本。

**Comment by hanhan1990** [comment]
> 模型的输入输出： ![image](https://user-images.githubusercontent.com/63625557/139181508-e22e41f2-dc27-4b17-afd4-1d90e34e62e1.png)

老铁 你这个问题解决了吗

**Comment by hanhan1990** [comment]
> 环境：win10,cuda11,paddleseg2.3,paddlex2.0,bisenetv2
> 
> 模型导出命令：python export.py --config configs\quick_start/bisenet_optic_disc_512x512_1k-100000.yml --model_path output\best_model\model.pdparams --input_shape 1 3 1024 1024 --save_dir output
> 
> 推理命令：tensorrt_infer.exe --model_filename=model/model.pdmodel --params_filename=model/model.pdiparams --cfg_file=model/deploy.yaml --image=Z:\Member_dir\lpt\paddle\dataset\saveImg/1.jpg --model_type=seg
> 
> 报错报错情况： ![image](https://user-images.githubusercontent.com/63625557/139169762-9b5d37e5-b4ef-4086-9792-6a0cc1c7ae99.png)

老铁 你这个问题解决了吗 我也遇见相同问题
