### ISSUE TITLE
windows c++ tensorrt_infer

### ISSUE THREAD

**Issue by lvpinrui** [PaddlePaddle/PaddleX#1227]
hello,my  environment is cuda:10.2,cudnn:7.6,TensorRT:7.0.0.11,paddlex:2.0，paddle-inference:2.1
when i run model_infer demo is ok, i run tensorrt_infer failed.
my tensorrt_infer .cpp is:
#include <gflags/gflags.h>
#include <string>
#include <vector>
#include "model_deploy/common/include/paddle_deploy.h"
DEFINE_string(model_filename, "D:\\paddlex_20211026\\PaddleX-2.0.0\\deploy\\cpp\\build\\paddle_deploy\\yolov3_mbv1\\model\\model.pdmodel", "Path of det inference model");
DEFINE_string(params_filename, "D:\\paddlex_20211026\\PaddleX-2.0.0\\deploy\\cpp\\build\\paddle_deploy\\yolov3_mbv1\\model\\model.pdiparams", "Path of det inference params");
DEFINE_string(cfg_file, "D:\\paddlex_20211026\\PaddleX-2.0.0\\deploy\\cpp\\build\\paddle_deploy\\yolov3_mbv1\\model\\infer_cfg.yml", "Path of yaml file");
DEFINE_string(model_type, "det", "model type");
//DEFINE_string(image, "D:\\paddlex_20211026\\PaddleX-2.0.0\\deploy\\cpp\\build\\paddle_deploy\\20190822_105.jpg", "Path of test image file");
DEFINE_string(image, "D:\\paddlex_20211026\\PaddleX-2.0.0\\deploy\\cpp\\build\\paddle_deploy\\yolov3_mbv1\\images\\000000010707.jpg", "Path of test image file");
DEFINE_int32(gpu_id, 0, "GPU card id");
int main(int argc, char** argv) {
  // Parsing command-line
  google::ParseCommandLineFlags(&argc, &argv, true);
  std::cout << "*******line31" << std::endl;
  // create model
  PaddleDeploy::Model* model = PaddleDeploy::CreateModel(FLAGS_model_type);
  std::cout << "*******line34" << std::endl;
  // model init
  model->Init(FLAGS_cfg_file);
  std::cout << "*******line37" << std::endl;
  // inference engine init
  PaddleDeploy::PaddleEngineConfig engine_config;
  engine_config.model_filename = FLAGS_model_filename;
  engine_config.params_filename = FLAGS_params_filename;
  engine_config.gpu_id = FLAGS_gpu_id;
  engine_config.use_gpu = true;
  engine_config.use_trt = true;
  engine_config.precision = 0;
  engine_config.min_subgraph_size = 10;
  engine_config.max_workspace_size = 1 << 30;
  std::cout << "**********ten line49" << std::endl;

  if ("clas" == FLAGS_model_type) {
    // Adjust shape according to the actual model
    engine_config.min_input_shape["inputs"] = {1, 3, 224, 224};
    engine_config.max_input_shape["inputs"] = {1, 3, 224, 224};
    engine_config.optim_input_shape["inputs"] = {1, 3, 224, 224};
  } else if ("det" == FLAGS_model_type)
  {
      std::cout << "**********ten line63" << std::endl;
    // Adjust shape according to the actual model
    engine_config.min_input_shape["image"] = {1, 3, 608, 608};
    engine_config.max_input_shape["image"] = {1, 3, 608, 608};
    engine_config.optim_input_shape["image"] = {1, 3, 608, 608};
  } else if ("seg" == FLAGS_model_type) 
  {
    engine_config.min_input_shape["x"] = {1, 3, 100, 100};
    engine_config.max_input_shape["x"] = {1, 3, 2000, 2000};
    engine_config.optim_input_shape["x"] = {1, 3, 1024, 1024};
    // Additional nodes need to be added, pay attention to the output prompt
  }
  std::cout << "**********ten line93" << std::endl;

  // 上面报错，配置文件填写示例
    engine_config.min_input_shape["nearest_interp_v2_0.tmp_0"] = { 1,256, 19, 19 };
    engine_config.max_input_shape["nearest_interp_v2_0.tmp_0"] = { 1,256, 38, 38 };
    engine_config.optim_input_shape["nearest_interp_v2_0.tmp_0"] = { 1,256,38,38 };
    engine_config.min_input_shape["nearest_interp_v2_1.tmp_0"] = { 1,128,38,38 };
    engine_config.max_input_shape["nearest_interp_v2_1.tmp_0"] = { 1,128,76,76 };
    engine_config.optim_input_shape["nearest_interp_v2_1.tmp_0"] = { 1,128, 76,76 };
    engine_config.min_input_shape["relu_8.tmp_0"] = { 1,256, 13, 13 };
    engine_config.max_input_shape["relu_8.tmp_0"] = { 1,256, 76, 76 };
    engine_config.optim_input_shape["relu_8.tmp_0"] = { 1,256, 3, 3 };
    engine_config.min_input_shape["relu_12.tmp_0"] = { 1,512, 13, 13 };
    engine_config.max_input_shape["relu_12.tmp_0"] = { 1,512, 38, 38 };
    engine_config.optim_input_shape["relu_12.tmp_0"] = { 1,512, 3, 3 };
  model->PaddleEngineInit(engine_config);
  std::cout << "**********ten line95" << std::endl;
  // prepare data
  std::vector<cv::Mat> imgs;
  imgs.push_back(std::move(cv::imread(FLAGS_image)));
  // predict
  std::vector<PaddleDeploy::Result> results;
  model->Predict(imgs, &results, 1);

  std::cout << results[0] << std::endl;

  delete model;
  return 0;
}

When I run tensorrt_infer demo, the following problem occurs,

![11111](https://user-images.githubusercontent.com/44189445/139171939-e65d2742-5d6e-4eec-9090-a0d77a91d8f6.jpg)

can you help me?waitting for your answer!,thanks!

**Comment by heliqi** [comment]
请问你是部署哪个套件的哪个模型？paddlex的分割模型？

看报错应该是min max input_shape设置的有问题。

**Comment by lvpinrui** [comment]
您好，我是按照这个链接PaddleX/windows.md at release/2.0.0 · PaddlePaddle/PaddleX · GitHub (fastgit.org)部署的，参照这个PaddleX/tensorrt_infer.md at release/2.0.0 · PaddlePaddle/PaddleX · GitHub (fastgit.org)运行的tensorrt_infer,下载的模型也是通过点击下面图片里面的下载下载下来的，保存是最大最小问题但是我已经通过模型查看工具更改值了，您能帮我看下我设置的值哪里有问题吗








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月28日(星期四) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] windows c++ tensorrt_infer (Issue #1227)





 
请问你是部署哪个套件的哪个模型？paddlex的分割模型？
 
看报错应该是min max input_shape设置的有问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvpinrui** [comment]
您好，我已经试出来了，是min，max shape改成一样了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月28日(星期四) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] windows c++ tensorrt_infer (Issue #1227)





 
请问你是部署哪个套件的哪个模型？paddlex的分割模型？
 
看报错应该是min max input_shape设置的有问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by heliqi** [comment]
min_input_shape 、max_input_shape修改正确后，已经可以了？

**Comment by lvpinrui** [comment]
是的是的，可以了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 晚上6:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] windows c++ tensorrt_infer (Issue #1227)





 
min_input_shape 、max_input_shape修改正确后，已经可以了？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
