### ISSUE TITLE
S2ANet用于检测旋转框的  c++推理结果不对

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleX#1229]
S2ANet用于检测旋转框的 用python推理ouput的图片显示是准确的
c++推理结果如下      但是看不出这些数值哪个是中心点   哪个是长宽   哪个是角度
![HDOSOHASE~{2YFEL@VG`~NH](https://user-images.githubusercontent.com/88479008/139364169-7a524271-256c-443b-a6a5-2a14fabe8bdb.png)

std::string model_type = "det";

是哪里的配置不对吗？

**Comment by heliqi** [comment]
https://github.com/PaddlePaddle/PaddleX/blob/release/2.0.0/deploy/cpp/docs/models/paddledetection.md 文档中有写，检测结果输出的值分别为： 类别id， 类别标签，置信度，xmin, ymin, width, height

**Comment by 534114658** [comment]
没角度？
S2ANet用于检测旋转框只能在python展示？  C++用不了？

**Comment by heliqi** [comment]
c++暂时没适配支持检测模型的旋转框
