### ISSUE TITLE
The third-party dynamic library (mklml.dll) that Paddle depends on is not configured 

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1232]
## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
2. 
paddlepaddle-gpu                  2.1.3.post112
paddleslim                        2.1.1
paddlex                           2.0.0

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
WIN10

3. 请问您使用的Python版本是？
python 3.7

5. 请问您使用的CUDA/cuDNN的版本号是？
cuda11.2 cudnn8

---------
```

2021-10-29 19:06:26 [INFO]      Model[FasterRCNN] loaded.
Exception in thread CAM_BENDI_00:
Traceback (most recent call last):
  File "C:\Users\hello\threading.py", line 932, in _bootstrap_inner
  File "C:\Users\hello\threading.py", line 870, in run
  File "C:\Users\hello\hello_class.py", line 4999, in Work_threadai_0
  File "C:\Users\hello\paddlex\deploy.py", line 64, in __init__
    self.predictor = self.create_predictor(
  File "C:\Users\hello\paddlex\deploy.py", line 126, in create_predictor

    predictor = create_predictor(config)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly. (error code is 182)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release3\paddle\fluid\platform\dynload\dynamic_loader.cc:265)

```

用户安装了线描相机的软件和驱动之后   paddle就报错

python环境是这样的问题

之前打包好独立的EXE环境 也是一样的错误

conda新建环境不行  

重新安装cuda+cudnn 也不行

**Comment by lmw0320** [comment]
@monkeycc  你好，请问你这个问题解决了么？ 我是使用multiprocessing模块时，遇到了这个报错。。用threading模块就不会。。感觉很迷糊。。---我是用paddlepaddle库做文本检测的，没有用到paddleX...我只是想请教下，你是怎么解决这个问题的。。
常规情况下，我使用GPU是没有报错的。。

**Comment by monkeycc** [comment]
@lmw0320 
直接把线描相机的软件和驱动 删除就好了
CPU加速的模块 有冲突

multiprocessing模块时，遇到了这个报错。。用线程模块就不会

multiprocessing的时候，初始化模型放在主程序，预测放在multiprocessing进程

**Comment by lmw0320** [comment]
> 

没太明白您的意思:
1.  要删除线描相机的软件和驱动？？ 哪个才是？？我貌似没安装过啊？（win10企业版）
2.  我的线程和进程操作，都是你说的那样，初始化模型放在主程序，然后把这个变量传入具体的进程函数中。进程函数内进行具体的预测操作。
![1](https://user-images.githubusercontent.com/37755235/157218123-c53f7513-df7e-4e56-b926-9a599f743116.png)
![2](https://user-images.githubusercontent.com/37755235/157218129-a12eb1fd-4539-4a34-a7e1-054d514a4d68.png)

**Comment by changmaoguai** [comment]
paddlepaddle验证通过，
Running verify PaddlePaddle program ...
W1208 13:21:04.446607 14284 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W1208 13:21:04.450608 14284 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.

但运行Paddleocr的时候报错，
RuntimeError: (PreconditionNotMet) The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly.(error code is 126)

没有多进程，没有多线程。
paddlepaddle-gpu==2.4.0.post117
paddleocr             2.6.1.1

**Comment by MiShiDeHaiLuo** [comment]
您好，请问您解决了吗？

**Comment by monkeycc** [comment]
应该是某个软件
增加了系统环境
导致有冲突的地方

可以删除一部分系统环境设置
排除一下

**Comment by Heryk13** [comment]
https://learn.microsoft.com/ja-jp/cognitive-toolkit/setup-mkl-on-windows
downloading from here worked for me
