### ISSUE TITLE
Jetson 平台如何部署模型

### ISSUE THREAD

**Issue by careylipu** [PaddlePaddle/PaddleX#1233]
请问Jetson 平台如何部署模型，github文档里没有这方面的内容

**Comment by lailuboy** [comment]
可以参考这里的文档说明：https://paddlex.readthedocs.io/zh_CN/release-1.3/deploy/jetson/index.html

**Comment by careylipu** [comment]
> 可以参考这里的文档说明：https://paddlex.readthedocs.io/zh_CN/release-1.3/deploy/jetson/index.html

2.0版本支持吗，这文档看到了不知道2.0版本支持吗，也是类似的方式还是2.0不支持了，还请解答下困惑，谢谢啦

**Comment by lailuboy** [comment]
2.0部署时也是转为静态图去部署，流程上是一样的。

**Comment by careylipu** [comment]
> 2.0部署时也是转为静态图去部署，流程上是一样的。


文档里提到的PaddlePaddle C++ 预测库是1.6.2的，请问哪里有2.0的


Step2: 下载PaddlePaddle C++ 预测库 paddle_inference
目前PaddlePaddle为Nvidia Jetson提供了一个基于1.6.2版本的C++ 预测库。

**Comment by FlyingQianMM** [comment]
关于jetson部署代码和文档，还在review中。你这边可以参考pr https://github.com/PaddlePaddle/PaddleX/pull/1220 先跑下试试
