### ISSUE TITLE
PaddleDection 训练的模型怎么在 paddlex上使用呢？

### ISSUE THREAD

**Issue by xiayongtao** [PaddlePaddle/PaddleX#1235]
问题类型：模型部署
问题描述

========================
paddleDection 导出的模型可以在paddlex上部署使用吗？

导出模型结构如图：
![image](https://user-images.githubusercontent.com/11712819/140007899-557ed1d2-9573-4e2f-9752-2817b26a8a3b.png)

**Comment by FlyingQianMM** [comment]
picodet我们还未适配。想问下转到paddlex上部署是想要用哪块部署能力？
