### ISSUE TITLE
如何使用其他的优化器在paddlex里面

### ISSUE THREAD

**Issue by QIANXUNZDL123** [PaddlePaddle/PaddleX#1236]
optimizer=paddle.optimizer.adamw,我想使用其他的优化器，但是总是报错。。。

AttributeError: 'tuple' object has no attribute 'step'

不知道  optimizer这个地方该怎么设置

**Comment by FlyingQianMM** [comment]
参考issue https://github.com/PaddlePaddle/PaddleX/issues/1146 里的回答
