### ISSUE TITLE
C++部署预测结果有偏差

### ISSUE THREAD

**Issue by lv9618** [PaddlePaddle/PaddleX#1240]
使用PaddleX GUI 2.0.0 Windows10版本训练好一个模型，并在GUI中使用该模型对一副图像进行测试，得到第一个结果。
发布该模型，使用C++部署代码model_infer进行测试，得到第二个结果。
这两个结果有偏差，从效果上看第一个结果更优。
C++部署环境中使用OpenCV3.4.6和4.1.2两个版本均进行了测试，结果相同，差于GUI自带测试结果。

**Comment by FlyingQianMM** [comment]
请提供下模型的model.yml文件

> 并在GUI中使用该模型对一副图像进行测试，得到第一个结果

这个是指在GUI里面测试图片得到的可视化结果吗？

**Comment by lv9618** [comment]
Model: FasterRCNN
Transforms:
- Normalize:
    is_scale: true
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.229
    - 0.224
    - 0.225
- ResizeByShort:
    interp: LINEAR
    max_size: 1333
    short_size: 800
- Padding:
    im_padding_value:
    - 0.0
    - 0.0
    - 0.0
    label_padding_value: 255
    offsets: null
    pad_mode: 0
    size_divisor: 32
    target_size: null
_Attributes:
  eval_metrics:
    bbox_map: 99.67248080386764
  fixed_input_shape:
  - -1
  - 3
  - -1
  - -1
  labels:
  - '1'
  model_type: detector
  num_classes: 1
_init_params:
  anchor_sizes:
  - - 32
  - - 64
  - - 128
  - - 256
  - - 512
  aspect_ratios:
  - 0.5
  - 1.0
  - 2.0
  backbone: ResNet50_vd
  fpn_num_channels: 256
  keep_top_k: 100
  nms_threshold: 0.5
  num_classes: 1
  rpn_batch_size_per_im: 256
  rpn_fg_fraction: 0.5
  score_threshold: 0.05
  test_post_nms_top_n: 1000
  test_pre_nms_top_n: null
  with_dcn: false
  with_fpn: true
completed_epochs: 0
status: Infer
version: 2.0.0

环境：cuda10.2+cudnn 7.6.5+opencv3.4.6

GUI模式
name:1,score:0.9960533380508423,left:347,top:417,width:192,height:181
name:1,score:0.991341769695282,left:41,top:323,width:133,height:212

PaddleX API模式
{'bbox': [346.8389587402344, 418.053955078125, 192.76565551757812, 181.63543701171875], 'category': '1', 'category_id': 0, 'score': 0.9961109757423401}
{'bbox': [41.96996307373047, 322.5478820800781, 133.25267791748047, 213.82571411132812], 'category': '1', 'category_id': 0, 'score': 0.9914113283157349}

C++预测部署模式
Box(0   1       0.99605334      347.15164185    405.30029297    192.22769165    175.89398193)
Box(0   1       0.99134177      41.97715759     313.30499268    133.31355286    206.54565430)

**Comment by lv9618** [comment]
> 请提供下模型的model.yml文件
> 
> > 并在GUI中使用该模型对一副图像进行测试，得到第一个结果
> 
> 这个是指在GUI里面测试图片得到的可视化结果吗？

对，在2.0.0GUI里面修改部分代码，获得相关位置信息

**Comment by FlyingQianMM** [comment]
该问题已修复，见pr https://github.com/PaddlePaddle/PaddleX/pull/1253
