### ISSUE TITLE
报错：AttributeError: module 'paddlex' has no attribute 'MobileNetV3_small'

### ISSUE THREAD

**Issue by qing130** [PaddlePaddle/PaddleX#1242]
## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
是
2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
没修改。

3. 您使用的数据集是？
代码提供的
4. 请提供您出现的报错信息及相关log

Traceback (most recent call last):
  File "D:/qing/pyProject/test/test.py", line 38, in <module>
    model = pdx.MobileNetV3_small(num_classes=num_classes)
AttributeError: module 'paddlex' has no attribute 'MobileNetV3_small'

## 环境
1. 请提供您使用的PaddlePaddle和PaddleX的版本号
  PaddlePaddle：2.1.3
   Paddle： 2.0.0
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows
3. 请问您使用的Python版本是？
 3.8
5. 请问您使用的CUDA/cuDNN的版本号是？
11.0  

目前在官网下载的模型也不支持PaddleX2.0版本,相关文档也只是到1.3版本，请问这些什么时候能整好？

**Comment by will-jl944** [comment]
> model = pdx.MobileNetV3_small(num_classes=num_classes)

这里应该是`model = pdx.cls.MobileNetV3_small(num_classes=num_classes)`。

PaddleX 2.0.0文档见[https://github.com/PaddlePaddle/PaddleX#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3](https://github.com/PaddlePaddle/PaddleX#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)。
