### ISSUE TITLE
git checkout develop error: pathspec 'develop' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleX#1245]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by Williamlizl** [comment]
`pip uninstall paddlex
git clone https://github.com/PaddlePaddle/PaddleX.git
cd PaddleX
git checkout develop
git pull
pip install -r requirements.txt
python setup.py install`

git clone ，port 443: Connection timed out， then i download the paddleX, and unzip. but cd PaddleX, git checkout shows error,

**Comment by FlyingQianMM** [comment]
> then i download the paddleX, and unzip. but cd PaddleX, git checkout shows error

需要git clone才行，或者下载develop分支代码也可以
