### ISSUE TITLE
配置TensorRT的动态shape参数

### ISSUE THREAD

**Issue by lbq779660843** [PaddlePaddle/PaddleX#1250]
想请教一下，在TensorRT配置参数配置时，min_input_shape、max_input_shape、optim_input_shape 这三个参数是如何计算的。

能否以yolov3这个模型为例，如何在打开模型信息后，配置batch_norm_37.tmp_2等节点的参数
![捕获](https://user-images.githubusercontent.com/27773249/141440374-2ae899e6-0269-405e-94de-458f716a5389.JPG)
。

这个是我拿hrnet训练voc后，尝试用trt推理的信息
![1](https://user-images.githubusercontent.com/27773249/141440564-ff96ce51-4a7e-4ce8-8524-6825d97bf6e9.JPG)
。

**Comment by heliqi** [comment]
min_input_shape: 动态shape中最小的shape
max_input_shape：动态shape中最大的shape
optim_input_shape： 动态shape中最常见的shape
如果你的输入不会变化，固定为某个shape(比如 1,3,224,224)， 那输入节点的这三个参数都设置为同一个固定shape即可(比如1，3，224，224)。


后续节点的shape(比如图中的 batch_normal_37.tmp_2节点)，需要根据输入节点的shape推断。假设Netorn中的batch_norm节点就是batch_normal_37.tmp_2节点, 该节点的输入是 ?x256*38*38(实际你截图没截到，这个shape是输入shape)。 

输入假如都是是1，3，224，224(N, C, H, W)，代表batch是1:
min_input_shape['x']=(1,3,224,224)
max_input_shape['x']=(1,3,224,224)
optim_input_shape['x']=(1,3,224,224)
那么batch_normal_37.tmp_2节点的填写是:
min_input_shape['batch_normal_37.tmp_2']=(1,256,38,38)
max_input_shape['batch_normal_37.tmp_2']=(1,256,38,38)
optim_input_shape['batch_normal_37.tmp_2']=(1,256,38,38)

假如你的输入是动态变化(比如例子是动态shape)，那其它节点的min_input_shape、max_input_shape也要跟着成比例变化

**Comment by lbq779660843** [comment]
@heliqi 
谢谢，我先试一下。

**Comment by lbq779660843** [comment]
@heliqi 你好，yolov3的我调成功了，但是hrnet我还是有问题的。Hrnet不像yolov3,每次推理的时候，报错的输入节点都不一样。
![1](https://user-images.githubusercontent.com/27773249/142386470-30d37263-31cd-4338-9823-b72c39570090.JPG)

我两次运行hrnet的结果：
![11](https://user-images.githubusercontent.com/27773249/142386748-b215d7f5-06c8-4dc6-9cbc-4b6ce87afd0b.JPG)
![22](https://user-images.githubusercontent.com/27773249/142386758-c3ffb380-dbe9-4063-a025-e2484dcd8fe1.JPG)

**Comment by FlyingQianMM** [comment]
您好，Paddle Inference 2.1针对分割模型使用trt比较麻烦，整图切分成了多个子图，所以每个子图都需要设置输入shape。

![image](https://user-images.githubusercontent.com/22235422/142615440-f20e160d-0150-4bea-a1d4-6dce732d2147.png)

您截图中的这几个层都需要设置shape。
