### ISSUE TITLE
demo运行正常，自己训练的模型在服务器环境运行良好，转化为nb模型使用paddlex sdk 加载的时候程序崩溃，使用bugly没抓到c++日志，

### ISSUE THREAD

**Issue by SJJ-dot** [PaddlePaddle/PaddleX#1272]
demo运行正常，自己训练的模型在服务器环境运行良好，转化为nb模型使用paddlex sdk 加载的时候程序崩溃，使用bugly没抓到c++日志， #1272

**Comment by FlyingQianMM** [comment]
paddlex manufacture sdk目前仅支持用Paddle Inference推理引擎

**Comment by SJJ-dot** [comment]
忘记这个了，实际上是内存溢出了
