### ISSUE TITLE
模型训练的时候一直卡在Decompressing环节

### ISSUE THREAD

**Issue by metaire** [PaddlePaddle/PaddleX#1274]
原先在paddlex2.0训练时是可以的，由于一些原因，降级到1.3.11，并将cuda降到10.2，进行训练时候，却一直停在Decompressing output/yolov3_darknet53\pretrain\DarkNet53_ImageNet1k_pretrained.tar...
如图:
![微信图片_20211129202916](https://user-images.githubusercontent.com/34330583/143869163-786bfd87-2909-4e42-973e-06168f39e338.png)
不报错，也不继续。

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddle1.8.5,paddlex 1.3.11
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
window
3. 请问您使用的Python版本是？
3.7
5. 请问您使用的CUDA/cuDNN的版本号是？
cuda10.2 cudnn 7.6.5

**Comment by metaire** [comment]
耐心等待了过了十几分钟，报了RuntimeError: parallel_for failed: no kernel image is available for execution on the device

**Comment by FlyingQianMM** [comment]
> 原先在paddlex2.0训练时是可以的，由于一些原因，降级到1.3.11，并将cuda降到10.2

可以了解下是什么原因要回退版本呢？

> RuntimeError: parallel_for failed: no kernel image is available for execution on the device

你的卡是30系列的么？paddle1.8.5不支持30系列
