### ISSUE TITLE
picodet模型

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleX#1275]
paddle detection发布了picodet轻量级模型，请问paddlex什么时候支持？

**Comment by FlyingQianMM** [comment]
感谢关注PaddleX，您目前可以先使用PaddleDetection来体验picodet呢～

**Comment by Monday-Leo** [comment]
看到picodet已经加入了paddlex，什么时候发布新版本呢？

**Comment by FlyingQianMM** [comment]
PaddleX 2.1已经新增PicoDet。
