### ISSUE TITLE
训练失败的内存释放问题

### ISSUE THREAD

**Issue by ucsk** [PaddlePaddle/PaddleX#1279]
关于 PaddleX 模型的 `model.train()`，若过程中出现异常（如参数错误，数据未对齐等），数据仍在内存中得不到释放，需要重启内核。该问题导致在 Notebook 中的体验可能不会太好，未来请考虑能否修复这个问题。

**Comment by FlyingQianMM** [comment]
用的PaddleX和Paddle版本是多少呢？
