### ISSUE TITLE
使用PaddleX GUI各种报错

### ISSUE THREAD

**Issue by wyc880622** [PaddlePaddle/PaddleX#128]
1.用模型选择FasterRcnn 竟然不出来，只有yolo的Backbone选择
![image](https://user-images.githubusercontent.com/25219834/83491656-b2f32780-a4e4-11ea-85b8-74bd26ea3ae3.png)
2.在训练参数都设置好后，开始训练，就报如图所示错误，还一直报，一直弹框
![image](https://user-images.githubusercontent.com/25219834/83491803-e6ce4d00-a4e4-11ea-9181-58f649ad21ef.png)

1､win7和server版本提示cv2 已排除 是win10系统
2､不是管理员运行 已排除
3､中文路径 已排除
4､有后台进程未退出 已排除

请大神给解决一下把。

**Comment by lailuboy** [comment]
1､选择FasterRCNN后backbone列表没有刷新是吧？
2､下面的报错对应选择的参数是什么样的？

**Comment by wyc880622** [comment]
> 择FasterRCNN后backbone

是的没有刷新
这个是报错日志
[paddlex.zip](https://github.com/PaddlePaddle/PaddleX/files/4715571/paddlex.zip)

**Comment by lailuboy** [comment]
已发布新版本修复backbone列表没有刷新的问题，请试下是否ok。
