### ISSUE TITLE
数据集负样本制作

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleX#1304]
paddlex2.1.0新增了负样本，一直使用的是labelImg制作voc格式数据集，请问负样本怎么制作？

**Comment by will-jl944** [comment]
负样本使用示例见[文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data/format/detection.md#%E6%B7%BB%E5%8A%A0%E8%B4%9F%E6%A0%B7%E6%9C%AC)。

如果所标注的数据中本身包含负样本图像，且使用的标注工具支持生成空标签（.xml）文件，可使用文档中的第一种方式。空标签示例如下：
```
<annotation>
    <folder>JPEGImages</folder>
    <filename>1.jpg</filename>
    <source>
        <database>Unknown</database>
    </source>
    <size>
        <width>384</width>
        <height>216</height>
        <depth>3</depth>
    </size>
    <segmented>0</segmented>
</annotation>
```

如果负样本只有图像而没有相应的标注文件，可使用文档中的第二种方式。
