### ISSUE TITLE
数据集太多，加载时客户端卡死，无响应

### ISSUE THREAD

**Issue by clSpider** [PaddlePaddle/PaddleX#1305]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？
图像分类
4. 请提供您出现的报错信息及相关log
点我的数据集 查看，然后无反应
## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
PaddleX： 1.1.7
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows
3. 请问您使用的Python版本是？
3.6.5
5. 请问您使用的CUDA/cuDNN的版本号是？
10.0/7.6.5

**Comment by FlyingQianMM** [comment]
如果数据量太大的话，建议您使用PaddleX API开发模式
