### ISSUE TITLE
强烈建议PaddleX增加模型组网功能

### ISSUE THREAD

**Issue by qing130** [PaddlePaddle/PaddleX#1306]
1.工程上有时候主要的工作就是改模型结构，用自己的数据集训练。
自定义模型结构PaddlePaddle可以，但是自定义数据集似乎很麻烦（如果最简单的自定义数据集方法如以下链接所示的话：https://yeyupiaoling.blog.csdn.net/article/details/87895105 。虽然paddle数据自定义对专门做深度学习应该不难，但是像我们这种搞工程的（工业检测），深度学习只是其中一部分工作，不想把时间浪费在本来可以通用的接口上面）；
而Paddlex虽然自定义自己的数据集方便，但是不能自定义模型结构，犹如一只手残废了。而且，paddle自定义的模型，也不能在PaddleX上训练吧？

2.个人愚见PaddleX的产品定位是对标Keras，PaddlePaddled的产品定位是对标TensorFlow。而keras能满足我第一点的所讲的两个需求，如果PaddleX可以借鉴一下Keras，把Keras该有的功能加上，那估计使用体验更好。

**Comment by FlyingQianMM** [comment]
感谢您的建议！

- 自定义数据集不麻烦。因为数据集格式和网络模型无关，您可以根据实际情况设计数据集格式，并自行搭建数据预处理流程，只需要保证最终喂给模型的数据符合预期即可。
- PaddleX的底座是PaddlePaddle，目前借助了PaddleClas/PaddleDetection/PaddleSeg模型套件来完成模型组网。而这三个模型套件是直接基于PaddlePaddle进行开发。
- 直接使用PaddlePaddle不难。如果您既要自定义数据预处理流程，又要自定义模型结构，您可以参考这三个模型套件搭建自己的模型。PaddlePaddle也提供了详尽易用的Python API和文档说明。整个训练过程只需要开发3个环节：数据读取、预处理流程、模型组网。

**Comment by qing130** [comment]
> 感谢您的建议！
> 
> * 自定义数据集不麻烦。因为数据集格式和网络模型无关，您可以根据实际情况设计数据集格式，并自行搭建数据预处理流程，只需要保证最终喂给模型的数据符合预期即可。
> * PaddleX的底座是PaddlePaddle，目前借助了PaddleClas/PaddleDetection/PaddleSeg模型套件来完成模型组网。而这三个模型套件是直接基于PaddlePaddle进行开发。
> * 直接使用PaddlePaddle不难。如果您既要自定义数据预处理流程，又要自定义模型结构，您可以参考这三个模型套件搭建自己的模型。PaddlePaddle也提供了详尽易用的Python API和文档说明。整个训练过程只需要开发3个环节：数据读取、预处理流程、模型组网。

那意味着PaddleX在此需求面前已经没用了？
paddle自定义数据集的最简模式是不是这个（https://my.oschina.net/u/4067628/blog/4827044）？还是很繁琐。
我发现PaddlePaddle很多博客都是用网上载入的模型，网上的数据集，然后就吹得天花乱坠。
我感觉Paddle还是要向Keras学习的，把一些繁琐的文件操作给封装起来。

还有，官方对于自定义数据集的教程仅仅是简单说了几个接口，能看接口就会自定义数据集的占不到2%吧。官方展示的例子却是可以直接看文档就会的。
网上查到的自定义数据集，看起来挺麻烦了，还没跑通

**Comment by FlyingQianMM** [comment]
考虑到您应该是自主研发的需求比较大吧？我们以[Paddle DataLoader](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader)提供的例子来看，
![image](https://user-images.githubusercontent.com/22235422/147431278-174db1fc-4bf5-49ac-8919-29326655ed3e.png)
只需要保证Dataloader`yield image, label`是模型所需的数据即可。至于数据要怎么组织，预处理要做哪些操作，完全是可以自己设计的。

另外，我们一般推荐用户按照公开数据集格式来组织自己的数据，PaddleX也有提供相应文档和格式转换工具，可以参考下文档[数据准备](https://github.com/PaddlePaddle/PaddleX#1-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)
