### ISSUE TITLE
paddleX 分割模型 推理使用gpu加速，速度不降反升

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleX#1307]
## 描述问题
笔记本 win10 使用 paddleX分割预测时，不使用GPU速度1.2s，使用GPU后速度反而提升到3.4，没有任何报错或提示

## 环境
笔记本 win10系统 
python3.8 paddleX2.0 
cuda10.2 cudnn7.7
显卡GTX1660Ti

## 
有没有大佬给分析一下是什么原因造成的？

**Comment by will-jl944** [comment]
请详细说明使用方式。使用的是什么模型？调用的是模型的`predict`接口，还是使用的Python部署api `paddlex.deploy.Predictor`，还是C++部署？是否可以提供相应代码？

是否参考了[FAQ](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md/#%E6%8E%A8%E7%90%86%E9%83%A8%E7%BD%B2%E9%97%AE%E9%A2%98)进行预热？

**Comment by bowencarry** [comment]
老哥，我也遇到这个问题了，请问咋解决的？
