### ISSUE TITLE
C#部署无法初始化模型

### ISSUE THREAD

**Issue by theonelittlewhite** [PaddlePaddle/PaddleX#1316]
按着官方文档进行编译，在CMake编译的时候就出现红字（如下图），但是还是能生成“sln”文件。
![1](https://user-images.githubusercontent.com/96402892/146708905-1199f267-066e-4d10-8d4c-3dc5b0d5044b.png)
接下去则是修改“CMakeLists.txt”以及替换了“model_infer.cpp”，然后重新生成“model_infer”得到“model_infer.dll”，将生成的dll按官方文档全部放置于“...\PaddleX\deploy\cpp\docs\csharp_deploy\c#\bin\x64\Debug\net5.0-windows”。最后在直接运行样例程序，在初始化模型的时候，一直说dll中没有“InitModel”（如下图），请教各位是那步出了问题呢？
![2](https://user-images.githubusercontent.com/96402892/146708933-a2d42643-0e3b-40fc-96e7-7408e333830c.png)

**Comment by FlyingQianMM** [comment]
红字是正常的提示。

参考https://github.com/PaddlePaddle/PaddleX/pull/1318/files 修改下代码后，重新编译，看能否解决当前问题。

**Comment by nalanlan** [comment]
你好，请问这个问题你解决了吗？ 能否分享一下经验（qq：1229066620）

**Comment by FlyingQianMM** [comment]
该问题已在issue https://github.com/PaddlePaddle/PaddleX/issues/1329 中解决。
