### ISSUE TITLE
ubuntu c++部署

### ISSUE THREAD

**Issue by wang971124** [PaddlePaddle/PaddleX#1322]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？
没有
    * 您是否在demo基础上修改代码内容？还请您提供运行的代码
无
2. c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？
没有
    * 您是否在demo基础上修改代码内容？还请您提供运行的代码
没有
    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？
没有
3. 您使用的**模型**和**数据集**是？
unet 自制数据集
4. 请提供您出现的报错信息及相关log

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号

2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
linux ubuntu20.04
4. 请问您使用的CUDA/cuDNN的版本号是？
cuda11.3 cudnn8

**Comment by wang971124** [comment]
报错日志如下：
[ 77%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/paddlex/src/x_model.cpp.o
[ 78%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppdet/src/det_model.cpp.o
[ 80%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppdet/src/det_postprocess.cpp.o
[ 81%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppdet/src/det_preprocess.cpp.o
[ 83%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppseg/src/seg_model.cpp.o
[ 84%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/paddlex/src/x_postprocess.cpp.o
[ 85%] Building CXX object demo/CMakeFiles/batch_infer.dir/__/model_deploy/paddlex/src/x_preprocess.cpp.o
[ 87%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppseg/src/seg_postprocess.cpp.o
/usr/bin/ld: warning: libjasper.so.1, needed by ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_writecmpt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_encode'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_decode'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cleanup'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_strtofmt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_create'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_init'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cmprof_createfromclrspc'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_stream_fopen'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_matrix_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_stream_close'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_readcmpt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_getcmptbytype'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cmprof_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_matrix_create'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_chclrspc'
collect2: error: ld returned 1 exit status
make[2]: *** [demo/CMakeFiles/multi_gpu_model_infer.dir/build.make:390：demo/multi_gpu_model_infer] 错误 1
make[1]: *** [CMakeFiles/Makefile2:181：demo/CMakeFiles/multi_gpu_model_infer.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 88%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppseg/src/seg_preprocess.cpp.o
[ 90%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppclas/src/clas_model.cpp.o
[ 91%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppclas/src/clas_postprocess.cpp.o
[ 92%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/ppclas/src/clas_preprocess.cpp.o
[ 94%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/paddlex/src/x_model.cpp.o
[ 95%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/paddlex/src/x_postprocess.cpp.o
[ 97%] Building CXX object demo/CMakeFiles/model_infer.dir/__/model_deploy/paddlex/src/x_preprocess.cpp.o
[ 98%] Linking CXX executable batch_infer
/usr/bin/ld: warning: libjasper.so.1, needed by ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_writecmpt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_encode'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_decode'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cleanup'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_strtofmt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_create'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_init'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cmprof_createfromclrspc'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_stream_fopen'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_matrix_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_stream_close'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_readcmpt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_getcmptbytype'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cmprof_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_matrix_create'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_chclrspc'
collect2: error: ld returned 1 exit status
make[2]: *** [demo/CMakeFiles/batch_infer.dir/build.make:390：demo/batch_infer] 错误 1
make[1]: *** [CMakeFiles/Makefile2:154：demo/CMakeFiles/batch_infer.dir/all] 错误 2
[100%] Linking CXX executable model_infer
/usr/bin/ld: warning: libjasper.so.1, needed by ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_writecmpt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_encode'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_decode'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cleanup'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_strtofmt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_create'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_init'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cmprof_createfromclrspc'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_stream_fopen'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_matrix_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_stream_close'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_readcmpt'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_getcmptbytype'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_cmprof_destroy'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_matrix_create'
/usr/bin/ld: ../../deps/opencv3.4.6gcc4.8ffmpeg/lib/libopencv_imgcodecs.so.3.4.6: undefined reference to `jas_image_chclrspc'
collect2: error: ld returned 1 exit status
make[2]: *** [demo/CMakeFiles/model_infer.dir/build.make:390：demo/model_infer] 错误 1
make[1]: *** [CMakeFiles/Makefile2:127：demo/CMakeFiles/model_infer.dir/all] 错误 2
make: *** [Makefile:84：all] 错误 2

**Comment by wang971124** [comment]
由于我的ubuntu20.04，所以对PaddleX/deploy/cpp/scripts/bootstrap.sh进行了修改，将if [ $system_version == '"18.04"' ]中修改为了"20.04"

**Comment by FlyingQianMM** [comment]
参考issue https://github.com/PaddlePaddle/PaddleX/issues/1091

在ubuntu 20.4下需要自己编译Paddle Inference。
