### ISSUE TITLE
关于PaddleX导出模型的格式问题

### ISSUE THREAD

**Issue by zgwg** [PaddlePaddle/PaddleX#1324]
请问一下，PaddleX导出的训练模型和推理模型和用其他套件导出的模型格式一样吗

**Comment by FlyingQianMM** [comment]
模型格式都是一样，均为PaddlePaddle支持的。PaddleX模型格式说明参考文档[模型格式说明](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/export_model.md#%E6%A8%A1%E5%9E%8B%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E)
