### ISSUE TITLE
c#部署paddlex模型问题

### ISSUE THREAD

**Issue by usuixingyili** [PaddlePaddle/PaddleX#1325]
ppdet导出的模型使用c#部署通过，但是paddlex导出的模型使用c#部署报错。model_tpye已经设置为paddlex
![image](https://user-images.githubusercontent.com/74706568/147304410-a2ab7052-0bce-4460-b2a4-763a47ee9f2b.png)

**Comment by FlyingQianMM** [comment]
PaddleX导出的模型使用c++部署可以正常运行么？

**Comment by usuixingyili** [comment]
![image](https://user-images.githubusercontent.com/74706568/147800379-7d4dc082-991f-4876-b35a-82980ed0b323.png)

**Comment by FlyingQianMM** [comment]
请确认下paddlex训练模型时的Paddle、CUDA和cuDNN版本与部署时的Paddle Inference、CUDA和cudnn版本是否一致？

另外在windows上编译paddlex部署代码时，有没有勾选使用TensorRT?
