### ISSUE TITLE
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3452: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.   warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

### ISSUE THREAD

**Issue by banrieen** [PaddlePaddle/PaddleX#1327]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
BML codelab：
3.2 定义图像处理流程transforms

定义数据处理流程，其中训练和测试需分别定义，训练过程包括了部分测试过程中不需要的数据增强操作，如在本示例中，训练过程使用了RandomHorizontalFlip数据增强方式，更多图像预处理流程transforms的使用可参见paddlex.det.transforms。

已经安装paddlex, 任抛出错误：

Your running script needs PaddleX<2.0.0, please refer to https://github.com/PaddlePaddle/PaddleX/tree/release/2.0-rc/tutorials/train#%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7 to solve this issue.

An exception has occurred, use %tb to see the full traceback.

SystemExit: -1

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3452: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by FlyingQianMM** [comment]
![image](https://user-images.githubusercontent.com/22235422/148005476-496872cf-1325-45f4-9df7-9689ada4c047.png)

这个链接里面已经说报错原因：您使用的是训练脚本只能使用PaddleX <=1.3.11才能正常运行，但是您目前安装的PaddleX是2.0.0的。

您可以将PaddleX降至1.3.11，或者使用适配PaddleX 2.0的训练脚本。
