### ISSUE TITLE
版本问题？

### ISSUE THREAD

**Issue by yuyifan-lab** [PaddlePaddle/PaddleX#1328]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
半年前跑好的项目（以“10分钟快速上手使用PaddleX——Faster RCNN目标检测”为基础完成的），现在在“安装PaddleX”时出错，原码为"! pip install paddlex -i https://mirror.baidu.com/pypi/simple"，报错为
“
ERROR: blackhole 0.3.2 has requirement scikit-learn==0.22.1, but you'll have scikit-learn 0.23.2 which is incompatible.
ERROR: blackhole 0.3.2 has requirement xgboost==1.1.0, but you'll have xgboost 1.3.3 which is incompatible.
”
后发现新的例子改为“! pip install "paddlex<=2.0.0" -i https://mirror.baidu.com/pypi/simple”，第一步（安装PaddleX）不报错，但原项目后续皆无法运行。
请问该怎样解决？
## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by will-jl944** [comment]
paddlex已经发布新版本至2.1.0，安装旧版本需要指定版本号，即命令改为`pip install paddlex==1.3.11`。
