### ISSUE TITLE
PaddleX在Windows上训练完成之后导出模型文件。然后将模型文件在JetsonNnano上部署，通过Paddle_inference在服务器上识别报错。

### ISSUE THREAD

**Issue by MiShiDeHaiLuo** [PaddlePaddle/PaddleX#1332]
## 描述问题
PaddleX在Windows上训练完成之后导出模型文件。然后将模型文件在JetsonNnano上部署，通过Paddle_inference在服务器上识别报错。
## 错误信息
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  
![IVYT5QQAW319Z XHS(D2TZ3](https://user-images.githubusercontent.com/97105652/148068089-5f637ec0-5051-415c-a008-8d0bcf2d5ca9.png)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::~AnalysisPredictor()
3   paddle::AnalysisPredictor::~AnalysisPredictor()
4   unsigned long paddle::memory::legacy::Release<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&)
5   paddle::memory::legacy::GetGPUBuddyAllocator(int)
6   paddle::memory::legacy::GPUBuddyAllocatorList::Get(int)
7   std::call_once<paddle::memory::legacy::GPUBuddyAllocatorList::Get(int)::{lambda()#1}>(std::once_flag&, paddle::memory::legacy::GPUBuddyAllocatorList::Get(int)::{lambda()#1}&&)::{lambda()#2}::_FUN()
8   paddle::platform::GpuMaxChunkSize()
9   paddle::platform::GpuMaxAllocSize()
10  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
11  [paddle::platform::GetCurrentTraceBackString[abi:cxx11](bool)]([url](url))
----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: Not enough available GPU memory.

**Comment by lailuboy** [comment]
看错误是显存不足，尝试使用更轻量模型试试。

**Comment by MiShiDeHaiLuo** [comment]
这么晚打扰实在抱歉。
显存方面，我已经将设置值从500降低到300，并且我用inference_model中自带的Demo（显存大小设置为500）测试可以运行。但是换成Paddlex导出的模型文件就不行。
轻量模型方面，我也测试了PaddleX上的最简单的蔬菜分类模型，将模型文件拷贝到JetsonNano上还是不行。报错一致。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 晚上10:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] PaddleX在Windows上训练完成之后导出模型文件。然后将模型文件在JetsonNnano上部署，通过Paddle_inference在服务器上识别报错。 (Issue #1332)





 
看错误是显存不足，尝试使用更轻量模型试试。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FlyingQianMM** [comment]
Paddle Inference的预编译包下载的是针对jetson平台的吗？

运行时关掉tensorrt可以正常运行吗？

**Comment by MiShiDeHaiLuo** [comment]
您好，已经解决了。最后直接在JetsonNano的C++上调用成功了。最终没有使用Pyhton。
