### ISSUE TITLE
训练数据分割模型，自动下载deeplabv3预训练模型DeepLabv3p_Xception65_COCO后，但报错不是有效参数。

### ISSUE THREAD

**Issue by panicwq** [PaddlePaddle/PaddleX#1334]
问题描述：工业表计案例训练语义分割模型时 

**Exception: File output/meter_seg\pretrain\DeepLabv3p_Xception65_COCO is not a paddle parameter file**

版本、环境信息：
   1）PaddlePaddle 版本：paddlepaddle-gpu 2.2.1
   2）Paddlex: 1.3.10
   3）系统环境：win10 python3.8
  4) GPU:GTX1650Ti CUDA10.2 cudnn 8.2.2.26

注：后来我尝试把paddlex版本改为2.0.0 ，其中train_segmentation.py也更新了，默认下载的模型不同，这个问题也没有了，但是在paddlex1.3中仍会出现这个问题。

**Comment by FlyingQianMM** [comment]
- PaddleX目前已经全面升级飞桨动态图了，建议您使用PaddleX 2.1
适配飞桨动态图的工业表计读数的案例：https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/meter_reader

- 关于您之前使用PaddleX 1.3.10训练报错的[问题](https://github.com/PaddlePaddle/Paddle/issues/38704 )，我这边没有复现出该问题。您检查下预训练模型是否下载成功，即`output/meter_seg\pretrain\DeepLabv3p_Xception65_COCO`是否存在且是否包含`decoder/  encoder/  logit/  @LR_DECAY_COUNTER@  xception_65/`。

**Comment by panicwq** [comment]
感谢回复， output/meter_seg\pretrain\DeepLabv3p_Xception65_COCO这个模型存在，但没有decoder/ encoder/ logit/ @LR_DECAY_COUNTER@ xception_65/，请问这是什么原因造成的？



> * PaddleX目前已经全面升级飞桨动态图了，建议您使用PaddleX 2.1
>   适配飞桨动态图的工业表计读数的案例：https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/meter_reader
> * 关于您之前使用PaddleX 1.3.10训练报错的[问题](https://github.com/PaddlePaddle/Paddle/issues/38704)，我这边没有复现出该问题。您检查下预训练模型是否下载成功，即`output/meter_seg\pretrain\DeepLabv3p_Xception65_COCO`是否存在且是否包含`decoder/  encoder/  logit/  @LR_DECAY_COUNTER@  xception_65/`。

**Comment by FlyingQianMM** [comment]
应该是预训练模型下载出错了。把`output/meter_seg\pretrain\DeepLabv3p_Xception65_COCO`删除后重新试下看看会不会下载报错，或者直接使用PaddleX 2.1.0即可。
