### ISSUE TITLE
PY需要打包成EXE，只需要预测，哪些是可以注释的模型

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1335]
WIN系统

python需要打包成EXE

PaddleX 只要预测的话

哪些文件可以不要的

方便打包

或者哪些可以注释

**Comment by FlyingQianMM** [comment]
不是很理解只要预测是什么意思？

**Comment by monkeycc** [comment]
GUI界面  打包exe给用户
只有预测图片功能

全部打包的话 就会把paddleX所有的模型 都打包进去
第三方模块 太多了 容易报错

**Comment by FlyingQianMM** [comment]
那你看下paddlex/deploy.py都需要从哪些文件里import，不需要的不打进去就行了
