### ISSUE TITLE
预测时间优化问题,preprocess_time_per_im,inference_time_per_batch(ms),postprocess_time_per_im

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1341]
total_time(ms): 504.09999999999997, img_num: 1, batch_size: 1
average latency time(ms): 504.10, QPS: 1.983733
preprocess_time_per_im(ms): 173.00, inference_time_per_batch(ms): 331.10, postprocess_time_per_im(ms): 0.00

1.是什么问题会导致
preprocess_time_per_im
时间过长
需要怎么解决

2.是什么问题会导致
inference_time_per_batch
时间过长
需要怎么解决

3.在哪里设置 
可以禁止这个信息提示出来
Inference Time Info

**Comment by FlyingQianMM** [comment]
1、`preprocess_time_per_im `是预处理的时间。时间过长跟很多因素有关，例如图片太大、预处理算子耗时等等。可以根据您实际的业务场景进行优化，具体可以在代码中打断点看下哪些操作的时间过长。

2、`inference_time_per_batch `是模型推理的时间。模型太大、输入数据太大都会引起时间过长。您可以看目前是哪方面导致，模型太大就换小模型。

3、没有关闭日志打印的标志
要么您就用源码开发模式，自行删除打印日志的代码即可
