### ISSUE TITLE
PaddleX/deploy/cpp/demo/model_infer.cpp编译后生成model_infer.exe，使用demo中的yolov3模型作为输入，无结果显示

### ISSUE THREAD

**Issue by MattixLee** [PaddlePaddle/PaddleX#1342]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 描述问题
按照https://gitee.com/paddlepaddle/PaddleX/blob/develop/deploy/cpp/docs/demo/model_infer.md
编译生成model_infer.exe，运行文档提供的YOLOv3模型，没有输出。
## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？
按照demo运行没有输出
    * 您是否在demo基础上修改代码内容？还请您提供运行的代码
  没有修改demo程序内容

2. c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？

3. 您使用的**模型**和**数据集**是？
使用文档提供的YOLOv3模型和图片

4. 请提供您出现的报错信息及相关log
model_infer.exe --model_filename=D:\MaskRCNN\paddle\yolov3_mbv1\yolov3_mbv1\model\model.pdmodel --params_filename=D:\MaskRCNN\paddle\yolov3_mbv1\yolov3_mbv1\model\model.pdiparams --cfg_file=D:\MaskRCNN\paddle\yolov3_mbv1\yolov3_mbv1\model\infer_cfg.yml --image=D:\MaskRCNN\paddle\yolov3_mbv1\yolov3_mbv1\model\images\000000010583.jpg --model_type=det --use_gpu=1
REGISTER_CLASS:det
init DetModel,model_type=det
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0107 09:19:08.534175   408 fuse_pass_base.cc:57] ---  detected 34 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0107 09:19:08.579454   408 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0107 09:19:08.635644   408 memory_optimize_pass.cc:216] Cluster name : yolo_box_1.tmp_0  size: 69312
I0107 09:19:08.635644   408 memory_optimize_pass.cc:216] Cluster name : leaky_relu_12.tmp_0  size: 2957312
I0107 09:19:08.635644   408 memory_optimize_pass.cc:216] Cluster name : image  size: 4435968
I0107 09:19:08.637151   408 memory_optimize_pass.cc:216] Cluster name : relu_2.tmp_0  size: 23658496
I0107 09:19:08.637151   408 memory_optimize_pass.cc:216] Cluster name : depthwise_conv2d_2.tmp_0  size: 11829248
I0107 09:19:08.637151   408 memory_optimize_pass.cc:216] Cluster name : relu_1.tmp_0  size: 11829248
I0107 09:19:08.637151   408 memory_optimize_pass.cc:216] Cluster name : relu_13.tmp_0  size: 2957312
I0107 09:19:08.637151   408 memory_optimize_pass.cc:216] Cluster name : yolo_box_0.tmp_0  size: 17328
I0107 09:19:08.638149   408 memory_optimize_pass.cc:216] Cluster name : scale_factor  size: 8
I0107 09:19:08.638149   408 memory_optimize_pass.cc:216] Cluster name : leaky_relu_13.tmp_0  size: 739328
I0107 09:19:08.638149   408 memory_optimize_pass.cc:216] Cluster name : im_shape  size: 8
I0107 09:19:08.639147   408 memory_optimize_pass.cc:216] Cluster name : cast_0.tmp_0  size: 8
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0107 09:19:08.701462   408 analysis_predictor.cc:717] ======= optimize end =======
I0107 09:19:08.701850   408 naive_executor.cc:98] ---  skip [feed], feed -> scale_factor
I0107 09:19:08.701850   408 naive_executor.cc:98] ---  skip [feed], feed -> image
I0107 09:19:08.703156   408 naive_executor.cc:98] ---  skip [feed], feed -> im_shape
I0107 09:19:08.705169   408 naive_executor.cc:98] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I0107 09:19:08.706166   408 naive_executor.cc:98] ---  skip [save_infer_model/scale_1.tmp_1], fetch -> fetch

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号

2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号
paddleX   develop
PaddleInference  cuda10.1_cudnn7.6_avx_mkl_no_trt
使用vs2019编译时，将tensorrt均未选择，只勾选了mkl，gpu,  cuda

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
windows10

4. 请问您使用的CUDA/cuDNN的版本号是？
CUDA10.1   CUDNN7.6.5

**Comment by FlyingQianMM** [comment]
> 使用vs2019编译时，将tensorrt均未选择，只勾选了mkl，gpu, cuda

请问您使用的Paddle Inference是什么版本？windows下请用带trt的paddle inference并勾选trt进行编译。

**Comment by MattixLee** [comment]
@FlyingQianMM  您好，换用带trt的paddle inference，demo就可以顺利运行了，谢谢您！

使用官方提供的小熊数据集训练mask rcnn网络(训练代码为官方代码直接运行，无修改)，再根据官方文档导出模型，使用直接导出的文件，会产生如下错误：
D:\MaskRCNN\paddle\PaddleX\deploy\cpp\out\build\x64-Release\paddle_deploy\model_infer.exe --model_filename=model.pdmodel --params_filename=model.pdiparams --cfg_file=model.yml --image=../Xiaoduxiong110.jpeg --model_type=paddlex
REGISTER_CLASS:paddlex
init PaddleXModel,model_type=paddlex
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0110 16:40:22.823590 14160 analysis_predictor.cc:647] MKLDNN is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [mkldnn_placement_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_v2_to_mul_pass]e[0m
I0110 16:40:23.089151 14160 fuse_pass_base.cc:57] ---  detected 4 subgraphs
e[32m--- Running IR pass [map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0110 16:40:23.120409 14160 fuse_pass_base.cc:57] ---  detected 4 subgraphs
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0110 16:40:23.214123 14160 fuse_pass_base.cc:57] ---  detected 53 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[32m--- Running IR pass [depthwise_conv_mkldnn_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bias_mkldnn_fuse_pass]e[0m
I0110 16:40:23.276615 14160 fuse_pass_base.cc:57] ---  detected 23 subgraphs
e[32m--- Running IR pass [conv_transpose_bias_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv3d_bias_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_mkldnn_fuse_pass]e[0m
I0110 16:40:23.448451 14160 conv_elementwise_add_mkldnn_fuse_pass.cc:408] Fused graph 16
I0110 16:40:23.448451 14160 fuse_pass_base.cc:57] ---  detected 16 subgraphs
e[32m--- Running IR pass [conv_concat_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu_mkldnn_fuse_pass]e[0m
I0110 16:40:23.479691 14160 fuse_pass_base.cc:57] ---  detected 54 subgraphs
e[32m--- Running IR pass [conv_leaky_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu6_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_hard_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [scale_matmul_fuse_pass]e[0m
e[37m---    fused 0 scale with matmule[0m
e[32m--- Running IR pass [reshape_transpose_matmul_mkldnn_fuse_pass]e[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patternse[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshapee[0m
e[32m--- Running IR pass [matmul_transpose_reshape_fuse_pass]e[0m
e[37m---    Fused 0 MatmulTransposeReshape patternse[0m
e[32m--- Running IR pass [batch_norm_act_fuse_pass]e[0m
e[37m---    fused 0 batch norm with relu activatione[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0110 16:40:23.917084 14160 analysis_predictor.cc:717] ======= optimize end =======
I0110 16:40:23.917084 14160 naive_executor.cc:98] ---  skip [feed], feed -> scale_factor
I0110 16:40:23.917084 14160 naive_executor.cc:98] ---  skip [feed], feed -> image
I0110 16:40:23.932682 14160 naive_executor.cc:98] ---  skip [feed], feed -> im_shape
I0110 16:40:23.932682 14160 naive_executor.cc:98] ---  skip [concat_13.tmp_0], fetch -> fetch
I0110 16:40:23.932682 14160 naive_executor.cc:98] ---  skip [multiclass_nms3_0.tmp_2], fetch -> fetch
I0110 16:40:23.932682 14160 naive_executor.cc:98] ---  skip [_generated_var_69], fetch -> fetch
I0110 16:40:24.010818 14160 device_context.cc:641] oneDNN v2.3.2
Compute category id is greater than labels in your config file
Compute Category ID: 1, but length of labels is 1
Error happend while process bboxes
Box(0   xiaoduxiong     0.00000000      0.00000000      0.00000000      0.99496472      0.99304444)

具体错误如下：
Compute category id is greater than labels in your config file
Compute Category ID: 1, but length of labels is 1

请问这个是什么导致？
谢谢您

祝好！

**Comment by FlyingQianMM** [comment]
1、https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/demo/model_infer.cpp#L26 把`use_gpu`设置为`true`试试？

2、第1点跑通后，请尝试下选择Paddle Inference 2.2版本，看下use_gpu=false的情况下，上述问题是否还存在。

**Comment by MattixLee** [comment]
@FlyingQianMM 您好，非常感谢您的回答！

Paddle Inference 为2.2，在use_gpu=false情况下，上述问题仍然存在，需要使用GPU才能正常运行。

按照官方问文档使用c++部署，每次运行后mask不一致，具体结果如下，您帮忙看下是哪里出现错误？
代码参考Jetson平台QT可视化部署Demo方案

 ```
void get_color_map_list(int num_classes, uchar* color_map)
{
	uchar* color_list = new uchar[num_classes * 3];
	num_classes += 1;
	for (int i = 0; i < num_classes; i++)
	{
		int j = 0;
		int lab = i;
		while (lab != 0)
		{
			color_list[(i - 1) * 3] |= (uchar)(((lab >> 0) & 1)
				<< (7 - j));
			color_list[(i - 1) * 3 + 1] |= (uchar)(((lab >> 1) & 1)
				<< (7 - j));
			color_list[(i - 1) * 3 + 2] |= (uchar)(((lab >> 2) & 1)
				<< (7 - j));

			j += 1;
			lab >>= 3;
		}
	}
	color_map = color_list;
}
```

```
Mask_ModelPredict mask_predict;
	mask_predict = (Mask_ModelPredict)GetProcAddress(hdll, "Mask_ModelPredict");
	printf("fun1:%p\n", mask_predict);
	if (mask_predict == NULL) {
		FreeLibrary(hdll);
		return 0;
	}
	cv::Mat img = cv::imread("D:/MaskRCNN/VS2019/TestPaddleX/x64/Release/Xiaoduxiong110.jpeg");
	float bboxs[600];
	int bbox_num[1];
	char labellist[1000];
	//unsigned char out_image[image.cols * image.rows];
	unsigned char* out_image = new unsigned char[img.cols * img.rows];
	mask_predict((const unsigned char*)img.data, img.cols, img.rows, 3, bboxs, out_image, bbox_num, labellist);

	
	cv::Mat out3c_image = cv::Mat(img.clone());
	for (int i = 0; i < out3c_image.rows; i++)   // height
	{
		for (int j = 0; j < out3c_image.cols; j++)  // width
		{
			int indexSrc = i * out3c_image.cols + j;

			unsigned char color_id = (int)out_image[indexSrc] % 256;

			if (color_id == 0)
				out3c_image.at<cv::Vec3b>(i, j) = cv::Vec3b(0, 0, 0);
			else
				out3c_image.at<cv::Vec3b>(i, j) = cv::Vec3b(color_map[color_id * 3],
					color_map[color_id * 3 + 1], color_map[color_id * 3 + 2]);
		}
	}
```
![img1](https://user-images.githubusercontent.com/49889155/149740216-2745a908-184c-430e-aecf-0cd63cbad937.PNG)
![img2](https://user-images.githubusercontent.com/49889155/149740218-1353a294-8411-40d3-bc9b-41d6abdf0978.PNG)
