### ISSUE TITLE
无法可视化PPTOLOTiny敏感度分析的model.sensi.data

### ISSUE THREAD

**Issue by AdobeDW** [PaddlePaddle/PaddleX#1344]
问题：没有找到能够可视化敏感度分析结果的方法

出现的报错信息及相关log：
2022-01-07 16:15:11 [INFO]      Model[PPYOLOTiny] loaded.
Traceback (most recent call last):
  File "slim_visualize.py", line 3, in <module>
    pdx.slim.visualize(model, 'PaddleX/output/fined-ppyolotiny/prune/model.sensi.data', save_dir='./')
AttributeError: module 'paddlex' has no attribute 'slim'
使用的操作系统Linux、使用的Python版本3.6、使用的CUDA/cuDNN的版本号是10.2
我没有找到在PaddleX2.0、develop或是2.1版本、paddlepaddle2.0、2.1、2.2版本中能够实现对PPYOLOTiny敏感度分析得到的model.sensi.data进行可视化的代码，它总是提示我module 'paddlex' has no attribute 'slim'，另外，由于ppyolotiny模型在PaddleX2.0之前的版本中并不被包含，所以我也无法使用之前版本的程序。
![b](https://user-images.githubusercontent.com/30259085/148569308-4ccb778a-fac8-4f47-a9ef-b4b211e03e1b.png)

**Comment by FlyingQianMM** [comment]
抱歉，PaddleX 2.0未提供`pdx.slim.visualize`API接口。您可以选择相应的剪裁比例后，剪裁完再重新训练以减少精度损失。2.0使用剪裁功能的示例见 https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/slim/prune/object_detection 。

**Comment by AdobeDW** [comment]
> 抱歉，PaddleX 2.0未提供`pdx.slim.visualize`API接口。您可以选择相应的剪裁比例后，剪裁完再重新训练以减少精度损失。2.0使用剪裁功能的示例见 https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/slim/prune/object_detection 。

谢谢您的回复，我主要是想选择最合适的比例值，可视化不了的话就没办法选择，而且分析生成的model.sensi.data我查看不了具体信息，打开是乱码，请问这种情况我该怎么办呢？

**Comment by FlyingQianMM** [comment]
可以根据您想要的模型大小来选择剪裁比例。`model.sensi.data`目前记录的是剪裁的一些中间信息。

**Comment by AdobeDW** [comment]
> 可以根据您想要的模型大小来选择剪裁比例。`model.sensi.data`目前记录的是剪裁的一些中间信息。

好的
