### ISSUE TITLE
paddleX.deploy.Predictor报错

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleX#1348]
## 描述问题
paddleX 训练的ppyolov2模型
使用paddleX 部署测试报错

![6FCJJJ`NN38ZF{2)0RUGSK3](https://user-images.githubusercontent.com/42758082/148639714-108149fe-92df-4edf-b6bb-d56a7d7ba564.png)

使用
det_predictor = pdx.deploy.Predictor(model_dir=det_model_path, use_gpu=True, gpu_id=0)
报错：UnboundLocalError: local variable 'downsample_ratios' referenced before assignment

而使用
model = pdx.load_model('D:\\My_Demo\\WorkSpace\\pipe_stereo\\pipedetmodel\\inference_model\\inference_model')
result = model.predict(im)
则不会报错，正常运行

## 环境
PaddleX2.0.0， paddle2.0-gpu，win10，python3.7，cuda 10.2， cuDNN Version: 7.6

**Comment by FlyingQianMM** [comment]
更新PaddleX至2.1.0可解决该问题
