### ISSUE TITLE
分割模型支持fastscnn

### ISSUE THREAD

**Issue by chliang** [PaddlePaddle/PaddleX#135]
需要把paddleseg 里面的模型都迁移到paddlex中来。比如 fastscnn

**Comment by jiangjiajun** [comment]
预计在下周会集成进来

**Comment by chliang** [comment]
> 预计在下周会集成进来

好的辛苦了

**Comment by jiangjiajun** [comment]
> > 预计在下周会集成进来
> 
> 好的辛苦了

fastscnn已经集成，目前已经提到github上，如若有需求，当前可以直接使用github上最新的代码进行使用，这里是相关的示例 https://github.com/PaddlePaddle/PaddleX/blob/develop/new_tutorials/train/segmentation/fast_scnn.py

我们也会在本周内，将最新代码同步到pip源。
