### ISSUE TITLE
nuitka打包问题集合

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1350]
1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddlepaddle-gpu      2.2.1.post112
paddleslim            2.2.1
paddlex               2.1.0
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
win10
3. 请问您使用的Python版本是？
anaconda python 3.8
5. 请问您使用的CUDA/cuDNN的版本号是？
cuda11.2 cudnn8.2

`python -m nuitka    --standalone  --nofollow-imports   --output-dir=OUT  paddlexV2.py `
------------------------------------------
`pdx.deploy.Predictor` 高性能接口

```python
import os.path as osp
import numpy as np
from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType
from paddlex.cv.models import load_model
from paddlex.utils import logging, Timer
```
-------------------------------------------
只需要预测功能，只预测图片，不需要训练等其他模块
pdx.deploy.Predictor接口 还是会调用 paddle 
paddle 又有一堆不需要的模块 导致打包的时候会有点问题
--------------------------------------------
根目录
...
paddle
paddlex
google
             ---- protobuf

....
``` python 

Traceback (most recent call last):
  File "F:\paddleX2\paddlexV2.py", line 15, in <module>
  File "F:\paddleX2\paddlex\__init__.py", line 17, in <module>
    from paddlex.utils.env import get_environ_info, init_parallel_env # 这里应该不能删除
  File "F:\paddleX2\paddlex\utils\__init__.py", line 15, in <module>
    from . import logging   # 这里是日志系统 是否注释这一行
  File "F:\paddleX2\paddlex\utils\logging.py", line 21, in <module>
    import paddle
  File "F:\paddleX2\paddle\__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable 
  File "F:\paddleX2\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "F:\paddleX2\paddle\fluid\framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "F:\paddleX2\paddle\fluid\proto\framework_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google.protobuf' # 程序根目录有google文件夹里面有protobuf，不知道为什么检测不到

```

**Comment by FlyingQianMM** [comment]
paddlex的底座是paddle，即便您只要推理功能，也离不开paddle。您可以不打包paddlex的训练模块，但是paddle还是需要打进去的

**Comment by mayuxian** [comment]
@monkeycc 麻烦问下，使用nuitka打包paddle，我这总报错libgcc_s.1.1.dylib的问题，麻烦怎么解决的啊？

**Comment by monkeycc** [comment]
PaddlePaddle 的底层计算逻辑是 C++ 编写的，它依赖于 GCC 的运行时库 libgcc_s.1.1.dylib。
Paddle 官方提供的 whl 包通常是在特定环境下编译的，或者在 Conda 环境中依赖于 GCC。
Nuitka 在打包时，虽然会包含大部分 Python 依赖，但对于这种深层的系统级动态链接库，有时无法自动识别并正确设置，导致打包后的可执行文件运行时找不到这个文件。

libgcc_s.1.1.dylib

复制文件到打包目录
假设你的 Nuitka 打包输出目录是 dist/main.app（或者单文件 dist/main）。
如果是单文件模式，你需要将其放在同级目录
@mayuxian
