### ISSUE TITLE
分割模型部署，内存占用11.9G

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleX#1351]
## 描述问题
使用paddlex中的分割模型，C++部署的一个分割模型
模型为使用deeplabv3训练的，图像大小为2000*2000，然后运行的时候
paddle库为cuda11.0版本的，官网下载的
运行时，内存占用12G，这也太大了，多张图同时的时候，直接内存崩溃：
![图片](https://user-images.githubusercontent.com/40679769/148968585-4c85f2f5-35ca-4128-a418-04d0827682c5.png)

**Comment by FlyingQianMM** [comment]
deeplabv3本身是个大模型，输入图像大小是2000*2000的话，显存占用大是属于正常现象。
要么就用小模型，要么就调小输入大小。
