### ISSUE TITLE
C# paddle X 部署后dll无法使用

### ISSUE THREAD

**Issue by nalanlan** [PaddlePaddle/PaddleX#1352]
C# paddle X 部署后dll无法使用
![3FU9Q%MQG${ DZ202X6WTQT](https://user-images.githubusercontent.com/88658615/149105694-59dc74d5-5d19-420c-a581-4403ceb87b43.png)
![A263B{6_SKZZ180$6} T6$5](https://user-images.githubusercontent.com/88658615/149106000-04ef4284-2181-4b4c-a2ea-87e46dc8e156.png)

paddle X C#部署引起这个错误的原因是model_infer.dll没有编译正确
![1D@ %$N} X`( 3R3~M{HXOT](https://user-images.githubusercontent.com/88658615/149107293-f406a6fa-8d1b-40f4-8e54-294f30fdefe6.png)

![W_PD%S1{O%L{4(JLYRPYTSQ](https://user-images.githubusercontent.com/88658615/149106383-b7a92c3c-1e86-4a9e-a1c4-29a0d646ff37.png)
编译后是64位的

环境也是按照官方文档去准备的

![8QX}OQNZ_~F2T`0$AJJK0~Q](https://user-images.githubusercontent.com/88658615/149107744-3b7f10e2-b73c-43e6-b382-95c7d60d2712.png)

不知道是不是这个原因导致的，求大佬们指点一下！！！
ps:另外能不能拜求一个编译好的 model_infer.dll  比对一下  感谢大佬

**Comment by FlyingQianMM** [comment]
参考下这个issue：https://github.com/PaddlePaddle/PaddleX/issues/1329
