### ISSUE TITLE
工业表计-训练集中的annotations中的instance_train.json如何生成的？感谢！

### ISSUE THREAD

**Issue by Leelongqi** [PaddlePaddle/PaddleX#1353]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX数据准备文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#2-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)

## 描述问题
1.先用labelme进行标注图片

2.paddlex转成PascalVOC格式后生成各个图片xml文件。如下图所示：

![image](https://user-images.githubusercontent.com/33893308/149128889-f48af5da-2cc8-4bda-bc68-5b3ee41cc400.png)

3.接下来怎么复现工业表计中的instance_train.json文件？

## 复现

1. 您使用的命令是？

2. 您使用的数据集是？
工业表计
3. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddleX的版本号
paddlex=2.0.0

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
macos m1

3. 请问您使用的Python版本是
python3.7

**Comment by FlyingQianMM** [comment]
数据准备环节可以参考文档: https://github.com/PaddlePaddle/PaddleX#1-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87

数据格式转换：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data/convert.md

**Comment by flyweb291** [comment]
> ## Checklist:
> 1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
> 2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
> 3. 确认bug是否在新版本里还未修复
> 4. 翻阅[PaddleX数据准备文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#2-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)
> 
> ## 描述问题
> 1.先用labelme进行标注图片
> 
> 2.paddlex转成PascalVOC格式后生成各个图片xml文件。如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/33893308/149128889-f48af5da-2cc8-4bda-bc68-5b3ee41cc400.png)
> 
> 3.接下来怎么复现工业表计中的instance_train.json文件？
> 
> ## 复现
> 1. 您使用的命令是？
> 2. 您使用的数据集是？
>    工业表计
> 3. 请提供您出现的报错信息及相关log
> 
> ## 环境
> 1. 请提供您使用的PaddleX的版本号
>    paddlex=2.0.0
> 2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
>    macos m1
> 3. 请问您使用的Python版本是
>    python3.7

你好，请问m1芯片你是怎么装上python3.7的，我电脑提示搜索不到3.7对应m1的版本
