### ISSUE TITLE
PaddleX GUI模型导出报错：启动模型导出失败：'result'

### ISSUE THREAD

**Issue by ff12343** [PaddlePaddle/PaddleX#1354]
## 描述问题
Paddlex gui 正常训练的Deeplabv3+，训练完成模型评估时报错，具体如下：
模型测试启动测试之后，完成进度一直显示启动中，且预览测试图片目录下没有图片。
点击下一步，去模型发布时报错：启动模型导出失败：'result'
请提供您使用的GUI版本号
PaddleX2.0.0_ubantu1804_amd64
cuda10.2

**Comment by FlyingQianMM** [comment]
请将GUI升级至2.1，2.1下Deeplabv3+可以正常导出。
