### ISSUE TITLE
工业指针仪表C++推理方案修改

### ISSUE THREAD

**Issue by xfdbse** [PaddlePaddle/PaddleX#1358]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 描述问题
参考地址：https://www.paddlepaddle.org.cn/tutorials/projectdetail/3387933
基于该地址的det和seg模型（未训练，直接下载使用），在**不使用**PaddleX Manufature SDK的情况下，使用C++部署遇到问题。

**咨询如下问题**：
1）在C++部署方式下，能否不使用PaddleX Manufature SDK的情况下，实现二个模型的串联推理？比如先通过det识别出图片中的指针区域，然后再将指针区域图片传入seg模型进行指针读数的推理。
2）使用seg模型进行推理时，传入的参数是否正确？当前在进行seg推理时程序崩溃。
示例代码：
```
PaddleDeploy::Model* seg_model = PaddleDeploy::CreateModel(FLAGS_model_type);
std::vector<cv::Mat> det_roi; // 图片上各仪表框的图像区域，通过det推理已经正确获取，通过写文件确认
std::vector<PaddleDeploy::Result> seg_results;
seg_model->Predict(det_roi, &seg_results, 1); // 此步程序崩溃
```

## 复现
1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

3. 您使用的**模型**和**数据集**是？
// 模型

4. 请提供您出现的报错信息及相关log
// 无报错日志，只有dump文件

## 环境

2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号
// C++部署
// PaddleX develop分支
// 推理引擎，cuda11.0_cudnn8.0_avx_mkl_trt7

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
// windows 10 64bit

4. 请问您使用的CUDA/cuDNN的版本号是？
// cuda 11.0
// cuDNN 8.0

**Comment by xfdbse** [comment]
问题解决，是model_type参数错误，要使用“seg”。

但是很奇怪，我在https://www.paddlepaddle.org.cn/tutorials/projectdetail/3387933这个地址下载的二个模型文件，目标检测传"paddlex"，语义分割的却要传"seg".

**Comment by xfdbse** [comment]
很遗憾，程序预测仪表读数错误，返回：Meter 1: -0.05000000

当前的状态：
模型来源：
https://www.paddlepaddle.org.cn/tutorials/projectdetail/3387933

图片来源：
meter_det.tar.gz数据集中的20190829151141174.jpg文件

该模型和图片通过PaddleX\examples\meter_reader\reader_infer.py预测读数正确。
Meter 1: 1.1548611097608028

C++程序流程：
1）通过det检测出指针区域，并将指针表抠取出来，缩放到（512, 512）；
2）然后参考PaddleX\examples\meter_reader\deploy\cpp\meter_reader中的流程，进行Erode，GetMeterReading和PrintMeterReading处理。

针对该问题，有哪些思路可以提供？

**Comment by xfdbse** [comment]
cv::Mat vis_seg;
Visualize(imgs[0], *(results[0].seg_result), &vis_seg, 2);
cv::imwrite("vis_seg.jpg", vis_seg);

通过添加可视化输出后发现，图片上无分割区域的信息。

对比图片如下所示：
这是通过det裁减出来的图片：
![roi0](https://user-images.githubusercontent.com/1415127/149656700-94768a2b-314f-45d4-ab90-3ecb57e999cf.jpg)
这是通过seg可视化输出后的图片：
![vis_seg](https://user-images.githubusercontent.com/1415127/149656718-17567762-adea-4c41-bd29-4e63c8db0c6b.jpg)

从结果看，seg_model->Predict(det_roi, &seg_results, 1);预测的结果不正确。

**Comment by FlyingQianMM** [comment]
该案例教程在PaddleX的位置：https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/meter_reader

 > 1）在C++部署方式下，能否不使用PaddleX Manufature SDK的情况下，实现二个模型的串联推理？比如先通过det识别出图片中的指针区域，然后再将指针区域图片传入seg模型进行指针读数的推理。

当然可以。只不过需要您修改当前的代码，单个模型的部署使用可以参考：https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/demo/model_infer.cpp

> 2）使用seg模型进行推理时，传入的参数是否正确？当前在进行seg推理时程序崩溃。

用paddlex训练出的模型进行部署时，`model_type`都需要传`paddlex`

> 从结果看，seg_model->Predict(det_roi, &seg_results, 1);预测的结果不正确。

请再检查下前后处理是否符合python部署代码或者我们给出的c++代码。

**Comment by xfdbse** [comment]
>> > 2）使用seg模型进行推理时，传入的参数是否正确？当前在进行seg推理时程序崩溃。
>>
>> 用paddlex训练出的模型进行部署时，`model_type`都需要传`paddlex`

实际运行时，从[该地址](https://www.paddlepaddle.org.cn/tutorials/projectdetail/3387933)下载的二个模型，针对分割，如果传`paddlex`参数，程序会在`seg_model->Predict(det_roi, &seg_results, 1);`处崩溃，错误点见下图，数据越界错误：
![image](https://user-images.githubusercontent.com/1415127/149709341-e38e2aed-c07e-4b0a-9211-3995243a520e.png)



使用如下参数，程序可正常运行：
```
// 目标检测
PaddleDeploy::Model* det_model = PaddleDeploy::CreateModel("paddlex");
// 仪表分割
PaddleDeploy::Model* seg_model = PaddleDeploy::CreateModel("seg");
```

这是**问题1**，为什么都是paddlex训练的模型，C++初始化时，需要传不同的参数？

**Comment by xfdbse** [comment]
>> > 从结果看，seg_model->Predict(det_roi, &seg_results, 1);预测的结果不正确。
>> 
>> 请再检查下前后处理是否符合python部署代码或者我们给出的c++代码。

问题2，使用Visualize可视化`seg_model->Predict(det_roi, &seg_results, 1);`推理后的结果，没有mask数据，这一点让人无从下手诊断，需要更多的思路。
因为同样的模型和图片，使用python推理正常。

**Comment by xfdbse** [comment]
@FlyingQianMM

**Comment by xfdbse** [comment]
> 该案例教程在PaddleX的位置：https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/meter_reader

使用该代码，添加了可视化功能对比发现，**分割推理后的输出图像显示也不对**。该问题你们应该能复现。
代码如下所示：
```
cv::Mat vis_seg;
Visualize(imgs[0], *(results[0].seg_result), &vis_seg, 3);
cv::imwrite("yibiao_seg.jpg", vis_seg);
```
执行命令：
`./model_infer --model_filename=.\seg\meter_seg_model\model.pdmodel --params_filename=.\seg\meter_seg_model\model.pdiparams --cfg_file=.\seg\meter_seg_model\model.yml --image=.\seg\6.jpg --model_type=seg --use_gpu=1`
原图：
![6](https://user-images.githubusercontent.com/1415127/149757887-c1309dd6-ff95-4918-9038-5a97d8cec4b7.jpg)
seg可视化图：
![yibiao_seg](https://user-images.githubusercontent.com/1415127/149757939-8b9538f8-7a9a-4298-ab8e-ec6176640ace.jpg)

**Comment by xfdbse** [comment]
直接试用官网提供的模型不对，需要自己重新训练。
