### ISSUE TITLE
paddlex训练时调用dll失败

### ISSUE THREAD

**Issue by 13626730715** [PaddlePaddle/PaddleX#1360]
使用python3.8运行paddlex2.1.0，paddlepaddle装的是2.1.1，vc++装了2015的，但是运行的时候MSVCP140.dll报错
![image](https://user-images.githubusercontent.com/90882556/149612272-3b166c96-715b-4f4c-8f53-5000eba88511.png)
训练也停止了
运行的是蔬菜分类的demo

**Comment by FlyingQianMM** [comment]
看下安装文档：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/quick_start_API.md#paddlex-210%E5%AE%89%E8%A3%85

![image](https://user-images.githubusercontent.com/22235422/149703871-d3406f70-7889-421b-98bd-e8da8f698bc7.png)
