### ISSUE TITLE
 Please compile with gpu to EnableGpu()

### ISSUE THREAD

**Issue by 15254042250** [PaddlePaddle/PaddleX#1361]
windows10   pip install paddlex 

print("Loading zitai model...")
这是执行的代码
#attitude_model = pdx.load_model(r'F:\py_webspase\paddleInfercnceIot001\model\zi_tai',use_gpu=True)
predictor = pdx.deploy.Predictor(r'F:\py_webspase\paddleInfercnceIot001\model\inference_model\inference_model',use_gpu=True)
print("zitai Model loaded.")

E0115 15:22:49.592789 29820 analysis_config.cc:91] Please compile with gpu to EnableGpu()

**Comment by FlyingQianMM** [comment]
请确认下安装的是paddlepaddle还是paddlepaddle_gpu。这里提示的是您安装的是cpu版本的paddle
