### ISSUE TITLE
paddlex2.1版本建模能不能导出到1.2版本使用？

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleX#1362]
## 描述问题
利用paddlex --export_inference  导模型用于c++部署，请问题paddlex2.1版本建模能不能导出到1.2版本使用？如何处理？

**Comment by FlyingQianMM** [comment]
> 请问题paddlex2.1版本建模能不能导出到1.2版本使用？
2.1版本是动态图开发模式的，不能导出到1.2版本

2.1版本的c++部署见PaddleX Deployment：https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp

**Comment by abanger** [comment]
谢谢
