### ISSUE TITLE
C++编译DLL失败

### ISSUE THREAD

**Issue by Foreverrrrrr** [PaddlePaddle/PaddleX#1364]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 描述问题
在安装文档修改完C++代码后进行编译DLL，出现报错
## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？
是
    * 您是否在demo基础上修改代码内容？还请您提供运行的代码
否
2. c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？

3. 您使用的**模型**和**数据集**是？

4. 请提供您出现的报错信息及相关log
![6X7)35JYMUMD)9`(@%I~LHF](https://user-images.githubusercontent.com/97782838/149930227-036c40ad-632a-4988-9a9d-3b8bf51708e5.png)
![6M)T$WZ AMWUFN8~3{~3KI9](https://user-images.githubusercontent.com/97782838/149930247-e851154a-dd0d-4509-a694-58d43b912f9d.png)

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号

2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows
4. 请问您使用的CUDA/cuDNN的版本号是？
cuda10.2.89/cudnn7.6.5

**Comment by FlyingQianMM** [comment]
部署代码使用的是develop版本吗？如果不是，试下develop版本的

**Comment by Foreverrrrrr** [comment]
> 部署代码使用的是develop版本吗？如果不是，试下develop版本的

是使用的develop版本的，vs是使用的2022版本，没有选择TensorRT加速，但是我注意到model_infel文件下的引用是带感叹号的。
![image](https://user-images.githubusercontent.com/97782838/149946409-ff3f6928-011e-485f-8142-e4b466cf802b.png)

**Comment by Foreverrrrrr** [comment]
> 部署代码使用的是develop版本吗？如果不是，试下develop版本的

您好找到问题了，是vs2022的问题，按照文档的方法编译这个dll用vs2019能够成功
