### ISSUE TITLE
PaddleX-develop/deploy/cpp执行有一个段错误

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/PaddleX#1366]
**环境版本：**
PaddleX版本：develop 默认版本。
paddle_inference版本：预测库(2.1)，GPU版本（CUDA10.1/CUDNN7.6/TensorRT6，gcc 8.2

我修改了PaddleX-develop/deploy/cpp/demo/model_infer.cpp
我增加了一个for循环，不断的创建销毁。
int main(int argc, char **argv)
{

  **for (int i = 0; i < 100; i++)**
  **{**
    // Parsing command-line
    google::ParseCommandLineFlags(&argc, &argv, true);

    // create model
    PaddleDeploy::Model *model = PaddleDeploy::CreateModel(FLAGS_model_type);

    // model init
    model->Init(FLAGS_cfg_file, FLAGS_key);

    // inference engine init
    PaddleDeploy::PaddleEngineConfig engine_config;
    engine_config.model_filename = FLAGS_model_filename;
    engine_config.params_filename = FLAGS_params_filename;
    engine_config.use_gpu = FLAGS_use_gpu;
    engine_config.gpu_id = FLAGS_gpu_id;
    engine_config.key = FLAGS_key;
    model->PaddleEngineInit(engine_config);

    // prepare data
    std::vector<cv::Mat> imgs;
    imgs.push_back(std::move(cv::imread(FLAGS_image)));

    // predict
    std::vector<PaddleDeploy::Result> results;
    model->Predict(imgs, &results, 1);

    std::cout << results[0] << std::endl;
    delete model;
  **}**
  return 0;
}
在运行./build/demo/model_infer --model_filename。。。。。的时候**跑几个循环**会出现段错误。

错误如下：
init DetModel,model_type=det
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0119 07:48:38.365031 14999 fuse_pass_base.cc:57] ---  detected 101 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0119 07:48:38.627542 14999 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0119 07:48:38.771947 14999 memory_optimize_pass.cc:216] Cluster name : scale_factor  size: 8
I0119 07:48:38.771976 14999 memory_optimize_pass.cc:216] Cluster name : im_shape  size: 8
I0119 07:48:38.771991 14999 memory_optimize_pass.cc:216] Cluster name : tmp_1  size: 819200
I0119 07:48:38.772003 14999 memory_optimize_pass.cc:216] Cluster name : tmp_8  size: 1638400
I0119 07:48:38.772018 14999 memory_optimize_pass.cc:216] Cluster name : tmp_21  size: 3276800
I0119 07:48:38.772032 14999 memory_optimize_pass.cc:216] Cluster name : batch_norm_82.tmp_2  size: 3276800
I0119 07:48:38.772040 14999 memory_optimize_pass.cc:216] Cluster name : batch_norm_12.tmp_3  size: 26214400
I0119 07:48:38.772049 14999 memory_optimize_pass.cc:216] Cluster name : elementwise_add_8  size: 6553600
I0119 07:48:38.772063 14999 memory_optimize_pass.cc:216] Cluster name : relu_5.tmp_0  size: 26214400
I0119 07:48:38.772073 14999 memory_optimize_pass.cc:216] Cluster name : elementwise_add_2  size: 26214400
I0119 07:48:38.772083 14999 memory_optimize_pass.cc:216] Cluster name : image  size: 4915200
--- Running analysis [ir_graph_to_program_pass]
I0119 07:48:38.972628 14999 analysis_predictor.cc:717] ======= optimize end =======
I0119 07:48:38.981061 14999 naive_executor.cc:98] ---  skip [feed], feed -> scale_factor
I0119 07:48:38.981091 14999 naive_executor.cc:98] ---  skip [feed], feed -> image
I0119 07:48:38.981101 14999 naive_executor.cc:98] ---  skip [feed], feed -> im_shape
I0119 07:48:38.989351 14999 naive_executor.cc:98] ---  skip [matrix_nms_0.tmp_0], fetch -> fetch
I0119 07:48:38.989373 14999 naive_executor.cc:98] ---  skip [matrix_nms_0.tmp_2], fetch -> fetch
**Segmentation fault**

**使用GDB调试打印错误：**
--- Running analysis [ir_graph_to_program_pass]
I0119 08:24:16.621028 31863 analysis_predictor.cc:717] ======= optimize end =======
I0119 08:24:16.631916 31863 naive_executor.cc:98] ---  skip [feed], feed -> scale_factor
I0119 08:24:16.631947 31863 naive_executor.cc:98] ---  skip [feed], feed -> image
I0119 08:24:16.631971 31863 naive_executor.cc:98] ---  skip [feed], feed -> im_shape
I0119 08:24:16.640828 31863 naive_executor.cc:98] ---  skip [matrix_nms_0.tmp_0], fetch -> fetch
I0119 08:24:16.640856 31863 naive_executor.cc:98] ---  skip [matrix_nms_0.tmp_2], fetch -> fetch

Program received signal SIGSEGV, Segmentation fault.
0x00007fffbacafd4a in paddle::framework::Scope::FindVarLocally(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so

**bt后：**
(gdb) bt
#0  0x00007fffbacafd4a in paddle::framework::Scope::FindVarLocally(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#1  0x00007fffbacb165c in paddle::framework::Scope::VarInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#2  0x00007fffbeb08002 in paddle::framework::OperatorWithKernel::PrepareData(paddle::framework::Scope const&, paddle::framework::OpKernelType const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, paddle::framework::RuntimeContext*) const ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#3  0x00007fffbeb09db4 in paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const () from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#4  0x00007fffbeb0a3e6 in paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#5  0x00007fffbeb0703c in paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&) ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#6  0x00007fffbacf0a80 in paddle::framework::NaiveExecutor::Run() ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#7  0x00007fffba9ba343 in paddle::AnalysisPredictor::ZeroCopyRun() ()
   from /home/PaddleX-develop/deploy/cpp/3rdparty/paddle_inference/paddle/lib/libpaddle_inference.so
#8  0x0000000000464431 in PaddleDeploy::PaddleInferenceEngine::Infer(std::vector<PaddleDeploy::DataBlob, std::allocator<PaddleDeploy::DataBlob> > const&, std::vector<PaddleDeploy::DataBlob, std::allocator<PaddleDeploy::DataBlob> >*) ()
#9  0x000000000044197a in main ()

**麻烦一下，看能不能复现问题，并告知原因或者说我这样做是不对的。**

**Comment by FlyingQianMM** [comment]
现在这个for循环会导致不断的创建模型浪费资源。猜测您应该是想不断的预测图片吧？对下面这段代码进行循环即可：
```
// prepare data
std::vector<cv::Mat> imgs;
imgs.push_back(std::move(cv::imread(FLAGS_image)));

// predict
std::vector<PaddleDeploy::Result> results;
model->Predict(imgs, &results, 1);

std::cout << results[0] << std::endl;
```
