### ISSUE TITLE
3050GPU笔记本电脑，无法使用GPU进行预测

### ISSUE THREAD

**Issue by Foreverrrrrr** [PaddlePaddle/PaddleX#1367]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
代码运行到此处就会卡死
![image](https://user-images.githubusercontent.com/97782838/150121514-1e01bfe5-0645-40ff-b883-9350cfa37260.png)

## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows10
3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？
cuda10.2，cudnn7.6.5

**Comment by FlyingQianMM** [comment]
用c++部署（https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/models/paddlex.md）可以正常运行吗？
