### ISSUE TITLE
在aistudio中训练，添加add_negative_samples后会报错

### ISSUE THREAD

**Issue by Aierbx** [PaddlePaddle/PaddleX#1370]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX数据准备文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#2-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)

## 描述问题
使用add_negative_samples后，训练会报错：Blocking queue is killed because the data reader raises an exception.

## 复现

1. 您使用的命令是？
![image](https://user-images.githubusercontent.com/66861365/150706018-c454aa54-2e72-4710-bde7-ea396c3f4d72.png)
![image](https://user-images.githubusercontent.com/66861365/150706128-380e79e8-fc4e-43d8-a352-0baf9796bc68.png)
![image](https://user-images.githubusercontent.com/66861365/150706179-803f2c3a-ad2c-4d46-832d-39818286abd2.png)

2. 您使用的数据集是？
使用的是自己制作的数据集，如果没有添加负样本是可以正常训练的

3. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddleX的版本号
paddlex 2.0.0
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
aistudio 至尊版
3. 请问您使用的Python版本是

**Comment by FlyingQianMM** [comment]
更新paddlex至2.1.0试下。

**Comment by Aierbx** [comment]
可是我更新到2.1.0后，连import都不行了是什么情况呀？
![image](https://user-images.githubusercontent.com/66861365/150714702-5cde9bd2-90e9-4147-87cf-1e426348cb8c.png)
![image](https://user-images.githubusercontent.com/66861365/150714730-a94ce617-5a73-4cbf-adda-ad45d6a3f26b.png)

**Comment by Aierbx** [comment]
解决了，多谢
