### ISSUE TITLE
请问paddlex GUI到哪个版本开始不再支持windows7的呢？

### ISSUE THREAD

**Issue by kkhuangzekai** [PaddlePaddle/PaddleX#1372]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）

2. 请提供您使用的GUI版本号

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

4. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by kkhuangzekai** [comment]
> ## 清单：
> 1. 寻找[历史相关问题](https://github.com/PaddlePaddle/PaddleX/issues)寻求答案
> 2. 翻阅[FAQ 常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
> 3. bug是否在新版本里需要确认修复
> 4. 如果bug是由PaddleX API 2.0导致，且该bug在开发分支里已修复，请参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换编入PaddleX API
> 
> ## 描述问题
> ## 复现
> 1. 请提供您出现的报错信息及相关日志（日志查找见[FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
> 2. 请提供您使用的 GUI 版本号
> 3. 请提供您的操作系统信息，例如 Linux/Windows/MacOS
> 4. 请使用您的 CUDA/cuDNN 的版本号是？

![image](https://user-images.githubusercontent.com/82854498/150743369-a7612103-7ed4-4769-9d45-e3116a29dd11.png)
我使用paddlex_GUI win_1.0.0_PaddleX  把batchsize调为1 cpu模式下学习率调为最低，都无法训练，我使用的电脑是联想thinkpadS3

**Comment by kkhuangzekai** [comment]
![image](https://user-images.githubusercontent.com/82854498/150743997-c6250ca7-7dd0-4355-a3d8-f234c594eb88.png)
这是xu训练日志

**Comment by kkhuangzekai** [comment]
我的系统是win7 64位，显存4095M，
![image](https://user-images.githubusercontent.com/82854498/150746468-53176f38-fc11-4875-948b-039b85ecf35b.png)

**Comment by kkhuangzekai** [comment]
![image](https://user-images.githubusercontent.com/82854498/150749945-6a879479-3b84-4d1b-849c-810614ae34e4.png)
这是erro.log

**Comment by will-jl944** [comment]
尝试一下如下解决方法：
1. 数据集路径中不要有中文
2. 更新一下GUI的版本（[https://www.paddlepaddle.org.cn/paddlex/download](https://www.paddlepaddle.org.cn/paddlex/download)）
