### ISSUE TITLE
用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10

### ISSUE THREAD

**Issue by kkhuangzekai** [PaddlePaddle/PaddleX#1373]
## Checklist:
![image](https://user-images.githubusercontent.com/82854498/150765038-1e714f9e-f493-49bd-b741-55daa79b3013.png)

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）

2. 请提供您使用的GUI版本号

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

4. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by will-jl944** [comment]
1. 查看是否有报错，方法参考
> 1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）
2. 如果使用了GPU，确认一下GPU的占用率
3. 如果没有GPU，API中调小`log_interval_steps`参数，GUI中调小保存间隔，看是否有输出

**Comment by kkhuangzekai** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 晚上7:45
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)





  
查看是否有报错，方法参考
    
请提供您出现的报错信息及相关log（log的查找见 FAQ Q2）
    
如果使用了GPU，确认一下GPU的占用率
 
如果没有GPU，API中调小log_interval_steps参数，GUI中调小保存间隔，看是否有输出
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkhuangzekai** [comment]
请问我的图像是1280（宽）*592像素（高）的，使用PPYOLOV2的输入模型参数的时候图像输入尺寸是填1280*1280吗？因为模型强制等比了


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 晚上7:45
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)





  
查看是否有报错，方法参考
    
请提供您出现的报错信息及相关log（log的查找见 FAQ Q2）
    
如果使用了GPU，确认一下GPU的占用率
 
如果没有GPU，API中调小log_interval_steps参数，GUI中调小保存间隔，看是否有输出
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
修改数据增强设置即可，指定你需要的尺寸，同时确保长和宽都是32的倍数

**Comment by kkhuangzekai** [comment]
我怀疑我可能是CPU跑的太慢了，因为COLAB提示我虽然我开启了GPU模式 但是paddleX没有使用GPU模式去运行。请问您能提供GPU模式的paddlex指令或者DEMO吗？如果paddlex是本地运行的话会自动检测环境，但是我是在colab云端运行的，所以好像没有检测




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 晚上8:14
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)





 
修改数据增强设置即可，指定你需要的尺寸，同时确保长和宽都是32的倍数
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
colab中环境设置选择使用GPU后，首先需要安装对应cuda版本的paddlepaddle-gpu，PaddleX会自动使用GPU.

**Comment by kkhuangzekai** [comment]
所以paddlepaddle对应的是cpu版本，我不安装就不会用CPU模式运行是吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 晚上8:21
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)





 
colab中环境设置选择使用GPU后，首先需要安装对应cuda版本的paddlepaddle-gpu，PaddleX会自动使用GPU.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
paddlepaddle是cpu版本，只能使用cpu运行。使用gpu需要安装paddlepaddle-gpu，安装方法参考官网[https://www.paddlepaddle.org.cn/](https://www.paddlepaddle.org.cn/)。

**Comment by kkhuangzekai** [comment]
刚刚我用colab GPU 跑PPYOLOV2，为什么参数已经设得这么低了还会Out of memory error on GPU 0. Cannot allocate 184.500244MB memory on GPU 0, 14.708984GB memory has been allocated and available memory is only 47.750000MB




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 晚上8:27
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)





 
paddlepaddle是cpu版本，只能使用cpu运行。使用gpu需要安装paddlepaddle-gpu，安装方法参考官网https://www.paddlepaddle.org.cn/。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
> 参数已经设得这么低了

指的是batch size吗？设置的多少？

**Comment by kkhuangzekai** [comment]
workernumber 是0&nbsp; &nbsp; BATCHSIZE是8


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月24日(星期一) 晚上8:38
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)





  
参数已经设得这么低了
  
指的是batch size吗？设置的多少？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
worker_num不影响gpu内存占用，`/dev/shm`空间足够的话可以设置大一些，训练会快一些。

batch size调小一些。

**Comment by kkhuangzekai** [comment]
学习率调低一点也可以节约内存防止爆运行内存吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月24日(周一) 晚上8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)




 
worker_num不影响gpu内存占用，/dev/shm空间足够的话可以设置大一些，训练会快一些。
 
batch size调小一些。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
> 学习率调低一点也可以节约内存防止爆运行内存吗？
> 
> 
> 
> 
> 
> 
> 
> ---原始邮件---
> 
> 发件人: ***@***.***&gt;
> 
> 发送时间: 2022年1月24日(周一) 晚上8:54
> 
> 收件人: ***@***.***&gt;;
> 
> 抄送: ***@***.******@***.***&gt;;
> 
> 主题: Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> worker_num不影响gpu内存占用，/dev/shm空间足够的话可以设置大一些，训练会快一些。
> 
>  
> 
> batch size调小一些。
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

学习率不会影响内存占用

**Comment by kkhuangzekai** [comment]
请问paddlex gui支持对mAp参数的评估吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月24日(周一) 晚上11:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)




  
学习率调低一点也可以节约内存防止爆运行内存吗？
 
---原始邮件---
 
发件人: @.***&gt;
 
发送时间: 2022年1月24日(周一) 晚上8:54
 
收件人: @.***&gt;;
 
抄送: @.@.&gt;;
 
主题: Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)
 
worker_num不影响gpu内存占用，/dev/shm空间足够的话可以设置大一些，训练会快一些。
 
batch size调小一些。
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
Triage notifications on the go with GitHub Mobile for iOS or Android.
 
You are receiving this because you authored the thread.Message ID: @.***&gt;
  
学习率不会影响内存占用
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
支持

**Comment by kkhuangzekai** [comment]
查了一下是paddlet包的问题，是不是版本更新了？
2022-01-26 01:27:46 [INFO] Start to evaluate(total_samples=7, total_steps=7)...
Traceback (most recent call last):
&nbsp; File "/content/drive/My Drive/helmet.py", line 67, in <module&gt;
&nbsp; &nbsp; use_vdl=True)&nbsp; # 其用visuadl进行可视化训练记录
&nbsp; File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/detector.py", line 334, in train
&nbsp; &nbsp; use_vdl=use_vdl)
&nbsp; File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/base.py", line 397, in train_loop
&nbsp; &nbsp; return_details=True)
&nbsp; File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/detector.py", line 500, in evaluate
&nbsp; &nbsp; eval_metric.update(data, outputs)
&nbsp; File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/utils/det_metrics/metrics.py", line 120, in update
&nbsp; &nbsp; difficult)
&nbsp; File "/usr/local/lib/python3.7/dist-packages/paddlex/ppdet/metrics/map_utils.py", line 233, in update
&nbsp; &nbsp; self.class_score_poss[int(l)].append([s, 0.0])
IndexError: list index out of range







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 下午2:13
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)





 
支持
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkhuangzekai** [comment]
paddlex我用gui版本训练自定义模型然后预测跑成功了，但是paddlex的api代码版本训练模型成功以后预测一直报错：no gpu attributes ，想问一下对指定文件夹的图片进行预测的步骤是使用gui app文件夹中的python文件实现的呢？我想对照一下gui里的代码看看错在哪里


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月25日(周二) 下午2:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373)




 
支持
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xovow** [comment]
> 刚刚我用colab GPU 跑PPYOLOV2，为什么参数已经设得这么低了还会Out of memory error on GPU 0. Cannot allocate 184.500244MB memory on GPU 0, 14.708984GB memory has been allocated and available memory is only 47.750000MB
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PaddlePaddle/PaddleX" ***@***.***&gt;; 发送时间:&nbsp;2022年1月24日(星期一) 晚上8:27 ***@***.***&gt;; 抄送:&nbsp;"life is ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PaddlePaddle/PaddleX] 用paddlex的API版本在colab中运行和PAADLEX的gui版本中运行，提示五个warning后进入训练，但是一直等了3个小时都没有epcho出现。我训练的是PPYOLOV2,PECHO为2，学习率为0.00001，batchsize=1，warmingup step设置为10 (Issue #1373) paddlepaddle是cpu版本，只能使用cpu运行。使用gpu需要安装paddlepaddle-gpu，安装方法参考官网[https://www.paddlepaddle.org.cn/。](https://www.paddlepaddle.org.cn/%E3%80%82) — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问你是怎么在colab上安装paddlex的，我一安装就报错
