### ISSUE TITLE
当我使用PADDLEX resultful并且在ubuntu命令行部署时，我复制了命令行中返回的地址，chrome浏览器却提示我无法访问

### ISSUE THREAD

**Issue by kkhuangzekai** [PaddlePaddle/PaddleX#1374]
这是我的代码和返回：
 paddlex_restful --start_restful --port 27000 --workspace_dir py36
2022-01-25 15:21:59,442 app.py[line:966] INFO:RESTful服务启动成功后，您可以在浏览器打开 144.214.138.98:27000 使用WEB版本GUI
 * Serving Flask app 'paddlex_restful.restful.app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2022-01-25 15:21:59,443 _internal.py[line:225] WARNING: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-01-25 15:21:59,444 _internal.py[line:225] INFO: * Running on http://144.214.138.98:27000/

然后我复制了144.214.138.98:27000，却出现了这样：
![image](https://user-images.githubusercontent.com/82854498/150930618-2925fb2a-16ac-4663-9aed-cea30b380e0b.png)

**Comment by lailuboy** [comment]
检测系统防火墙中对应的端口是否打开

**Comment by kkhuangzekai** [comment]
使用权重文件 output/model/epocho_170/model.pdparams 加上 -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml 组装没有问题，但当我把 yml 文件的引用从 -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml 改为 -c output /model/epocho_170/model.yml 报错：没有属性'use_gpu'







描述问题

复现

这是我的代码：!python tools/infer.py -c output/model/epoch_170/model.yml --infer_dir="/content/drive/My Drive/PaddleDetection/dataset/voc/aistudio/JPEGImages" -o weights =output/model/epoch_170/model.pdparams --output_dir=output/INFERimages1 --draw_threshold=0.2 --use_vdl=True --vdl_log_dir=output/infervdl_log #&nbsp;https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_roadsign .pdparams&nbsp;#模型预测
#下面这行可以的，上面这行就报错
#!python tools/infer.py -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml --infer_img="/content/drive/My Drive/PaddleDetection/ dataset/voc/aistudio/JPEGImages/990.jpg" -o weights=output/model/epoch_499/model.pdparams #&nbsp;https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_roadsign.pdparams&nbsp;#模型预测


我尝试



!paddlex&nbsp;--export_inference&nbsp;--model_dir=output/model/best_model&nbsp;--save_dir=output/inference_model&nbsp;--fixed_input_shape=[480,480]&nbsp;&nbsp;#生成推理模型,但是用推理模型-c output/inference_model/model.yml去预测也是一样的 no gpu attribute 报错


环境

当我用paddlex训练自己的数据集出的模型组装到paaleDetection/tools/iner.py进行预测时使用权重文件output/model/epocho_170/model.pdparams加上-c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml组装没有问题，但当我 yml 文件的引用从 -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml 改为 -c output/model/epocho_170/
model.yml不带GPU运行命令呢？集用的是自定义的。这是我训练出的模型文件：






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月26日(星期三) 中午11:56
***@***.***&gt;;
抄送:&nbsp;"life is ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 当我使用PADDLEX resultful并且在ubuntu命令行部署时，我复制了命令行中返回的地址，chrome浏览器却提示我无法访问 (Issue #1374)





 
检测系统防火墙中对应的端口是否打开
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kkhuangzekai** [comment]
paddlex我用gui版本训练自定义模型然后预测跑成功了，但是paddlex的api代码版本训练模型成功以后预测一直报错：no gpu attributes ，想问一下对指定文件夹的图片进行预测的步骤是使用gui app文件夹中的python文件实现的呢？我想对照一下gui里的代码看看错在哪里


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 中午11:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 当我使用PADDLEX resultful并且在ubuntu命令行部署时，我复制了命令行中返回的地址，chrome浏览器却提示我无法访问 (Issue #1374)




 
检测系统防火墙中对应的端口是否打开
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FlyingQianMM** [comment]
该issue最后的问题与https://github.com/PaddlePaddle/PaddleX/issues/1373 一样，都是用paddlex的模型到paddledetection部署，因两个repo的model.yml内容不一致，无法直接加载模型导致报错。故先关闭该issue。
