### ISSUE TITLE
当我用paddlex训练自己的数据集出的模型装配到paaleDetection/tools/iner.py 进行预测时  报错

### ISSUE THREAD

**Issue by kkhuangzekai** [PaddlePaddle/PaddleX#1377]
## Checklist:
使用权重文件output/model/epocho_170/model.pdparams加上 -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml装配没有问题，但当我把yml文件的引用从 -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml 改为 -c output/model/epocho_170/model.yml  报错：no attribute 'use_gpu'
![image](https://user-images.githubusercontent.com/82854498/151492901-83908afa-789a-4c1c-868a-a5e93d55b5e5.png)

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)
这是我训练出的模型文件夹：
![image](https://user-images.githubusercontent.com/82854498/151492326-29d90411-2f2d-46fe-86a4-12a8db0491f0.png)

## 复现
这是我的代码：!python tools/infer.py -c output/model/epoch_170/model.yml --infer_dir="/content/drive/My Drive/PaddleDetection/dataset/voc/aistudio/JPEGImages"  -o 	weights=output/model/epoch_170/model.pdparams --output_dir=output/INFERimages1 --draw_threshold=0.2 --use_vdl=True --vdl_log_dir=output/infervdl_log #https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_roadsign.pdparams #模型预测
#下面这行是可以的，上面这行就报错
#!python tools/infer.py -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml --infer_img="/content/drive/My Drive/PaddleDetection/dataset/voc/aistudio/JPEGImages/990.jpg"  -o 	weights=output/model/epoch_499/model.pdparams  #https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_roadsign.pdparams #模型预测
1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

当我用paddlex训练自己的数据集出的模型装配到paaleDetection/tools/iner.py 进行预测时  使用权重文件output/model/epocho_170/model.pdparams加上 -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml装配没有问题，但当我把yml文件的引用从 -c configs/ppyolo/ppyolov2_r50vd_dcn_voc.yml 改为 -c output/model/epocho_170/model.yml  报错：no attribute 'use_gpu'  
请问是不是paddlex训练出的模型是不是默认不带GPU运行命令呢？  我使用的训练模型的代码是修改了VOC头盔示例helmet.py（https://aistudio.baidu.com/aistudio/projectdetail/2577364?channelType=0&channel=0）进行的，数据集用的是自定义的。这是我训练出的模型文件：
![image](https://user-images.githubusercontent.com/82854498/151493597-63d36507-10f9-4ce7-a660-2efdbd6e3014.png)

**Comment by FlyingQianMM** [comment]
paddlex的训练出来的模型跟paddledetection的差异在于model.yml，model.yml记录了预处理算子和模型信息。直接按您现在运行是不太可行的，PaddleX模型到PaddleDetection模型转换需要对model.yml做一些转换，镜像问题可以参考issue https://github.com/PaddlePaddle/PaddleX/issues/1371

已在QQ交流群回复您，该issue暂时关闭。
