### ISSUE TITLE
请问paddlex gui中训练模型成功后对指定文件夹的图片进行预测的步骤是使用文件夹中的python文件实现的呢？

### ISSUE THREAD

**Issue by kkhuangzekai** [PaddlePaddle/PaddleX#1378]
## Checklist:
我是用gui版本跑成功了，但是paddlex的api代码版本训练模型成功以后预测一直报错：no gpu attributes ，想问一下对指定文件夹的图片进行预测的步骤是使用gui app文件夹中的python文件实现的呢？我想对照一下gui里的代码看看错在哪里
1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by FlyingQianMM** [comment]
已在QQ交流群回复您，该issue暂关闭。
