### ISSUE TITLE
在pip安装paddlex时，安装scikit-learn时报错

### ISSUE THREAD

**Issue by foreverseer** [PaddlePaddle/PaddleX#1379]
## 描述问题

在pip安装paddlex时，安装scikit-learn时报错

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号 
**paddle2.2 paddlex2.1.0**

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
 **windows11专业版 21H2**

3. 请问您使用的Python版本是？
**python 3.9 anaconda 安装在user文件夹**

5. 请问您使用的CUDA/cuDNN的版本号是？
**cuda10.2 cudnn 7.6.5**

电脑型号，机械革命X7Ti，
CPU：Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.60 GHz
GPU：NVIDIA GeForce GTX 1060 6GB
内存：16.0 GB
x64系统，x64处理器

报错信息：

Building wheels for collected packages: scikit-learn, bce-python-sdk, lap, pycocotools, py-cpuinfo
  Building wheel for scikit-learn (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\zxb\anaconda3\python.exe' 'C:\Users\zxb\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\zxb\AppData\Local\Temp\tmp36fjxus8'
       cwd: C:\Users\zxb\AppData\Local\Temp\pip-install-_7a0z_cb\scikit-learn_e023d9eceead48caa4c701b807361b7c
  Complete output (959 lines):
  Partial import of sklearn during the build process.
  C:\Users\zxb\AppData\Local\Temp\pip-build-env-yt5yatcb\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py:528: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
    warnings.warn(
  [ 1/51] Cythonizing sklearn\__check_build\_check_build.pyx
...
  [51/51] Cythonizing sklearn\utils\sparsefuncs_fast.pyx
  Compiling sklearn\__check_build\_check_build.pyx because it changed.
  Compiling sklearn\preprocessing\_csr_polynomial_expansion.pyx because it changed.
....
  Compiling sklearn\linear_model\_sgd_fast.pyx because it changed.
  Compiling sklearn\linear_model\_sag_fast.pyx because it changed.
  Compiling sklearn\_isotonic.pyx because it changed.
  running bdist_wheel
  running build
  running config_cc
  running config_fc
  running build_src
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\sklearn
....
  creating build\bdist.win-amd64\wheel\sklearn\datasets\tests\data\openml\1
  copying sklearn\datasets\tests\data\openml\1\data-v1-download-1.arff.gz -> build\bdist.win-
....
build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292
  copying sklearn\datasets\tests\data\openml\292\api-v1-json-data-292.json.gz -> build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292
  copying sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz -> build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292
  error: could not create 'build\bdist.win-amd64\wheel\.\sklearn\datasets\tests\data\openml\292\api-v1-json-data-list-data_name-australian-limit-2-data_version-1-status-deactivated.json.gz': No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn

**Comment by FlyingQianMM** [comment]
另外建个环境，用python 3.7试下

**Comment by linuxonly801** [comment]
> 另外建个环境，用python 3.7试下

Ubuntu20.04 works!
