### ISSUE TITLE
使用PaddelX训练导出的模型中的model.yaml文件，cpp推理，cpp根本没法直接读取导出的model.yaml文件，能不能修改下这个问题？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/PaddleX#1382]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

2. c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？

3. 您使用的**模型**和**数据集**是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号

2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

4. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by FlyingQianMM** [comment]
> cpp根本没法直接读取导出的model.yaml文件

我们提供的部署代码是读取了model.yml文件的，如果您是自己开发，可以参考下我们的代码，我们先关闭该issue。

**Comment by xinsuinizhuan** [comment]
> > cpp根本没法直接读取导出的model.yaml文件
> 
> 我们提供的部署代码是读取了model.yml文件的，如果您是自己开发，可以参考下我们的代码，我们先关闭该issue。

您最好试一下吧，使用工程里面的cpp代码，读取使用paddleX训练导出的model.yml，目标检测、分类和分割，测试过这三个，三个都不对，都崩溃。
目标检测，paddleX-gui里面导出的mode.yml：
Model: PicoDet
Transforms:
- Resize:
    interp: CUBIC
    keep_ratio: false
    target_size: !!python/tuple
    - 640
    - 640
- Normalize:
    is_scale: true
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.229
    - 0.224
    - 0.225
_Attributes:
  eval_metrics:
    bbox_map: 80.42651757313699
  fixed_input_shape:
  - -1
  - 3
  - 640
  - 640
  labels:
  - leconte
  - boerner
  - armandi
  - linnaeus
  - coleoptera
  - acuminatus
  model_type: detector
  num_classes: 6
_init_params:
  backbone: ESNet_l
  nms_iou_threshold: 0.6
  nms_keep_topk: 100
  nms_score_threshold: 0.025
  nms_topk: 1000
  num_classes: 6
completed_epochs: 0
status: Infer
version: 2.1.0

代码中要读取：
![图片](https://user-images.githubusercontent.com/40679769/152735191-88fe3b5a-5f8e-4716-9b07-ac3b97ab5a39.png)
您看看到底的mode.yaml里面有label_list字段吗？

目标分类，model.yml文件：
Model: MobileNetV2
Transforms:
- ResizeByShort:
    interp: LINEAR
    max_size: -1
    short_size: 256
- CenterCrop:
    crop_size: 224
- Normalize:
    is_scale: true
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.229
    - 0.224
    - 0.225
_Attributes:
  eval_metrics:
    acc1: 0.6171875
  fixed_input_shape:
  - -1
  - 3
  - -1
  - -1
  labels:
  - bocai
  - changqiezi
  - hongxiancai
  - huluobo
  - xihongshi
  - xilanhua
  model_type: classifier
  num_classes: 6
_init_params:
  num_classes: 6
completed_epochs: 0
status: Infer
version: 2.1.0

代码中需要，lables:
![图片](https://user-images.githubusercontent.com/40679769/152735607-de21da05-2523-4c65-b41a-40785d3ff834.png)
但是，model.yml中的lables是二级目标，导致没法访问。

目标分割，model.yam:
Model: DeepLabV3P
Transforms:
- Resize:
    interp: LINEAR
    keep_ratio: false
    target_size:
    - 512
    - 512
- Normalize:
    is_scale: true
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.5
    - 0.5
    - 0.5
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.5
    - 0.5
    - 0.5
_Attributes:
  eval_metrics:
    miou: 0.9178956151008606
  fixed_input_shape:
  - -1
  - 3
  - -1
  - -1
  labels:
  - background
  - optic_disc
  model_type: segmenter
  num_classes: 2
_init_params:
  num_classes: 2
  use_mixed_loss: false
completed_epochs: 0
status: Infer
version: 2.1.0
代码中，需要根据version区分不同版本：
![图片](https://user-images.githubusercontent.com/40679769/152735884-65b383d7-d96b-405b-9c58-175634fcf5ae.png)
但是，Init(const YAML::Node& yaml_config)中的yaml_config中根本没有version字段，因为这边传的是yaml_config_字段，不是源seg_config = YAML::LoadFile(cfg_file);字段：
我手动加了version字段：
![图片](https://user-images.githubusercontent.com/40679769/152736093-aff0955e-e248-444e-9e76-a1b3b4146a11.png)

这三个，我都没法直接用model.yml文件，是从可用的其他yml中修改了关键字段，才可以了。
所以，建议您，帮忙看看，最好只能用model.yml，否则很难使用。
