### ISSUE TITLE
分类模型predict说明页面不存在，想了解更多predict的返回参数

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/PaddleX#1383]
## 描述问题
1. 关于分类模型的predict接口介绍页面404NotFound https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/apis/models/classification.md#predict
2. 请问paddlex.cls是否支持返回用户一个list，并且在里面标注每个类别的概率或者给出每个类别的分类可能性排序

## 环境

aistudio

**Comment by will-jl944** [comment]
1. 正确链接为 [https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/classification.md#predict](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/classification.md#predict)。这个错误链接是具体哪一篇aistudio教程里的呢？我们改一下。

2. 支持，指定`topk`参数为你的类别数即可，具体见`predict`接口的文档。

**Comment by Liyulingyue** [comment]
感谢回复
包含此错误链接的界面为：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/prediction.md
具体位置在 ## 目标检测 上面一行


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月9日(星期三) 上午10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 分类模型predict说明页面不存在，想了解更多predict的返回参数 (Issue #1383)





  
 
正确链接为 https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/classification.md#predict。这个错误链接是具体哪一篇aistudio教程里的呢？我们改一下。
 
 
 
支持，指定topk参数为你的类别数即可，具体见predict接口的文档。
 
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by will-jl944** [comment]
链接已修复，感谢反馈。
