### ISSUE TITLE
使用视频流出现的问题

### ISSUE THREAD

**Issue by HyChingXu** [PaddlePaddle/PaddleX#1394]
我是用的paddle_lite提供的demo，其他还有paddlex和paddleDetection里面的视频流demo也试过。但都不行。
以下是demo链接
https://github.com/PaddlePaddle/Paddle-Lite-Demo/tree/master/PaddleLite-android-demo
我试了ssd和yolo的

然后附件是我用paddlex导出来的模型以及用paddlelite生成的nb文件，感谢大佬！

**Comment by FlyingQianMM** [comment]
关于PaddleLite的demo，如果使用demo提供的模型可以跑通单张图片的预测的话，建议排除下是否是视频流处理本身的问题。

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～
