### ISSUE TITLE
windows , c++ ,编译链接失败，求路过的大佬指点一下：LINK : fatal error LNK1104: 无法打开文件“libyaml-cppmt.lib” [cpp\build\demo\model_infer.vcxproj]

### ISSUE THREAD

**Issue by SJJ-dot** [PaddlePaddle/PaddleX#1395]
## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？

    * 未修改代码，编译失败

4. 请提供您出现的报错信息及相关log

![图片](https://user-images.githubusercontent.com/15243969/154845653-6979ff48-3356-4ecf-bd17-7cb2b0717a53.png)

## 环境

2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号
最新版本。gitclone 未切换分支。cpu。mkl。

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows

4. 请问您使用的CUDA/cuDNN的版本号是？
cpu

**Comment by FlyingQianMM** [comment]
链接失败了，无法动态链接libyaml库，编译的DCMAKE_CXX_FLAGS加上-fPIC选项试试。

**Comment by SJJ-dot** [comment]
@FlyingQianMM 试了半天还是不行。。。我是在windows下编译的。是我写错地方了吗？

![图片](https://user-images.githubusercontent.com/15243969/154884683-7a086c5b-f1bd-4c7e-9f6b-ef98baf8564e.png)

**Comment by SJJ-dot** [comment]
这是我填写的配置项

![图片](https://user-images.githubusercontent.com/15243969/154884868-10efcc0e-7cce-434a-bdcd-7e974d4f3008.png)

**Comment by FlyingQianMM** [comment]
你的电脑有安装GPU吗？

**Comment by SJJ-dot** [comment]
@FlyingQianMM 没有，编译的CPU版本的 。

我把cmake的编译选项改成 release 版本后链接成功了，编译脚本里有配置只能选MKL。
使用vscode cmake编译生成的exe 启动不正常 没有任何输出。
使用Visual Studio 2019 编译生成的exe 能看到控制台的输出。但是没看到paddle的日志，不知道是不是报错程序直接退出了。

**Comment by thornsu** [comment]
debug编译生成的是libyaml-cppmtd.lib，名字不一样

**Comment by sillyho** [comment]
更换链接库，将libyaml-cppmt.lib改成libyaml-cppmtd.lib会报一些其他的错误

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MTd_StaticDebug”(model_infer.obj 中)	model_infer	F:\paddlex\PaddleX\PaddleX-develop\deploy\cpp\out\demo\gflags_static.lib(gflags.obj)	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2038	检测到“_ITERATOR_DEBUG_LEVEL”的不匹配项: 值“0”不匹配值“2”(model_infer.obj 中)	model_infer	F:\paddlex\PaddleX\PaddleX-develop\deploy\cpp\out\demo\gflags_static.lib(gflags_reporting.obj)	1

**Comment by ty01528** [comment]
paddle inference遇到了同样的问题

**Comment by ty01528** [comment]
> paddle inference遇到了同样的问题

release下编译没问题，debug下就是不通过

**Comment by SJJ-dot** [comment]
> make的编译选项改成 release 版本后链接成功了，编译脚本里有配置只

[debug编译生成的是libyaml-cppmtd.lib，名字不一样](https://github.com/PaddlePaddle/PaddleX/issues/1395#issuecomment-1118227768)
