### ISSUE TITLE
paddlex可视化客户端如何添加新的算法模型

### ISSUE THREAD

**Issue by wyyzxml2120** [PaddlePaddle/PaddleX#1398]
我是做目标检测的，客户端里只有少量模型，可能是我数据问题，使用yolo时一直mAP为0，我想使用ssd模型，但没有这个选项，想问下paddlex如何使用其他模型。

**Comment by FlyingQianMM** [comment]
PaddleX客户端暂时不支持自行添加模型。目前PaddleX没有集成SSD，如果需要使用，可至PaddleDetection使用SSD: https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3/configs/ssd

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～
