### ISSUE TITLE
cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. 

### ISSUE THREAD

**Issue by llt-Nancy** [PaddlePaddle/PaddleX#1399]
paddleX GUI版本号:2.1.0,  Windows，飞桨版本：PaddlePaddle2.2.1
CUDA:11.2  ,   cuDNN:8.1.0
驱动:511.23
训练项目为安装时所下载的“果蔬类别”

err.log
> This log file path is D:\paddlex_workspace\projects\P0002\T0005\err.log
> 注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
> D:\Desktop\PaddleX\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
>   "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
> D:\Desktop\PaddleX\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   if data.dtype == np.object:
> Process Process-1:3:
> Traceback (most recent call last):
>   File "multiprocessing\process.py", line 297, in _bootstrap
>   File "multiprocessing\process.py", line 99, in run
>   File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
>   File "paddlexui\pms\model_tasks\train\classification.py", line 118, in train
>   File "D:\Desktop\PaddleX\paddlex\cv\models\classifier.py", line 628, in __init__
>     model_name=model_name, num_classes=num_classes, **params)
>   File "D:\Desktop\PaddleX\paddlex\cv\models\classifier.py", line 71, in __init__
>     self.net = self.build_net(**params)
>   File "D:\Desktop\PaddleX\paddlex\cv\models\classifier.py", line 76, in build_net
>     class_dim=self.num_classes, **params)
>   File "D:\Desktop\PaddleX\paddlex\ppcls\modeling\architectures\mobilenet_v2.py", line 237, in MobileNetV2
>     model = MobileNet(scale=1.0, **args)
>   File "D:\Desktop\PaddleX\paddlex\ppcls\modeling\architectures\mobilenet_v2.py", line 173, in __init__
>     name=prefix_name + "conv1_1")
>   File "D:\Desktop\PaddleX\paddlex\ppcls\modeling\architectures\mobilenet_v2.py", line 56, in __init__
>     bias_attr=False)
>   File "D:\Desktop\PaddleX\paddle\nn\layer\conv.py", line 646, in __init__
>     data_format=data_format)
>   File "D:\Desktop\PaddleX\paddle\nn\layer\conv.py", line 135, in __init__
>     default_initializer=_get_default_param_initializer())
>   File "D:\Desktop\PaddleX\paddle\fluid\dygraph\layers.py", line 412, in create_parameter
>     default_initializer)
>   File "D:\Desktop\PaddleX\paddle\fluid\layer_helper_base.py", line 374, in create_parameter
>     **attr._to_kwargs(with_initializer=True))
>   File "D:\Desktop\PaddleX\paddle\fluid\framework.py", line 2895, in create_parameter
>     initializer(param, self)
>   File "D:\Desktop\PaddleX\paddle\fluid\initializer.py", line 366, in __call__
>     stop_gradient=True)
>   File "D:\Desktop\PaddleX\paddle\fluid\framework.py", line 2925, in append_op
>     kwargs.get("stop_gradient", False))
>   File "D:\Desktop\PaddleX\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
>     not stop_gradient)
> SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
> The exception content is
> :parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at C:\home\workspace\Paddle_release2\paddle\fluid\imperative\tracer.cc:192)

**Comment by FlyingQianMM** [comment]
看安装的CUDA、cuDNN版本没啥问题，启一个python环境按照如下确认下：
1、验证安装的Paddle:
![image](https://user-images.githubusercontent.com/22235422/155253956-940c2ef0-3794-4115-afa8-fcdf87c72bbf.png)
![image](https://user-images.githubusercontent.com/22235422/155253972-c1734e37-4d8e-447b-a562-726b8d1678c5.png)

Paddle安装链接：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

2、验证PaddleX训练脚本：
安装PaddleX pip 安装包，然后运行训练脚本：https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train

**Comment by FlyingQianMM** [comment]
安装成功的话，这个issue先关闭了哈～
