### ISSUE TITLE
paddlex发布模型，导出格式变化了吗

### ISSUE THREAD

**Issue by meishitouzhele** [PaddlePaddle/PaddleX#1400]
1.1.7与2.1.0版本发布导出模型更改了吗；导出的文件不一样了啊，我导出后需要转化为paddlehub使用   两种我截图了
![555](https://user-images.githubusercontent.com/11419081/155290819-2a3500ef-89ff-40ed-b709-ae1e0682f625.png)
![66666](https://user-images.githubusercontent.com/11419081/155290828-7cb6d667-ea33-47da-a218-5e375475ad2b.png)

**Comment by FlyingQianMM** [comment]
1.x版本是静态图格式。2.x版本是动态图格式，对应paddlehub可以使用2.x版本的

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～
