### ISSUE TITLE
WINDOWS支持仅CPU运行么(如果可以怎么做)

### ISSUE THREAD

**Issue by lubupang** [PaddlePaddle/PaddleX#1401]
## 描述问题

训练失败,日志如下

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2]
SystemError: (Fatal) Operator gaussian_random raises an class thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at ..\paddle\fluid\imperative\tracer.cc:221)

2. 请提供您使用的GUI版本号
2.1.0
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
windows 10版本号如截图
![image](https://user-images.githubusercontent.com/31611588/155641992-1d8b8cfa-b8ac-4f32-bbd4-5b336d3396da.png)

5. 请问您使用的CUDA/cuDNN的版本号是？
显卡不支持CUDA

**Comment by FlyingQianMM** [comment]
本地有GPU的情况下，PaddleX GUI 2.0要求CUDA >= 11.0，cuDNN>=8.0，如果不满足，启动CPU训练也会有问题。
要么用PaddleX API模式，安装CPU版本的PaddlePaddle。

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～
