### ISSUE TITLE
模型转换后，安卓端部署，输出结果问题

### ISSUE THREAD

**Issue by zjyhll** [PaddlePaddle/PaddleX#1403]
![image](https://user-images.githubusercontent.com/8895877/155940361-e561c307-a703-4255-ad5f-3664fff83b76.png)
![image](https://user-images.githubusercontent.com/8895877/155940378-6fbe56e5-5284-4541-ad35-e59e3d8a5eaa.png)
![image](https://user-images.githubusercontent.com/8895877/155940393-f1c52e71-25a8-4b9d-acf9-6d5fc2976263.png)
在手机上右下坐标为(0.0)，这样没法绘制准确的框框
但是这个模型在windows下使用paddlex
pdx.det.visualize(image_name, result, threshold=0.1, save_dir='./output/ppyolotiny2')
输出结果正确
![image](https://user-images.githubusercontent.com/8895877/155940626-7ad263f6-1a81-4e63-9aad-0833e0138247.png)
咨询过paddlelite那边，说的是paddlex套件的问题

**Comment by FlyingQianMM** [comment]
在安卓端部署的时候，输入给模型的数据预处理和拿到模型结果的后处理，跟paddlex的python处理是一样的吗？可以对齐下这两个环节

**Comment by zjyhll** [comment]
> 在安卓端部署的时候，输入给模型的数据预处理和拿到模型结果的后处理，跟paddlex的python处理是一样的吗？可以对齐下这两个环节

我发现是现在paddlex2.1.0和paddledetection2.3的输出后面两个点是按宽和高来的，但paddlelite那边是按右下角来处理的，所以问题的解决还是得靠paddlelite那边才行
![image](https://user-images.githubusercontent.com/8895877/156957226-cb9f7d9e-b75e-448f-bd65-4cc2cc5c235c.png)

**Comment by FlyingQianMM** [comment]
嗯嗯，定位到问题就好！
> 但paddlelite那边是按右下角来处理的，所以问题的解决还是得靠paddlelite那边才行

拿到模型的结果之后怎么做下游任务例如可视化，您这边也可以根据实际情况自行开发。
这部分也不依赖于paddlelite引擎，不过可以反馈给paddlelite。

这个issue就先关闭了哈～
