### ISSUE TITLE
import paddlex as pdx 启动慢，只要目标检测预测，应该怎么弄

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1407]
`import paddlex as pdx`

加了全部的paddlex的模块 
启动的时候 就会比较慢

如果我只要 目标检测
其他什么都不需要 也不需要训练

那么我要怎么调用具体的模型 而不需要全部加载
识别 只需要返回坐标信息

**Comment by FlyingQianMM** [comment]
> 如果我只要 目标检测
> 其他什么都不需要 也不需要训练

如果用paddlex发布的包，这个比较难办到。要么就基于develop分支，自行修改paddlex的代码
