### ISSUE TITLE
Python推理时出错Exception: transforms need to be defined, now is None.

### ISSUE THREAD

**Issue by yuanjim** [PaddlePaddle/PaddleX#1409]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 复现
2022数字中国创新大赛：卫星应用赛题——海上船舶智能检测的baseline

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
是
2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
是

import paddlex as pdx
model = pdx.load_model('output/faster_rcnn_r50_fpn/best_model')
img_path = 'JPEGImages/05555.jpg'
result = model.predict(img_path)
print('result=', result)
pdx.det.visualize(img_path, result, save_dir='output/predict_imgs/')

3. 您使用的数据集是？
train

4. 请提供您出现的报错信息及相关log
2022-03-01 08:53:04 [INFO]      Model[FasterRCNN] loaded.
Traceback (most recent call last):
  File "predict.py", line 5, in <module>
    result = model.predict(img_path)
  File "/usr/local/lib/python3.7/dist-packages/paddlex/cv/models/detector.py", line 530, in predict
    raise Exception("transforms need to be defined, now is None.")
Exception: transforms need to be defined, now is None.
## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddle 2.2.2
paddleX 2.1.0

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Linux
3. 请问您使用的Python版本是？
3.7.0
5. 请问您使用的CUDA/cuDNN的版本号是？
Driver API Version: 11.4, Runtime API Version: 11.2
cuDNN Version: 8.1.

**Comment by will-jl944** [comment]
查看一下`output/faster_rcnn_r50_fpn/best_model`路径下是否有`model.yml`文件，以及其中是否包含'Transforms'字段。如果模型是在训练过程中自动评估并保存的，会包含Transforms。否则，按照报错信息提示，在调用`model.predict`时定义transform即可。

**Comment by yuanjim** [comment]
我已收到您的邮件。谢谢！
