### ISSUE TITLE
对于不同类别样本数据不均衡，有什么办法吗？

### ISSUE THREAD

**Issue by JimXu1989** [PaddlePaddle/PaddleX#1410]
您好，
我想训练分类模型，但是数据中每个类别的数量差异比较大请问有什么方法，比如在界面上设计一个按键，调整loss的计算方式

**Comment by FlyingQianMM** [comment]
> 数据中每个类别的数量差异比较大

这个差异具体有统计是多大吗？一般情况下，数据集不会出现长尾问题。

**Comment by JimXu1989** [comment]
> > 数据中每个类别的数量差异比较大
> 
> 这个差异具体有统计是多大吗？一般情况下，数据集不会出现长尾问题。

差异大呀，差10倍以上

**Comment by FlyingQianMM** [comment]
差异大的话，可以关注下长尾问题和相应的解决办法。
这个issue先关闭了哈，如有需要再打开～
