### ISSUE TITLE
训练出来的模型，转成onnx后，无法被opencv读取，paddlehub的模型就可以

### ISSUE THREAD

**Issue by JimXu1989** [PaddlePaddle/PaddleX#1411]
新版的opencv支持paddle的模型之后，支持将paddle的模型转化为onnx后读取。
来自paddlehub的模型这样做可以，但是paddlex gui训练出来的模型就不行。

**Comment by FlyingQianMM** [comment]
> 来自paddlehub的模型这样做可以，但是paddlex gui训练出来的模型就不行。
想确认下是相同的任务模型，paddlex gui的不行，但paddlehub的可以？具体是哪个模型？

**Comment by JimXu1989** [comment]
图像分类的模型应该是都不行，我试的res18

**Comment by FlyingQianMM** [comment]
paddlehub的模型和paddlex的模型本质上都是paddle的模型格式：model.pdmodel、model.pdparams。
> paddlex gui训练出来的模型就不行。

这个报错信息还有么
