### ISSUE TITLE
paddlex  api 训练的时候如何设置多卡训练。找了半天文档，没找到再哪里设置。

### ISSUE THREAD

**Issue by smallhaozigithub** [PaddlePaddle/PaddleX#1412]
paddlex  api 训练的时候如何设置多卡训练。找了半天文档，没找到再哪里设置。

**Comment by kassol** [comment]
## 环境检测
`paddle.utils.run_check()`
`paddle.fluid.cuda_places()`

## gpu 并行配制（nccl2）
1. 下载压缩包
2. 解压
3. export LD_LIBRARY_PATH=<lib 目录>


## 并行训练
`python -m paddle.distributed.launch --gpus 0,1 <py 路径>`

**Comment by FlyingQianMM** [comment]
多卡训练的启动方式在tutorials的文档里有说明： https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials/train#%E5%BC%80%E5%A7%8B%E8%AE%AD%E7%BB%83
