### ISSUE TITLE
目标检测，旋转框，怎么实现

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1413]
目标检测，旋转框，怎么实现

旋转框检测
我看PaddleDetection有

但是我想在PaddleX的框架下实现

**Comment by FlyingQianMM** [comment]
目前PaddleX没有集成旋转框检测的计划，您可以使用PaddleDetection完成。如果您想在PaddleX的框架下实现的话，可以参考目前PaddleX的设计，self.net直接调用PaddleDetection的模型组网代码，预处理部分和预测结果后处理做下适配即可。

**Comment by monkeycc** [comment]
@FlyingQianMM 

水平有限

有空可以做一个代码不 
还能更新在paddleX的教程中 一举两得

**Comment by FlyingQianMM** [comment]
目前PaddleX没有集成旋转框检测的计划哈~
