### ISSUE TITLE
ValueError: `paddle.load` can not parse the MaskRCNN_ResNet50_fpn_COCO\mask_rcnn_r50_fpn_2x_coco.pdparams.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1416]
paddleX 2.1

看上去因为服务器没有这个模型
导致不能下载

`ValueError: `paddle.load` can not parse the MaskRCNN_ResNet50_fpn_COCO\mask_rcnn_r50_fpn_2x_coco.pdparams.`

**Comment by FlyingQianMM** [comment]
我这边测试可以正常加载，确认下是不是这个预训练模型没有下载完整
