### ISSUE TITLE
python3.9  安装paddlex的时候   引用scikit-learn 0.23.2 版本，但是 0.23.2 不支持python3.9 ，导致安装失败

### ISSUE THREAD

**Issue by aaa106** [PaddlePaddle/PaddleX#1418]
python3.9  安装paddlex的时候  
引用scikit-learn 0.23.2 版本，但是 0.23.2 不支持python3.9 导致安装失败，希望修复

**Comment by FlyingQianMM** [comment]
两种解决方案：
1、降低python版本至3.9
2、安装适配python 3.9的高版本scikit-learn

建议采取第一种方案

**Comment by PMPBinZhang** [comment]
这边默认就是安装0.23.2版本的scikit-learn，这个没法修改吧

**Comment by dly667** [comment]
自己打包paddlex
