### ISSUE TITLE
代码库中「PaddleX可视化客户端介绍」里的 Readme.md 中，「安装使用」部分的链接失效 

### ISSUE THREAD

**Issue by philip8728** [PaddlePaddle/PaddleX#1419]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题

GUI 文档中的链接失效：https://github.com/PaddlePaddle/PaddleX/tree/develop/docs/gui
具体链接如下：

请参考[快速开始](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/gui/quick_start.md)查看[视频教程](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/gui/quick_start.md/#%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B)和[文档教程](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/gui/quick_start.md/#%E6%96%87%E6%A1%A3%E6%95%99%E7%A8%8B)。

## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
是

3. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
否

5. 您使用的数据集是？
n/a

7. 请提供您出现的报错信息及相关log
https://github.com/PaddlePaddle/PaddleX/tree/develop/docs/gui

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
2.0.0

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
MacOS

5. 请问您使用的Python版本是？
n/a

9. 请问您使用的CUDA/cuDNN的版本号是？
n/a

**Comment by FlyingQianMM** [comment]
感谢指正，该问题已修复，见pr #1427 。
