### ISSUE TITLE
C++部署batch_infer.exe, 使用MaskRCNN模型batchsize>1时会报错。

### ISSUE THREAD

**Issue by lishuai903** [PaddlePaddle/PaddleX#1423]
## 问题描述
1. demo：https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy
使用demo生成的batch_infer.exe

2. 数据：小度熊分拣数据

3. 模型：paddlex 训练的模型:MaskRCNN,  Backbone:ResNet50

4. 问题描述：
 **使用batch_infer.exe batch_size = 1是正常的可以出结果，但是batch_size>1时会报错，尝试其他分类或检测模型是没有问题的，是否mask只支持batch_size = 1**
代码如下：
` .\batch_infer.exe --model_filename D:\paddlex_workspace\xiaoduxiong_mask\inference_model\inference_model\model.pdmodel --params_filename D:\paddlex_workspace\xiaoduxiong_mask\inference_model\inference_model\model.pdiparams --cfg_file D:\paddlex_workspace\xiaoduxiong_mask\inference_model\inference_model\model.yml --model_type paddlex --image_list D:\paddlex_workspace\datasets\D0001\list.txt --batch_size 4 `

5. 错误内容：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: condition input's data type should be bool, numel should be 1, actual numel is 4
  [Hint: Expected ips[0]->type() == framework::proto::VarType::BOOL && ips[0]->numel() == 1 == true, but received ips[0]->type() == framework::proto::VarType::BOOL && ips[0]->numel() == 1:0 != true:1.] (at ..\paddle/fluid/operators/controlflow/conditional_block_op.h:73)

**Comment by FlyingQianMM** [comment]
目前mask只支持batch_size = 1。
这个issue先关闭了哈，如有需要再打开～
