### ISSUE TITLE
文档中实例分割的数据集下载链接挂掉了

### ISSUE THREAD

**Issue by linhandev** [PaddlePaddle/PaddleX#1426]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX数据准备文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#2-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)

## 描述问题

[文档地址](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data/format/instance_segmentation.md#%E8%AE%AD%E7%BB%83%E9%9B%86%E9%AA%8C%E8%AF%81%E9%9B%86%E5%88%97%E8%A1%A8)
[数据集地址](https://bj.bcebos.com/paddlex/datasets/garbage_ins_det.tar.gz)
![image](https://user-images.githubusercontent.com/29757093/159231220-3426fc39-c019-4e35-b718-ed0e3af2e2c0.png)

## 复现

1. 您使用的命令是？

2. 您使用的数据集是？

3. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是

**Comment by FlyingQianMM** [comment]
您好，这个数据集暂时不提供了，您可以使用现在教程里的小度熊数据集
