### ISSUE TITLE
数据集训练问题

### ISSUE THREAD

**Issue by Qiao12-pixel** [PaddlePaddle/PaddleX#1428]
训练任务T0004异常终止，请查阅错误日志具体确认原因D:\paddleX\projects\P0001\T0004\err.log。

**Comment by will-jl944** [comment]
看一下`D:\paddleX\projects\P0001\T0004\err.log`里的报错信息。

**Comment by Qiao12-pixel** [comment]
[Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at ..\paddle\fluid\platform\gpu_info.c

**Comment by Qiao12-pixel** [comment]
> 
[Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at ..\paddle\fluid\platform\gpu_info.c

**Comment by FlyingQianMM** [comment]
您的机器本地有GPU吗？有GPU的情况下，PaddleX GUI >=2.0要求CUDA>=11.0, cuDNN>=8.0。

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～

**Comment by Peri-Galaxy** [comment]
> 您的机器本地有GPU吗？有GPU的情况下，PaddleX GUI >=2.0要求CUDA>=11.0, cuDNN>=8.0。

这个具体怎么操作呢
