### ISSUE TITLE
C++部署，编译成exe，未读取配配置文件中的_init_params，修改无效

### ISSUE THREAD

**Issue by wzy123456wzy** [PaddlePaddle/PaddleX#1429]
Paddlex版本为2.10
训练模型是2.1paddlex GUI训练出来的
配置文件如下：
Model: PicoDet
Transforms:
- Resize:
    interp: CUBIC
    keep_ratio: false
    target_size: !!python/tuple
    - 640
    - 640
- Normalize:
    is_scale: true
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.229
    - 0.224
    - 0.225
_Attributes:
  eval_metrics:
    bbox_map: 99.17355371900825
  fixed_input_shape:
  - -1
  - 3
  - 640
  - 640
  labels:
  - yumi
  model_type: detector
  num_classes: 1
_init_params:
  backbone: ESNet_m
  nms_iou_threshold: 0.6
  nms_keep_topk: 1
  nms_score_threshold: 0.025
  nms_topk: 1000
  num_classes: 1
completed_epochs: 0
status: Infer
version: 2.1.0

![image](https://user-images.githubusercontent.com/44393339/159851522-ce5deb79-7a60-49f2-8170-e4bc9b4f4516.png)
我删掉或更改_init_params，并未生效

**Comment by FlyingQianMM** [comment]
_init_params是用于在训练过程中定义模型参数。部署代码不会读取这个字段，模型参数定义已经保存在model.pdmodels里面了

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～

**Comment by wzy123456wzy** [comment]
> 这个issue先关闭了哈，如有需要再打开～
等下哈，我在Paddlex中训练的，如何更改呢

**Comment by FlyingQianMM** [comment]
训练的时候直接修改PicoDet()的参数即可

**Comment by wzy123456wzy** [comment]
> 训练的时候直接修改PicoDet()的参数即可

GUI版本的也可以嘛。

**Comment by FlyingQianMM** [comment]
GUI训练就直接改界面上的参数设定就行，如果觉得暴露的参数不够多，可以使用API开发。
