### ISSUE TITLE
工业指针实力中坐标是如何转化的

### ISSUE THREAD

**Issue by jianxin123** [PaddlePaddle/PaddleX#1430]
由于我的仪表和示例中的不太一样，所以要修改推理函数，但是看了两天不是很明白，不知道该如何修改，附上我自己已经分割完的仪表 和几处不太明白的地方 希望大佬帮帮忙
![微信图片_20220324161956](https://user-images.githubusercontent.com/32336392/159873284-0242c6a6-aae3-4b43-a931-00cd20d8f4e7.jpg)
![屏幕截图 2022-03-24 161559](https://user-images.githubusercontent.com/32336392/159873297-3c1b1c77-96ba-4af9-8669-c6b8735cd31c.jpg)
![屏幕截图 2022-03-24 161223](https://user-images.githubusercontent.com/32336392/159873301-e22b116f-6e1e-4e13-a518-697e293b3e53.jpg)

**Comment by jianxin123** [comment]
按照公式上x，y的范围是0~2r，而以中心为原点，x，y范围不是-r~r吗 @FlyingQianMM

**Comment by FlyingQianMM** [comment]
![image](https://user-images.githubusercontent.com/22235422/161371604-daad67e7-33e8-4117-8962-1aad49b3f56a.png)
x-y坐标系-y轴开始逆时针转一圈，对应theta 0-360

**Comment by jianxin123** [comment]
按照这个角度的话 代码中x和y的范围是0到2r了 和以中心点为圆心不是不符合吗，因为这样的范围不是-r到r吗

**Comment by FlyingQianMM** [comment]
-y轴对应0，以中心点为圆心逆时针绕一圈回来是360，
