### ISSUE TITLE
paddlex 1.c#程序运行报错，2.生成的dll文件少了几个

### ISSUE THREAD

**Issue by for-magic** [PaddlePaddle/PaddleX#1431]
1.运行c#工程实例报错
![image](https://user-images.githubusercontent.com/69380005/159887791-426c10f9-ebd5-4936-b275-b6aff96d04ac.png)
2.用model_infer生成的dll文件不全
![image](https://user-images.githubusercontent.com/69380005/159888085-92829856-9c3b-4c70-8212-75b52ddd3d8e.png)
3.参考视频https://www.bilibili.com/video/BV1vS4y1R7wT?p=2&spm_id_from=pageDriver

**Comment by yzl19940819** [comment]
应该是你没有配置trt的库。https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy 你看一下这个文档，还缺少好几个dll

**Comment by for-magic** [comment]
![image](https://user-images.githubusercontent.com/69380005/159889970-b7a23464-13e2-48b4-8261-c4fe49370410.png)
我的库应该都是配置好的吧

**Comment by yzl19940819** [comment]
with_paddle_trt这个勾选一下

**Comment by for-magic** [comment]
可以跑通了，好像支持paddlex导出的模型
![image](https://user-images.githubusercontent.com/69380005/159917488-3744e5a8-e05d-45df-b2be-417676a6ce90.png)
![image](https://user-images.githubusercontent.com/69380005/159917554-ef1bc7e7-4a61-4d3c-aae3-2d949266f7c3.png)

**Comment by yzl19940819** [comment]
如果是paddlex导出的，选择paddlex，paddledetection导出的，选择det，详细参考
https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy

**Comment by FlyingQianMM** [comment]
该issue先关闭了哈，如有需要再打开～
