### ISSUE TITLE
c#加载模型后，推理模型报错

### ISSUE THREAD

**Issue by for-magic** [PaddlePaddle/PaddleX#1432]
![image](https://user-images.githubusercontent.com/69380005/159922796-b34330ba-030b-4224-ac79-8a0c6348353d.png)

**Comment by bbloodtech** [comment]
模型你用的是paddlex导出的模型吗，如果是的话把模型类型改成paddlex就行了
![image](https://user-images.githubusercontent.com/55309644/160078722-1e4a40f2-dbc6-4f19-8cdd-1e032249eb9c.png)

**Comment by for-magic** [comment]
是paddledetection导出来的，paddlx导出的yml文件也不能加载

**Comment by whisky-12** [comment]
> 模型你用的是paddlex导出的模型吗，如果是的话把模型类型改成paddlex就行了 ![image](https://user-images.githubusercontent.com/55309644/160078722-1e4a40f2-dbc6-4f19-8cdd-1e032249eb9c.png)

这里模型加载后 ，不是自动选择好了类型嘛? 还需要修改嘛？
我们很多人遇到同样的问题，能=否指点下

**Comment by whisky-12** [comment]
楼主解决了嘛 ？ 同样的问题 困扰很久了

**Comment by for-magic** [comment]
解决了，gui2.1版本导出的模型选择paddleX可以推理

**Comment by whisky-12** [comment]
> 解决了，gui2.1版本导出的模型选择paddleX可以推理
方便的话，可否提供下model文件，我这边测试下，gui2.1版本是指？ 还请指点下， 目前这个问题比较关紧，还请帮忙指点，定重谢

**Comment by whisky-12** [comment]
就是我按照githup上的流程走的，没有多做其他操作
模型是ai studio&nbsp;上下载的 ，可以初始化成功，但不能推理
可以帮忙看下嘛 ，真的很感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 下午4:43
***@***.***&gt;;
抄送:&nbsp;"→孤← ***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] c#加载模型后，推理模型报错 (Issue #1432)





 
解决了，gui2.1版本导出的模型选择paddleX可以推理

**Comment by yzl19940819** [comment]
![image](https://user-images.githubusercontent.com/48433081/160619633-9fcbed2d-9887-43e2-8319-afb0dd197e84.png)
仔细阅读一下文档内容，看一下这部分https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy

**Comment by whisky-12** [comment]
恩这部分 ，应该可以确定是没有问题的吧，模型是ai studio&nbsp;中导出的模型， （paddleDetection模型），这里选中模型后，会弹出模型为det&nbsp;的弹框，模型初始化成功&nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月29日(星期二) 晚上9:16
收件人: ***@***.***&gt;; 
抄送: "→孤← ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleX] c#加载模型后，推理模型报错 (Issue #1432)





 

 仔细阅读一下文档内容，看一下这部分https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy

**Comment by whisky-12** [comment]
> ![image](https://user-images.githubusercontent.com/48433081/160619633-9fcbed2d-9887-43e2-8319-afb0dd197e84.png) 仔细阅读一下文档内容，看一下这部分https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy


模型如果是错误的不就直接初始化失败了呀， 模型不用选择，导入后就自己选择了呀？

**Comment by yzl19940819** [comment]
> 

你看一下文档，文档3.5有操作过程，第一步是选择模型类型！

**Comment by whisky-12** [comment]
> > 
> 
> 你看一下文档，文档3.5有操作过程，第一步是选择模型类型！
好的 ，多谢了 。没有注意到这一点， 问题已经解决， 再次感谢。

**Comment by FlyingQianMM** [comment]
该issue先关闭了哈，如有需要再打开～
