### ISSUE TITLE
albumentations数据增强分割实例，标签与实际不符合

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1437]
`https://albumentations.ai/docs/examples/example_kaggle_salt/`

![下载](https://user-images.githubusercontent.com/6490927/160277577-df8cd3d6-6ae9-45ff-902d-749657530483.png)

语义分割用了albumentations数据增强

导出规定的数据集格式

提示  标签与实际不符合

应该要怎么弄

**Comment by FlyingQianMM** [comment]
检查下自行添加的albumentations操作逻辑是否正确，是否符合paddlex的transforms格式。

该issue先关闭了哈，如有需要再打开～
