### ISSUE TITLE
C# windows 部署 模型推理报 ： System.AccessViolationException:“Attempted to read or write protected memory. xxx.”

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/PaddleX#1438]
使用平台windows10 ， Cuda ： 10.2 ，cudnn:7.6 , opencv 3.4.6
目前模型在CPU、GPU下 初始化都可以初始化成功，
尝试导入的模型为det类的aistudio中开源的火灾监测模型以及水表监测模型
模型导入后会弹出模型类型为det的弹窗，单击后 会显示模型初始化成功

导入图片没有问题 ，随后点击模型推理 就弹出
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”的NG现象

由于本次项目部署对答辩项目展示非常重要，因此也特地请朋友们也按照步骤进行部署测试，目前NG现象相同
对此我们目前存在疑惑，推断是否与加载model有关， 但model是在 ai studio的开源项目中，直接下载的模型，开源项目画面显示可推理，所以也感到不解。

希望有相关Reviewer ，看到本条Issue，可以帮忙提出debug意见，时间比较紧迫，比较项目能否跑通对后续答辩影响比较重要，
再次感谢，还望在百忙中，指点疑惑，不胜感激。

代码从git上下拉最新版本，操作步骤按照B站讲解视频以及git中md文件 实施
![图片](https://user-images.githubusercontent.com/79358023/160283880-8b100a6a-3c30-44ee-a2a3-ab5366e9e6d8.png)
![图片](https://user-images.githubusercontent.com/79358023/160283980-f8822aa9-b47c-409b-90a5-7afa8ce1aff2.png)
![图片](https://user-images.githubusercontent.com/79358023/160284857-671b82e9-0783-4b36-8486-e64c2802d9ab.png)
![图片](https://user-images.githubusercontent.com/79358023/160284882-3133ce8e-ceb4-4d46-8485-84348388d3b2.png)
![图片](https://user-images.githubusercontent.com/79358023/160285192-7418b862-b6e0-4918-b3bf-4971a7308764.png)
![图片](https://user-images.githubusercontent.com/79358023/160285201-4c4827d8-1a3a-4325-a92d-cd9b81e123c8.png)

![图片](https://user-images.githubusercontent.com/79358023/160285527-82236bfb-9aa4-4117-89b5-942dcf1b3395.png)

**Comment by yzl19940819** [comment]
你好，确定一下，你是paddlex训练出来的模型吧，应该选择模型的类型是paddlex

**Comment by yzl19940819** [comment]
https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy  可以看一下文档中3.4小节的说明

**Comment by zhinangubei** [comment]
你好，最后问题解决了吗？我碰到同样的问题，同学麻烦回复一下

**Comment by whisky-12** [comment]
一般情况下，模型类型都选择为paddlex即可，其他类型排除发自我的 iPhone在 2023年1月28日，11:09，zhinangubei ***@***.***> 写道：﻿
你好，最后问题解决了吗？我碰到同样的问题，同学麻烦回复一下
