### ISSUE TITLE
语义分割返回的mask，如何得到mask坐标

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#1439]
语义分割返回的mask，如何得到mask坐标
需要外轮廓的所有坐标点

**Comment by LeeGeong** [comment]
同问，C++部署，CMake编译能不能改成Debug模式，自己调试也行

**Comment by FlyingQianMM** [comment]
参考 issue https://github.com/PaddlePaddle/PaddleX/issues/975 里的回复

该issue与https://github.com/PaddlePaddle/PaddleX/issues/1420 问题相似，issue先关闭，如有需要再打开
