### ISSUE TITLE
visualdl运行的网址打不开

### ISSUE THREAD

**Issue by smallwhi** [PaddlePaddle/PaddleX#1441]
![image](https://user-images.githubusercontent.com/66171021/160850765-2cfa8d01-f84b-4496-9c61-67814a3c1706.png)
![image](https://user-images.githubusercontent.com/66171021/160851277-d7129c01-110c-46de-861f-ad96c447e7fe.png)

![image](https://user-images.githubusercontent.com/66171021/160850825-1bd8b429-8fbf-44ad-a864-1b1c128455d7.png)

**Comment by smallwhi** [comment]
已解决，放在本地运行可行

**Comment by for-magic** [comment]
结构可以展示吗，我上传一直报错
![image](https://user-images.githubusercontent.com/69380005/161080514-91f6d471-4f19-4c88-b47d-59db76b15f2c.png)

**Comment by FlyingQianMM** [comment]
> 结构可以展示吗，我上传一直报错 ![image](https://user-images.githubusercontent.com/69380005/161080514-91f6d471-4f19-4c88-b47d-59db76b15f2c.png)

可以的。展示以pdmodels结尾的文件即可。

**Comment by FlyingQianMM** [comment]
问题已经解决，这个issue先关闭了哈，如有需要再打开～
