### ISSUE TITLE
paddlex api训练如何获取训练指标信息，比如获取训练中loss等信息？

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/PaddleX#1443]
目前我在使用paddlex api来训练网络，虽然官方提供了use_vdl来对训练数据可视化，但是我要如何在训练时获取loss，bbox等指标，用于我进行其他分析？

**Comment by FlyingQianMM** [comment]
loss，bbox等指标都在输出日志中，解析输出日志即可。
这个issue先关闭了哈，如有需要再打开～

**Comment by thgpddl** [comment]
请问要如何打开呢？我初步用sublime软件打开visualdl产生的log文件，但是似乎都存在乱码，效果最好的UTF-8也存在，如下图：
![image](https://user-images.githubusercontent.com/48787805/161372774-d4b93cf4-1a01-4d22-950c-c983fa360c52.png)

**Comment by FlyingQianMM** [comment]
把终端输出日志重定向到文件里
