### ISSUE TITLE
Paddlex客户端模型裁剪报错

### ISSUE THREAD

**Issue by XxsSss** [PaddlePaddle/PaddleX#1444]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 描述问题
用paddlex客户端训练语义分割模型时报错
![image](https://user-images.githubusercontent.com/56816574/161006103-fbadd336-88d0-4d3d-a041-8f280ba74431.png)

参数配置
![image](https://user-images.githubusercontent.com/56816574/161006393-c579a9bc-4a51-497d-8b35-cd4660b56259.png)

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）

err.log文件
This log file path is F:\PaddlePaddleWorkPath\projects\P0007\T0020\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\PaddleX\paddle\distributed\parallel.py:120: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  "Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything."
D:\PaddleX\paddle\tensor\creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Process Process-1:15:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 297, in _bootstrap
  File "multiprocessing\process.py", line 99, in run
  File "paddlexui\pms\model_tasks\tasks.py", line 73, in _call_paddlex_train
  File "paddlexui\pms\model_tasks\train\segmentation.py", line 169, in train
  File "D:\PaddleX\paddlex\cv\models\base.py", line 82, in net_initialize
    backbone_name=backbone_name)
  File "D:\PaddleX\paddlex\utils\checkpoint.py", line 374, in get_pretrain_weights
    flag))
ValueError: Given pretrained weights F:\PaddlePaddleWorkPath\projects\P0007\T0019\output\best_model\model.pdparams\model.pdparams is undefined.

3. 请提供您使用的GUI版本号
![image](https://user-images.githubusercontent.com/56816574/161006527-2348b58d-7295-4d88-92e9-805085f12eaf.png)

4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
![image](https://user-images.githubusercontent.com/56816574/161006629-f720733d-f14a-4f1c-b0ed-1225c8cf9a61.png)

5. 请问您使用的CUDA/cuDNN的版本号是？
![image](https://user-images.githubusercontent.com/56816574/161006573-8700fd35-b7ed-451b-beca-3d64258b41b2.png)

**Comment by XxsSss** [comment]
script.py文件如下

import paddle
from paddle.regularizer import L2Decay
import paddlex as pdx
from paddlex import transforms as T

# 定义训练和验证时的transforms
# API说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/transforms/transforms.md
train_transforms = T.Compose([
    T.Resize(target_size=[512, 512]),
    T.RandomBlur(prob=0.0),
    T.RandomDistort(
        brightness_range=0.5,
        brightness_prob=0.0,
        contrast_range=0.5,
        contrast_prob=0.0,
        saturation_range=0.5,
        saturation_prob=0.0,
        hue_range=18.0,
        hue_prob=0.0),
    T.RandomVerticalFlip(prob=0.5),
    T.RandomHorizontalFlip(prob=0.5), T.Normalize(
        mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

eval_transforms = T.Compose([
    T.Resize(target_size=[512, 512]), T.Normalize(
        mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

# 定义训练和验证所用的数据集
# API说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/datasets.md
train_dataset = pdx.datasets.SegDataset(
    data_dir=r'F:\PaddlePaddleWorkPath\datasets\D0014',
    file_list=r'F:\PaddlePaddleWorkPath\datasets\D0014\train_list.txt',
    label_list=r'F:\PaddlePaddleWorkPath\datasets\D0014\labels.txt',
    transforms=train_transforms,
    shuffle=True)

eval_dataset = pdx.datasets.SegDataset(
    data_dir=r'F:\PaddlePaddleWorkPath\datasets\D0014',
    file_list=r'F:\PaddlePaddleWorkPath\datasets\D0014\val_list.txt',
    label_list=r'F:\PaddlePaddleWorkPath\datasets\D0014\labels.txt',
    transforms=eval_transforms,
    shuffle=False)

# 初始化模型，并进行训练
# 可使用VisualDL查看训练指标，参考https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/train/visualdl.md
num_classes = len(train_dataset.labels)
model = pdx.seg.DeepLabV3P(
    num_classes=num_classes, backbone='ResNet50_vd', use_mixed_loss=False)

# 定义优化器：使用PolynomialDecay
train_batch_size = 2
step_each_epoch = train_dataset.num_samples // train_batch_size
num_epochs = 300
learning_rate = 0.02
decay_step = num_epochs * step_each_epoch
decayed_lr = paddle.optimizer.lr.PolynomialDecay(
    learning_rate=learning_rate,
    decay_steps=decay_step,
    end_lr=0.0,
    power=.9)

optimizer = paddle.optimizer.Momentum(
    learning_rate=decayed_lr,
    momentum=0.9,
    weight_decay=L2Decay(1e-4),
    parameters=model.net.parameters())

# API说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/semantic_segmentation.md
# 各参数介绍与调整说明：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/parameters.md
model.train(
    num_epochs=300,
    train_dataset=train_dataset,
    train_batch_size=train_batch_size,
    eval_dataset=eval_dataset,
    save_interval_epochs=1,
    log_interval_steps=2,
    save_dir=r'F:\PaddlePaddleWorkPath\projects\P0007\T0019\output',
    pretrain_weights=r'CITYSCAPES',
    optimizer=optimizer,
    use_vdl=True,
    resume_checkpoint=None)

**Comment by FlyingQianMM** [comment]
升级GUI至2.1.0可解决该问题。

**Comment by FlyingQianMM** [comment]
这个issue先关闭了哈，如有需要再打开～

**Comment by XxsSss** [comment]
已经升级到2.1.0问题没有解决
![image](https://user-images.githubusercontent.com/56816574/162134663-edf9290f-c122-4826-a5d4-98a217f05ea3.png)
![image](https://user-images.githubusercontent.com/56816574/162135081-721b307b-646a-49b4-a9fe-68e494ea3561.png)

**Comment by XxsSss** [comment]
> 这个issue先关闭了哈，如有需要再打开～
已经升级到2.1.0问题没有解决
![image](https://user-images.githubusercontent.com/56816574/162403049-0b7980d8-a43c-494c-8ded-cc29b4f08409.png)
![image](https://user-images.githubusercontent.com/56816574/162403066-c1d723c3-72e4-46bd-a18c-d844cb649005.png)
