### ISSUE TITLE
python部署模型怎么调用SetModelBuffer从内存读取模型数据呢

### ISSUE THREAD

**Issue by wuqi930907** [PaddlePaddle/PaddleX#1449]
现在有导出的模型文件model.pdiparams、model.pdparams、model.pdiparams.info，请问下怎么使用python语言从内存中加载模型？

**Comment by lailuboy** [comment]
可以通过C写一个程序调用SetModelBuffer，然后用Python调用

**Comment by wuqi930907** [comment]
@lailuboy 好的，十分感谢
