### ISSUE TITLE
paddleX用C++部署生成DLL，python调用DLL预测的问题

### ISSUE THREAD

**Issue by ihunzi** [PaddlePaddle/PaddleX#1454]
背景：
我用pyqt5写了一个上位机，实现语义分割的功能。将程序打包，用pyinstaller打包出来之后，paddlepadle老是报错，而且在网上查了很多资料都没有解决，程序根本跑不起来。后来想到，把paddleX用C++部署，生成DLL给python调用，来实现我的需求，于是有了上面的问题。现在已经成功生成dll并且python成功加载模型。

问题：
①Python用的是ctypes库来调用dll，我想知道的是，我预处理完的图像要转成ctypes的数据形式输入给预测函数，这一步要怎么操作或者说代码怎么写。这一步我写了一个好像没报错，但是我现在获取不到输出结果，所以不知道写得对不对：
`fake_input = np.asarray(fake_input)`
`fake_input = fake_input.ctypes.data_as(c_char_p) # 输入图像`

![image](https://user-images.githubusercontent.com/87402289/162861686-a006f4ef-a3a9-461d-a38b-9bf21b00c2b3.png)

②我接收预测结果，用什么样的ctypes数据类型来接收，这个变量怎么定义或者说代码怎么写？

③好像C++预测完的结果是 bytes[] 类型的，我该怎么转成python的list或者numpy类型的数据或者opencv的图像。

C++函数的原型 【Seg_ModelPredict】：https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/csharp_deploy/model_infer.cpp

由于我C++水平不行，这个问题困扰有几天了

**Comment by FlyingQianMM** [comment]
理解这个跟C#使用差不多，可以参考下C#的图像输入和结果获取 https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/docs/csharp_deploy
