### ISSUE TITLE
YOLOv3模型predict接口说明文档

### ISSUE THREAD

**Issue by 123ty** [PaddlePaddle/PaddleX#1457]
文档404，查不到借口说明文档
https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/apis/models/detection.md#predict

**Comment by FlyingQianMM** [comment]
https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/detection.md 换这个试试。
另外，想问下这个链接是从文档哪个地方跳转到的？

**Comment by 123ty** [comment]
> https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/models/detection.md 换这个试试。 另外，想问下这个链接是从文档哪个地方跳转到的？

https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/prediction.md
这里，YOLOv3模型predict接口

**Comment by FlyingQianMM** [comment]
该问题已修复，见PR https://github.com/PaddlePaddle/PaddleX/pull/1480
