### ISSUE TITLE
使用YOLOv3的DarkNet53生成的模型，为什么检测框的id都是0啊，如何能够自动排序呢，谢谢大家

### ISSUE THREAD

**Issue by 123ty** [PaddlePaddle/PaddleX#1458]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
使用YOLOv3的DarkNet53生成的模型，为什么检测框的id都是0啊，如何能够自动排序呢，谢谢大家
## 复现
输出如下：
[{'category_id': 0, 'bbox': [743.912109375, 792.4161376953125, 93.0260009765625, 221.236572265625], 'score': 0.8182322978973389, 'category': 'person'}, {'category_id': 0, 'bbox': [652.9109497070312, 775.3060913085938, 102.697265625, 247.8985595703125], 'score': 0.7955699563026428, 'category': 'person'}, {'category_id': 0, 'bbox': [972.8240966796875, 640.7797241210938, 69.775634765625, 171.6656494140625], 'score': 0.7825419902801514, 'category': 'person'}, 
 您使用的数据集是？
MOT20
## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
1.3.11
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Macos

model = pdx.det.YOLOv3(
    num_classes= 1,
    backbone='DarkNet53' #骨架网络
)
model.train(
    num_epochs=60, #训练迭代次数
    train_dataset=train_dataset,
    train_batch_size=4,
    eval_dataset=eval_dataset,
    learning_rate=0.00025, #默认优化器的学习率
    lr_decay_epochs=[20,40], #优化器学习率衰减轮数
    save_interval_epochs=4,
    log_interval_steps=100,
    save_dir='./YOLOv', #模型保存路径
    use_vdl=True)

import paddlex as pdx
from paddlex.det import transforms
test_jpg = './YOLOv/test.jpg'
model = pdx.load_model('./YOLOv/best_model')
result = model.predict(test_jpg)
print(result)

**Comment by FlyingQianMM** [comment]
category_id表示类别id，看下你这张测试图片是不是只有人这一类。
