### ISSUE TITLE
PaddleX GUI版本预训练权重格式有问题

### ISSUE THREAD

**Issue by GitLD** [PaddlePaddle/PaddleX#146]
使用paddleX GPU版图像识别demo用的mobilenet，但是预训练权重格式貌似不对，好像还是老版本格式，不是pd.param，格式不对报错

**Comment by jiangjiajun** [comment]
> 使用paddleX GPU版图像识别demo用的mobilenet，但是预训练权重格式貌似不对，好像还是老版本格式，不是pd.param，格式不对报错

报错信息是什么呢，如下是下面这种警告信息，可以直接忽略，目前接口兼容老版本的预训练权重，因此会有下面的这种警告信息，后面会逐步升级到新版本格式

2020-06-10 15:37:04,051-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]

**Comment by GitLD** [comment]
> > 使用paddleX GPU版图像识别demo用的mobilenet，但是预训练权重格式貌似不对，好像还是老版本格式，不是pd.param，格式不对报错
> 
> 报错信息是什么呢，如下是下面这种警告信息，可以直接忽略，目前接口兼容老版本的预训练权重，因此会有下面的这种警告信息，后面会逐步升级到新版本格式
> 
> 2020-06-10 15:37:04,051-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
对，就是上述的error信息然后就没有办法训练下去了，不选择预训练就没有问题

**Comment by GitLD** [comment]
好像就是这个信息，这个信息不影响吗，那可能就是我训练显存超了。。

**Comment by jiangjiajun** [comment]
> 好像就是这个信息，这个信息不影响吗，那可能就是我训练显存超了。。

嗯，此信息不影响使用。如若是显存问题，再尝试调一下batch_size
