### ISSUE TITLE
部署后的模型与实际模型效果不同

### ISSUE THREAD

**Issue by Aierbx** [PaddlePaddle/PaddleX#1460]
使用aistudio将训练好的模型导出为inference_model后，在部署端进行测试，然后再将部署端测试的图像上传到aistudio进行测试，两次测试结果不同
请问这怎么解决呢？谢谢

**Comment by lailuboy** [comment]
具体不同表现在哪里，还有需要关注一下模型前后处理是否一致。

**Comment by Aierbx** [comment]
谢谢回复，不同表现在得分情况，目标检测，在部署端的得分普遍较低，模型前后处理应该是一样的

**Comment by FlyingQianMM** [comment]
部署方式是C++的还是python的？现在有差异的是哪个模型？另外，可以提供下两边的测试结果吗？
