### ISSUE TITLE
PaddleX GUI 训练信息实时在界面上可视化是否会影响训练时间？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleX#1461]
感谢推出PaddleX GUI这个界面化深度学习训练工具！很好用！

但我有一个疑惑想请教：

PaddleX GUI，是能在训练的同时，将训练信息（比如已训练时间、loss、精度信息等）实时可视化到界面上的，
- 这是否用到了Python多线程设计呢？
- 如果用到了多线程，训练线程就会申请GIL，另一个线程，即界面训练信息实时显示也要申请GIL，而为了避免冲突，可能就会让训练线程不停的等待，从而增加了训练时间？

**Comment by jiangjiajun** [comment]
基本不会影响。

GUI是一个独立的进程，会以间隔的时间去扫描训练日志，并将日志解析后可视化在界面上。GUI的进程后与后台的训练进程，不会有锁的情况，GUI读取本地的训练日志，后台进程负责训练，并将日志写在本地。

**Comment by geoexploring** [comment]
@jiangjiajun , 感谢解答，很有意思！
