### ISSUE TITLE
Jetson Xavier部署工业表计读数demo编译失败

### ISSUE THREAD

**Issue by sxjpage** [PaddlePaddle/PaddleX#1463]
## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号
PaddlePaddle：2.2
PaddleX：1.3
Python：3.6.9
2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号
推理引擎：Jetpack4.4(4.5): nv-jetson-cuda10.2-cudnn8-trt7(xavier)
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Jetson Xavier Ubuntu 18
Jetpack:4.5
4. 请问您使用的CUDA/cuDNN的版本号是？
CUDA:10.2。89
OpenCV：4.5.5
TensorRT:7.1.3.0
cuDNN:8.0.0.180
参照https://paddlex.readthedocs.io/zh_CN/release-1.3/deploy/jetson/index.html 执行Step3: 
sh ./scripts/jetson_build.sh
报错如下：

<img width="953" alt="微信图片_20220419150342" src="https://user-images.githubusercontent.com/36979751/163945166-ad3f72fb-fac8-4173-b2ce-9145e0657551.png">

但是文件本身存在，tree目录后：
<img width="156" alt="微信图片_20220419150222" src="https://user-images.githubusercontent.com/36979751/163944912-796166e2-177f-4b81-95e3-239be671fbcd.png">
请问如何解决，谢谢

**Comment by FlyingQianMM** [comment]
建议您使用PaddleX >= 2.0，jetson部署可参考pr https://github.com/PaddlePaddle/PaddleX/pull/794/files
