### ISSUE TITLE
实例分割训练好的模型的热力图

### ISSUE THREAD

**Issue by Enn29** [PaddlePaddle/PaddleX#1465]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
用实例分割训练好的模型（maskrcnn），怎么做热力图，有没有相关的文档或者例子做参考

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
PaddleX=1.3.11， paddle=2.0.2
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
windows
3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by FlyingQianMM** [comment]
目前没有画热力图的例子，您可以根据自己的需求自行开发。
