### ISSUE TITLE
c#的GUI版本加载初始化模型接口就报错，找不到model_infer.dll

### ISSUE THREAD

**Issue by sdjxmikill** [PaddlePaddle/PaddleX#1466]
c#的GUI版本加载初始化模型接口就报错，找不到model_infer.dll，debug看了一下一调用InitModel（）就出现内存错误，这个问题怎么解决
![QQ截图20220421113621](https://user-images.githubusercontent.com/20013022/164369063-becf5216-8826-41ea-9b21-7616c008639c.png)
？

加载的模型是PaddleX导出的debug下看读取都没有问题。
![图片](https://user-images.githubusercontent.com/20013022/164369205-f268bceb-b7c9-4809-af5a-8e73df253e9a.png)

**Comment by cjh3020889729** [comment]
如果是未放置相应的文件，可能需要你将编译生成的model_infer.dll等文件放在C#工程目录的相应文件夹下。

**Comment by kylechen77** [comment]
我的配置如下：
Visual studio 2022, CUDA10.2;CUDNN7.6.5;OPENCV 3..4.6;Paddlex-inference avx_mkl_cuda10.2_cudnn7.6.5rtt7.0.11;TensorRT7.0.0.11

不能装载模型，运行C#的官方DEMO  报错如下：
System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'model_infer.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)
  Source=WinFormsApp_final
  StackTrace:
   在 WinFormsApp_final.Form1.InitModel(String model_type, String model_filename, String params_filename, String cfg_file, Boolean use_gpu, Int32 gpu_id, Byte& paddlex_model_type)
   在 WinFormsApp_final.Form1.button1_Click(Object sender, EventArgs e) 在 D:\projects\deepMatch\packagecmake_paddleX\PaddleX-develop\deploy\cpp\docs\csharp_deploy\c#\Form1.cs 中: 第 401 行

  此异常最初是在此调用堆栈中引发的: 
    WinFormsApp_final.Form1.button1_Click(object, System.EventArgs) (位于 Form1.cs 中)
