### ISSUE TITLE
执行resnet50.py出错

### ISSUE THREAD

**Issue by zjc5477** [PaddlePaddle/PaddleX#147]
python tutorials/train/classification/resnet50.py 
2020-06-10 11:14:27 [INFO]	Decompressing ./vegetables_cls.tar.gz...
2020-06-10 11:14:27 [INFO]	Starting to read file list from dataset...
2020-06-10 11:14:27 [INFO]	840 samples in file vegetables_cls/train_list.txt
2020-06-10 11:14:27 [INFO]	Starting to read file list from dataset...
2020-06-10 11:14:27 [INFO]	240 samples in file vegetables_cls/val_list.txt
W0610 11:14:29.627683  4592 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0610 11:14:29.630448  4592 device_context.cc:245] device: 0, cuDNN Version: 7.6.
2020-06-10 11:14:30 [INFO]	Load pretrain weights from output/resnet50/pretrain/ResNet50.
2020-06-10 11:14:30 [WARNING]	[SKIP] Shape of pretrained weight output/resnet50/pretrain/ResNet50/fc_0.w_0 doesn't match.(Pretrained: (2048, 1000), Actual: (2048, 6))
2020-06-10 11:14:30 [WARNING]	[SKIP] Shape of pretrained weight output/resnet50/pretrain/ResNet50/fc_0.b_0 doesn't match.(Pretrained: (1000,), Actual: (6,))
2020-06-10 11:14:30,463-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-10 11:14:30,463-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-06-10 11:14:30 [INFO]	There are 265 varaibles in output/resnet50/pretrain/ResNet50 are loaded.
I0610 11:14:46.227094  4592 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0610 11:14:46.261431  4592 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0610 11:14:46.331351  4592 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0610 11:14:46.360970  4592 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
*** Error in `python': double free or corruption (!prev): 0x0000000001311660 ***
W0610 11:14:47.626109 10483 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0610 11:14:47.626158 10483 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0610 11:14:47.626163 10483 init.cc:214] The detail failure signal is:

W0610 11:14:47.626169 10483 init.cc:217] *** Aborted at 1591758887 (unix time) try "date -d @1591758887" if you are using GNU date ***
W0610 11:14:47.627741 10483 init.cc:217] PC: @                0x0 (unknown)
W0610 11:14:47.628168 10483 init.cc:217] *** SIGABRT (@0x3e8000028f1) received by PID 10481 (TID 0x7fca13278700) from PID 10481; stack trace: ***
*** Error in `python': double free or corruption (!prev): 0x0000000001311660 ***
W0610 11:14:47.653316 10488 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0610 11:14:47.653357 10488 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0610 11:14:47.653362 10488 init.cc:214] The detail failure signal is:

W0610 11:14:47.653367 10488 init.cc:217] *** Aborted at 1591758887 (unix time) try "date -d @1591758887" if you are using GNU date ***

**Comment by jiangjiajun** [comment]
> python tutorials/train/classification/resnet50.py
> 2020-06-10 11:14:27 [INFO] Decompressing ./vegetables_cls.tar.gz...
> 2020-06-10 11:14:27 [INFO] Starting to read file list from dataset...
> 2020-06-10 11:14:27 [INFO] 840 samples in file vegetables_cls/train_list.txt
> 2020-06-10 11:14:27 [INFO] Starting to read file list from dataset...
> 2020-06-10 11:14:27 [INFO] 240 samples in file vegetables_cls/val_list.txt
> W0610 11:14:29.627683 4592 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
> W0610 11:14:29.630448 4592 device_context.cc:245] device: 0, cuDNN Version: 7.6.
> 2020-06-10 11:14:30 [INFO] Load pretrain weights from output/resnet50/pretrain/ResNet50.
> 2020-06-10 11:14:30 [WARNING] [SKIP] Shape of pretrained weight output/resnet50/pretrain/ResNet50/fc_0.w_0 doesn't match.(Pretrained: (2048, 1000), Actual: (2048, 6))
> 2020-06-10 11:14:30 [WARNING] [SKIP] Shape of pretrained weight output/resnet50/pretrain/ResNet50/fc_0.b_0 doesn't match.(Pretrained: (1000,), Actual: (6,))
> 2020-06-10 11:14:30,463-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
> 2020-06-10 11:14:30,463-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
> 2020-06-10 11:14:30 [INFO] There are 265 varaibles in output/resnet50/pretrain/ResNet50 are loaded.
> I0610 11:14:46.227094 4592 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
> I0610 11:14:46.261431 4592 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
> I0610 11:14:46.331351 4592 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
> I0610 11:14:46.360970 4592 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
> *** Error in `python': double free or corruption (!prev): 0x0000000001311660 ***
> W0610 11:14:47.626109 10483 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> W0610 11:14:47.626158 10483 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> W0610 11:14:47.626163 10483 init.cc:214] The detail failure signal is:
> 
> W0610 11:14:47.626169 10483 init.cc:217] *** Aborted at 1591758887 (unix time) try "date -d @1591758887" if you are using GNU date ***
> W0610 11:14:47.627741 10483 init.cc:217] PC: @ 0x0 (unknown)
> W0610 11:14:47.628168 10483 init.cc:217] *** SIGABRT (@0x3e8000028f1) received by PID 10481 (TID 0x7fca13278700) from PID 10481; stack trace: ***
> *** Error in `python': double free or corruption (!prev): 0x0000000001311660 ***
> W0610 11:14:47.653316 10488 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> W0610 11:14:47.653357 10488 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> W0610 11:14:47.653362 10488 init.cc:214] The detail failure signal is:
> 
> W0610 11:14:47.653367 10488 init.cc:217] *** Aborted at 1591758887 (unix time) try "date -d @1591758887" if you are using GNU date ***

检查一下你的paddle版本，要求paddlepaddle-gpu 1.8.1

**Comment by zjc5477** [comment]
> > python tutorials/train/classification/resnet50.py
> > 2020-06-10 11:14:27 [INFO] Decompressing ./vegetables_cls.tar.gz...
> > 2020-06-10 11:14:27 [INFO] Starting to read file list from dataset...
> > 2020-06-10 11:14:27 [INFO] 840 samples in file vegetables_cls/train_list.txt
> > 2020-06-10 11:14:27 [INFO] Starting to read file list from dataset...
> > 2020-06-10 11:14:27 [INFO] 240 samples in file vegetables_cls/val_list.txt
> > W0610 11:14:29.627683 4592 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
> > W0610 11:14:29.630448 4592 device_context.cc:245] device: 0, cuDNN Version: 7.6.
> > 2020-06-10 11:14:30 [INFO] Load pretrain weights from output/resnet50/pretrain/ResNet50.
> > 2020-06-10 11:14:30 [WARNING] [SKIP] Shape of pretrained weight output/resnet50/pretrain/ResNet50/fc_0.w_0 doesn't match.(Pretrained: (2048, 1000), Actual: (2048, 6))
> > 2020-06-10 11:14:30 [WARNING] [SKIP] Shape of pretrained weight output/resnet50/pretrain/ResNet50/fc_0.b_0 doesn't match.(Pretrained: (1000,), Actual: (6,))
> > 2020-06-10 11:14:30,463-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
> > 2020-06-10 11:14:30,463-WARNING: output/resnet50/pretrain/ResNet50.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
> > 2020-06-10 11:14:30 [INFO] There are 265 varaibles in output/resnet50/pretrain/ResNet50 are loaded.
> > I0610 11:14:46.227094 4592 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
> > I0610 11:14:46.261431 4592 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
> > I0610 11:14:46.331351 4592 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
> > I0610 11:14:46.360970 4592 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
> > *** Error in `python': double free or corruption (!prev): 0x0000000001311660 ***
> > W0610 11:14:47.626109 10483 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> > W0610 11:14:47.626158 10483 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> > W0610 11:14:47.626163 10483 init.cc:214] The detail failure signal is:
> > W0610 11:14:47.626169 10483 init.cc:217] *** Aborted at 1591758887 (unix time) try "date -d @1591758887" if you are using GNU date ***
> > W0610 11:14:47.627741 10483 init.cc:217] PC: @ 0x0 (unknown)
> > W0610 11:14:47.628168 10483 init.cc:217] *** SIGABRT (@0x3e8000028f1) received by PID 10481 (TID 0x7fca13278700) from PID 10481; stack trace: ***
> > *** Error in `python': double free or corruption (!prev): 0x0000000001311660 ***
> > W0610 11:14:47.653316 10488 init.cc:209] Warning: PaddlePaddle catches a failure signal, it may not work properly
> > W0610 11:14:47.653357 10488 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
> > W0610 11:14:47.653362 10488 init.cc:214] The detail failure signal is:
> > W0610 11:14:47.653367 10488 init.cc:217] *** Aborted at 1591758887 (unix time) try "date -d @1591758887" if you are using GNU date ***
> 
> 检查一下你的paddle版本，要求paddlepaddle-gpu 1.8.1

Traceback (most recent call last):
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/dataset.py", line 161, in _read_into_queue
    queue.put(result)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/queue.py", line 79, in put
    buff.free()
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 187, in free
    self.owner().free(self)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 110, in owner
    return SharedMemoryMgr.get_mgr(self._owner)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 387, in get_mgr
    id)
AssertionError: invalid id[3215002] for memory managers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/queue.py", line 70, in put
    buff.put(obj)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 133, in put
    self.owner().put_data(self, data)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 110, in owner
    return SharedMemoryMgr.get_mgr(self._owner)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 387, in get_mgr
    id)
AssertionError: invalid id[3215002] for memory managers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/dataset.py", line 164, in _read_into_queue
    queue.put("")
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/queue.py", line 79, in put
    buff.free()
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 187, in free
    self.owner().free(self)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 110, in owner
    return SharedMemoryMgr.get_mgr(self._owner)
  File "/home/caros/paddle-venv/lib/python3.5/site-packages/paddlex-1.0.6-py3.5.egg/paddlex/cv/datasets/shared_queue/sharedmemory.py", line 387, in get_mgr
 更新完paddlepaddle-gpu版本之后，执行还是有错误

**Comment by zjc5477** [comment]
![snapshot13](https://user-images.githubusercontent.com/20104333/84236071-9e88dd80-ab29-11ea-80a0-5fd13d26e38b.png)
![snapshot14](https://user-images.githubusercontent.com/20104333/84236072-a052a100-ab29-11ea-9e6a-45a48b221435.png)

**Comment by jiangjiajun** [comment]
看起来是由于内存的原因，麻烦修改一下你的代码，将buffer_size改小一些，参考下面的代码
```
train_dataset = pdx.datasets.ImageNet(
    data_dir='vegetables_cls',
    file_list='vegetables_cls/train_list.txt',
    label_list='vegetables_cls/labels.txt',
    transforms=train_transforms,
    buffer_size=32,
    shuffle=True)
eval_dataset = pdx.datasets.ImageNet(
    data_dir='vegetables_cls',
    file_list='vegetables_cls/val_list.txt',
    label_list='vegetables_cls/labels.txt',
    transforms=eval_transforms,
    buffer_size=32,
)
```

**Comment by zjc5477** [comment]
![snapshot15](https://user-images.githubusercontent.com/20104333/84239869-bfecc800-ab2f-11ea-99e0-b4cd7ebd79c7.png)
您好，看起来像是已经执行完train和eval了，也按照您说的修改了buffer_size大小，还是和以前一样出现这个问题

**Comment by jiangjiajun** [comment]
> ![snapshot15](https://user-images.githubusercontent.com/20104333/84239869-bfecc800-ab2f-11ea-99e0-b4cd7ebd79c7.png)
> 您好，看起来像是已经执行完train和eval了，也按照您说的修改了buffer_size大小，还是和以前一样出现这个问题

把并行方式改成多线程试下，参照下面代码，设置parallel_method
```
train_dataset = pdx.datasets.ImageNet(
    data_dir='vegetables_cls',
    file_list='vegetables_cls/train_list.txt',
    label_list='vegetables_cls/labels.txt',
    transforms=train_transforms,
    parallel_method='thread',
    buffer_size=32,
    shuffle=True)
eval_dataset = pdx.datasets.ImageNet(
    data_dir='vegetables_cls',
    file_list='vegetables_cls/val_list.txt',
    label_list='vegetables_cls/labels.txt',
    transforms=eval_transforms,
    parallel_method='thread',
    buffer_size=32,
)
```

**Comment by zjc5477** [comment]
> parallel_method='thread',

好使了，谢谢！

**Comment by jiangjiajun** [comment]
方便的话，提供一下你的环境信息

操作系统：
内存大小：
Python版本：

我这边查一下原因

**Comment by zjc5477** [comment]
> 方便的话，提供一下你的环境信息
> 
> 操作系统：
> 内存大小：
> Python版本：
> 
> 我这边查一下原因

ubuntu 1404,内存32g，python3.5,我刚刚试了一下，只改成多线程就可以了，不用修改buffer_size大小

**Comment by jiangjiajun** [comment]
> > 方便的话，提供一下你的环境信息
> > 操作系统：
> > 内存大小：
> > Python版本：
> > 我这边查一下原因
> 
> ubuntu 1404,内存32g，python3.5,我刚刚试了一下，只改成多线程就可以了，不用修改buffer_size大小

由于我这边没有相应环境，如果方便的话，帮忙再测一下在不修改parallel_method的情况下，buffer_size要改到多小才不会有上面的问题，buffer_size表示内存中缓存的批数量

**Comment by zjc5477** [comment]
> > > 方便的话，提供一下你的环境信息
> > > 操作系统：
> > > 内存大小：
> > > Python版本：
> > > 我这边查一下原因
> > 
> > 
> > ubuntu 1404,内存32g，python3.5,我刚刚试了一下，只改成多线程就可以了，不用修改buffer_size大小
> 
> 由于我这边没有相应环境，如果方便的话，帮忙再测一下在不修改parallel_method的情况下，buffer_size要改到多小才不会有上面的问题，buffer_size表示内存中缓存的批数量

32 16 8 4 2 1 都试过了，都不好使，都有问题

**Comment by jiangjiajun** [comment]
> > > > 方便的话，提供一下你的环境信息
> > > > 操作系统：
> > > > 内存大小：
> > > > Python版本：
> > > > 我这边查一下原因
> > > 
> > > 
> > > ubuntu 1404,内存32g，python3.5,我刚刚试了一下，只改成多线程就可以了，不用修改buffer_size大小
> > 
> > 
> > 由于我这边没有相应环境，如果方便的话，帮忙再测一下在不修改parallel_method的情况下，buffer_size要改到多小才不会有上面的问题，buffer_size表示内存中缓存的批数量
> 
> 32 16 8 4 2 1 都试过了，都不好使，都有问题

好的，多谢，我再找机器环境尝试复现一下

**Comment by zjc5477** [comment]
![snapshot17](https://user-images.githubusercontent.com/20104333/84361539-656e6d00-abfe-11ea-8d35-8ef8895b6076.png)
按照文档实现了一遍，感觉这个目标检测准确率不高啊，是我哪儿有问题吗？

**Comment by jiangjiajun** [comment]
> ![snapshot17](https://user-images.githubusercontent.com/20104333/84361539-656e6d00-abfe-11ea-8d35-8ef8895b6076.png)
> 按照文档实现了一遍，感觉这个目标检测准确率不高啊，是我哪儿有问题吗？

这个看起来准确率不高，是由于没有过滤低置信度目标框的原因。

在调用pdx.det.visualize时，通过设置`threshold`参数，可以过滤掉置信度低于`threshold`的目标结果。

**Comment by zjc5477** [comment]
> > ![snapshot17](https://user-images.githubusercontent.com/20104333/84361539-656e6d00-abfe-11ea-8d35-8ef8895b6076.png)
> > 按照文档实现了一遍，感觉这个目标检测准确率不高啊，是我哪儿有问题吗？
> 
> 这个看起来准确率不高，是由于没有过滤低置信度目标框的原因。
> 
> 在调用pdx.det.visualize时，通过设置`threshold`参数，可以过滤掉置信度低于`threshold`的目标结果。

![snapshot18](https://user-images.githubusercontent.com/20104333/84362726-453fad80-ac00-11ea-926f-f70a5baf7543.png)
但是我下载了这个训练好的模型，检测的准确率就挺高的，
![snapshot19](https://user-images.githubusercontent.com/20104333/84362965-9e0f4600-ac00-11ea-9ea1-4b3219e33d76.png)

**Comment by zjc5477** [comment]
![snapshot20](https://user-images.githubusercontent.com/20104333/84378371-a7a3a880-ac16-11ea-8452-ed4b134acd56.png)

您好，这是我用paddlex 的语义分割功能做的一个预测，左边是原图，右边是预测的图，和我之前用PaddleSeg的实验结果差别有点大，请问一下这个是正常输出吗？？ @jiangjiajun

**Comment by jiangjiajun** [comment]
1. 上面的检测模型训练会有一定随机因素，所以还需要自行根据数据情况设定threshold。
2. 语义分割模型， 由于为了让用户快速完成训练，我们对数据作了压缩（图片数量和分辨率），如若你需要训练更好的模型，可以使用更大的数据集
