### ISSUE TITLE
AttributeError: module 'paddlex' has no attribute 'models'

### ISSUE THREAD

**Issue by kungkook** [PaddlePaddle/PaddleX#1470]
环境: win11 显卡:3050ti cuda11.2
paddlepaddle-gpu==2.2.2
paddleslim==2.2.1
paddlex==2.1.0
运行examples/robot_grap/code/train.py
报错:
Traceback (most recent call last):
  File "E:/PaddleX/examples/robot_grab/code/train.py", line 37, in <module>
    model = pdx.models.MaskRCNN(
AttributeError: module 'paddlex' has no attribute 'models'

**Comment by FlyingQianMM** [comment]
该问题已修复，见pr https://github.com/PaddlePaddle/PaddleX/pull/1482
