### ISSUE TITLE
c#部署能正常加载模型，推理一张图片要几万秒，推理结果不正确

### ISSUE THREAD

**Issue by Wulingtian** [PaddlePaddle/PaddleX#1473]
## 描述问题
c#能正常加载模型，推理一张图片要几万秒，推理结果不正确，python推理结果是正确的
## 复现
c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？
    是
    * 您是否在demo基础上修改代码内容？还请您提供运行的代码
    没有修改任何代码
    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？
    python推理正常

3. 您使用的**模型**和**数据集**是？
YOLOv3 官方提供的昆虫检测数据集
5. 请提供您出现的报错信息及相关log
  没有报错
## 环境
 
2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号
PaddleX develop分支 PaddleInference 2.3.0-rc0版本
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows
4. 请问您使用的CUDA/cuDNN的版本号是？
cuda 11.2 cudnn7.6.5

**Comment by cjh3020889729** [comment]
请问是使用C#的GUI测试的吗？如果是的话，想问一下这个结果是第一次测试耗时吗？还是加载模型后连续对同一图像多次测试都耗时很长呢？如果是前者，可能是模型第一次运行，模型优化耗时导致的。如果是后者的话，不知是否是在GUI面板选择了GPU推理/或手动配置GPU启动呢？(GUI上默认是以ms为单位显示的。)
