### ISSUE TITLE
restful中没有PicoDet训练配置

### ISSUE THREAD

**Issue by mutemoon** [PaddlePaddle/PaddleX#1474]
https://github.com/PaddlePaddle/PaddleX/blob/8f38bf6608b22aa2b29880bdca1d7ff610bb3f01/paddlex_restful/restful/project/train/params_v2.py#L16
https://github.com/PaddlePaddle/PaddleX/blob/8f38bf6608b22aa2b29880bdca1d7ff610bb3f01/paddlex_restful/restful/templates/paddlex_restful_demo.html#L535

**Comment by FlyingQianMM** [comment]
目前没有，restful api目前都是开源的，您可以自行添加模型。
