### ISSUE TITLE
paddleX提供的目标检测示例项目一直训练失败

### ISSUE THREAD

**Issue by alibolun** [PaddlePaddle/PaddleX#1476]
This log file path is D:\projects\P0002\T0019\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
gpu和cpu的都试了，一直训练失败。

**Comment by wxc2012** [comment]
我也是这个问题……！不知道该怎么解决呀

**Comment by FlyingQianMM** [comment]
目前这个日志文件看不出任何报错信息，请参考[FAQ GUI相关问题 Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md/#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98) 看下其他日志文件。

**Comment by FunJoo** [comment]
你是同时安装有PaddleDetection吧
