### ISSUE TITLE
【代码相关】请问分割任务在eval阶段绕过mask的设计初衷是什么

### ISSUE THREAD

**Issue by Bobholamovic** [PaddlePaddle/PaddleX#1477]
https://github.com/PaddlePaddle/PaddleX/blob/8f38bf6608b22aa2b29880bdca1d7ff610bb3f01/paddlex/cv/transforms/__init__.py#L24

想请教一下，为什么对于分割任务，在eval阶段需要设置`apply_im_only`为`True`呢？是为了解决一些特别的情况吗？

**Comment by jiangjiajun** [comment]
`apply_im_only`表示所有的预处理只处理图像，不处理label。 eval阶段只需要针对原图进行如resize或normalize后，得到预测结果，并还原到原图大小，进行指标的评估。

在训练阶段apply_im_only为True则是有些处理需同步到label上，例如数据增强过程中从原图随机裁剪出一个框，那也应该到对应label的位置裁剪出对应的值

**Comment by Bobholamovic** [comment]
感谢解答
