### ISSUE TITLE
There's no attribute PicoDet in paddlex.cv.models

### ISSUE THREAD

**Issue by Leon-E-Zion** [PaddlePaddle/PaddleX#1478]
C:\Users\LeonZion\.conda\envs\Leon_Deep\python.exe F:/Leon_Coding_Station/Paddle-Family/PaddleX_Data/P0001-T0003_export_model/paddlex_python_predict/predict.py
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddle\distributed\parallel.py:135: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddlex\paddleseg\models\losses\decoupledsegnet_relax_boundary_loss.py:19: DeprecationWarning: Please use `shift` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated.
  from scipy.ndimage.interpolation import shift
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddlex\paddleseg\transforms\functional.py:18: DeprecationWarning: Please use `distance_transform_edt` from the `scipy.ndimage` namespace, the `scipy.ndimage.morphology` namespace is deprecated.
  from scipy.ndimage.morphology import distance_transform_edt
C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\sklearn\utils\multiclass.py:13: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
Traceback (most recent call last):
  File "F:/Leon_Coding_Station/Paddle-Family/PaddleX_Data/P0001-T0003_export_model/paddlex_python_predict/predict.py", line 8, in <module>
    model = pdx.load_model(r'F:\Leon_Coding_Station\Paddle-Family\PaddleX_Data\P0001-T0003_export_model\inference_model\inference_model')
  File "C:\Users\LeonZion\.conda\envs\Leon_Deep\lib\site-packages\paddlex\cv\models\load_model.py", line 77, in load_model
    raise Exception("There's no attribute {} in paddlex.cv.models".format(
Exception: There's no attribute PicoDet in paddlex.cv.models
Loading model...

Process finished with exit code 1

**Comment by FlyingQianMM** [comment]
提供下PaddleX GUI和 PaddleX的版本号
