### ISSUE TITLE
'E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib', needed by 'paddlex_inference/video_classifier.exe', missing and no known rule to make it	E:\projects\PaddleX\deploy\cpp\out\build\x64-Release\cpp	E:\projects\PaddleX\deploy\cpp\out\build\x64-Release\ninja	1	

### ISSUE THREAD

**Issue by kungkook** [PaddlePaddle/PaddleX#1479]
cuda11.2 
下载推理库网址:https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#c
下载了适合cuda11.2的windows下的推理库，但是全部生成时显示缺少paddle_inference/paddle/lib/libpaddle_fluid.lib文件

**Comment by FlyingQianMM** [comment]
> E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib', needed by 'paddlex_inference/video_classifier.exe', missing and no known rule to make it

确认下paddle_inference的路径是否填写正确

**Comment by kungkook** [comment]
路径是正确的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 'E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib', needed by 'paddlex_inference/video_classifier.exe', missing and no known rule to make it E:\projects\PaddleX\deploy\cpp\out\build\x64-Release\cpp E:\projects\PaddleX\deploy\cpp\out\build\x64-Release\ninja 1  (Issue #1479)





  
E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib', needed by 'paddlex_inference/video_classifier.exe', missing and no known rule to make it
  
确认下paddle_inference的路径是否填写正确

**Comment by FlyingQianMM** [comment]
`E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib`这个路径是存在的？

**Comment by kungkook** [comment]
> `E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib`这个路径是存在的？
是存在的呢

**Comment by kungkook** [comment]
> `E:/projects/paddle_inference/paddle/lib/libpaddle_fluid.lib`这个路径是存在的？

但是不是libpaddle_fluid.lib，下载后是libpaddle_inference.lib

**Comment by FlyingQianMM** [comment]
看起来你是用的PaddleX 1.3.x版本的预测代码？
Paddle >=2.0以后才适配了cuda11，所以更换使用对应的PaddleX develop版本或者2.0版本的预测代码吧～
