### ISSUE TITLE
2.1.0 添加负样本。评估模型效果的数据集加入负样本会内存溢出

### ISSUE THREAD

**Issue by SJJ-dot** [PaddlePaddle/PaddleX#1489]
2.1.0 添加负样本。评估模型效果的数据集加入负样本会内存溢出

**Comment by FlyingQianMM** [comment]
负样本优化策略在训练时有考虑加入的必要，但是评估时就没跟空框计算mAP的必要了，所以评估数据集把allow_empty设置为False就行。看这样子是issue #1486 解决了？
