### ISSUE TITLE
这个解码后的数组 是使用opencv解码的嘛

### ISSUE THREAD

**Issue by ccLemonTree** [PaddlePaddle/PaddleX#1492]
![1652263295(1)](https://user-images.githubusercontent.com/94359077/167824515-6d5f1514-0ac0-400e-a47f-8995b38dcc1b.jpg)

**Comment by FlyingQianMM** [comment]
是的，具体可以看下代码： https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/deploy.py
