### ISSUE TITLE
使用TensorRT配置PadddleX环境时异常

### ISSUE THREAD

**Issue by LiyqSmile** [PaddlePaddle/PaddleX#1494]
PaddleX-release-2.1

1.配置TensorRT时，Cmake中的提示：
You might need to add D:\SoftWares\DeepLearn\Paddlx_PaddleInference\opencv-3.4.6\build\x64\vc15\bin to your PATH to be able to run your applications.
Found OpenMP_C: -openmp (found version "2.0") 
Found OpenMP_CXX: -openmp (found version "2.0") 
Found OpenMP: TRUE (found version "2.0")  
OPENMP FOUND
Current TensorRT header is /NvInfer.h. Current TensorRT version is v8. 
-----DEPS = opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_world;D:/SoftWares/DeepLearn/Paddlx_PaddleInference/paddle_inference/paddle/lib/paddle_inference.lib;glog;gflags_static;libprotobuf;xxhash;cryptopp-static;libyaml-cppmt;shlwapi;D:/SoftWares/DeepLearn/Paddlx_PaddleInference/paddle_inference/third_party/install/mklml/lib/mklml.lib;D:/SoftWares/DeepLearn/Paddlx_PaddleInference/paddle_inference/third_party/install/mklml/lib/libiomp5md.lib;D:/SoftWares/DeepLearn/Paddlx_PaddleInference/paddle_inference/third_party/install/mkldnn/lib/mkldnn.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64/cudart.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64/cublas.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/lib/x64/cudnn.lib;D:/SoftWares/DeepLearn/Paddlx_PaddleInference/tensorrt-release-8.0/lib/nvinfer.lib;D:/SoftWares/DeepLearn/Paddlx_PaddleInference/tensorrt-release-8.0/lib/nvinfer_plugin.lib
Configuring done
Generating done

2.使用VS2017打开提示无法打开输入文件“tensorrt-release-8.0\lib\nvinfer.lib”

**Comment by FlyingQianMM** [comment]
确认下文件tensorrt-release-8.0\lib\nvinfer.lib是否存在吧。
