### ISSUE TITLE
对于推理功能来说，paddle_inference.dll是否过大呢

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleX#1495]
按照[The-PaddleX-QT-Visualize-GUI](https://github.com/cjh3020889729/The-PaddleX-QT-Visualize-GUI)编译出来的`paddle_inference.dll`有1.13G。

请问有没有在保证推理功能的前提下，减小dll大小的方法呢？比如如果我只是需要目标检测功能，删除其它分类、语义分割等的代码，应该会减小`paddle_inference.dll`?

谢谢！

**Comment by FlyingQianMM** [comment]
感谢建议，Paddle Inference推理引擎缩减体积在进行中，后续可关注Paddle的最新进展。
