### ISSUE TITLE
希望适配paddleslim2.2.2版本

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleX#1496]
windows系统,python 3.9.12,使用pip方式更新paddleslim时,提示ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlex 2.1.0 requires paddleslim==2.2.1, but you have paddleslim 2.2.2 which is incompatible.
希望paddlex可以适配paddleslim2.2.2版本,谢谢

**Comment by FlyingQianMM** [comment]
暂未适配python 3.9，您可以降低python版本至3.7，降低paddleslim至2.2.1，以确保当前PaddleX版本能够正常运行。
