### ISSUE TITLE
希望paddlex可以适配scikit-learn 1.1.0最新版本,谢谢.

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleX#1497]
windows系统,python3.9.12,使用pip升级scikit-learn最新版,报错,提示ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlex 2.1.0 requires scikit-learn==0.23.2, but you have scikit-learn 1.1.0 which is incompatible.

希望paddlex可以适配scikit-learn 1.1.0最新版本,谢谢.

**Comment by FlyingQianMM** [comment]
pip版本太高了，可以适当降低pip版本，不影响功能使用。
