### ISSUE TITLE
paddlex的评估接口evaluate中没有use_vdl参数接口，请问该如何绘制验证集的loss曲线

### ISSUE THREAD

**Issue by Trensking** [PaddlePaddle/PaddleX#1504]
## 描述问题
paddlex的训练接口train中有use_vdl参数接口，但是评估接口evaluate中并没有相关参数接口，请问该如何利用paddlex绘制验证集的loss曲线？

**Comment by FlyingQianMM** [comment]
paddlex evaluate针对验证集没有计算loss，只计算精度，visualdl里面也展示评估集精度。

理解验证集上的精度比loss更能反应准确度吧？

**Comment by Trensking** [comment]
多谢，由于根据训练集loss曲线反映出模型可能有些过拟合，因此我才想绘制验证集loss曲线对模型收敛程度进一步判断，现已解决问题
