### ISSUE TITLE
剪枝

### ISSUE THREAD

**Issue by wenjiett** [PaddlePaddle/PaddleX#151]
请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢

**Comment by SunAhong1993** [comment]
> 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢

你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题

**Comment by wenjiett** [comment]
> > 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢
> 
> 你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题
我仿照文档里进行敏感度计算，输出的结果就是{}
model_dir = 'infer'
model = pdx.load_model(model_dir)

# 定义验证所用的数据集
eval_dataset = pdx.datasets.VOCDetection(
    data_dir='work/TrafficData/',
    file_list='work/TrafficData/val_list2.txt',
    label_list='work/TrafficData/label.txt',
    transforms=model.eval_transforms)

pdx.slim.cal_params_sensitivities(model,
                                'sensitivities.data',
                                eval_dataset,
                                batch_size=8)

**Comment by wenjiett** [comment]
> > 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢
> 
> 你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题

我看文件夹那块也没有生成sensitivities.data这个文件

**Comment by SunAhong1993** [comment]
> > > 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢
> > 
> > 
> > 你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题
> 
> 我看文件夹那块也没有生成sensitivities.data这个文件

使用上没有问题，请问使用的模型是Faster RCNN吗？目标检测模型目前只支持YOLOV3模型

**Comment by wenjiett** [comment]
> > > > 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢
> > > 
> > > 
> > > 你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题
> > 
> > 
> > 我看文件夹那块也没有生成sensitivities.data这个文件
> 
> 使用上没有问题，请问使用的模型是Faster RCNN吗？目标检测模型目前只支持YOLOV3模型

目前只支持YOLOV3的剪枝是吗

**Comment by wenjiett** [comment]
> > > > 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢
> > > 
> > > 
> > > 你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题
> > 
> > 
> > 我看文件夹那块也没有生成sensitivities.data这个文件
> 
> 使用上没有问题，请问使用的模型是Faster RCNN吗？目标检测模型目前只支持YOLOV3模型

我是对YOLOV3的模型进行的剪枝

**Comment by SunAhong1993** [comment]
> > > > > 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢
> > > > 
> > > > 
> > > > 你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题
> > > 
> > > 
> > > 我看文件夹那块也没有生成sensitivities.data这个文件
> > 
> > 
> > 使用上没有问题，请问使用的模型是Faster RCNN吗？目标检测模型目前只支持YOLOV3模型
> 
> 我是对YOLOV3的模型进行的剪枝

是的，只支持YOLOV3，这边查看下infer文件夹下是否包含model.yml、model.pdmodel、model.pdparams这几个文件。代码没有报其他错误吗，或者日志方便提供一下吗？

**Comment by wenjiett** [comment]
> > > > > > 请问一下，我仿照文档在使用模型剪枝的时候，最后运行的结果是{}，为什么呢
> > > > > 
> > > > > 
> > > > > 你好，请问是在裁剪什么模型，运行到哪个步骤出现的问题
> > > > 
> > > > 
> > > > 我看文件夹那块也没有生成sensitivities.data这个文件
> > > 
> > > 
> > > 使用上没有问题，请问使用的模型是Faster RCNN吗？目标检测模型目前只支持YOLOV3模型
> > 
> > 
> > 我是对YOLOV3的模型进行的剪枝
> 
> 是的，只支持YOLOV3，这边查看下infer文件夹下是否包含model.yml、model.pdmodel、model.pdparams这几个文件。代码没有报其他错误吗，或者日志方便提供一下吗？

我是在Aistudio上跑的，运行没有报其他的错，infer文件夹下有__model__、__params__、model.yml三个文件，还有一个问题我的save_file写的是sensitivities.data,但是运行完后，并没有生成那个文件

**Comment by SunAhong1993** [comment]
> __model__

你是否使用量化后的模型进行裁剪？

**Comment by wenjiett** [comment]
> > **model**
> 
> 你是否使用量化后的模型进行裁剪？

不是

**Comment by SunAhong1993** [comment]
> > > **model**
> > 
> > 
> > 你是否使用量化后的模型进行裁剪？
> 
> 不是

正常训练后的模型应该为model.yml、model.pdmodel、model.pdparams这几个文件，不应该有__params__。

**Comment by wenjiett** [comment]
> > > > **model**
> > > 
> > > 
> > > 你是否使用量化后的模型进行裁剪？
> > 
> > 
> > 不是
> 
> 正常训练后的模型应该为model.yml、model.pdmodel、model.pdparams这几个文件，不应该有__params__。

我训练完后运行了这一段代码!paddlex --export_inference --model_dir output/yolov3/epoch_260 --save_dir infer,然后就生成了那三个文件

**Comment by SunAhong1993** [comment]
> > > > > **model**
> > > > 
> > > > 
> > > > 你是否使用量化后的模型进行裁剪？
> > > 
> > > 
> > > 不是
> > 
> > 
> > 正常训练后的模型应该为model.yml、model.pdmodel、model.pdparams这几个文件，不应该有__params__。
> 
> 我训练完后运行了这一段代码!paddlex --export_inference --model_dir output/yolov3/epoch_260 --save_dir infer,然后就生成了那三个文件

不需要执行这段代码，直接使用训练后的模型即可进行裁剪。

**Comment by wenjiett** [comment]
> > > > > > **model**
> > > > > 
> > > > > 
> > > > > 你是否使用量化后的模型进行裁剪？
> > > > 
> > > > 
> > > > 不是
> > > 
> > > 
> > > 正常训练后的模型应该为model.yml、model.pdmodel、model.pdparams这几个文件，不应该有__params__。
> > 
> > 
> > 我训练完后运行了这一段代码!paddlex --export_inference --model_dir output/yolov3/epoch_260 --save_dir infer,然后就生成了那三个文件
> 
> 不需要执行这段代码，直接使用训练后的模型即可进行裁剪。

嗯嗯好的。还有一个问题请教一下，我得到敏感度信息后怎么进一步得到裁剪后的模型呢

**Comment by SunAhong1993** [comment]
获得敏感度信息后，可用过https://paddlex.readthedocs.io/zh_CN/latest/apis/visualize.html#id10 这一接口，分析在不同的eval_metric_loss参数下，模型被裁剪的比例情况。然后重新跑model.train，设置sensitivities_file和eval_metric_loss，跑完train之后，即为裁剪后的模型。

**Comment by wenjiett** [comment]
> 获得敏感度信息后，可用过https://paddlex.readthedocs.io/zh_CN/latest/apis/visualize.html#id10 这一接口，分析在不同的eval_metric_loss参数下，模型被裁剪的比例情况。然后重新跑model.train，设置sensitivities_file和eval_metric_loss，跑完train之后，即为裁剪后的模型。

好的，谢谢
