### ISSUE TITLE
案例中预测函数用的都是训练完的模型，文档中却说用导出后的模型，请问有区别吗

### ISSUE THREAD

**Issue by jianxin123** [PaddlePaddle/PaddleX#1511]
训练完后 生成best_model文件夹可以用来预测，模型导出后生成的模型和这个有什么区别吗，文档好像说导出后是静态的，不是很明白什么意思。建议用哪个呢，还是说一样的，如果换成导出后的模型，预测函数除了换一下模型地址，还需要什么修改吗，预测的结果和直接训练完的模型有不一样吗，还有裁剪模型用的yolov3_prune.py有吗？谢谢大佬了@FlyingQianMM

**Comment by jianxin123** [comment]
@[FlyingQianMM](https://github.com/FlyingQianMM)

**Comment by FlyingQianMM** [comment]
模型格式说明都在这里啦：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/export_model.md
