### ISSUE TITLE
部署模型导出 paddlex --export_inference --save_dir 参数小bug

### ISSUE THREAD

**Issue by cnhemiya** [PaddlePaddle/PaddleX#1514]
## 描述问题

例如：paddlex --export_inference --model_dir=./output/deeplabv3p_r50vd/best_model/ --save_dir=./my_out_infer

这里 --save_dir=./my_out_infer 我原意是导出到 ./my_out_infer，实际上是导出到 ./my_out_infer/inference_model

希望用户自定义 **--save_dir** 后取消后面的 **inference_model**。

**Comment by FlyingQianMM** [comment]
抱歉，让您的部署体验多了一步指定到`inference_model`。

之前我们加上`inference_model是担心有时候会把`save_dir`直接设置成训练模型所在路径，这样会把原本训练模型的`model.pdmodel`、`model.pdparams`、`model.yaml`覆盖掉。

目前您还是需要在部署阶段多指定到`inference_model`才行。
