### ISSUE TITLE
复现教程 工业指针型表计读数https://aistudio.baidu.com/aistudio/projectdetail/4487340 ，模型预测时报错

### ISSUE THREAD

**Issue by ulen2000** [PaddlePaddle/PaddleX#1587]
复现教程 工业指针型表计读数 https://aistudio.baidu.com/aistudio/projectdetail/4487340 ，模型预测时报错

按照教程训练好模型，运行reader_infer.py，报错如下：

root@05a394f2334d:~# python reader_infer.py --det_model_dir output/ppyolov2_r50vd_dcn/best_model --seg_model_dir output/deeplabv3p_r50vd/best_model/ --image meter_det/test/20190822_105.jpg
/usr/local/miniconda3/lib/python3.8/site-packages/matplotlib/__init__.py:152: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(module.__version__) < minver:
/usr/local/miniconda3/lib/python3.8/site-packages/setuptools/_distutils/version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
2022-09-07 03:00:58,218-WARNING: type object 'QuantizationTransformPass' has no attribute '_supported_quantizable_op_type'
2022-09-07 03:00:58,218-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 1.8.4 or develop version
/usr/local/miniconda3/lib/python3.8/site-packages/paddlex/ppcls/data/preprocess/ops/timm_autoaugment.py:38: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
/usr/local/miniconda3/lib/python3.8/site-packages/paddlex/ppcls/data/preprocess/ops/timm_autoaugment.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
W0907 03:00:59.895490 18580 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0907 03:00:59.899395 18580 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
2022-09-07 03:01:00 [INFO]	Model[PPYOLOv2] loaded.
2022-09-07 03:01:00 [INFO]	Model[DeepLabV3P] loaded.
Traceback (most recent call last):
  File "reader_infer.py", line 583, in <module>
    infer(args)
  File "reader_infer.py", line 576, in infer
    meter_reader.predict(image, args.save_dir, args.use_erode,
  File "reader_infer.py", line 549, in predict
    seg_results = self.erode(seg_results, erode_kernel)
  File "reader_infer.py", line 265, in erode
    eroded_results[i]['label_map'] = cv2.erode(
cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-eirhwqtr/opencv/modules/imgproc/src/morph.simd.hpp:756: error: (-213:The function/feature is not implemented) Unsupported data type (=4) in function 'getMorphologyRowFilter'

**Comment by lailuboy** [comment]
看错误是32位带符号的单通道在新版本的OpenCV不被支持，可以将结果转成uint8，使用低版本的OpenCV试试

**Comment by ulen2000** [comment]
好的，谢谢

**Comment by ulen2000** [comment]
> 看错误是32位带符号的单通道在新版本的OpenCV不被支持，可以将结果转成uint8，使用低版本的OpenCV试试
谢谢
