### ISSUE TITLE
Deploy部署预测出来的ROI位置和paddlex Gui位置不一致

### ISSUE THREAD

**Issue by aaaaalun** [PaddlePaddle/PaddleX#1618]
2. 如果您使用的是c++或c#部署方式，请提供您使用的PaddleX分支、推理引擎（例如PaddleInference）版本号
paddlex-develop,2.3
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
windows
4. 请问您使用的CUDA/cuDNN的版本号是？
11

使用yolov3训练出来的模型，在gui和deploy预测结果一致，但是faster-rcnn预测出来的框没有框住目标，有点偏移。
输入图像是多尺度的，不是固定尺寸的，使用的是model_infer.exe的历程，没有进行任何数据增强，gui的也只是水平翻转。

**Comment by lailuboy** [comment]
训练时候设置的图像大小是多少

**Comment by aaaaalun** [comment]
> 训练时候设置的图像大小是多少

我的原图尺寸有450*281的 还有513*340、354*356的，因为是从网上爬下来所以图片比较多
然后训练尺寸试过好几个了，有默认的800*1333，也有32倍数的 608*608 640*640的 但是这些都还是会有点的偏移和gui 预测的不太一样

**Comment by lailuboy** [comment]
偏移多少，图像尺寸不同的话会resize，检查下前后处理。GUI上使用的模型也是一样的

**Comment by aaaaalun** [comment]
就是原先能框住物体，现在没框住，大概就偏了几个到十几个像素把，大体位置是差不多的。
我感觉也是前后处理的resize问题，使用model_infer的例子跑的，我看例子里面没有任何说要进行resize、reshape的操作，在进入predict的后，里面会有操作进行reshape，具体也不会改因为也不是很懂，而且试了其他模型都不会
但是我做了一些测试，比训练时候尺寸大的小的我都测试了，都会不同程度的偏差，然后我就直接将原图的尺寸事先调整到和训练尺寸大小一致在进行预测，发现这时候框就全部正常了。然后我去看gui的预测结果图，发现批量测试的图片结果大小其实都是不一致的，x方向有大有小，但是y方向都是统一的尺寸，不明白是怎么回事？
还请大佬帮忙看看怎么进一步去解决呢。

**Comment by aaaaalun** [comment]
已解决，cpp的deploy里面的resize有问题
