### ISSUE TITLE
window10系统安装paddleX后，点击打开时一直在加载中，打不开软件

### ISSUE THREAD

**Issue by lky-bit** [PaddlePaddle/PaddleX#163]
电脑环境：笔记本、windows10、1080ti

**Comment by MichaelZhero** [comment]
如果之前装过paddlex的话，需要把工作目录名字给改掉，才能进行打开。否则，就把工作目录给删了。

**Comment by lailuboy** [comment]
1.0正式版本后是兼容的，不需要设置新的工作目录。
如果不能打开，请发下c:\users\xxx\\.paddlex\logs目录的日志

**Comment by lky-bit** [comment]
好的好的，多谢
