### ISSUE TITLE
_export_inference_model将训练好的模型导出到中文路径下会新建乱码文件夹

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PaddleX#1644]
## 描述问题
[`_export_inference_model`](https://github.com/PaddlePaddle/PaddleX/blob/f06130bac098a227a9de80a6db4f10ca9fd31434/paddlex/cv/models/base.py#L592)函数，只要模型导出路径中包含中文，就会新建乱码文件夹，比如我的输出路径是`D:\dataset\potsdam数据集\train_out\1\best_infer_model`，会自动创建两个乱码文件夹: `potsdam鏁版嵁闆`和`potsdam鏁版嵁闆哱train_out`，`model.pdiparams`保存在乱码文件夹（比如`potsdam鏁版嵁闆哱train_out`）下，而其它推理文件，如`model.pdmodel`， `model.pdiparams.info`, `model.yml`，会正常保存在`D:\dataset\potsdam数据集\train_out\1\best_infer_model`文件夹下面。

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
`paddlepaddle-gpu` =  2.2.2
`paddlex`  = 2.1.0
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
`win10`

3. 请问您使用的Python版本是？
`python3.7.6`
5. 请问您使用的CUDA/cuDNN的版本号是？
`CUDA10.2`, `cuDNN 7.6`.

请问有没有替代`_export_inference_model`函数 解决方案呢？
谢谢

**Comment by jiangjiajun** [comment]
不支持带中文或空格的路径
