### ISSUE TITLE
在公司内部服务器 import paddlex 出现奇怪的报错，求解答

### ISSUE THREAD

**Issue by tspp520** [PaddlePaddle/PaddleX#166]
import paddlex
WARNING: OMP_NUM_THREADS set to 16, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
2020-06-19 14:10:28,252-INFO: Instantiated empty configuration.

HDFS initialization failed, please check if .hdfscli，cfg exists.

**Comment by lailuboy** [comment]
是提示设置OpenMP并行区域线程数量以及VisualDL使用HDFS, 对使用没有影响。
