### ISSUE TITLE
添加图片语义分割时labels.txt不是0和1页是254

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleX#1674]
添加图片语义分割时labels.txt不是0和1页是254

![图片](https://user-images.githubusercontent.com/6648329/224883833-ff5e750d-247a-4d78-b404-73c8d65080ef.png)
![图片](https://user-images.githubusercontent.com/6648329/224883847-f83d6a10-a3c6-457c-8457-b714b295753b.png)
![图片](https://user-images.githubusercontent.com/6648329/224883902-0e1a03e2-bdce-4a91-8d89-e4ef021093d6.png)
![图片](https://user-images.githubusercontent.com/6648329/224884033-9eebcfa9-0f6d-4d5d-b2f7-092b1b15bb28.png)

应该是0和1才对呀，怎么会到254去？

**Comment by gg22mm** [comment]
我看了，我网上下载的蒙版是0-256 那么多分类，不知道为什么会这样，我只能把它变成二分类，但是这样很多头发 就看到不了。会丢失细节  ~~

**Comment by lailuboy** [comment]
精细化分割可以试试PaddleSeg中的PP-Matting模型

**Comment by gg22mm** [comment]
> PP-Matting

PP-Matting 用过，我现在转用pp_liteseg ，感觉非常好~
