### ISSUE TITLE
Failed to build lap

### ISSUE THREAD

**Issue by whisky-12** [PaddlePaddle/PaddleX#1718]
## Checklist:

3. 确认bug是否在新版本里还未修复

## 描述问题
使用多种示例都无法安装lap库 导致无法正常安装Paddlex
Failed to build lap
ERROR: Could not build wheels for lap, which is required to install pyproject.toml-based projects

环境为 centos7 paddle cpu

**Comment by hcx1002** [comment]
我也遇到了，lap出错，试试这条命令：conda install -c conda-forge lap 
地址：https://blog.csdn.net/qq_51831335/article/details/126458403

**Comment by whisky-12** [comment]
我也遇到了，lap出错，试试这条命令：conda install -c conda-forge lap
地址：https://blog.csdn.net/qq_51831335/article/details/126458403
----------------------------------------------------------------------------------
尝试过 依旧报错 但在linux上为出现这个问题 ，我尝试了新建环境 ，类似与paddlepaddle不兼容

**Comment by hcx1002** [comment]
linux看看这篇：https://blog.csdn.net/weixin_45943355/article/details/132110443
