### ISSUE TITLE
运行 MobileNetV3_large_ssld 然后一直卡在 train 这里

### ISSUE THREAD

**Issue by tspp520** [PaddlePaddle/PaddleX#175]
![image](https://user-images.githubusercontent.com/13615964/85908518-f3299980-b847-11ea-9b3e-df8fbc0da662.png)
我以为睡一觉起来会有 状态更新，但是并没有。

**Comment by FlyingQianMM** [comment]
可以尝试以下方法排除下问题：1. 参考tutorial里面https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/classification/mobilenetv2.py   用样例数据集跑MobileNetV3_large_ssld，如果能成功运行，那可能是你的数据集有问题 2. 如果按照1运行后，程序还是hang住的话，麻烦再反馈下运行系统、paddle的版本、cuda和cudnn版本是什么。

**Comment by tspp520** [comment]
![image](https://user-images.githubusercontent.com/13615964/85914777-e6bb3600-b873-11ea-86af-a61f34fc99a5.png)
用蔬菜那个运行跑的

**Comment by tspp520** [comment]
不知道自己数据集出了什么问题，反正用 keras 跑那个 数据集也能run

**Comment by tspp520** [comment]
好吧，是我数据集的问题，已经解决了
