### ISSUE TITLE
No voc record found in %s' % (file_list)

### ISSUE THREAD

**Issue by BarryAlllen** [PaddlePaddle/PaddleX#1751]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
文件和代码都按照官方的，运行的时候出现了这个错误

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
pp 2.2.2
px 2.1.0

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
ubuntu20.04

4. 请问您使用的Python版本是？
3.7

6. 请问您使用的CUDA/cuDNN的版本号是？
12.1

**Comment by changdazhou** [comment]
建议检查voc数据集是否符合规范
