### ISSUE TITLE
文档错误！

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/PaddleX#178]
https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/tutorials/deploy/deploy_server/deploy_cpp/deploy_cpp_linux.md
“
编译cmake的命令在scripts/build.sh中，请根据实际情况修改主要参数，其主要内容说明如下：”
这段说清楚 scripts/build.sh 是在哪个目录下的，
如果是PaddleX-develop/deploy/cpp/scripts 下，则.sh文件需要权限，此处没有，增加权限 chmod 777 *.sh后

scripts/build.sh中

PADDLE_DIR=/path/to/fluid_inference/
这路径怎么来的？
Step2: 中：
“下载并解压后/root/projects/fluid_inference” 那么此处路径是 “/root/projects/fluid_inference”
“
执行build脚本：
sh ./scripts/build.sh”
路径也不写清楚，举个例子也好！
下面执行：
`/PaddleX-develop/deploy/cpp/scripts $ ./build.sh 
sh: 0: Can't open /home/pi/PaddleX-develop/deploy/cpp/scripts/scripts/bootstrap.sh
sh: 0: Can't open /home/pi/PaddleX-develop/deploy/cpp/scripts/scripts/bootstrap.sh
CMake Error: The source directory "/home/pi/PaddleX-develop/deploy/cpp/scripts" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.`

“sh: 0: Can't open /home/pi/PaddleX-develop/deploy/cpp/scripts/scripts/bootstrap.sh”

里面俩scripts/scripts/ 怎么出来的？

文档能否写的清楚点，都好好测试下，开发人员安心写代码，测试人员好好测试写文档。

**Comment by FlyingQianMM** [comment]
PADDLE_DIR=/path/to/fluid_inference/为你下载的fluid_inference所在的路径。修改好./scripts/build.sh后，在终端: cd /PaddleX-develop/deploy/cpp/  然后sh ./scripts/build.sh

**Comment by 60999** [comment]
依然有错误
`[ 30%] Built target ext-yaml-cpp
Scanning dependencies of target paddlex_inference
[ 34%] Building CXX object CMakeFiles/paddlex_inference.dir/src/visualize.cpp.o
In file included from /home/auser/PaddleX-develop/deploy/cpp/src/visualize.cpp:15:0:
/home/auser/PaddleX-develop/deploy/cpp/include/paddlex/visualize.h:25:10: fatal error: sys/io.h: 没有那个文件或目录
 #include <sys/io.h>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/paddlex_inference.dir/build.make:62: recipe for target 'CMakeFiles/paddlex_inference.dir/src/visualize.cpp.o' failed
make[2]: *** [CMakeFiles/paddlex_inference.dir/src/visualize.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/paddlex_inference.dir/all' failed
make[1]: *** [CMakeFiles/paddlex_inference.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by 60999** [comment]
多次尝试也无法通过

**Comment by Channingss** [comment]
fatal error: sys/io.h: 没有那个文件或目录，这个提示说明系统里面没 sys/io.h这个头文件，这是系统库，你的系统是什么

**Comment by jiangjiajun** [comment]
此issue长期未更新，将被关闭，如有需求可随时再打开。
