### ISSUE TITLE
请问下现在还是只有预测部分支持API形式，训练只支持命令行吗

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/PaddleX#1782]
一直想把paddle的目标检测和分割的一些优质的模型封装到软件中。之前都是基于paddle detection做，把读取config部分的代码自己修改了，但总体来说命令行形式对于二次开发实在是非常麻烦(那边也有人提建议，但是貌似没相关的计划)。
之前也是看了很多,有用paddle inferance原生的接口做预测，也有fastdeploy等一些针对部署的，但是这些其实都是割裂开的，训练部署经常中间还没打通等等。
不知道paddlex有没有把数据集分析，训练等也做API的计划呢。

**Comment by cuicheng01** [comment]
PaddleX会保证支持的模型训练和推理、部署打通，这块数据和训练主要还是以命令行为主，推理的话涉及到集成到系统中，我们计划提供完备的API，供大家串联模型，如果使用高性能部署的话，我们也会提供基于FastDeploy的高性能部署方案（包含本地部署和服务化部署）。
