### ISSUE TITLE
请问paddleX界面有开源计划吗？迫切需求

### ISSUE THREAD

**Issue by Stones3ma** [PaddlePaddle/PaddleX#1865]
希望paddlex界面也开源，这样更好用，跟讲的低代码训练模型将一致，现在只开源了api，跟其他套件没有太大差别。

**Comment by cuicheng01** [comment]
您好，现在的PaddleX的界面基于云端更好用一些，可以直接在[星河社区](https://aistudio.baidu.com/pipeline/mine)体验，这一套用到了很多星河社区本身的服务和能力，所以暂时不太考虑开源。PaddleX可以同时以低代码的方式迭代大部分场景下的模型，且可以实现模型的无缝串联，实现真实场景的多模型组合使用，这个是和其他套件的主要区别哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by monkeycc** [comment]
因为云端可以偷你的数据集

**Comment by liu-jiaxuan** [comment]
您好，星河社区对用户上传的数据集有严格的保护机制，没有任何人可以“偷”数据集，这一点可以放心~
