### ISSUE TITLE
昇腾910B，aarch64 ARM 架构部署PaddleX失败

### ISSUE THREAD

**Issue by fallbernana123456** [PaddlePaddle/PaddleX#1867]
## 描述问题

在进行paddlex --install 安装时，报错AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text' ，网上的说是opencv-python版本不对，但是 paddlex 指定了 opencv-python-4.5.5.64，改不了，

## 复现
由于 不提供 Aarch64 架构docker镜像，只能手动安装。
git clone https://gitee.com/paddlepaddle/PaddleX.git
cd PaddleX
//注意，如果是 arm64 架构的 xpu 机器，需要先手动安装 tool_helpers，x86 架构机器不需要
pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlenlp-device/tool_helpers-0.1.1-cp310-cp310-linux_aarch64.whl
我是arm64 架构的npu机器，不知道是否需要安装，但是还是安装了
pip install -e .  (成功)
paddlex --install  报错

## 环境
python 3.10
paddlex 3.0.0b0

##其他 
Aarch64 架构 npu系统 没有支持的镜像，支持的PaddleX模型列表也少。请问下OCR什么时候能支持？

**Comment by a31413510** [comment]
1、opencv的问题，可以尝试卸载opencv，然后重新安装opencv，再执行paddlex --install 
2、arm64 架构的npu镜像和paddle包计划近期支持上去，OCR已经支持，敬请期待

**Comment by fallbernana123456** [comment]
> 1、opencv的问题，可以尝试卸载opencv，然后重新安装opencv，再执行paddlex --install 2、arm64 架构的npu镜像和paddle包计划近期支持上去，OCR已经支持，敬请期待

我修改了requirement.txt里的opencv_python的版本就可以了。
但是你说ocr已经支持了。我在[PaddleX 昇腾模型列表](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/models/support_npu_model_list.md) 里并没看到。你说已经支持了，那我该怎么用呢？

**Comment by a31413510** [comment]
这个模型列表近期会更新，在x86机器上我们已经支持了OCR，我们后续会发布arm的镜像和paddle包，到时候就可以在arm机器上使用了。

**Comment by fallbernana123456** [comment]
> 这个模型列表近期会更新，在x86机器上我们已经支持了OCR，我们后续会发布arm的镜像和paddle包，到时候就可以在arm机器上使用了。

好的。多谢回复。
