### ISSUE TITLE
name 'paddle' is not defined

### ISSUE THREAD

**Issue by hu-qi** [PaddlePaddle/PaddleX#1895]
## 描述问题

name 'paddle' is not defined

## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
是

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
否

3. 您使用的数据集是？
与数据集无关

4. 请提供您出现的报错信息及相关log

![image](https://github.com/user-attachments/assets/351cd6df-7f5a-454c-a32a-ceeed00d5996)

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

![image](https://github.com/user-attachments/assets/96b6c7eb-71b3-4ff7-a9a9-760c7976ae7e)

```
Name: paddlepaddle-gpu
Version: 3.0.0b1

Name: paddlex
Version: 3.0.0b0
```

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

linux

5. 请问您使用的Python版本是？

![image](https://github.com/user-attachments/assets/6fade8db-add0-460a-8668-a0339c6509ea)
Python 3.10.13
pip 23.3.1 from /opt/conda/lib/python3.10/site-packages/pip (python 3.10)

9. 请问您使用的CUDA/cuDNN的版本号是？
11.8
![image](https://github.com/user-attachments/assets/cc007864-d818-4c81-92fb-fee43678e82d)

**Comment by hu-qi** [comment]
paddlepaddle-gpu 换成 3.0.0b0 之后也是一样的报错

**Comment by hu-qi** [comment]
已解决， release 代码不是最新的， 缺少 import paddle
https://github.com/PaddlePaddle/PaddleX/commit/3e949a3f04c7d8cdfb08670f1e1a7907fd3ebc54#r145310878

**Comment by cuicheng01** [comment]
感谢，已修复～
