### ISSUE TITLE
昇腾910B arm架构npu推理速度比cpu还慢

### ISSUE THREAD

**Issue by yujunhuics** [PaddlePaddle/PaddleX#1904]
环境
paddle-custom-npu         3.0.0b1
paddleocr                 2.8.1
paddlepaddle              3.0.0b1
paddlex                   3.0.0b0     

问题如题：
在测试paddleocr时发现速度巨慢

**Comment by wangna11BD** [comment]
辛苦发一下使用的flag和命令

**Comment by yujunhuics** [comment]
> 辛苦发一下使用的flag和命令

关于脚本，我使用的是ocr产线的python API使用脚本，原封不动：
```
import cv2
from paddlex import OCRPipeline
from paddlex import PaddleInferenceOption
from paddlex.pipelines.OCR.utils import draw_ocr_box_txt


kernel_option = PaddleInferenceOption()
kernel_option.set_device("npu:0")

pipeline = OCRPipeline(
    'PP-OCRv4_mobile_det',
    'PP-OCRv4_mobile_rec',
    text_det_kernel_option=kernel_option,
    text_rec_kernel_option=kernel_option,)
result = pipeline.predict(
    {"input_path": "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_002.png"},
)

draw_img = draw_ocr_box_txt(result['original_image'],result['dt_polys'], result["rec_text"])
cv2.imwrite("ocr_result.jpg", draw_img[:, :, ::-1])
```
测试时发现，使用npu速度比cpu的速度慢了将近8倍。

**Comment by wangna11BD** [comment]
这个是因为第一次运行触发了jit编译导致耗时很久，可以看看你文件下是不是有生成一个kernel_meta文件夹。我在predict里加了个循环，测试det第一次运行需要5.67s，后面只需要0.05s，rec也是一样的现象。
![image](https://github.com/user-attachments/assets/d187b427-1585-4fd4-a459-4162b69dbf3c)
![image](https://github.com/user-attachments/assets/af3b6972-d7ca-48aa-ac78-8e97c7c32b3e)

**Comment by wangna11BD** [comment]
如果需要测速的话建议推理时加一下warmup 20iter，然后取80iter推理时间均值

**Comment by yujunhuics** [comment]
> 这个是因为第一次运行触发了jit编译导致耗时很久，可以看看你文件下是不是有生成一个kernel_meta文件夹。我在predict里加了个循环，测试det第一次运行需要5.67s，后面只需要0.05s，rec也是一样的现象。 ![image](https://private-user-images.githubusercontent.com/79366697/357811291-d187b427-1585-4fd4-a459-4162b69dbf3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODgwNzQsIm5iZiI6MTcyMzY4Nzc3NCwicGF0aCI6Ii83OTM2NjY5Ny8zNTc4MTEyOTEtZDE4N2I0MjctMTU4NS00ZmQ0LWE0NTktNDE2MmI2OWRiZjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAyMDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ODc2MTQ5NzRlODIzZGU4MzhjODk5ZGIxZDBlOWE0YWRkNmE5M2FiYjI4MDQ1MTdjOWE1Y2RkYzM2NTc0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7zyWrOYj0j8C-xLIN7aInCf9wfP9tR6JbTNjFk3hhgM) ![image](https://private-user-images.githubusercontent.com/79366697/357811362-af3b6972-d7ca-48aa-ac78-8e97c7c32b3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODgwNzQsIm5iZiI6MTcyMzY4Nzc3NCwicGF0aCI6Ii83OTM2NjY5Ny8zNTc4MTEzNjItYWYzYjY5NzItZDdjYS00OGFhLWFjNzgtOGU5N2M3YzMyYjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAyMDkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MGM2NTk4NGUxODM0ZTI1OTFiNWE0ZDI1YmY4MGYxMDc5YmI4MTRmOWI4ODYyOTJlYTRlZWI5ODlhYWVjMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5nY8GOK2rJjz7q_Ldon9T0hVcguMvyAQ3PdSt7IIDY)

原来是第一次出发jit编译耗费的大量的时间，感谢科普

**Comment by yujunhuics** [comment]
这个bug还是得重新开一下，经常出现如下问题
Warning: tiling offset out of range, index: 32
Warning: tiling offset out of range, index: 32
Warning: tiling offset out of range, index: 32
