### ISSUE TITLE
目前最新版本支持TensorRT加速部署吗？

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleX#1915]
问题如上，遇到项目对预测速度有要求，需要用到tensorrt加速部署，x86平台，rtx3080ti

**Comment by Bobholamovic** [comment]
你好，可以使用[基于FastDeploy的部署方案](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/pipelines/pipeline_deployment_with_fastdeploy.md)，该方案支持使用TensorRT在x86平台加速推理～

**Comment by CashBai** [comment]
@Bobholamovic 我看了你给我链接里的说明，需要先去网页版生成一个模型及部署文件，那我如果直接按照FastDeploy模块在github上的文档去操作的话能行吗？

**Comment by Bobholamovic** [comment]
> @Bobholamovic 我看了你给我链接里的说明，需要先去网页版生成一个模型及部署文件，那我如果直接按照FastDeploy模块在github上的文档去操作的话能行吗？

PaddleX提供的FastDeploy（FD）和开源版本的FD不太一样，如果要使用PaddleX提供的FD进行部署的话，需要参考PaddleX文档哈

**Comment by CashBai** [comment]
也就是说，目前来源版本的FD暂时还不支持paddlex是吧



---- 回复的原邮件 ----
| 发件人 | Lin ***@***.***> |
| 日期 | 2024年08月16日 12:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleX] 目前最新版本支持TensorRT加速部署吗？ (Issue #1915) |

@Bobholamovic 我看了你给我链接里的说明，需要先去网页版生成一个模型及部署文件，那我如果直接按照FastDeploy模块在github上的文档去操作的话能行吗？

PaddleX提供的FastDeploy（FD）和开源版本的FD不太一样，如果要使用PaddleX提供的FD进行部署的话，需要参考PaddleX文档哈

**Comment by Bobholamovic** [comment]
是的

**Comment by cuicheng01** [comment]
@CashBai 感谢关注，未来PaddleX所有的模型都会通过PaddleX提供的FastDeploy（FD）提供高性能多硬件的部署方案，这部分能力正在升级建设中

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
