### ISSUE TITLE
paddlex2.1在ubuntu20.04启动失败

### ISSUE THREAD

**Issue by 77bw** [PaddlePaddle/PaddleX#1950]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 如果bug是由PaddleX API 2.0导致，且该bug在develop分支里已修复，参考[FAQ Q4](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)替换内置PaddleX API

## 复现

1. 请提供您出现的报错信息及相关log（log的查找见 [FAQ Q2](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md#gui%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)）

![image](https://github.com/user-attachments/assets/416680af-6182-4f96-90cc-54d550854d78)
主要报错如下：
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at /paddle/paddle/fluid/platform/device_context.h:418)
  [operator < gaussian_random > error]

2. 请提供您使用的GUI版本号
paddlex2.1
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
ubuntu20.04.6
4. 请问您使用的CUDA/cuDNN的版本号是？
CUDA Version: 12.4

**Comment by cuicheng01** [comment]
建议降低CUDA版本试试，比如10.2，2.x版本的CUDA版本支持比较低

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
