### ISSUE TITLE
模型训练时出现 UnsupportedParamError: 'PP-YOLOE_plus-S' is not a registered model name.

### ISSUE THREAD

**Issue by YSU-Spectroscopy-Lab** [PaddlePaddle/PaddleX#1967]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 描述问题

报错：
Traceback (most recent call last):
  File "/home/aistudio/PaddleX/paddlex/repo_apis/base/config.py", line 31, in _create_config
    model_info = get_registered_model_info(model_name)
  File "/home/aistudio/PaddleX/paddlex/repo_apis/base/register.py", line 81, in query
    return self._table[prim_key]
KeyError: 'PP-YOLOE_plus-S'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aistudio/PaddleX/paddlex/utils/result_saver.py", line 30, in wrap
    result = func(self, *args, **kwargs)
  File "/home/aistudio/PaddleX/paddlex/engine.py", line 41, in run
    trainer = build_trainer(self.config)
  File "/home/aistudio/PaddleX/paddlex/modules/base/trainer/trainer.py", line 35, in build_trainer
    return BaseTrainer.get(model_name)(config)
  File "/home/aistudio/PaddleX/paddlex/modules/base/trainer/trainer.py", line 53, in __init__
    self.pdx_config, self.pdx_model = build_model(self.global_config.model)
  File "/home/aistudio/PaddleX/paddlex/modules/base/build_model.py", line 34, in build_model
    config = Config(model_name, config_path)
  File "/home/aistudio/PaddleX/paddlex/repo_apis/base/config.py", line 33, in _create_config
    raise UnsupportedParamError(
paddlex.utils.errors.others.UnsupportedParamError: 'PP-YOLOE_plus-S' is not a registered model name.

## 复现
运行代码

%cd ~/PaddleX

!python main.py -c paddlex/configs/object_detection/PP-YOLOE_plus-S.yaml \
    -o Global.mode=train \
    -o Global.dataset_dir=/home/aistudio/work/dataset

## 环境
平台：AI Studio 星河社区的BML CodeLab
PaddlePaddle ==  3.0.0beta1
PaddleX == 3.0
Python == 3.10.10

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by YSU-Spectroscopy-Lab** [comment]
已校验数据：
Start loading xml annotation files from /home/aistudio/work/dataset/train_anno_list.txt ...
Start converting !
100%|█████████████████████████████████████| 4250/4250 [00:01<00:00, 3429.94it/s]
The converted annotations has been save to /home/aistudio/work/dataset/annotations/instance_train.json.
Start loading xml annotation files from /home/aistudio/work/dataset/val_anno_list.txt ...
Start converting !
100%|███████████████████████████████████████| 750/750 [00:00<00:00, 3611.04it/s]
The converted annotations has been save to /home/aistudio/work/dataset/annotations/instance_val.json.
Convert dataset successfully !
loading annotations into memory...
Done (t=0.22s)
creating index...
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
loading annotations into memory...
Done (t=0.16s)
creating index...
index created!
Check dataset passed !

**Comment by YSU-Spectroscopy-Lab** [comment]
> 尝试此操作 https://gofile.io/d/yMHabA 在安装程序中选择所需的编译器

没有在本地运行，是在BML CodeLab上面train的，这个没有用，感谢

**Comment by cuicheng01** [comment]
感觉是训练部分没有安装成功，可以尝试如下命令，重新安装`paddlex --install PaddleDetection --platform gitee.com`

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by xiaoxiaoo8** [comment]
@YSU-Spectroscopy-Lab 您好，您后来解决了吗？我也遇到了这个问题

**Comment by whisky-12** [comment]
您好，您后来解决了吗？我也遇到了这个问题
