### ISSUE TITLE
PaddleX什么时候支持Windows安装？

### ISSUE THREAD

**Issue by openvino-book** [PaddlePaddle/PaddleX#1969]
https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta/docs/tutorials/INSTALL.md
请给出Windows上的安装步骤，谢谢！~

**Comment by cuicheng01** [comment]
您好，这块关于Windows的支持也在持续进行中了，请您持续关注，相关更新会在develop分支体现

**Comment by openvino-book** [comment]
> 您好，这块关于Windows的支持也在持续进行中了，请您持续关注，相关更新会在develop分支体现

非常期待，在工业自动化里面，基于PC的AI+运控，90%都是基于Windows，用C#开发的应用程序。PaddleX支持Windows，会极大方便该领域开发者。

**Comment by cuicheng01** [comment]
好的，具体来说，你们更希望是用windows推理部署吧，并不是训练？

**Comment by openvino-book** [comment]
> 好的，具体来说，你们更希望是用windows推理部署吧，并不是训练？

每个项目给End User配一台训练机(4U工控机+4060/4080)放现场，给EU的技术员标注新样本并训练新模型用。Windows上使用PaddleX可以降低技术员的学习门槛。

**Comment by cuicheng01** [comment]
明白了

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
