### ISSUE TITLE
Ubuntu 20.04使用Docker安装仍然出现Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by sjchen** [PaddlePaddle/PaddleX#1985]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
我使用docker方式安装：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html  但是在docker中 import paddle 还是会报错，何解

## 复现 

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
no
2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
no
3. 您使用的数据集是？
no
4. 请提供您出现的报错信息及相关log
user@user-ESC8000A-E11:~/paddle$ sudo docker run --runtime=nvidia --gpus all --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:3.0.0b1-gpu-cuda12.3-cudnn9.0-trt8.6 /bin/bash

==========
== CUDA ==
==========

CUDA Version 12.3.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

λ dcee8b8bdf33 /home ll
total 16K
drwxr-xr-x  1 root root 4.0K Jul  4 06:59 ./
drwxr-xr-x  1 root root 4.0K Sep 11 07:47 ../
drwxrwxr-x 12 root root 4.0K May 14 12:17 ccache-4.8.2/
drwxr-xr-x  6 root root 4.0K May 14 12:12 cmake-3.18.0-Linux-x86_64/
λ dcee8b8bdf33 /home python
Python 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Illegal instruction (core dumped)
λ dcee8b8bdf33 /home exit
exit

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
3.0.0b1
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-119-generic x86_64)
3. 请问您使用的Python版本是？
Python 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0] on linux
5. 请问您使用的CUDA/cuDNN的版本号是？
CUDA Version: 12.3

**Comment by zhang-prog** [comment]
`nvidia-smi` 看一下宿主机支持的cuda驱动版本是不是12以上

**Comment by sjchen** [comment]
NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2

> `nvidia-smi` 看一下宿主机支持的cuda驱动版本是不是12以上

**Comment by zhang-prog** [comment]
麻烦把cpu和gpu型号都贴一下吧

**Comment by cuicheng01** [comment]
如果使用CUDA12.3，需要升级docker，建议升级为最新的docker版本

**Comment by sjchen** [comment]
> 麻烦把cpu和gpu型号都贴一下吧
CPU:
processor	: 127
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 49
model name	: AMD EPYC 7542 32-Core Processor
stepping	: 0
microcode	: 0x830107a
cpu MHz		: 1500.000
cache size	: 512 KB
physical id	: 1
siblings	: 64
core id		: 31
cpu cores	: 32
apicid		: 191
initial apicid	: 191
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogomips	: 5771.26
TLB size	: 3072 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

GPU: A100 80G

**Comment by sjchen** [comment]
> 如果使用CUDA12.3，需要升级docker，建议升级为最新的docker版本

请问升级的理由是什么，有具体技术原因还是盲猜？

**Comment by cuicheng01** [comment]
这是一个实践结论，可以试试哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
