### ISSUE TITLE
安装paddlex后导入报cython错误

### ISSUE THREAD

**Issue by yimingdingqq** [PaddlePaddle/PaddleX#2149]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
使用conda安装PaddleX，通过python导入paddlex时候出错。
pip install paddlex
import paddlex as pdx
AttributeError: module 'Cython.Plex.Actions' has no attribute 'Method'

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
安装并导入paddlex时候就报错误了。

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
当前版本号：
(paddlex-p37) [root@lenovo-g5050 Fire_and_Smoke_Detection-PaddleX###]# conda list | grep paddlex
packages in environment at /opt/app/conda3/envs/paddlex-p37:
paddlex                   2.1.0                    pypi_0    pypi
(paddlex-p37) [root@lenovo-g5050 Fire_and_Smoke_Detection-PaddleX###]# conda list | grep paddlepaddle
paddlepaddle              2.5.2           py37_cpu_many_linux    paddle

conda list | grep cython
cython                    3.0.11                   pypi_0    pypi
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Linux
3. 请问您使用的Python版本是？
Python 3.7.16
# 创建名为paddlex-p37的环境，指定Python版本为3.7
conda create -n paddlex-p37 python=3.7

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by changdazhou** [comment]
建议使用最新版本的PaddleX哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
