### ISSUE TITLE
图片中的表格识别会报错：local variable 'ocr_res' referenced before assignment

### ISSUE THREAD

**Issue by li7dragonball** [PaddlePaddle/PaddleX#2151]
我在用PaddleX的“table_recognition”模块识别图片中的表格时，有些表格图片会报错：
single_img_res["ocr_result"] = OCRResult(ocr_res)
UnboundLocalError: local variable 'ocr_res' referenced before assignment

## 环境
PaddlePaddle版本：3.0.0b1
PaddleX的版本：3.0.0b1
操作系统：Windows
Python版本：3.9
笔记本没有独立显卡，未用显卡加速

**Comment by zhang-prog** [comment]
收到，最近看一下

**Comment by cyxconfluence** [comment]
有进站了么

**Comment by valleyUp** [comment]
简单看了一下似乎是识别后的图片标签没有table类型的。这个是前面这个识别模型的问题吗，使用网页版示例是可以正常运行的，换成paddlex命令行不行了。https://github.com/PaddlePaddle/PaddleX/blob/0f4289d67fba53ae1976423d57e03ec1da00c74e/paddlex/inference/pipelines/table_recognition/table_recognition.py#L113

**Comment by vivansxu** [comment]
试了一下把`if sub["label"].lower() == "table": `改成`if sub["label"].lower() == "figure": `能运行了

**Comment by valleyUp** [comment]
> 试了一下把`if sub["label"].lower() == "table": `改成`if sub["label"].lower() == "figure": `能运行了

啊这，但是根据我粗浅的理解不得要版面识别为table的部分图片，再继续往下走table recognition吗？不过你这样改，最终识别的效果怎么样？

我是换了一个版面识别模型（`RT-DETR-H_layout_3cls`）,这样就能获得标签是table的部分图片了，但是后续的table recognition有点差（相同的图片使用paddlex提供的网页demo就可以正常区分），不知道是不是我姿势不对，明显1列的表硬是搞成2列，但是看了https://github.com/PaddlePaddle/PaddleX/issues/2182#issue-2580383041 这个后，愈发怀疑我那地方搞错了。

**Comment by zhang-prog** [comment]
这个PR已经修复 https://github.com/PaddlePaddle/PaddleX/pull/2167 ，麻烦拉一下代码试试是否可以解决问题

**Comment by valleyUp** [comment]
> 这个PR已经修复 #2167 ，麻烦拉一下代码试试是否可以解决问题

你好，目前使用paddlex命令是可以正常使用了，感谢！

但是我有一个问题想要请教一下，这个命令行的模型识别出来效果感觉好像和网页版提供的demo有点差距，是我姿势不对吗？
![2_layout](https://github.com/user-attachments/assets/6548d851-b27a-4cca-9a0d-932c7960ea18)

**Comment by zhang-prog** [comment]
是有做过其他什么修改吗？麻烦提供下运行命令。

**Comment by valleyUp** [comment]
> 是有做过其他什么修改吗？麻烦提供下运行命令。

命令：`paddlex --pipeline table_recognition --input 2.jpg --device gpu:0`

修改的话，将table_recognition.yaml里面的PP-OCRv4_mobile_det和PP-OCRv4_mobile_rec换成服务器版的PP-OCRv4_server，其他都没有变化。上面那个版面识别就是用默认的PicoDet_layout_1x。

你们这边运行这个示例没问题吗？

**Comment by zhang-prog** [comment]
我这边运行示例没问题哈，只得到了一个figure label，麻烦你按照指南直接安装最新的paddlex再运行试试看～
<img width="875" alt="simple" src="https://github.com/user-attachments/assets/f68fb0d1-3381-4ed7-9c6d-5248bab5b9ac">

**Comment by valleyUp** [comment]
> 我这边运行示例没问题哈，只得到了一个figure label，麻烦你按照指南直接安装最新的paddlex再运行试试看～ <img alt="infoflow 2024-10-17 20-23-36" width="875" src="https://private-user-images.githubusercontent.com/69562787/377462970-f68fb0d1-3381-4ed7-9c6d-5248bab5b9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNjg1OTAsIm5iZiI6MTcyOTE2ODI5MCwicGF0aCI6Ii82OTU2Mjc4Ny8zNzc0NjI5NzAtZjY4ZmIwZDEtMzM4MS00ZWQ3LTljNmQtNTI0OGJhYjViOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDEyMzEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ODFiM2FkNzU1MmM5MGVkMGZlNWE1ZTM1YzdjNjczZGRhNmZmMjZiYmE5NmNjOThhYmNlOTZmYzNlZDc1MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-Mwm94uoYzdOx5wBuTNKUhaU0wwhpBLqUaflZWieHgQ">

好的好的，我再试试，感谢

**Comment by zhang-prog** [comment]
好的，有问题欢迎再提issue～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
