### ISSUE TITLE
Ubuntu24.04 LTS 使用Docker安装PaddleX后无法成功import paddle

### ISSUE THREAD

**Issue by ILoveAmy** [PaddlePaddle/PaddleX#2153]
本机信息(非虚拟机)如下：
Intel i7-13700K + NV 3060 + Ubuntu 24.04.1 LTS + Docker version 27.3.1, build ce12230
![C7B2EC161E0AA29087B5440905450CAD](https://github.com/user-attachments/assets/04469d4e-9856-44a6-ba25-188e5774880f)

NV驱动成功安装，版本550.107.02
![AB901BA85F9B54972787D7D9EC1136A4](https://github.com/user-attachments/assets/ecaaafb0-add0-4e27-b997-e08b227b1912)

参考[PaddleX安装文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/installation/installation.md),使用命令启动paddlex镜像后，import paddle失败，如下图所示：
> sudo docker run --gpus all --name paddlex -v $PWD:/paddle --shm-size=8G --network=host -it registry.baidubce.com/paddlex/paddlex:3.0.0b1-gpu-cuda12.3-cudnn9.0-trt8.6 /bin/bash

![1728121282122](https://github.com/user-attachments/assets/7482a53e-62d3-45a8-bef7-0933aadba312)

**Comment by openvino-book** [comment]
BTW, if I use the installation command:
> conda install paddlepaddle-gpu==3.0.0b1 paddlepaddle-cuda=11.8 -c paddle -c nvidia

Paddle works!
![1728131331962](https://github.com/user-attachments/assets/0a9e94d1-20f2-41c5-bc67-9a25cc75abf1)

**Comment by risemeup1** [comment]
用我们提供的镜像呢？你们都是wsl+docker？

**Comment by risemeup1** [comment]
这个paddlex提供的镜像有问题，我反馈了，先用第二种方式吧

**Comment by risemeup1** [comment]
你用的不会是wsl吧？

**Comment by openvino-book** [comment]
> 你用的不会是wsl吧？

全新的硬件，纯血安装Ubuntu

**Comment by openvino-book** [comment]
> 用我们提供的镜像呢？你们都是wsl+docker？

在Intel i7-13700K + NV 3060 机器上，直接安装Ubuntu 24.04 LTS

**Comment by TingquanGao** [comment]
目前确认ubuntu24.04存在兼容性问题，paddle框架仍在修复中，有进展后会同步。感谢关注~

**Comment by TingquanGao** [comment]
该问题已被修复，可以试下最新的docker：`registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b2-paddlepaddle3.0.0b2-gpu-cuda11.8-cudnn8.6-trt8.5`，相关文档：`https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/installation/installation.md#21-%E5%9F%BA%E4%BA%8Edocker%E8%8E%B7%E5%8F%96paddlex`

**Comment by openvino-book** [comment]
> 该问题已被修复，可以试下最新的docker：`registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b2-paddlepaddle3.0.0b2-gpu-cuda11.8-cudnn8.6-trt8.5`，相关文档：`https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/installation/installation.md#21-%E5%9F%BA%E4%BA%8Edocker%E8%8E%B7%E5%8F%96paddlex`

pip install 方式，什么时候更新啊？
![1730703624017](https://github.com/user-attachments/assets/05fcee21-1e81-4994-9c8f-6370d843dec1)

**Comment by TingquanGao** [comment]
whl应该没问题吧？有问题的是我们提供的镜像和ubuntu 24.04不兼容

**Comment by zqverse** [comment]
请问镜像registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b1-paddlepaddle3.0.0b1-cpu什么时候更新啊？

**Comment by TingquanGao** [comment]
更新了呀：registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b2-paddlepaddle3.0.0b2-cpu

**Comment by ILoveAmy** [comment]
问题完美解决，感谢PaddleX团队！~
![image](https://github.com/user-attachments/assets/ef384060-2ae7-4690-8935-2c941d5cde34)

**Comment by ILoveAmy** [comment]
问题完美解决，如下图所示，Close this issue
![image](https://github.com/user-attachments/assets/4d6b22a3-4366-4626-b28a-cac776bdf298)
