### ISSUE TITLE
FatalError: `Process abort signal` is detected by the operating system.

### ISSUE THREAD

**Issue by openvino-book** [PaddlePaddle/PaddleX#2156]
[PC information]：
Intel i7-13700K + NV 3060 + Ubuntu 24.04.1 LTS + CUDA 11.8

[Steps to Reproduce]
1. Install PaddlePaddle using:
> conda install paddlepaddle-gpu==3.0.0b1 paddlepaddle-cuda=11.8 -c paddle -c nvidia

The validation shows “PaddlePaddle is installed successfully!”
![1728181696832](https://github.com/user-attachments/assets/1bc5ce3f-7f73-4087-a6af-ad6f179f9268)

2. Install PaddleX using
> pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl

*paddlex --help* works well as below
![1728181799992](https://github.com/user-attachments/assets/b9f7cb2e-045b-4a00-8c5b-ed623ce84e52)

3. Execute the command:
> paddlex --pipeline object_detection --input https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_object_detection_002.png --device gpu:0

FatalError: `Process abort signal` is detected by the operating system.
![1728181944828](https://github.com/user-attachments/assets/aa2671ae-a5fa-471c-a23a-2bd0b7f3db08)

**Comment by TingquanGao** [comment]
Which docker image is being used? The error appears to be caused by the libcublasLt.so.12 file not being found. You can try to find the file, and add the file path to PATH.

**Comment by openvino-book** [comment]
> Which docker image is being used? The error appears to be caused by the libcublasLt.so.12 file not being found. You can try to find the file, and add the file path to PATH.

I install the PaddlePaddle + PaddleX by whl file directly with 2 commands:
> conda install paddlepaddle-gpu==3.0.0b1 paddlepaddle-cuda=11.8 -c paddle -c nvidia
pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl

No docker

**Comment by TingquanGao** [comment]
Please try to use docker provided by PaddleX: https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/installation/installation_en.md#21-get-paddlex-based-on-docker

**Comment by openvino-book** [comment]
> Please try to use docker provided by PaddleX: https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/installation/installation_en.md#21-get-paddlex-based-on-docker

I tried, however, there will be another problem: https://github.com/PaddlePaddle/PaddleX/issues/2153

**Comment by TingquanGao** [comment]
We will test the docker on Ubuntu 24.

**Comment by openvino-book** [comment]
> We will test the docker on Ubuntu 24.

@TingquanGao Any update? :)

**Comment by TingquanGao** [comment]
I have confirmed that the 20.04 is supported by Paddle. Could you try this cmd: `docker run --gpus all --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:3.0.0b1-gpu-cuda12.3-cudnn9.0-trt8.6 /bin/bash`

**Comment by TingquanGao** [comment]
We have confirmed that there is an issue, and will fix as soon as possible.

**Comment by openvino-book** [comment]
> We have confirmed that there is an issue, and will fix as soon as possible.

Looking foward to it!

**Comment by TingquanGao** [comment]
The issue has been fixed. Please try using the latest docker: `registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b2-paddlepaddle3.0.0b2-gpu-cuda11.8-cudnn8.6-trt8.5`. And more infomation please refer to https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/installation/installation_en.md#21-get-paddlex-based-on-docker

**Comment by openvino-book** [comment]
The problem has been solved by PaddlePaddle team, Thank You, Paddle team!
![image](https://github.com/user-attachments/assets/fae4bddd-063a-4d5c-baa6-89bc592788ad)

**Comment by openvino-book** [comment]
Isssue has been solved, close it.
