### ISSUE TITLE
Cannot find main.py file？

### ISSUE THREAD

**Issue by nlilili** [PaddlePaddle/PaddleX#2158]
where can i get the **main.py** file showed in module usage tutorials as below？
```
python main.py -c paddlex/configs/image_classification/PP-LCNet_x1_0.yaml \
    -o Global.mode=check_dataset \
    -o Global.dataset_dir=./dataset/cls_flowers_examples
```

**Comment by zhangyubo0722** [comment]
是在PaddleX目录下运行的吗

**Comment by nlilili** [comment]
是的。
paddlex下只有这些文件：
![IMG_6465](https://github.com/user-attachments/assets/24778589-18fa-4545-86b7-b1a526797bac)

**Comment by zhangyubo0722** [comment]
在PaddleX目录下运行，而不是paddlex
![image](https://github.com/user-attachments/assets/92562ecd-7041-4420-b85c-5475d4bf8148)
