### ISSUE TITLE
Ascend 910B 推理报错

### ISSUE THREAD

**Issue by MinaRoss** [PaddlePaddle/PaddleX#2166]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 描述问题

基于昇腾910B npu运行ocr工作流推理报错：(InvalidArgument) The size of outputs_args names (2) must be equal to the size of kernel output_defs (1).

## 复现

1. 基于镜像registry.baidubce.com/device/paddle-npu:cann80RC1-ubuntu20-aarch64-gcc84-py39在ascend 910B上按照说明（https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu/install_cn.html#anzhuangfangshier-yuandaimabianyianzhuang）已经部署，测试成功。
`λ huawei /work python -c "import paddle_custom_device; paddle_custom_device.npu.version()"
I1008 17:31:10.595837 104899 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.9/dist-packages/paddle_custom_device
I1008 17:31:10.595896 104899 init.cc:145] Try loading custom device libs from: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I1008 17:31:11.193534 104899 custom_device.cc:1099] Succeed in loading custom runtime in lib: /usr/local/lib/python3.9/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1008 17:31:11.199738 104899 custom_kernel.cc:63] Succeed in loading 357 custom kernel(s) from loaded lib(s), will be used like native ones.
I1008 17:31:11.199941 104899 init.cc:157] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I1008 17:31:11.199985 104899 init.cc:242] CustomDevice: npu, visible devices count: 2
I1008 17:31:11.725132 104899 custom_operator.cc:1296] register pir custom op :my_add_n
I1008 17:31:11.725349 104899 custom_operator.cc:1296] register pir custom op :update_inputs
I1008 17:31:11.725461 104899 custom_operator.cc:1296] register pir custom op :get_output
I1008 17:31:11.725528 104899 custom_operator.cc:1296] register pir custom op :set_stop_value_multi_ends
I1008 17:31:11.725586 104899 custom_operator.cc:1296] register pir custom op :fused_blha_layer_op
I1008 17:31:11.725720 104899 custom_operator.cc:1296] register pir custom op :remove_padding
I1008 17:31:11.725770 104899 custom_operator.cc:1296] register pir custom op :fused_get_rotary_embedding
I1008 17:31:11.725817 104899 custom_operator.cc:1296] register pir custom op :fused_rope
I1008 17:31:11.725829 104899 custom_operator.cc:1296] register pir custom op :fused_rope_grad
I1008 17:31:11.725883 104899 custom_operator.cc:1296] register pir custom op :rms_norm_npu
I1008 17:31:11.725896 104899 custom_operator.cc:1296] register pir custom op :rms_norm_npu_grad
I1008 17:31:11.725948 104899 custom_operator.cc:1296] register pir custom op :fused_mm_reduce_scatter
I1008 17:31:11.726001 104899 custom_operator.cc:1296] register pir custom op :fused_allgather_mm
I1008 17:31:11.726094 104899 custom_operator.cc:1296] register pir custom op :rebuild_padding_v2
I1008 17:31:11.726140 104899 custom_operator.cc:1296] register pir custom op :flash_attention_npu
I1008 17:31:11.726153 104899 custom_operator.cc:1296] register pir custom op :flash_attention_npu_grad
I1008 17:31:11.726226 104899 custom_operator.cc:1296] register pir custom op :write_cache_kv
I1008 17:31:11.726269 104899 custom_operator.cc:1296] register pir custom op :rebuild_padding
I1008 17:31:11.726306 104899 custom_operator.cc:1296] register pir custom op :get_padding_offset
I1008 17:31:11.726347 104899 custom_operator.cc:1296] register pir custom op :fused_mm_allreduce
I1008 17:31:11.726397 104899 custom_operator.cc:1296] register pir custom op :get_token_penalty_multi_scores_v2
I1008 17:31:11.726447 104899 custom_operator.cc:1296] register pir custom op :get_padding_offset_v2
I1008 17:31:11.726490 104899 custom_operator.cc:1296] register pir custom op :lm_head
I1008 17:31:11.726543 104899 custom_operator.cc:1296] register pir custom op :quant_int8
I1008 17:31:11.726598 104899 custom_operator.cc:1296] register pir custom op :qkv_transpose_split
I1008 17:31:11.726649 104899 custom_operator.cc:1296] register pir custom op :save_with_output
I1008 17:31:11.726698 104899 custom_operator.cc:1296] register pir custom op :set_value_by_flags_and_idx
I1008 17:31:11.726734 104899 custom_operator.cc:1296] register pir custom op :save_output
I1008 17:31:11.726774 104899 custom_operator.cc:1296] register pir custom op :set_value_by_flags_and_idx_v2
I1008 17:31:11.726822 104899 custom_operator.cc:1296] register pir custom op :dequant_int8
I1008 17:31:11.726859 104899 custom_operator.cc:1296] register pir custom op :get_token_penalty_multi_scores
I1008 17:31:11.726903 104899 custom_operator.cc:1296] register pir custom op :step_paddle
I1008 17:31:11.727062 104899 custom_operator.cc:1296] register pir custom op :set_stop_value_multi_ends_v2
I1008 17:31:11.727108 104899 custom_operator.cc:1296] register pir custom op :write_int8_cache_kv
I1008 17:31:11.727152 104899 custom_operator.cc:1296] register pir custom op :encode_rotary_qk
I1008 17:31:11.727202 104899 custom_operator.cc:1296] register pir custom op :transpose_remove_padding
version: 0.0.0
commit: 45315d1195939bbdd6ee199f9b31425219799653
custom_op commit: 45315d1195939bbdd6ee199f9b31425219799653
cann: 8.0.RC1`
2. 请提供您出现的报错信息及相关log
运行如下命令会报错：
命令：
`paddlex --pipeline OCR --input https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_002.png --device npu:0` 
报错：
`Using official model (PP-OCRv4_mobile_det), the model files will be be automatically downloaded and saved in /root/.paddlex/official_models.
Using official model (PP-OCRv4_mobile_rec), the model files will be be automatically downloaded and saved in /root/.paddlex/official_models.
Connecting to https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_ocr_002.png ...
Downloading general_ocr_002.png ...
[==================================================] 100.00%
I1008 17:37:46.739485 108169 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.9/dist-packages/paddle_custom_device
I1008 17:37:46.739544 108169 init.cc:145] Try loading custom device libs from: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I1008 17:37:47.344105 108169 custom_device.cc:1099] Succeed in loading custom runtime in lib: /usr/local/lib/python3.9/dist-packages/paddle_custom_device/libpaddle-custom-npu.so
I1008 17:37:47.350199 108169 custom_kernel.cc:63] Succeed in loading 357 custom kernel(s) from loaded lib(s), will be used like native ones.
I1008 17:37:47.350405 108169 init.cc:157] Finished in LoadCustomDevice with libs_path: [/usr/local/lib/python3.9/dist-packages/paddle_custom_device]
I1008 17:37:47.350450 108169 init.cc:242] CustomDevice: npu, visible devices count: 2
Traceback (most recent call last):
  File "/usr/local/bin/paddlex", line 8, in <module>
    sys.exit(console_entry())
  File "/usr/local/lib/python3.9/dist-packages/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/usr/local/lib/python3.9/dist-packages/paddlex/paddlex_cli.py", line 182, in main
    return pipeline_predict(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/paddlex_cli.py", line 144, in pipeline_predict
    for res in result:
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/base.py", line 38, in __call__
    yield from self.predict(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/pipelines/ocr.py", line 70, in predict
    for rec_res in self.text_rec_model(
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/models/base/base_predictor.py", line 48, in __call__
    for res in super().__call__(input):
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/base.py", line 57, in __call__
    for each_output in output:
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/models/base/basic_predictor.py", line 51, in apply
    yield from self._generate_res(self.engine(x))
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/utils/process_hook.py", line 46, in _wrapper
    for ele in input_:
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/base.py", line 273, in __call__
    yield from self.__call__(data, i + 1)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/base.py", line 273, in __call__
    yield from self.__call__(data, i + 1)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/base.py", line 272, in __call__
    for data in data_gen:
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/base.py", line 43, in __call__
    output = self.apply(**args)
  File "/usr/local/lib/python3.9/dist-packages/paddlex/inference/components/paddle_predictor/predictor.py", line 174, in apply
    self.predictor.run()
ValueError: (InvalidArgument) The size of outputs_args names (2) must be equal to the size of kernel output_defs (1).
  [Hint: Expected output_names.size() == output_defs.size(), but received output_names.size():2 != output_defs.size():1.] (at /paddle/paddle/fluid/framework/operator.cc:3210)
  [operator < squeeze2 > error]`

## 环境

paddlepaddle              3.0.0b1
paddlex                   3.0.0b1
python 3.9

**Comment by wangna11BD** [comment]
可以先设置一下3个环境变量试试
export FLAGS_npu_storage_format=0
export FLAGS_npu_jit_compile=0
export FLAGS_use_stride_kernel=0
