### ISSUE TITLE
Atlas 300v支持

### ISSUE THREAD

**Issue by FengJin-cv** [PaddlePaddle/PaddleX#2172]
尊敬的百度工程师们，请问什么时候支持Atlas 300v 加速卡

**Comment by nepeplwu** [comment]
@FengJin-cv 感谢反馈，相关推理卡上的部署能力正在支持中，请问您用的是什么模型？

**Comment by FengJin-cv** [comment]
yolo系列的模型。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月11日 11:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleX] Atlas 300v支持 (Issue #2172) |

@FengJin-cv 感谢反馈，相关推理卡上的部署能力正在支持中，请问您用的是什么模型？

**Comment by FengJin-cv** [comment]
主要是v8的检测



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月11日 11:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/PaddleX] Atlas 300v支持 (Issue #2172) |

@FengJin-cv 感谢反馈，相关推理卡上的部署能力正在支持中，请问您用的是什么模型？

**Comment by liuhongen1234567** [comment]
好的，感谢您的反馈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
