### ISSUE TITLE
无法安装高性能推理插件，提示参数不符

### ISSUE THREAD

**Issue by a19970519** [PaddlePaddle/PaddleX#2179]
安装命令
paddlex --serve --pipeline OCR --device gpu:0 --host 0.0.0.0 --port 5000 --use_hpip --serial_number XXXXX --update_license

安装环境
python3.10
cuda12
cudnn8.9
gpu A10 24G

提示错误
paddlex: error: unrecognized arguments: --serve --pipeline OCR --device gpu:0 --host 0.0.0.0 --port 5000 --use_hpip

**Comment by changdazhou** [comment]
尝试更换CUDA11.8哈

**Comment by a19970519** [comment]
> 尝试更换CUDA11.8哈

更换了，还是提示一样的内容

**Comment by a19970519** [comment]
usage: paddlex [-h] [--recipe RECIPE] [--loop] [--rest] [--build] [--config CONFIG]
paddlex: error: unrecognized arguments: --serve --pipeline OCR --device gpu:0 --host 0.0.0.0 --port 5000 --use_hpip --serial_number 序列号 --update_license

**Comment by a19970519** [comment]
<img width="229" alt="1728630919322" src="https://github.com/user-attachments/assets/f160e5ba-439e-41f9-b240-63ec5462e8f5">

**Comment by Bobholamovic** [comment]
请执行`cat $(which paddlex)`查看使用的paddlex脚本内容。

**Comment by a19970519** [comment]
> cat $(which paddlex)

root@lwp:~# cat $(which paddlex)
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'paddlex','console_scripts','paddlex'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'paddlex'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('paddlex', 'console_scripts', 'paddlex')())

**Comment by Bobholamovic** [comment]
请将如下脚本保存为`check.py`：

```python
#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'paddlex','console_scripts','paddlex'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'paddlex'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()

globals().setdefault('load_entry_point', importlib_load_entry_point)

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    entry_point = load_entry_point('paddlex', 'console_scripts', 'paddlex')
    print(entry_point.__code__)
```

然后执行`python check.py`。

**Comment by a19970519** [comment]
> 请将如下脚本保存为`check.py`：
> 
> ```python
> #!/usr/bin/python3
> # EASY-INSTALL-ENTRY-SCRIPT: 'paddlex','console_scripts','paddlex'
> import re
> import sys
> 
> # for compatibility with easy_install; see #2198
> __requires__ = 'paddlex'
> 
> try:
>     from importlib.metadata import distribution
> except ImportError:
>     try:
>         from importlib_metadata import distribution
>     except ImportError:
>         from pkg_resources import load_entry_point
> 
> 
> def importlib_load_entry_point(spec, group, name):
>     dist_name, _, _ = spec.partition('==')
>     matches = (
>         entry_point
>         for entry_point in distribution(dist_name).entry_points
>         if entry_point.group == group and entry_point.name == name
>     )
>     return next(matches).load()
> 
> globals().setdefault('load_entry_point', importlib_load_entry_point)
> 
> if __name__ == '__main__':
>     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
>     entry_point = load_entry_point('paddlex', 'console_scripts', 'paddlex')
>     print(entry_point.__code__)
> ```
> 
> 然后执行`python check.py`。

运行后
![1728640668814](https://github.com/user-attachments/assets/37f70e4b-b139-42be-9dd1-2610bbc7c77b)

**Comment by Bobholamovic** [comment]
请问你是否执行过类似`pip install fastdeploy`的指令？

**Comment by a19970519** [comment]
> fastdeploy

我执行过这个

**Comment by Bobholamovic** [comment]
那么请执行`pip uninstall fastdeploy fastdeploy-gpu-python`，然后重新安装高性能推理插件。此外，请注意当前高性能推理插件仅支持CUDA 11.8～

**Comment by a19970519** [comment]
> 那么请执行`pip uninstall fastdeploy fastdeploy-gpu-python`，然后重新安装高性能推理插件。此外，请注意当前高性能推理插件仅支持CUDA 11.8～

好的，感谢，我试一下

**Comment by a19970519** [comment]
> 那么请执行`pip uninstall fastdeploy fastdeploy-gpu-python`，然后重新安装高性能推理插件。此外，请注意当前高性能推理插件仅支持CUDA 11.8～

现在会提示这个错误：AssertionError: DBDetector initialize failed

**Comment by a19970519** [comment]
> 那么请执行`pip uninstall fastdeploy fastdeploy-gpu-python`，然后重新安装高性能推理插件。此外，请注意当前高性能推理插件仅支持CUDA 11.8～

现在会提示这个，然后web服务也无法使用
The `paddle::PlaceType::kCPU/kGPU` is deprecated since version 2.3, and will be removed in version 2.4! Please use `Tensor::is_cpu()/is_gpu()` method to determine the type of place
