### ISSUE TITLE
表格模型SLANet来源

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/PaddleX#2182]
我在 PaddleOCR repo 中使用最新的 SLANet，其推理效果低于PaddleX中的SLANet，请问PaddleX的SLANet来源于何处

**Comment by cuicheng01** [comment]
PaddleX依托于PaddleOCR的先进技术，支持了OCR领域的一站式全流程开发能力。PaddleX会在此基础上优化诸多模型，更多的优秀模型的训练和部署会在PaddleX中呈现。

**Comment by GuoQuanhao** [comment]
会改变模型结构么，还是用了更多的数据进行训练

**Comment by cuicheng01** [comment]
没有改变模型结构

**Comment by GuoQuanhao** [comment]
此外https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/paddlex/repo_apis/PaddleOCR_api/configs/SLANet_plus.yaml 和 https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/paddlex/repo_apis/PaddleOCR_api/configs/SLANet.yaml 完全一样，二者没有任何区别么

**Comment by changdazhou** [comment]
X训练过程中会基于这个配置文件进行进一步的调整的哈，实际训练起来两者还是有区别的

**Comment by GuoQuanhao** [comment]
> X训练过程中会基于这个配置文件进行进一步的调整的哈，实际训练起来两者还是有区别的

这个区别包括哪些方面，只是训练的轮数和batchsize么，还是涉及到优化器和数据增强等的trick

**Comment by changdazhou** [comment]
主要是训练的轮数、batchsize和学习率，评估间隔等，具体参考X自身的配置即可

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
