### ISSUE TITLE
AttributeError: module 'paddlex' has no attribute 'tools'

### ISSUE THREAD

**Issue by liming1010** [PaddlePaddle/PaddleX#2185]
版本3.0
3.0.0.beta1
Traceback (most recent call last):
  File "D:\pyproject\paddlexdemo\main.py", line 10, in <module>
    pdx.tools.labelme2voc(image_dir='imgs',
AttributeError: module 'paddlex' has no attribute 'tools'

**Comment by TingquanGao** [comment]
请问`pdx.tools.labelme2voc(image_dir='imgs',`这个用法是参考的那里的文档吗？
