### ISSUE TITLE
产品线 table_recognition， 官方示例中，调用 res.save_to_csv(...) 失败。 

### ISSUE THREAD

**Issue by vision1v1** [PaddlePaddle/PaddleX#2196]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

Name: paddlepaddle
Version: 3.0.0b1

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

Windows

5. 请问您使用的Python版本是？

Python 3.8.2

7. 请问您使用的CUDA/cuDNN的版本号是？

CPU

报错信息
res.save_to_csv("./output/table_recognition")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'TableResult' object has no attribute 'save_to_csv'

**Comment by cuicheng01** [comment]
文档确实有误，我们会尽快更新这块的文档～您可以先注释掉这一行～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
