### ISSUE TITLE
paddlex是否支持昇腾910

### ISSUE THREAD

**Issue by boreassun** [PaddlePaddle/PaddleX#2197]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题

paddlex是否支持昇腾910，如果支持有相关安装文档吗

## 环境
registry.baidubce.com/device/paddle-npu:cann701-ubuntu20-aarch64-gcc84-py39

**Comment by cuicheng01** [comment]
您好，是支持的，[详情](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/other_devices_support/multi_devices_use_guide.md)

**Comment by boreassun** [comment]
![image](https://github.com/user-attachments/assets/c8f516b5-3992-48f5-91c2-a96511f5635f)
我看文档里写的只支持910b，是否支持910a呢？

**Comment by Sunting78** [comment]
您好 目前暂不支持910a。更多型号排期支持中。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
