### ISSUE TITLE
测试文档场景信息抽取v3产线时，运行失败

### ISSUE THREAD

**Issue by a19970519** [PaddlePaddle/PaddleX#2199]
运行环境
python3.10
cuda11.8
cudnn8.6
ubuntu 22.04 64位
PaddlePaddle 3.0.0b1
PaddleX 3.0.0b1

运行命令
paddlex paddlex --pipeline /opt/PP-ChatOCRv3-doc.yaml --input /opt/img/1.jpeg --device gpu:0

配置文件 PP-ChatOCRv3-doc.yaml
<img width="593" alt="1728702769015" src="https://github.com/user-attachments/assets/74bed721-5da2-4626-8808-1297e5645234">

提示错误
Traceback (most recent call last):
  File "/usr/local/bin/paddlex", line 33, in <module>
    sys.exit(load_entry_point('paddlex', 'console_scripts', 'paddlex')())
  File "/opt/PaddleX/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/opt/PaddleX/paddlex/paddlex_cli.py", line 182, in main
    return pipeline_predict(
  File "/opt/PaddleX/paddlex/paddlex_cli.py", line 145, in pipeline_predict
    res.print(json_format=False)
AttributeError: 'list' object has no attribute 'print'

![1728702597452](https://github.com/user-attachments/assets/58e2cc98-140b-4c8e-ae01-305550974f89)

**Comment by a19970519** [comment]
使用测试demo测试提示
{'chat_res': '当前选择后端为AI Studio，千帆调用失败，请检查token', 'prompt': ''}

脚本内容
![1728703637547](https://github.com/user-attachments/assets/7afb3aca-e13b-4231-aa9c-530f0143be95)

**Comment by changdazhou** [comment]
建议检查AK SK是否正确哈，对于第一个问题，目前PP-chatOCRv3产线暂不支持cli方式调用

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
