### ISSUE TITLE
chatocr产线无法使用其他国产大模型

### ISSUE THREAD

**Issue by JoshonSmith** [PaddlePaddle/PaddleX#2215]

**Comment by Bobholamovic** [comment]
你好，目前暂时只支持文心大模型，后续我们将提供对其他模型的支持，敬请关注

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by JoshonSmith** [comment]
chatocr产线无法使用其他国产大模型
