### ISSUE TITLE
本地体验PP-ChatOCRv3产线，使用官方demo出现【AttributeError: 'NoneType' object has no attribute 'values'】

### ISSUE THREAD

**Issue by Ameng2126** [PaddlePaddle/PaddleX#2223]
# PDF文件也是通过官方文档下载的，下面是完整报错

Traceback (most recent call last):
  File "E:\Py\PaddleX\demo.py", line 14, in <module>
    print(predict.chat("乙方,手机号"))
  File "E:\Py\PaddleX\paddlex\inference\pipelines\ppchatocrv3\ppchatocrv3.py", line 536, in chat
    if list(res.values())[0] in failed_results:
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by changdazhou** [comment]
方便提供一下完整的调用代码吗，应该是大模型返回的结果有问题

**Comment by Ameng2126** [comment]
![image](https://github.com/user-attachments/assets/1a4a1124-6204-42b0-9af3-7b68fa198216)
借鉴的官方文档中的本地体验代码，PDF也是根据官方地址下载的

**Comment by Ameng2126** [comment]
> 方便提供一下完整的调用代码吗，应该是大模型返回的结果有问题
![image](https://github.com/user-attachments/assets/90e17c05-f055-427c-8315-e8a6475bdde7)
借鉴的官方文档中的本地体验代码，PDF也是根据官方地址下载的

**Comment by vivansxu** [comment]
遇到了相同问题，后续发现是官方获取AKSK的文档有问题，千帆需要在应用接入-创建应用里获取aksk，而不是管理控制台中获取

**Comment by Ameng2126** [comment]
好嘞，谢谢大佬
