### ISSUE TITLE
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (matplotlib)

### ISSUE THREAD

**Issue by AngHooVen** [PaddlePaddle/PaddleX#2230]
## Checklist:

安装pip编译时出现：ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (matplotlib)

1. PaddleX版本号：PaddleX-release-3.0-beta1

2. 请提供您使用的操作系统信息：Windows

3. 请问您使用的Python版本号：Python 3.11.7

4. 请问您使用的CUDA/cuDNN的版本号：12.4

**Comment by cuicheng01** [comment]
您使用Python3.8-3.10试一下呢？3.11暂时还不支持，预计会在下一个版本支持

**Comment by AngHooVen** [comment]
@cuicheng01 ，我今天重新把Conda安装，以及使用Python3.10，目前已经安装成功了，感谢！
