### ISSUE TITLE
本地体验PP-ChatOCRv3，大模型返回结果中chat("乙方,手机号")报【'NoneType' object has no attribute 'values'】

### ISSUE THREAD

**Issue by Ameng2126** [PaddlePaddle/PaddleX#2251]
调用下面代码出现报错
![image](https://github.com/user-attachments/assets/5fe8952b-6f76-4c51-a249-474ebf28239f)

报错信息如下↓
Traceback (most recent call last):
File "E:\Py\PaddleX\demo.py", line 14, in
print(predict.chat("乙方,手机号"))
File "E:\Py\PaddleX\paddlex\inference\pipelines\ppchatocrv3\ppchatocrv3.py", line 536, in chat
if list(res.values())[0] in failed_results:
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by TingquanGao** [comment]
麻烦使用最新的paddlex试试呢？`pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl`

**Comment by Ameng2126** [comment]
> 麻烦使用最新的paddlex试试呢？`pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl`

使用后也是报同样的错误，下面是打印了一些ppchatocrv3.py中的参数，希望能对精确到问题起到帮助：
![image](https://github.com/user-attachments/assets/8684c622-3587-4a74-8779-8e7588929532)

**Comment by Ameng2126** [comment]
可以了，非常感谢您的帮助
