### ISSUE TITLE
python调用或者server部署，模型文件下必须要有个 inference.yml文件，该文件如何生成，不同模型相同类型的是否能通用。或者自己新建有啥规则

### ISSUE THREAD

**Issue by alanOO7** [PaddlePaddle/PaddleX#2263]

**Comment by alanOO7** [comment]
![image](https://github.com/user-attachments/assets/d9a7ec31-e786-47d7-b44d-6ecfd64f304d)
Hpi:
  backend_config:
    onnx_runtime:
      cpu_num_threads: 8
    openvino:
      cpu_num_threads: 8
    paddle_infer:
      cpu_num_threads: 8
      enable_log_info: false
  selected_backends:
    cpu: onnx_runtime
    gpu: paddle_infer
  supported_backends:
    cpu:
    - paddle_infer
    - openvino
    - onnx_runtime
    gpu:
    - paddle_infer
    - onnx_runtime
Global:
  model_name: PP-OCRv4_server_det
PreProcess:
  transform_ops:
  - DecodeImage:
      channel_first: false
      img_mode: BGR
  - DetLabelEncode: null
  - DetResizeForTest:
      resize_long: 960
  - NormalizeImage:
      mean:
      - 0.485
      - 0.456
      - 0.406
      order: hwc
      scale: 1./255.
      std:
      - 0.229
      - 0.224
      - 0.225
  - ToCHWImage: null
  - KeepKeys:
      keep_keys:
      - image
      - shape
      - polys
      - ignore_tags
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

**Comment by zhangyubo0722** [comment]
这个模型是在做模型导出的时候根据配置文件解析参数得到的，每个模型不可通用
模型导出命令：python main.py -c paddlex/configs/text_detection/PP-OCRv4_server_det.yaml -o Global.mode=export 
注：配置文件可替换，换成自己的模型

**Comment by ming2681** [comment]
如果我只想下载并运行ocr进行推理，而不需要根据数据集进行训练，这个文件通过这个方式可以导出吗？
