### ISSUE TITLE
训练中evaluate阶段保错

### ISSUE THREAD

**Issue by Dingxiangtao** [PaddlePaddle/PaddleX#2264]
前四个epoch的evaluate能正常进行，第五个epoch就报错了ValueError: (InvalidArgument) matrix_nms(): argument (position 3) must be double, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:241)

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
2. paddlepaddle2.5.1
3. paddlex2.1.0

4. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
6. windows

7. 请问您使用的Python版本是？
8. 3.7

9. 请问您使用的CUDA/cuDNN的版本号是？
12.1

**Comment by zhangyubo0722** [comment]
麻烦提供下复现命令吧

**Comment by Dingxiangtao** [comment]
https://aistudio.baidu.com/projectdetail/5351168?searchKeyword=%E4%BB%AA%E8%A1%A8&searchTab=ALL就是在复现这个链接里的项目碰到的问题

**Comment by zhangyubo0722** [comment]
麻烦贴一下报错截图吧，我这边好复现

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
