### ISSUE TITLE
paddlx 高性能部署 和不同部署返回结果不同。 

### ISSUE THREAD

**Issue by alanOO7** [PaddlePaddle/PaddleX#2268]
beta1版本

同一张图片，use_hpip  开启和不开启两种结果

**Comment by cuicheng01** [comment]
使用的是什么产线呢？

**Comment by alanOO7** [comment]
> 使用的是什么产线呢？

OCR产线

**Comment by Bobholamovic** [comment]
如果方便的话，请给出最小可复现例子，或者提供输入、输出示例，以便我们确认问题～

**Comment by galaxyRocky** [comment]
> 如果方便的话，请给出最小可复现例子，或者提供输入、输出示例，以便我们确认问题～

您好，https://pic1.zhimg.com/80/v2-e1360e077f165da87342db2dddfdaa00 这张图片，
用 paddlex 和 paddleocr 产出结果不同，我对比了这两种方式下载下来的模型，MD5 也不一样
1、paddlex 方式：
```
from paddlex import create_pipeline
from PIL import Image
pipeline = create_pipeline(pipeline="OCR")

img_path = "v2-e1360e077f165da87342db2dddfdaa00.png"
output = pipeline.predict(img_path)

for res in output:
    res.print()
    res.save_to_img("./output/")
```
![image](https://github.com/user-attachments/assets/5b198b2d-74ef-44f9-ae91-591231468483)

2、paddleocr  2.9.0 
```
from paddleocr import PaddleOCR, draw_ocr
import time

# Paddleocr目前支持的多语言语种可以通过修改lang参数进行切换
# 例如`ch`, `en`, `fr`, `german`, `korean`, `japan`
ocr = PaddleOCR(use_angle_cls=True, lang="ch")  # need to run only once to download and load model into memory
img_path = 'v2-e1360e077f165da87342db2dddfdaa00.png'
t1 = time.time()
result = ocr.ocr(img_path, cls=True)
print(time.time()-t1)
for idx in range(len(result)):
    res = result[idx]
    for line in res:
        print(line)
```
![image](https://github.com/user-attachments/assets/85fde8ca-6f1f-46ee-9bf4-6e1ed381248b)

我的环境 
paddle-serving-app        0.8.3
paddle-serving-client     0.2.1
paddleocr                 2.9.0
paddlepaddle-gpu          3.0.0b1
paddlex                   3.0.0b1

**Comment by Bobholamovic** [comment]
这是一个已知问题，我们正在跟进中，感谢反馈～

**Comment by cuicheng01** [comment]
是paddlex开不开hpip二者不一样还是paddleocr和paddlex默认的结果不一样呢？从代码上看，好像没有启用hpip？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
