### ISSUE TITLE
服务化部署不使用高性能推理插件，能够进行并发请求吗？

### ISSUE THREAD

**Issue by charmowen** [PaddlePaddle/PaddleX#2279]
服务化部署不使用高性能推理插件，能够进行并发请求吗？并发数在哪修改

**Comment by Bobholamovic** [comment]
你好，可以进行并发请求，并发数固定为1，目前不支持修改或更换和配置server等。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
