### ISSUE TITLE
DeepLab v3模型预测图片边缘出现锯齿

### ISSUE THREAD

**Issue by andy-zhangtao** [PaddlePaddle/PaddleX#228]
求助，我使用Paddlex的DeepLabv3p预训练模型+自有数据集训练后，在预测图片时，人体边缘锯齿感很严重，同时图片中还有一些残缺。  
原图:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/8232737/87622644-23cd6680-c756-11ea-9de3-65c08c3f485b.png">

预测图:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/8232737/87622614-16b07780-c756-11ea-9532-bef07dfaaad7.png">

我使用的模型参数是:
```
# num_classes = 2
pdx.seg.DeepLabv3p(
    num_classes=num_classes, 
    backbone='Xception65',
    use_bce_loss=True )
```

transforms参数:
```
train_transforms = transforms.ComposedSegTransforms(mode='train', train_crop_size=[512, 512])
eval_transforms = transforms.ComposedSegTransforms(mode='eval')
```

训练好的模型验证集mIOU=0.93

请问我调整哪些参数可以解决这两个问题呢？

**Comment by jiangjiajun** [comment]
> 求助，我使用Paddlex的DeepLabv3p预训练模型+自有数据集训练后，在预测图片时，人体边缘锯齿感很严重，同时图片中还有一些残缺。
> 原图:
> <img alt="image" width="601" src="https://user-images.githubusercontent.com/8232737/87622644-23cd6680-c756-11ea-9de3-65c08c3f485b.png">
> 
> 预测图:
> <img alt="image" width="658" src="https://user-images.githubusercontent.com/8232737/87622614-16b07780-c756-11ea-9532-bef07dfaaad7.png">
> 
> 我使用的模型参数是:
> 
> ```
> # num_classes = 2
> pdx.seg.DeepLabv3p(
>     num_classes=num_classes, 
>     backbone='Xception65',
>     use_bce_loss=True )
> ```
> 
> transforms参数:
> 
> ```
> train_transforms = transforms.ComposedSegTransforms(mode='train', train_crop_size=[512, 512])
> eval_transforms = transforms.ComposedSegTransforms(mode='eval')
> ```
> 
> 训练好的模型验证集mIOU=0.93
> 
> 请问我调整哪些参数可以解决这两个问题呢？

请问PaddleX的版本是多少呢？

**Comment by andy-zhangtao** [comment]
使用的是1.1.0
```
paddlex --version
PaddleX-1.1.0

```

**Comment by jiangjiajun** [comment]
> 使用的是1.1.0
> 
> ```
> paddlex --version
> PaddleX-1.1.0
> ```

是用的这个文档来训练吗 https://paddlex.readthedocs.io/zh_CN/develop/examples/human_segmentation.html#fine-tune

**Comment by andy-zhangtao** [comment]
没有参考您给出的文档，我参考的下面文档:

// 整体流程
https://paddlex.readthedocs.io/zh_CN/latest/tutorials/train/segmentation.html 
// 模型参数
https://paddlex.readthedocs.io/zh_CN/latest/apis/models/semantic_segmentation.html#deeplabv3p
// 参考的demo代码
https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/semantic_segmentation/deeplabv3p_xception65.py

**Comment by jiangjiajun** [comment]
> 没有参考您给出的文档，我参考的下面文档:
> 
> // 整体流程
> https://paddlex.readthedocs.io/zh_CN/latest/tutorials/train/segmentation.html
> // 模型参数
> https://paddlex.readthedocs.io/zh_CN/latest/apis/models/semantic_segmentation.html#deeplabv3p
> // 参考的demo代码
> https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/semantic_segmentation/deeplabv3p_xception65.py

建议使用上面的文档来训人像分割，有已经训练好的人像分割模型参数作为预训练参数

**Comment by andy-zhangtao** [comment]
好的，多谢。 我用您提供的文档试试

**Comment by andy-zhangtao** [comment]
@jiangjiajun 根据您提供的文档，现在训练出的模型明显要优于我之前训练的模型。 但发现边缘像素仍然存在预测错误的情况。比如下图:

原图：
<img width="745" alt="image" src="https://user-images.githubusercontent.com/8232737/87653815-a96a0a00-c788-11ea-9b66-1a59e1614e3a.png">

预测图:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/8232737/87653786-9bb48480-c788-11ea-972e-16c38eb585a6.png">

使用的是HumanSegServer 预训练模型
当前测试集:
mIOU:0.93736
category_iou: 0.96708676, 0.90764637

训练参数:
learning_rate 0.01
image_shape 512 512

麻烦您再指点一下，是参数设置的问题么？ 还是仍然需要继续训练？

**Comment by jiangjiajun** [comment]
> @jiangjiajun 根据您提供的文档，现在训练出的模型明显要优于我之前训练的模型。 但发现边缘像素仍然存在预测错误的情况。比如下图:
> 
> 原图：
> <img alt="image" width="745" src="https://user-images.githubusercontent.com/8232737/87653815-a96a0a00-c788-11ea-9b66-1a59e1614e3a.png">
> 
> 预测图:
> <img alt="image" width="830" src="https://user-images.githubusercontent.com/8232737/87653786-9bb48480-c788-11ea-972e-16c38eb585a6.png">
> 
> 使用的是HumanSegServer 预训练模型
> 当前测试集:
> mIOU:0.93736
> category_iou: 0.96708676, 0.90764637
> 
> 训练参数:
> learning_rate 0.01
> image_shape 512 512
> 
> 麻烦您再指点一下，是参数设置的问题么？ 还是仍然需要继续训练？

你的训练和测试图片的分辨率大小是多少呢

**Comment by andy-zhangtao** [comment]
训练集，测试集和验证集图片都是 1200 × 800的分辨率。 这张测试照片是2316 × 3088的分辨率， 我在预测之前的确没有做尺寸转换，您的意思是不是：图片尺寸不一致导致的这个问题？

**Comment by FlyingQianMM** [comment]
> 训练集，测试集和验证集图片都是 1200 × 800的分辨率。 这张测试照片是2316 × 3088的分辨率， 我在预测之前的确没有做尺寸转换，您的意思是不是：图片尺寸不一致导致的这个问题？

使用HumanSegServer 预训练模型训练的时候，训练和测试的transform分别是怎么定义的呢？

**Comment by andy-zhangtao** [comment]
@FlyingQianMM 
使用train.py中定义的transform:

image_shape = 512, 512
```python
train_transforms = transforms.Compose([
        transforms.Resize(args.image_shape), transforms.RandomHorizontalFlip(),
        transforms.Normalize()
    ])

    eval_transforms = transforms.Compose(
        [transforms.Resize(args.image_shape), transforms.Normalize()])
```

**Comment by andy-zhangtao** [comment]
@FlyingQianMM  我直接使用`PaddleX/examples/human_segmentation/train.py`进行训练和测试, 没有额外使用其它的transform。

**Comment by FlyingQianMM** [comment]
> @FlyingQianMM 我直接使用`PaddleX/examples/human_segmentation/train.py`进行训练和测试, 没有额外使用其它的transform。

1. 这张图片边缘效果不好主要是背景和帽子颜色接近 ，如果您finuetune的数据集中较少覆盖这种情况的话，会出现目前这种现象。
2. 如果边缘标注的不够精细的话，重新训练后也会导致模型在边缘处预测结果粗糙。
3. 因为您实际的测试图片大小和训练数据的出入较大，导致大图片伸缩变小后出现锯齿问题，如果后续都要使用大分辨率图片做测试的话，建议训练的im_shape调大一点，显存充足的前提下可以调整至1024x1024
4. 如果您的数据充足的话 ，可以先不必考虑调整transform，如果数据不充足且想进一步提升精度，可以加入一些数据增强，数据增强接口参考文档https://paddlex.readthedocs.io/zh_CN/develop/apis/transforms/seg_transforms.html

**Comment by andy-zhangtao** [comment]
@FlyingQianMM 谢谢您的建议。 我先将imape shape调整到1024x1024，观察一下效果。 现在数据集是5000张图片，依据您的经验，用5000张图片做Fine Tune足够么？

**Comment by FlyingQianMM** [comment]
> @FlyingQianMM 谢谢您的建议。 我先将imape shape调整到1024x1024，观察一下效果。 现在数据集是5000张图片，依据您的经验，用5000张图片做Fine Tune足够么？

如果覆盖面大的话，5000长是够的

**Comment by andy-zhangtao** [comment]
@FlyingQianMM 明白了。 中午将image shape调整到1024了，训练完以后看看效果怎么样。

**Comment by andy-zhangtao** [comment]
更新一下进度。 在多次调整image shape, LR和图片增强后，最终发现将image shape设定为 512, 512. 将数据集图片尺寸也固定为(512, 512)，配合数据增强后训练出来的效果是最好的(截止到目前)。 
![image](https://user-images.githubusercontent.com/8232737/88635711-94776a00-d0ea-11ea-84ab-201f89194c7a.png)
