### ISSUE TITLE
通用目标分类例程如何保存或查看结果图像

### ISSUE THREAD

**Issue by AngHooVen** [PaddlePaddle/PaddleX#2283]
我在命令行中输入：paddlex --pipeline semantic_segmentation --input D:\DeepLearning\PaddleX\image\general_image_classification_001.jpg --device gpu:0   测试图像分类

测试结果如下：
![image](https://github.com/user-attachments/assets/42579ada-e3b8-4403-b679-bcbf99aa774d)

想要查看运行的结果下一步应该怎么做呢

1. PaddleX的版本号：    3.0.0b1
2. 使用的操作系统信息：  Windows
3. 使用的Python版本是？ 3.10
4. 使用的CUDA/cuDNN的版本号是？ CUDA：11.8

**Comment by cuicheng01** [comment]
默认不保存，可以查看[目标检测产线文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/cv_pipelines/object_detection.md)，里边有详细说明。具体你的问题，可以增加`--save_path`解决，文档中有描述～

**Comment by AngHooVen** [comment]
@cuicheng01 hello，我查看了目标检测产品文档，尝试了输入几种保存指令，但是均报错了。我想保存效果图在本地路径“ D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg”下，下面我是尝试了3个指令都是错误的，不知道正确的指令应该是怎样的。
1 paddleX export --save_dir [D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg]

2 paddleX [-- save_path D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg]

3 paddleX -- save_path D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg

**Comment by AngHooVen** [comment]
![image](https://github.com/user-attachments/assets/ded888ba-1975-414e-8cc9-ba0980195d34)
想把类似这样的运行结果打印在图像上的效果图保存到本地查看

**Comment by liu-jiaxuan** [comment]
paddlex --pipeline semantic_segmentation --input D:\DeepLearning\PaddleX\image\general_image_classification_001.jpg --device gpu:0 --save_path D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg

**Comment by cuicheng01** [comment]
> @cuicheng01 hello，我查看了目标检测产品文档，尝试了输入几种保存指令，但是均报错了。我想保存效果图在本地路径“ D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg”下，下面我是尝试了3个指令都是错误的，不知道正确的指令应该是怎样的。 1 paddleX export --save_dir [D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg]
> 
> 2 paddleX [-- save_path D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg]
> 
> 3 paddleX -- save_path D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg

这些命令不是paddlex的行为，可以看下文档哈

**Comment by AngHooVen** [comment]
稍作修改已正确导出结果图片；
paddlex --pipeline image_classification --input D:\DeepLearning\PaddleX\image\general_image_classification_001.jpg --device gpu:0 --save_path D:\DeepLearning\PaddleX\image\general_image_classification_Result



> paddlex --pipeline semantic_segmentation --input D:\DeepLearning\PaddleX\image\general_image_classification_001.jpg --device gpu:0 --save_path D:\DeepLearning\PaddleX\image\general_image_classification_Result.jpg
