### ISSUE TITLE
产线训练的模型可以用于paddlex吗

### ISSUE THREAD

**Issue by fightingshao** [PaddlePaddle/PaddleX#2295]
老师，产线训练的目标识别，离线导出部署包，不可以直接用于from paddlex import create_pipeline, create_model吗？

**Comment by Sunting78** [comment]
是可以的，云端基础产线的模型可以使用。但是可能模型权重中配置文件需要一定改动。比如添加 
Global:
  model_name: xxx

**Comment by fightingshao** [comment]
可以用了，非常感谢

**Comment by cuicheng01** [comment]
@fightingshao 星河社区的零代码产线正在升级中，预计升级完二者就完全一致了，到时候是可以无缝切换的，升级完回复你

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
