### ISSUE TITLE
高性能推理插件的安装完成后，使用PaddleX Python API联网激活或者服务化部署报错

### ISSUE THREAD

**Issue by jiangshanwe** [PaddlePaddle/PaddleX#2297]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 部署文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#5-%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)

## 复现

1. c++部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

2. c#部署方式

    * 您是否按照文档教程已经正常运行我们提供的[demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy)？

    * 您是否在demo基础上修改代码内容？还请您提供运行的代码

    * 如果c# demo无法正常运行，c++ [demo](https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/cpp/demo)是否已经正常运行？

3. 您使用的**模型**和**数据集**是？

4. 请提供您出现的报错信息及相关log

demo python文件内容如下：

λ localhost /paddle cat demo2.py
from paddlex import create_pipeline

pipeline = create_pipeline(pipeline="OCR", device="cpu",use_hpip=True, serial_number="79FB-C0E3-4141-A317")

output = pipeline.predict("general_ocr_002.png")
for res in output:
    res.print()
    res.save_to_json(save_path="./output/", ensure_ascii=True)
    res.save_to_img("./output/")

报错内容如下：

λ localhost /paddle python demo2.py 
Traceback (most recent call last):
  File "/paddle/demo2.py", line 3, in <module>
    pipeline = create_pipeline(pipeline="OCR", device="cpu",use_hpip=True, serial_number="79FB-XXXX-FFFF-ZZZZ")
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/__init__.py", line 110, in create_pipeline
    return create_pipeline_from_config(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/__init__.py", line 85, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/usr/local/lib/python3.10/dist-packages/paddlex/inference/pipelines/base.py", line 39, in _patched___init__
    ret = ctx.run(init_func, self, *args, **kwargs)
TypeError: OCRPipeline.__init__() got an unexpected keyword argument 'serial_number'

参考文档如下：

![image](https://github.com/user-attachments/assets/295ba830-f345-4251-9850-6216cc737586)

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号

使用的 docker 方式部署：
镜像版本：registry.baidubce.com/paddlepaddle/paddle:3.0.0b1
在容器内通过：pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl 安装了paddlex，然后执行：curl -s https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py | python3.10 - --arch x86_64 --os linux --device cpu --py 310

3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

Linux Centos 7

5. 请问您使用的CUDA/cuDNN的版本号是？

无，使用的 CPU

**Comment by Bobholamovic** [comment]
不好意思，这里的文档有误，我们将尽快修正～ 使用方式应该是：

```python
from paddlex import create_pipeline

pipeline = create_pipeline(
    pipeline="image_classification",
    use_hpip=True,
    hpi_params={"serial_number": "{序列号}"},
)
```

**Comment by jiangshanwe** [comment]
现在有新的报错了（python代码运行）：RuntimeError: FastDeploy initalized failed! Error: libcudart.so.11.0: cannot open shared object file: No such file or directory
![image](https://github.com/user-attachments/assets/c37cec51-71d2-4e5d-a48b-1de735e51700)
直接用服务化方式，也有类似的报错：
![image](https://github.com/user-attachments/assets/56a8f71a-e3ce-4005-9f92-9522d79ef6c7)

**Comment by Bobholamovic** [comment]
请确认环境是否与安装的高性能推理插件版本匹配：
<img width="964" alt="image" src="https://github.com/user-attachments/assets/6e38a2db-82d2-4b3b-aa80-108721993581">

**Comment by jiangshanwe** [comment]
> 请确认环境是否与安装的高性能推理插件版本匹配： <img alt="image" width="964" src="https://private-user-images.githubusercontent.com/21275753/379538911-6e38a2db-82d2-4b3b-aa80-108721993581.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDMwNTIsIm5iZiI6MTcyOTc0Mjc1MiwicGF0aCI6Ii8yMTI3NTc1My8zNzk1Mzg5MTEtNmUzOGEyZGItODJkMi00YjNiLWFhODAtMTA4NzIxOTkzNTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA0MDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NDY0Y2YwZTc4NmI5MjhmODkwODFiMGNlNDkyYWI4MjdlZDBkMzAwYWE1NDJmOGIwNjM5ZGMxODYwZjk2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gAajUopUzUG69ZMOCrKaKYgyECsEfBv8RhyM-ib8W74">

你这个恢复的是报错的问题，还是cpu使用率的问题。这个问题下，咱们专门讨论报错的问题吧。我用的cpu版本，镜像版本：registry.baidubce.com/paddlepaddle/paddle:3.0.0b1
在容器内通过：pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl 安装了paddlex，然后执行：curl -s https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py | python3.10 - --arch x86_64 --os linux --device cpu --py 310

**Comment by Bobholamovic** [comment]
收到！如果使用cpu版本的话，理论上不应该依赖libcudart。这可能是一个bug，我们排查下，感谢反馈～

**Comment by Bobholamovic** [comment]
> 收到！如果使用cpu版本的话，理论上不应该依赖libcudart。这可能是一个bug，我们排查下，感谢反馈～

这个bug应该已经修复了～ 请尝试卸载重装高性能推理插件：

```bash
pip uninstall paddlex-hpi
curl -s https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py | python3.10 - --arch x86_64 --os linux --device cpu --py 310
```

**Comment by jiangshanwe** [comment]
好像还不行呢，我在镜像 registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b1-paddlepaddle3.0.0b1-cpu 的容器中操作的
![image](https://github.com/user-attachments/assets/a1e82e1d-0ddb-4f3b-9585-6f2ebb8537f9)

**Comment by zhang-prog** [comment]
我们修复bug时更新了FD的包，看样子是没有重新安装最新的FD，可以执行下面命令重装下～
```
pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/pkgs/241017/fastdeploy_python-0.0.0.0.0.0-cp310-cp310-linux_x86_64.whl --force-reinstall --no-deps
```

**Comment by jiangshanwe** [comment]
新的报错 
![image](https://github.com/user-attachments/assets/748724db-29e1-4be9-a43a-f4fa07fdb475)

**Comment by zhang-prog** [comment]
我看你上面手动卸载了paddlex-hpi？重装FD不需要卸载paddlex-hpi的，执行下面命令安装一下paddlex-hpi吧。
```
curl -s https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py | python3.10 - --arch x86_64 --os linux --device cpu --py 310
```

**Comment by jiangshanwe** [comment]
安装之后，还是之前的报错（已经执行过了）。![image](https://github.com/user-attachments/assets/6b086422-e6de-4ab0-8f93-9946635d798b)


> 我们修复bug时更新了FD的包，看样子是没有重新安装最新的FD，可以执行下面命令重装下～
> 
> ```
> pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/pkgs/241017/fastdeploy_python-0.0.0.0.0.0-cp310-cp310-linux_x86_64.whl --force-reinstall --no-deps
> ```

**Comment by zhang-prog** [comment]
你重装FD的时候用的是缓存的whl，没有安装最新的whl（因为名字相同）。把缓存里的whl删除，再重新安装FD。
![image](https://github.com/user-attachments/assets/1e96027c-c4de-4dee-a7a8-81abe95c493e)

```
pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/pkgs/241017/fastdeploy_python-0.0.0.0.0.0-cp310-cp310-linux_x86_64.whl --force-reinstall --no-deps
```

**Comment by zhang-prog** [comment]
可以参考下面删除缓存的方式，使用 `pip cache dir` 看缓存路径，然后删除该路径下所有文件。一般路径会在 `/root/.cache/pip`：
```
pip cache dir
cd /root/.cache/pip 
rm -rf *
```

**Comment by jiangshanwe** [comment]
新的报错
![image](https://github.com/user-attachments/assets/d4e2e016-7480-47c8-94ee-89a1424d9f08)

**Comment by zhang-prog** [comment]
你现在使用的 PaddleX 项目应该不是最新版的，执行下面命令更到最新版本：
```
git pull
pip install -e .
```

**Comment by jiangshanwe** [comment]
我用的docker镜像安装呢

**Comment by zhang-prog** [comment]
镜像里不是最新的PaddleX，因为我们近期修复了少许bug，还未来得及重新打镜像。后续我们会更新镜像，现在麻烦手动升级一下吧～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
