### ISSUE TITLE
OCR版面识别问题

### ISSUE THREAD

**Issue by whwususu** [PaddlePaddle/PaddleX#2298]
请问下，版面分析模型的训练方法我看了半天不得其解，都是提供了各种数据集进行训练，而不是自定义训练集。那么有不有例如通过打标的方式，生成自己的训练集，然后进行训练的。
这个是我看的教程。https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md
谢谢！

**Comment by cuicheng01** [comment]
你是希望通过自己的数据集来训练时吧？可以参考这个文档的二次开发部分https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/layout_detection.md

**Comment by whwususu** [comment]
> 你是希望通过自己的数据集来训练时吧？可以参考这个文档的二次开发部分https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/layout_detection.md

嗯，我看了您发给我的这个地址，那么标注的过程也是通过Labelme或者PaddleLabel实现的吧？
例如这个地址：https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/data_annotations/cv_modules/object_detection.md

**Comment by cuicheng01** [comment]
是的，本质上是一个目标检测的模型，所以凡是可以标注目标检测的工具，都可以的

**Comment by whwususu** [comment]
> 是的，本质上是一个目标检测的模型，所以凡是可以标注目标检测的工具，都可以的
按照说明，我创建了数据集，并且执行了检测命令，报告正常，然后我执行了训练命令
![image](https://github.com/user-attachments/assets/5ed4fda0-51ed-47da-b1e5-570ae0c3e354)
提示模型没有注册，这是需要我单独下载，放到哪里么？谢谢！

**Comment by cuicheng01** [comment]
应该是没有安装二次开发的插件，你可以查看[安装文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/installation/installation.md)

**Comment by whwususu** [comment]
> 应该是没有安装二次开发的插件，你可以查看[安装文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/installation/installation.md)
 
![image](https://github.com/user-attachments/assets/2724034c-5a39-4cae-bc8f-ccb40515d4a9)
卡死了

**Comment by Sunting78** [comment]
这个应该是机器原因 内存超了

**Comment by whwususu** [comment]
MemoryError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::eager_api_conv2d(_object*, _object*, _object*)
1   conv2d_ad_func(paddle::Tensor const&, paddle::Tensor const&, std::vector<int, std::allocator<int> >, std::vector<int, std::allocator<int> >, std::string, std::vector<int, std::allocator<int> >, int, std::string)
2   paddle::experimental::conv2d(paddle::Tensor const&, paddle::Tensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&)
3   void phi::ConvCudnnKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::string const&, std::vector<int, std::allocator<int> > const&, int, std::string const&, phi::DenseTensor*)
4   void phi::ConvCudnnKernelImplV7<float, phi::GPUContext>(phi::DenseTensor const*, phi::DenseTensor const*, phi::GPUContext const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, phi::backends::gpu::DataLayout, phi::backends::gpu::DataLayout, bool, bool, int, phi::DenseTensor*)
5   phi::DnnWorkspaceHandle::ReallocWorkspace(unsigned long)
6   paddle::memory::allocation::Allocator::Allocate(unsigned long)
7   paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
8   paddle::memory::allocation::Allocator::Allocate(unsigned long)
9   paddle::memory::allocation::Allocator::Allocate(unsigned long)
10  paddle::memory::allocation::Allocator::Allocate(unsigned long)
11  paddle::memory::allocation::Allocator::Allocate(unsigned long)
12  paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
13  std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
14  common::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:




麻烦您看下，我换成了3090显卡，还是不行，有不有参数调下参数，让他训练下去

**Comment by whwususu** [comment]
我们换了一张3090显卡，调整batchsize到1了，还是不行，然后调整了epochs_iters参数到10，可以了。然后拿了样例数据进行了训练，发现训练后的标签还没有训练前的模型多，如果要继承基础模型的标签数据，是不是有什么需要配置的参数啊？谢谢！下面是训练前和训练和的标签比较：
![image](https://github.com/user-attachments/assets/a069aaeb-f617-4d59-ac36-195cece32d6d)
![image](https://github.com/user-attachments/assets/0510d1e4-4153-4553-a39b-9965e914d813)
明显image标签都没有了。

**Comment by Sunting78** [comment]
您好，训练后的类别数量和你训练的数据的类别数量是一致的。只要训练了，类别数量就会根据训练数据而改变。并不是集成原始模型分多少类别的能力，而且原始模型作为预训练模型提供在版面上训练过的权重，能更快收敛。看到您在paddledetection也提问了相同的问题，后续我们在这个issue下沟通吧。

**Comment by whwususu** [comment]
好的，谢谢您！我给您截取下目录关系
![image](https://github.com/user-attachments/assets/cbf9297d-5c86-442b-938a-3dd6a2f9ca10)
![image](https://github.com/user-attachments/assets/b1c7c056-7136-45b7-ac13-3686e9adae9d)
![image](https://github.com/user-attachments/assets/a97e7711-8a0d-460b-8866-8fbd535232ff)
![image](https://github.com/user-attachments/assets/e6ec3988-bcc3-4000-ad13-a6cb7f8c5c64)
这是三个数据集，用的是这个训练命令
python main.py -c paddlex/configs/structure_analysis/RT-DETR-H_layout_17cls.yaml -o Global.mode=train -o Global.dataset_dir=/paddle/PaddleX/dataset/test
推导用的这个命令：
python main.py -c paddlex/configs/structure_analysis/RT-DETR-H_layout_17cls.yaml -o Global.mode=predict -o Predict.model_dir="/paddle/PaddleX/output/best_model/inference" -o Predict.input="layout.jpg"
学习没报错，成功了，用训练后的模型推导，一个也没识别出来。
检测了整个，确实是按照文档https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/layout_detection.md去操作的。
谢谢！
我用官方训练数据进行了训练，评估能够达到45%，但是用这个新的模型进行推理的时候，整个界面依旧没有识别的元素

**Comment by Sunting78** [comment]
您好，看您截图的数据是只有两类是吗？训练后评估集上的指标是多少呢？我看您截图的数据，数量非常小，建议训练版面模型的数据量能至少800张。您训练后的模型保存在这里/paddle/PaddleX/output/best_model/inference 的yaml文件麻烦发一下看看吧。
另外可以用paddlex/configs/structure_analysis/RT-DETR-H_layout_3cls.yaml 配置训练，尝试下看看是否有一样的问题。

**Comment by whwususu** [comment]
> /paddle/PaddleX/output/best_model/inference 的yaml文件

感谢！
我用的官方数据集的名字叫det_layout_examples，训练图片大概90张，测试的大概20张
附件是inference.yaml
[inference.txt](https://github.com/user-attachments/files/17551225/inference.txt)

用RT-DETR-H_layout_3cls.yaml 去训练，也是也一样的，一个都没有识别出来。

**Comment by Sunting78** [comment]
数据太少了，官方给的只是demo数据，用来跑通程序的

**Comment by Sunting78** [comment]
如果你想有效果 可以用这个版面定位打卡营的数据  https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/practical_tutorials/document_scene_information_extraction(layout_detection)_tutorial.md

**Comment by whwususu** [comment]
> 如果你想有效果 可以用这个版面定位打卡营的数据 https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/practical_tutorials/document_scene_information_extraction(layout_detection)_tutorial.md

好的，谢谢!
1、我拿您给我的这个数据进行了训练后，推理还是无法识别出任何对象。

2、还有个问题请教下，我们刚刚对ocr模型进行了训练，数据集也是官方的，然后识别效果如下：
![ec3bf3e5408dc7bb19e9a64c65676ed](https://github.com/user-attachments/assets/375e5ba9-72f8-4305-8132-a5c3395079b9)
感觉都是乱码了，这个有可能是啥原因导致的啊

3、如果多次训练模型，需要多次叠加，我看了下配置中 pretrain_weight_path参数，是否可以采用下图中下划线的权重作为再次训练的基础，谢谢！
![image](https://github.com/user-attachments/assets/eb9d7cf6-59e2-4ef9-9ac6-35ea0a5b389e)
