### ISSUE TITLE
图像训练和预测时的数据增强算子在哪里调整？

### ISSUE THREAD

**Issue by CashBai** [PaddlePaddle/PaddleX#2307]
比如PP-YOLOE_plus-L的模型训练时，我想调节一下数据增强算子，比如我想把RandomSize改成Resize[800,800]
这个应该在哪里修改？我没有找到对应的文档

**Comment by Bobholamovic** [comment]
你好，可以修改这里的配置文件：
https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/paddlex/repo_apis/PaddleDetection_api/configs/PP-YOLOE_plus-L.yaml

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
