### ISSUE TITLE
用Jetson AGX orin做部署时报错module 'paddlex' has no attribute 'deploy'

### ISSUE THREAD

**Issue by Xiaorong-Zh** [PaddlePaddle/PaddleX#2308]
用Jetson AGX orin做部署时报错module 'paddlex' has no attribute 'deploy'，是不是paddlex3.0中去除了deploy函数，应该怎么解决呢？

**Comment by Bobholamovic** [comment]
paddlex 3.0的目录结构有很大改变，例如不再提供`paddlex.deploy`模块。建议可以尝试下 paddlex 3.0的部署方案呢～

**Comment by Xiaorong-Zh** [comment]
> paddlex 3.0的目录结构有很大改变，例如不再提供模块。建议可以尝试下 paddlex 3.0 的部署方案呢~`paddlex.deploy`

那请问一下paddlex3.0下的怎么部署？或者如何在Jetson AGX orin上安装适合paddlex2.0的环境呢，因为Jetson AGX orin自带的jetpack版本较高，无法适配paddlex2.0

**Comment by Bobholamovic** [comment]
可以考虑在Jetson设备上编译paddlepaddle（可参考[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile-by-ninja.html#anchor-0)），然后安装paddlex3.0，之后按照paddlex3.0的文档进行部署～不过，需要注意的是，目前Jetson设备上暂不支持高性能部署。

**Comment by Xiaorong-Zh** [comment]
> 可以考虑在Jetson设备上编译paddlepaddle（可参考[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile-by-ninja.html#anchor-0)），然后安装paddlex3.0，之后按照paddlex3.0的文档进行部署～不过，需要注意的是，目前Jetson设备上暂不支持高性能部署。

那可以发一下Jetson设备上支持的paddleX3.0下的部署文档吗？

**Comment by Bobholamovic** [comment]
paddlex部署文档是一样的哈，只是使用的paddlepaddle不太一样，需要编译jetson专用版本

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
