### ISSUE TITLE
非高性能推理模式下，服务化api调用时，top显示只有一个线程cpu使用率接近100%

### ISSUE THREAD

**Issue by jiangshanwe** [PaddlePaddle/PaddleX#2314]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

直接使用镜像：registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b1-paddlepaddle3.0.0b1-cpu
通过命令：paddlex --serve --pipeline OCR --port 8077 启动服务
通过 top -Hp xxx ，显示如下：
![image](https://github.com/user-attachments/assets/3da32b22-4ff7-4c43-90f0-8e03ecf9f96d)

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

Linux

## 疑问

1. 这是正常的吗？为什么不能完全利用 cpu?
2. 如果部署了高性能推理插件，会改善吗？（因另一个问题：https://github.com/PaddlePaddle/PaddleX/issues/2297 导致尚未成功）

**Comment by jiangshanwe** [comment]
我测试了并发调用api时，top观察现象也是一样的。

**Comment by Bobholamovic** [comment]
你好，目前paddlex的默认服务化部署方案基于 FastAPI，整体上使用协程代替线程处理并发请求，因此可以观察到一个线程的CPU占用率较高。对于同步的模型推理部分代码，会提交到线程池中处理，但由于目前产线推理逻辑并非线程安全的，所以这部分被加了锁，一次只执行一个推理任务，这也能解释为什么图中其他线程的CPU占用率较低。当前的方案主要考虑基础的服务化部署能力，并未充分考虑并发性能。理论上，使用高性能推理插件可以降低单个请求的rt，但对服务的并发性能也不会有改善。后续我们将推出高性能的服务化部署方案，敬请期待～
