### ISSUE TITLE
高性能报错

### ISSUE THREAD

**Issue by zhang19523zhao** [PaddlePaddle/PaddleX#2318]
paddlex --serve --pipeline ./ocr.yaml --port 6007 --serial_number xxxxxx   --update_licens   --use_hpip 
Using official model (PP-OCRv4_server_det), the model files will be be automatically downloaded and saved in /root/.paddlex/official_models.
Traceback (most recent call last):
  File "/usr/local/bin/paddlex", line 8, in <module>
    sys.exit(console_entry())
  File "/root/PaddleX/paddlex/__main__.py", line 28, in console_entry
    code = main()
  File "/root/PaddleX/paddlex/paddlex_cli.py", line 174, in main
    serve(
  File "/root/PaddleX/paddlex/paddlex_cli.py", line 155, in serve
    pipeline = create_pipeline_from_config(
  File "/root/PaddleX/paddlex/inference/pipelines/__init__.py", line 84, in create_pipeline_from_config
    pipeline = BasePipeline.get(pipeline_name)(
  File "/root/PaddleX/paddlex/inference/pipelines/ocr.py", line 36, in __init__
    self._build_predictor(text_det_model, text_rec_model)
  File "/root/PaddleX/paddlex/inference/pipelines/ocr.py", line 43, in _build_predictor
    self.text_det_model = self._create(model=text_det_model)
  File "/root/PaddleX/paddlex/inference/pipelines/base.py", line 44, in _create
    return create_predictor(
  File "/root/PaddleX/paddlex/inference/models/__init__.py", line 77, in create_predictor
    return _create_hp_predictor(
  File "/root/PaddleX/paddlex/inference/models/__init__.py", line 43, in _create_hp_predictor
    from paddlex_hpi.models import HPPredictor
  File "__init__.py", line 2, in init paddlex_hpi.models.__init__
  File "anomaly_detection.py", line 10, in init paddlex_hpi.models.anomaly_detection
  File "base.py", line 28, in init paddlex_hpi.models.base
  File "_auth.py", line 5, in init paddlex_hpi.models._auth
ImportError: cannot import name pipeline_info_list_var

**Comment by Bobholamovic** [comment]
你好，目前暂时请尝试参考这个issue：https://github.com/PaddlePaddle/PaddleX/issues/2297 更新镜像中的paddlex源码～

**Comment by zhang19523zhao** [comment]
可以了，容器里试了那个高性能ocr好像有问题没访问不到/dev/disk/by-uuid 这个

**Comment by zhang19523zhao** [comment]
可以了挂载的时候 -v /dev:/dev

**Comment by zhang19523zhao** [comment]
请求的时候报错
E1028 01:42:18.694365  2342 helper.h:131] 3: [builder.cpp::~Builder::307] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builder.cpp::~Builder::307, condition: mObjectCounter.use_count() == 1. Destroying a builder object before destroying objects it created leads to undefined behavior.
)

**Comment by Bobholamovic** [comment]
请问可以贴一下完整的报错信息吗

**Comment by zhang19523zhao** [comment]
docker run --gpus all --name paddlex2 -v $PWD:/paddle --shm-size=8g  -v /dev:/dev  --network=host -it registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b1-paddlepaddle3.0.0b1-gpu-cuda11.8-cudnn8.6-trt8.5 /bin/bash

# 执行命令
git pull
pip install -e .

curl -s https://paddle-model-ecology.bj.bcebos.com/paddlex/PaddleX3.0/deploy/paddlex_hpi/install_script/latest/install_paddlex_hpi.py | python3.10 - --arch x86_64 --os linux --device gpu_cuda118_cudnn86 --py 310



配置文件
#ocr.yaml
Global:
   pipeline_name: OCR
Pipeline:
  text_det_model: PP-OCRv4_server_det  #可修改为微调后模型的本地路径
  text_rec_model: PP-OCRv4_server_rec  #可修改为微调后模型的本地路径
  text_rec_batch_size: 10
  device: "gpu:0"
  
  #启动命令
  paddlex     --serve --pipeline ./ocr.yaml --port 6005    --use_hpip   --serial_number D7E5-17F6-xxxxx     --update_license
  
  Using official model (PP-OCRv4_server_det), the model files will be be automatically downloaded and saved in /root/.paddlex/official_models.
INFO:root:Create a symbolic link pointing to /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvcaffe_parser.so.8 named /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvcaffe_parser.so.
INFO:root:Create a symbolic link pointing to /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvinfer_plugin.so.8 named /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvinfer_plugin.so.
INFO:root:Create a symbolic link pointing to /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvinfer.so.8 named /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvinfer.so.
INFO:root:Create a symbolic link pointing to /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvonnxparser.so.8 named /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvonnxparser.so.
INFO:root:Create a symbolic link pointing to /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvparsers.so.8 named /usr/local/lib/python3.10/dist-packages/fastdeploy/libs/third_libs/tensorrt/lib/libnvparsers.so.
2024-10-28 02:39:11,556 DEBUG [PADDLEX] 139780482316096 0 licenses loaded
2024-10-28 02:39:11,920 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(170)::PaddleXAuth  License update succeeded.
2024-10-28 02:39:11,926 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
2024-10-28 02:39:11,931 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(185)::PaddleXAuth  Basic authentication succeeded.
2024-10-28 02:39:11,937 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
2024-10-28 02:39:11,941 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(263)::PaddleXAuth  Task authentication succeeded.
[INFO] fastdeploy/runtime/runtime.cc(327)::Init The unencrypted model will be used for inference.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(28)::BuildOption    Will inference_precision float32
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1028 02:39:12.468488   185 gpu_resources.cc:119] Please NOTE: device: 1, GPU Compute Capability: 8.6, Driver API Version: 12.4, Runtime API Version: 11.8
W1028 02:39:12.469617   185 gpu_resources.cc:164] device: 1, cuDNN Version: 8.9.
[INFO] fastdeploy/runtime/runtime.cc(474)::CreatePaddleBackend  Runtime initialized with Backend::PDINFER in Device::GPU.
Using official model (PP-OCRv4_server_rec), the model files will be be automatically downloaded and saved in /root/.paddlex/official_models.
Connecting to https://paddle-model-ecology.bj.bcebos.com/paddlex/official_inference_model/paddle3.0b1_v2/PP-OCRv4_server_rec_infer.tar ...
Downloading PP-OCRv4_server_rec_infer.tar ...
[==================================================] 100.00%
Extracting PP-OCRv4_server_rec_infer.tar
[==================================================] 100.00%
2024-10-28 02:39:17,784 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(170)::PaddleXAuth  License update succeeded.
2024-10-28 02:39:17,790 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
2024-10-28 02:39:17,796 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(185)::PaddleXAuth  Basic authentication succeeded.
2024-10-28 02:39:17,801 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
2024-10-28 02:39:17,806 DEBUG [PADDLEX] 139780482316096 License [D7E5-17F6-...] is permanently valid, skip check local time 
[INFO] fastdeploy/runtime/runtime.cc(263)::PaddleXAuth  Task authentication succeeded.
[INFO] fastdeploy/runtime/runtime.cc(327)::Init The unencrypted model will be used for inference.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(28)::BuildOption    Will inference_precision float32
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(67)::BuildOption    Will try to use tensorrt inference with Paddle Backend.
[WARNING] fastdeploy/runtime/backends/paddle/paddle_backend.cc(79)::BuildOption Detect that tensorrt cache file has been set to /root/.paddlex/official_models/PP-OCRv4_server_rec/trt_serialized.trt, but while enable paddle2trt, please notice that the cache file will save to the directory where paddle model saved.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(541)::GetDynamicShapeFromOption     x: the max shape = [1, 3, 48, 320], the min shape = [1, 3, 48, 320], the opt shape = [1, 3, 48, 320]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(504)::SetTRTDynamicShapeToConfig    Start setting trt dynamic shape.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(506)::SetTRTDynamicShapeToConfig    Finish setting trt dynamic shape.
[WARNING] fastdeploy/runtime/backends/paddle/paddle_backend.cc(170)::BuildOption        Currently, Paddle-TensorRT does not support the new IR, and the old IR will be used.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(276)::InitFromPaddle        Start generating shape range info file.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [save_optimized_model_pass]
--- Running analysis [ir_graph_to_program_pass]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(541)::GetDynamicShapeFromOption     x: the max shape = [1, 3, 48, 320], the min shape = [1, 3, 48, 320], the opt shape = [1, 3, 48, 320]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(308)::InitFromPaddle        Finish generating shape range info file.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(310)::InitFromPaddle        Start loading shape range info file /root/.paddlex/official_models/PP-OCRv4_server_rec/shape_range_info.pbtxt to set TensorRT dynamic shape.
W1028 02:39:21.582825   185 place.cc:242] The `paddle::PlaceType::kCPU/kGPU` is deprecated since version 2.3, and will be removed in version 2.4! Please use `Tensor::is_cpu()/is_gpu()` method to determine the type of place.
  [INFO] fastdeploy/runtime/runtime.cc(474)::CreatePaddleBackend  Runtime initialized with Backend::PDINFER in Device::GPU.
Batch size updated to 10
INFO:     Started server process [48]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6005 (Press CTRL+C to quit)

  ##上面起来后请求
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1028 02:43:34.175040  2343 helper.h:131] 3: [builder.cpp::~Builder::307] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builder.cpp::~Builder::307, condition: mObjectCounter.use_count() == 1. Destroying a builder object before destroying objects it created leads to undefined behavior.
)

![QQ_1730083441357](https://github.com/user-attachments/assets/5353585c-0a50-4d0d-b800-9ed006e0b83d)
![QQ_1730083453772](https://github.com/user-attachments/assets/3fda50af-8e09-40a3-a440-86857d763739)

**Comment by Bobholamovic** [comment]
看起来在当前环境中使用pptrt后端跑当前模型可能有点儿问题，请参考高性能推理文档中的说明，尝试为更换后端为`paddle_infer`～

**Comment by zhang19523zhao** [comment]
我看模型好像就是用的这个哦
![Uploading QQ_1730086571892.png…]()

**Comment by zhang19523zhao** [comment]
![QQ_1730086571892](https://github.com/user-attachments/assets/bd10e73b-4ceb-41a0-8cb5-2efd02c04305)

**Comment by zhang19523zhao** [comment]
可以了rec 的不是已经正常了

**Comment by Bobholamovic** [comment]
> 可以了rec 的不是已经正常了

请问是什么意思哦？

**Comment by zhang19523zhao** [comment]
paddle_infer 改成这个可以了

**Comment by Bobholamovic** [comment]
好的。考虑到问题已经解决，我将先关闭这个issue。后续如果有其他问题，欢迎继续提issue～

**Comment by zhang19523zhao** [comment]
我测了下好像高性能的还没普通的快呢

**Comment by zhang19523zhao** [comment]
高性能
![QQ_1730427550026](https://github.com/user-attachments/assets/6503d1b6-7a49-4a8c-8d7c-f803684c4ce3)

普通
![企业微信截图_153079ef-f0f3-4e52-bce5-deeb55275601](https://github.com/user-attachments/assets/96bc80fd-a10c-4fe2-b03d-72e9547cd464)
