### ISSUE TITLE
paddleX 容器中，服务化启动失败

### ISSUE THREAD

**Issue by jiangshanwe** [PaddlePaddle/PaddleX#2319]
镜像版本：registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b1-paddlepaddle3.0.0b1-gpu-cuda12.3-cudnn9.0-trt8.6
通过 host 模式启动：docker run -d --gpus all --name paddlex -v $PWD:/paddle --shm-size=8g --network=host -it registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b1-paddlepaddle3.0.0b1-gpu-cuda12.3-cudnn9.0-trt8.6
在容器内部执行：
![image](https://github.com/user-attachments/assets/f32ba2cf-eaed-45cb-8817-0c187ddc061b)

通过docker inspect 发现设置了代理：

![image](https://github.com/user-attachments/assets/4c51698c-04da-4576-a08b-1472c370bb05)

**Comment by Bobholamovic** [comment]
@changdazhou 辛苦看看这个问题

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
