### ISSUE TITLE
调用paddlex印章识别产线报错

### ISSUE THREAD

**Issue by wujf147** [PaddlePaddle/PaddleX#2323]
1、使用编写的脚本调用paddlex函数报错，提示没有predict函数

![image](https://github.com/user-attachments/assets/1b63988c-a03c-488b-a9b8-68119ead40d0)

**Comment by ysyuann** [comment]
您可以执行pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl命令重新安装paddlex的wheel包后执行图中命令（详细安装信息可参考https://github.com/PaddlePaddle/PaddleX/blob/5029b5053d82b9acfd4b0b6e57c3a58773224504/docs/installation/installation.md）。
