### ISSUE TITLE
验证印章识别产线的问题

### ISSUE THREAD

**Issue by wujf147** [PaddlePaddle/PaddleX#2324]
## Checklist:
在使用印章产线识别时，有以下问题：
1、安装paddlex后，在虚拟环境中运行paddlex --pipeline seal_recognition提示无法识别paddlex  
2、用脚本对印章产线进行识别时，使用create_pipeline()方法后，此方法没有predict方法，请问是什么原因？

**Comment by TingquanGao** [comment]
1. paddlex是如何安装的呢？
2. 是否方便贴一下代码和报错的截图？

**Comment by wujf147** [comment]
老师您好，有如下问题：我是根据paddlex README文档中第二步安装paddlex并检查虚拟环境可以import paddlex
![image](https://github.com/user-attachments/assets/85a11603-a057-4a78-9884-d7e572bb1e84)
但是在虚拟环境命令行运行paddlex命令时报错，如下：
![image](https://github.com/user-attachments/assets/bddf98a8-8cd4-4241-bc52-dd2d855c226f)

**Comment by wujf147** [comment]
问题二：在使用脚本运行官方示例时，出现报错，结果对象可以正常输出
![image](https://github.com/user-attachments/assets/c4369217-5c34-4e3b-a1c0-3cd470651c7c) 
问题如下：
![Uploading image.png…]()

我在网上查看到的是paddle和paddlex循环引用导致的问题，请老师帮忙看看

**Comment by TingquanGao** [comment]
我这边没能复现该问题，我是在Linux机器上运行的。想问下：1. 你安装的paddle版本是多少？2. “结果对象可以正常输出”是什么意思？3. “在网卡查看到是paddle和paddlex循环引用导致的问题”，具体是在哪里看到的呢？

**Comment by wujf147** [comment]
老师您好，针对您提的问题回答如下：
1、复现问题，在pycharm终端的虚拟环境中运行paddlex报错
![dc8eea02dec94fd8eb3efc7c53cc2b3](https://github.com/user-attachments/assets/a35b953b-4f55-4517-aff4-342a08e0e166)
2、paddle及paddlex版本：
![09867f7cccd4e55ce12584f2c19fec0](https://github.com/user-attachments/assets/cb016c0f-1cd7-4a3c-97f9-d742dea08e15)
3、结果对象正常输出，即output可以看到对象结果，但是打印outpu内容时报错了，以下为运行脚本的截图
![2edf2108c9008d52a77ca5fedb229a1](https://github.com/user-attachments/assets/b79fd71c-3248-4b03-a89b-bf49777d9b57)
![73449653f75e93c8124aa874a2107a5](https://github.com/user-attachments/assets/a4456497-37bb-4bbf-8741-af42b4285ddd)
![81f6a4872ac0734c9726e006bc6c93a](https://github.com/user-attachments/assets/558825df-8739-4981-92cb-910388bdd60a)
![a5e227c61997a7284f01fbde6adcdfa](https://github.com/user-attachments/assets/f6c9b7dc-0bb5-4f8d-95cd-bddda2331428)
4、报错问题搜索解决方案（但未解决）：
![image](https://github.com/user-attachments/assets/8883dc51-b90f-4655-9d22-a85a85fc7120)
请老师帮忙看看是否是paddle版本问题或是其他原因，谢谢！

**Comment by TingquanGao** [comment]
收到。
问题1：想问下你安装paddlex和运行paddlex是在同一个命令环境中吗？还是说在不同终端？如果在不同终端的话，是可能存在找不到运行命令，需要修改环境变量，否则可能找不到可执行文件；
问题2、3、4：paddlepaddle版本需要升级，目前PaddleX推荐使用PaddlePaddle 3.0.0b1版本，2.3.2太老了；

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
