### ISSUE TITLE
印章检测模型格式问题

### ISSUE THREAD

**Issue by wujf147** [PaddlePaddle/PaddleX#2325]
请问在inference/utils/official_model.py官方链接中下载的印章检测模型seal_server_infer.tar解压后是一个infer文件，请问怎么转换为常用的这几个文件呢
![Uploading image.png…]()

**Comment by TingquanGao** [comment]
是从哪个文档的什么位置看到的下载链接？可以贴一下您下载的官方链接吗？我们检查一下。

**Comment by wujf147** [comment]
老师您好，今天运行demo脚本可以正常下载模型文件了，里面包含了pdmodel等文件

**Comment by TingquanGao** [comment]
好的，那该issue我就先close了，如有问题可以reopen或new issue。
