### ISSUE TITLE
windows下报错找不到KeyError: 'Global'

### ISSUE THREAD

**Issue by xiaomujiang** [PaddlePaddle/PaddleX#2348]
## 描述问题
运行官方代码报错 找不到KeyError: 'Global'
from paddlex import create_model
model = create_model("PP-OCRv4_mobile_det")
output = model.predict("general_ocr_001.png", batch_size=1)
for res in output:
    res.print(json_format=False)
    res.save_to_img("./output/")
    res.save_to_json("./output/res.json")

## 复现
window10  paddlex最新版本 

  

3. 您使用的**模型**和**数据集**是？
 model = create_model("PP-OCRv4_mobile_det")

5. 请提供您出现的报错信息及相关log
6. (paddlex30beta) D:\lanrenjingling\script\PaddleX>python det.py
Using official model (PP-OCRv4_mobile_det), the model files will be be automatically downloaded and saved in 
Traceback (most recent call last):
  File "D:\script\PaddleX\det.py", line 2, in <module>
    model = create_model("PP-OCRv4_mobile_det")
  File "D:\script\PaddleX\paddlex\model.py", line 29, in create_model
    return _ModelBasedInference(model, *args, **kwargs)
  File "D:\script\PaddleX\paddlex\model.py", line 57, in __init__
    self._predictor = create_predictor(*args, **kwargs)
  File "D:\lanrenjingling\script\PaddleX\paddlex\inference\models\__init__.py", line 76, in create_predictor
    model_name = config["Global"]["model_name"]
KeyError: 'Global'

## 环境

1. 如果您使用的是python部署方式，请提供您使用的PaddlePaddle、PaddleX版本号、Python版本号
paddlepaddle-gpu          3.0.0b1
paddlex                   3.0.0b1
python是3.10.13

3. 请提供您使用的操作系统信息，Windows

4. 请问您使用的CUDA/cuDNN的版本号是？
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 9
#define CUDNN_PATCHLEVEL 7

**Comment by moonlightnoodles** [comment]
您好，请问是怎么解决的？
