### ISSUE TITLE
demo结果问题

### ISSUE THREAD

**Issue by lyc728** [PaddlePaddle/PaddleX#2349]
你好，关于demo的结果 我想问下 英文是没有文档标题吗？正文上面的应该是标题吧，
还有推理的时候显示这种问题， 我安装了paddle-gpu有各种问题 后面是直接安装的paddle

E1029 10:50:45.851501 136077 analysis_config.cc:126] Please use PaddlePaddle with GPU version.
E1029 10:50:49.604138 136077 analysis_config.cc:126] Please use PaddlePaddle with GPU version.

<img width="344" alt="企业微信截图_17301706377553" src="https://github.com/user-attachments/assets/7c692411-4cf1-42da-861e-790273385335">

**Comment by liuhongen1234567** [comment]
请问您用的是哪个版面区域检测模型呢？

**Comment by lyc728** [comment]
RT-DETR-H_layout_17cls

**Comment by liuhongen1234567** [comment]
您好，RT-DETR-H_layout_17cls 是支持段落标题的，不过目前标题必需带有1，2，3 或a，b，c之类的编号，比如这张图 
![01 (1)](https://github.com/user-attachments/assets/6588b21c-ed12-4a58-84fa-e0121ecb4d66)
就可以识别出来
![01 (2)](https://github.com/user-attachments/assets/fed12953-0dbe-4c7b-aa11-eaf503954f98)
识别出来的段落标题是paragraph title类别。如果您想要支持这种无编号的case，可以针对自己的数据集进行微调

**Comment by lyc728** [comment]
这是你们demo里面的展示 那你们把例子可以修改下
https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/layout_detection.md

**Comment by liuhongen1234567** [comment]
好的，感谢反馈🙏

**Comment by lyc728** [comment]
你好 关于RT-DETR-H_layout_17cls这个模型，有对应的开源数据集吗？或者现在有相关公开的数据集吗？

**Comment by liuhongen1234567** [comment]
您好，RT-DETR-H_layout_17cls 使用的是内部私有数据集，数据集不对外开源。

**Comment by liuhongen1234567** [comment]
其他公开数据集可以参考 https://github.com/PaddlePaddle/PaddleOCR/blob/ba7081179ff3c8e07c03dba99d2af62071e25162/docs/ppstructure/model_train/train_layout.md

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
