### ISSUE TITLE
预训练模型如何保留原来的标签 

### ISSUE THREAD

**Issue by quqianlong** [PaddlePaddle/PaddleX#2351]
[#630](https://github.com/PaddlePaddle/PaddleX/issues/630#issue-834330103)

PaddleX 现在是否支持模型增量训练?

**Comment by cuicheng01** [comment]
目前不支持增量训练，您可以考虑混合之前的数据一起训练

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
