### ISSUE TITLE
文档场景信息抽取v3产线 使用示例代码运行不成功

### ISSUE THREAD

**Issue by freezehe** [PaddlePaddle/PaddleX#2357]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
如题，我在windows系统和linux系统（centos7）使用示例代码运行不成功
windows 截图1-示例代码1
![image](https://github.com/user-attachments/assets/a42be9de-b80e-4101-88e3-09ab66240ca2)
截图2-示例代码2
![image](https://github.com/user-attachments/assets/fcb78d0c-7389-43e8-be29-02c53888ace7)

我是在windows系统上使用conda 创建了一个干净的paddlex 环境，python=3.10，
我的库的版本
![image](https://github.com/user-attachments/assets/64c45b28-0850-48e1-8588-fedc9c755a8f)

我是使用cpu模式的，linux和windows上都是cpu

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by freezehe** [comment]
补充描述一下问题，windows上pycharm运行，一直卡着不动，一直没有出结果。我使用两种方式，ak和sk 还有accesstoken都不行，请帮我解决一下谢谢，公司项目最近在使用这个paddlex做调研

**Comment by cuicheng01** [comment]
如果没有报错，卡着不动是不是因为文字内容比较多，大模型交互时间比较长？多大的PDF呢？

**Comment by cuicheng01** [comment]
还有一点是，目前默认的视觉模型，本身也不小，如果你的推理设备本身不是GPU，可能也比较慢，需要等一等

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
