### ISSUE TITLE
文档场景信息抽取v3产线 服务端部署，postman调用api报错

### ISSUE THREAD

**Issue by freezehe** [PaddlePaddle/PaddleX#2358]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX API文档说明](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
如题，我是在linux上部署了服务，部署命令是
paddlex --serve --pipeline ./my_path/PP-ChatOCRv3-doc.yaml
因为我的配置文件配置了ak和sk
postman调用api，已经将pdf文件转为了base64字符串
![image](https://github.com/user-attachments/assets/361f0cd6-b41b-4b3b-aa8d-05afd81f257c)
后台日志报错：
![image](https://github.com/user-attachments/assets/eeff60e5-219c-40dc-9137-331f0b5cc1cf)

paddlex 版本如下
![image](https://github.com/user-attachments/assets/f0ca2e45-29d3-45f9-ad5e-8108d37363cf)

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by changdazhou** [comment]
是使用PaddleX源码安装的吗，有测试过图片可以不

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
