### ISSUE TITLE
接口文档错误-图像异常检测产线

### ISSUE THREAD

**Issue by enryteam** [PaddlePaddle/PaddleX#2370]
![局部截取_20241031_173108](https://github.com/user-attachments/assets/4d3ca3a0-5e53-4847-9064-c9ea6e341c54)

问题 /anomaly-detection 应该为 /image-anomaly-detection

https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/cv_pipelines/image_anomaly_detection.md

**Comment by Bobholamovic** [comment]
你好，感谢反馈，我们将尽快修复这个问题

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by Bobholamovic** [comment]
你好，抱歉没有及时回复，这个问题应该已经修复了～
