### ISSUE TITLE
数据标注库paddlelabel数据集格式以及paddleX训练模型保存有误

### ISSUE THREAD

**Issue by luguoyixiazi** [PaddlePaddle/PaddleX#2373]
#### 目录树：
```
│  best_model.info.json
│  best_model.pdopt
│  best_model.pdparams
│  best_model.pdstates
│
├─best_model
│      model.pdparams
│
└─inference
        inference.yml
```
## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
  基于文档代码训练
2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
  否

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
  paddlex                           3.0.0b1
  paddleclas                        2.6.0
  paddlelabel                       1.0.1
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
  Windows
3. 请问您使用的Python版本是？
  3.10
4. 请问您使用的CUDA/cuDNN的版本号是？
  12.1

**Comment by luguoyixiazi** [comment]
paddlelabel应该是没同步更新，模型保存初步怀疑是路径有中文所以寄了，换了全英文路径能保存了

**Comment by Bobholamovic** [comment]
抱歉，paddlelabel目前暂时还没有适配PaddleX要求的格式，使用paddlelabel得到的标注数据需要经过手工调整格式才可以在PaddleX中使用；
对于模型保存的问题，请问你在训练日志中有观察到一些异常的错误信息嘛？

**Comment by luguoyixiazi** [comment]
> 抱歉，paddlelabel目前暂时还没有适配PaddleX要求的格式，使用paddlelabel得到的标注数据需要经过手工调整格式才可以在PaddleX中使用； 对于模型保存的问题，请问你在训练日志中有观察到一些异常的错误信息嘛？

    没有报错，日志输出显示已保存pdiparams，但是中文名路径保存会缺失pdiparams文件但是有pdparams、pdstates、pdopt文件，以及文档中没有提及pdmodel文件的来源，是通过下载的还是生成的？生成是靠paddlex的export还是说自己导模型的类？

    以及paddlex使用paddlex --install安装模块后不会自动更新对应OFFICIAL_MODELS以及模型对应的类吗？我看模型下载路径资源是存在的，但是在official_models.py里面没有更新进去，以及模型的类定义也有缺失，例如我试了PicoDet-L_layout_17cls，此模型没有被更新进去，但是PicoDet-L_layout_3cls是在的

**Comment by luguoyixiazi** [comment]
> 抱歉，paddlelabel目前暂时还没有适配PaddleX要求的格式，使用paddlelabel得到的标注数据需要经过手工调整格式才可以在PaddleX中使用； 对于模型保存的问题，请问你在训练日志中有观察到一些异常的错误信息嘛？


没有报错，日志输出显示已保存pdiparams，但是中文名路径保存会缺失pdiparams文件但是有pdparams、pdstates、pdopt文件，以及文档中没有提及pdmodel文件的来源，是通过下载的还是生成的？生成是靠paddlex的export还是说自己导模型的类？我翻了一下paddle.jit的api，save不会保存pdmodel

以及paddlex使用paddlex --install安装模块后不会自动更新对应OFFICIAL_MODELS以及模型对应的类吗？我看模型下载路径资源是存在的，但是在official_models.py里面没有更新进去，以及模型的类定义也有缺失，例如我试了PicoDet-L_layout_17cls，此模型没有被更新进去，但是PicoDet-L_layout_3cls是在的

**Comment by Bobholamovic** [comment]
对于模型训练阶段导出静态图格式模型的问题，以及与之相关的使用中文路径程序实际行为不符合预期的问题，一会我请熟悉的同学来帮忙看看～

对于paddlex安装模块后更新模型对应的类的问题，我理解如果**对应的模块被安装成功**，且**使用的paddlex版本支持相应的模型**，那么该模型应该就可以被使用。如果无法使用，最有可能的原因是模块安装存在问题，建议可以尝试重新安装。

**Comment by TingquanGao** [comment]
1. paddleX训练PP-HGNetV2-B4，自动保存没有inference.pdmodel

训练命令还有训练日志方便提供下吗？我们排查一下

**Comment by luguoyixiazi** [comment]
> 1. paddleX训练PP-HGNetV2-B4，自动保存没有inference.pdmodel
> 
> 训练命令还有训练日志方便提供下吗？我们排查一下

这个问题在paddle那边回复了，说是paddle新版本不再保存pdmodel
https://github.com/PaddlePaddle/Paddle/issues/69128

**Comment by TingquanGao** [comment]
但是你提供的目录树中，也没有inference.json文件呀。而且PaddleX目前应该还是默认导出inference.pdmodel文件的。所以我觉得这里还是不符合预期的。

**Comment by luguoyixiazi** [comment]
> 但是你提供的目录树中，也没有inference.json文件呀。而且PaddleX目前应该还是默认导出inference.pdmodel文件的。所以我觉得这里还是不符合预期的。

不好意思，我目录下面东西放的有点多，所以只是摘了这一部分，当时不知道inference.json的作用，所以没放进去，以为只需要放这几个文件，后面paddle那边回复了才知道改了不用pdmodel，inference.json是有的

**Comment by TingquanGao** [comment]
所以现在没问题了是么？不过用paddlex训练模型的话，默认是保存pdmodel文件的，不会保存json文件。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
