### ISSUE TITLE
高性能还没普通版本的快吗

### ISSUE THREAD

**Issue by zhang19523zhao** [PaddlePaddle/PaddleX#2376]
# docker 镜像 
registry.baidubce.com/paddlex/paddlex:paddlex3.0.0b1-paddlepaddle3.0.0b1-gpu-cuda11.8-cudnn8.6-trt8.5

# 高性能启动方式
![QQ_1730439717998](https://github.com/user-attachments/assets/8f0e2abc-7957-4c98-9a82-50ad38507ab9)
 ## 测试结果
![QQ_1730439846374](https://github.com/user-attachments/assets/f2ae81f5-50ea-42a2-b864-7c0650f8d2b4)

# 普通启动方式
![QQ_1730440045349](https://github.com/user-attachments/assets/e9a16726-050b-4940-9b73-4d462e81a9f8)
## 测试结果
![QQ_1730440342382](https://github.com/user-attachments/assets/0bc1ac3d-8ee6-4232-b13c-05f8937e6230)

**Comment by Bobholamovic** [comment]
不好意思，当前高性能推理插件在升级过程中出了点问题，我们将尽快修复～

**Comment by Bobholamovic** [comment]
请尝试重新安装`paddlex-hpi`插件：

```bash
pip uninstall paddlex-hpi
# 然后重新执行文档中的安装指令
```

**Comment by zhang19523zhao** [comment]
好的大佬

**Comment by Bobholamovic** [comment]
请问问题解决了不？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
