### ISSUE TITLE
版面分析数据

### ISSUE THREAD

**Issue by lyc728** [PaddlePaddle/PaddleX#2392]
你好 看了paddle的相关介绍 现在想基于此进行二次开发，我想知道有没有你们的数据集介绍，公开的数据我看了也很大，不太适合我的场景，请问你们的测试或者训练数据会开源吗？

**Comment by cuicheng01** [comment]
您好，我们的训练数据也不小，暂时不太考虑开源数据。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
