### ISSUE TITLE
平台的套件中有一个小小的代码顺序错误

### ISSUE THREAD

**Issue by liuxinyu-cv** [PaddlePaddle/PaddleX#2396]
## Checklist:
![image](https://github.com/user-attachments/assets/536a277c-33aa-4504-9e97-c38c7175b427)
## 描述问题
原代码中
            fpr = np.sum(
                gt_neg_score_list > threshold) / len(gt_neg_score_list)
这段代码在            
if len(gt_neg_score_list) == 0 and tpr > max_tpr:
                max_tpr = tpr
                result = "threshold: {}, fpr: {}, tpr: {:.5f}".format(
                    threshold, fpr, tpr)
的下面。
## 复现

1. 按照https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/training/PULC.md教程一步一步运行的

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
仅仅修改了训练的配置文件

4. 您使用的数据集是？
Kvasir

6. 请提供您出现的报错信息及相关log
找不到了

## 环境

![image](https://github.com/user-attachments/assets/b80b41c8-ca06-40d3-a4ca-9bd48b109d27)

**Comment by cuicheng01** [comment]
您好，问题已收到，我会反馈相关的负责同学

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
