### ISSUE TITLE
识别多页pdf的表格，出现预测多次的情况

### ISSUE THREAD

**Issue by CCbird** [PaddlePaddle/PaddleX#2397]
使用PP-ChatOCRv3-doc pipeline。
预测重复的情况发生在 页面只有上半部分有内容的pdf页面，
![image](https://github.com/user-attachments/assets/c89c6d28-57bf-4743-9f04-285c9614b657)

如整页都写满内容则暂时没有预测重复的情况。
网页版demo识别也是如此。

**Comment by liu-jiaxuan** [comment]
请问预测重复是指什么呢

**Comment by CCbird** [comment]
> 请问预测重复是指什么呢

就是一个表格识别了两次，产生两个图片，且识别出来的表格排版、准确度有点不同

**Comment by liu-jiaxuan** [comment]
收到，我们复现下哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
