### ISSUE TITLE
ModuleNotFoundError: No module named 'lazy_paddle.inference'

### ISSUE THREAD

**Issue by FHhui** [PaddlePaddle/PaddleX#2399]
安装完成之后，启动会报
ModuleNotFoundError: No module named 'lazy_paddle.inference'

**Comment by liu-jiaxuan** [comment]
没有复现你这个问题呢，请再检查下安装步骤和环境是否与文档要求的相同~

**Comment by yr-zh** [comment]
同样会报这个错，请问解决了吗

**Comment by liu-jiaxuan** [comment]
请再check下安装过程是否与文档相同~

**Comment by FHhui** [comment]
> 同样会报这个错，请问解决了吗

没有解决，dev说复现不了，放弃了

**Comment by FHhui** [comment]
> 请再check下安装过程是否与文档相同~

直接装的docker。。。

**Comment by liu-jiaxuan** [comment]
是什么环境呢，linux还是win

**Comment by FHhui** [comment]
> 是什么环境呢，linux还是win

linux

**Comment by liu-jiaxuan** [comment]
试下最新版docker镜像，请参考[文档](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/installation/installation.md)。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by xlcaptain** [comment]
百度这个是真的，全是bug
