### ISSUE TITLE
高性能PPYOLOE-S报错

### ISSUE THREAD

**Issue by guzichen** [PaddlePaddle/PaddleX#2407]
## 描述问题
跑默认的object_detection pipeline高性能模式下的picodet可以正常运行
`paddlex --pipeline object_detection --input https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg  --device gpu:0 --use_hpip --serial_number XXXX`

自己建立一个od.yaml,内容为
```
Global:
  pipeline_name: object_detection
  input: https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_object_detection_002.png
  
Pipeline:
  model: PP-YOLOE_plus-S
  batch_size: 1
```

在不用高性能模式的情况下，可以正常运行。但是在使用高性能模式会直接core dump。
`paddlex --pipeline od.yaml --input https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg  --device gpu:0 --use_hpip --serial_number XXXX`

log如下：

Using official model (PP-YOLOE_plus-S), the model files will be be automatically downloaded and saved in /home/lzhpc/.paddlex/official_models.
[INFO] fastdeploy/vision/common/processors/transform.cc(45)::FuseNormalizeCast  Normalize and Cast are fused to Normalize in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(93)::FuseNormalizeHWC2CHW       Normalize and HWC2CHW are fused to NormalizeAndPermute  in preprocessing pipeline.
[INFO] fastdeploy/vision/common/processors/transform.cc(159)::FuseNormalizeColorConvert BGR2RGB and NormalizeAndPermute are fused to NormalizeAndPermute with swap_rb=1
2024-11-06 17:18:08,741 DEBUG [PADDLEX] 140635146728640 1 licenses loaded
2024-11-06 17:18:08,741 DEBUG [PADDLEX] 140635146728640 /home/lzhpc/.baidu/paddlex/licenses/license.B466.9021.02.data
2024-11-06 17:18:08,741 DEBUG [PADDLEX] 140635146728640 License [B466-97BB-...] is permanently valid, skip check local time
2024-11-06 17:18:08,744 DEBUG [PADDLEX] 140635146728640 License [B466-97BB-...] is permanently valid, skip check local time
[INFO] fastdeploy/runtime/runtime.cc(185)::PaddleXAuth  Basic authentication succeeded.
2024-11-06 17:18:08,747 DEBUG [PADDLEX] 140635146728640 License [B466-97BB-...] is permanently valid, skip check local time
2024-11-06 17:18:08,750 DEBUG [PADDLEX] 140635146728640 License [B466-97BB-...] is permanently valid, skip check local time
[INFO] fastdeploy/runtime/runtime.cc(263)::PaddleXAuth  Task authentication succeeded.
[INFO] fastdeploy/runtime/runtime.cc(327)::Init The unencrypted model will be used for inference.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(28)::BuildOption    Will inference_precision float32
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(67)::BuildOption    Will try to use tensorrt inference with Paddle Backend.
[WARNING] fastdeploy/runtime/backends/paddle/paddle_backend.cc(79)::BuildOption Detect that tensorrt cache file has been set to /home/lzhpc/.paddlex/official_models/PP-YOLOE_plus-S/trt_serialized.trt, but while enable paddle2trt, please notice that the cache file will save to the directory where paddle model saved.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1106 17:18:08.754181 569306 analysis_config.cc:753] You have enabled Trt Cuda Graph, you must ensure that the input Shape remains unchanged.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(556)::GetDynamicShapeFromOption     im_shape: the max shape = [1, 2], the min shape = [1, 2], the opt shape = [1, 2]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(556)::GetDynamicShapeFromOption     image: the max shape = [1, 3, 640, 640], the min shape = [1, 3, 640, 640], the opt shape = [1, 3, 640, 640]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(556)::GetDynamicShapeFromOption     scale_factor: the max shape = [1, 2], the min shape = [1, 2], the opt shape = [1, 2]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(519)::SetTRTDynamicShapeToConfig    Start setting trt dynamic shape.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(521)::SetTRTDynamicShapeToConfig    Finish setting trt dynamic shape.
[WARNING] fastdeploy/runtime/backends/paddle/paddle_backend.cc(178)::BuildOption        Currently, Paddle-TensorRT does not support the new IR, and the old IR will be used.
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(291)::InitFromPaddle        Start generating shape range info file.
I1106 17:18:08.754524 569306 analysis_config.cc:1437] In CollectShapeInfo mode, we will disable optimizations and collect the shape information of all intermediate tensors in the compute graph and calculate the min_shape, max_shape and opt_shape.
I1106 17:18:09.898751 569306 analysis_predictor.cc:2124] MKLDNN is enabled
I1106 17:18:09.898783 569306 analysis_predictor.cc:2241] Ir optimization is turned off, no ir pass will be executed.
--- Running analysis [ir_graph_build_pass]
I1106 17:18:09.903661 569306 executor.cc:183] Old Executor is Running.
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [save_optimized_model_pass]
--- Running analysis [ir_graph_to_program_pass]
I1106 17:18:09.968288 569306 analysis_predictor.cc:2330] ======= ir optimization completed =======
I1106 17:18:09.969846 569306 naive_executor.cc:207] ---  skip [feed], feed -> scale_factor
I1106 17:18:09.969858 569306 naive_executor.cc:207] ---  skip [feed], feed -> image
I1106 17:18:09.971640 569306 naive_executor.cc:207] ---  skip [save_infer_model/scale_0.tmp_0], fetch -> fetch
I1106 17:18:09.971650 569306 naive_executor.cc:207] ---  skip [save_infer_model/scale_1.tmp_0], fetch -> fetch
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(556)::GetDynamicShapeFromOption     im_shape: the max shape = [1, 2], the min shape = [1, 2], the opt shape = [1, 2]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(556)::GetDynamicShapeFromOption     image: the max shape = [1, 3, 640, 640], the min shape = [1, 3, 640, 640], the opt shape = [1, 3, 640, 640]
[INFO] fastdeploy/runtime/backends/paddle/paddle_backend.cc(556)::GetDynamicShapeFromOption     scale_factor: the max shape = [1, 2], the min shape = [1, 2], the opt shape = [1, 2]
段错误 (核心已转储)

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddlepaddle-gpu          3.0.0b1
paddlex                   3.0.0b1
paddlex-hpi               0.0.0.dev0
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
ubuntu 20.04
3. 请问您使用的Python版本是？
3.10
5. 请问您使用的CUDA/cuDNN的版本号是？
cuda11.8/cudnn8.9
T4显卡，驱动版本535.183

**Comment by liu-jiaxuan** [comment]
不需要自己设定yaml哈，可以使用 “--save_path” 命令将yaml文件保存到指定路径，修改后再加载yaml文件即可，具体请参考请参考[文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/cv_pipelines/object_detection.md#22-%E6%9C%AC%E5%9C%B0%E4%BD%93%E9%AA%8C)。

**Comment by guzichen** [comment]
> 不需要自己设定yaml哈，可以使用 “--save_path” 命令将yaml文件保存到指定路径，修改后再加载yaml文件即可，具体请参考请参考[文档](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/cv_pipelines/object_detection.md#22-%E6%9C%AC%E5%9C%B0%E4%BD%93%E9%AA%8C)。

--save_path密令只保存了json和jpg的推理结果，并没有生成yaml

**Comment by liu-jiaxuan** [comment]
完整指令参考文档哈，paddlex --get_pipeline_config object_detection --save_path ./your_path

**Comment by guzichen** [comment]
> 完整指令参考文档哈，paddlex --get_pipeline_config object_detection --save_path ./your_path

我按照这个指令保存了yaml,然后把yaml中的model: PicoDet-S修改为了model: PP-YOLOE_plus-S，之后执行命令
`paddlex --pipeline ./your_path.yaml --input https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg  --device gpu:0 --use_hpip --serial_number XXXX`
依然报core dump，不加--use_hpip可以正常推理。

**Comment by Bobholamovic** [comment]
你好，这是高性能推理插件的一个bug，我们已经定位到问题，将在近期修复。感谢反馈～

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
