### ISSUE TITLE
文档种链接丢失

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/PaddleX#242]
文档

https://paddlex.readthedocs.io/zh_CN/develop/data/annotations

**Comment by jiangjiajun** [comment]
这个链接是在哪个文档里出现的呢

正确的链接应该是 https://paddlex.readthedocs.io/zh_CN/develop/data/annotation.html

**Comment by 60999** [comment]
忘了，你们没自动化测试吗，可以检测链接有效性的。

**Comment by jiangjiajun** [comment]
> 忘了，你们没自动化测试吗，可以检测链接有效性的。

好的，多谢反馈
