### ISSUE TITLE
paddlex版面区域检测模块linux推理比windows慢很多

### ISSUE THREAD

**Issue by narc1ssus1** [PaddlePaddle/PaddleX#2443]
版面区域检测模块RT-DETR-H_layout_3cls这个模型在linux下推理比windows慢很多，linux下要4s，windows下只要0.5s，显卡，显卡驱动，cuda和cudnn的版本都是一致的，这是为什么

**Comment by cuicheng01** [comment]
wsl还是纯linux呢？如果是wsl的话，本身有一些I/O开销和命令系统调用翻译的耗时，还有一些资源调度的差异，速度可能比windows慢，如果是纯Linux，应该不太可能。

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
