### ISSUE TITLE
paddlex服务化部署文档场景信息抽取v3产线存在bug

### ISSUE THREAD

**Issue by zx007nice** [PaddlePaddle/PaddleX#2449]
## 描述问题
在linux系统上，paddlex服务化部署PP-ChatOCRv3-doc（文档场景信息抽取v3产线），通过postman调用，发现如果参数是多页的pdf base64编码，json返回只有第一页的数据

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？
是
2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
没有
3. 您使用的数据集是？
多页的pdf文件转成的base64编码
4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
PaddlePaddle 3.0.0-beta1
PaddleX 3.0-beta1

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Linux

**Comment by Bobholamovic** [comment]
你好，我们复现了这个问题，看起来是一个bug，我们将尽快修复。感谢反馈～

**Comment by Bb91234567890** [comment]
> 你好，我们复现了这个问题，看起来是一个bug，我们将尽快修复。感谢反馈～·
