### ISSUE TITLE
在新建的虚拟环境中安装paddle-gpu3.0.0后import paddle报错

### ISSUE THREAD

**Issue by wujf147** [PaddlePaddle/PaddleX#2459]
在新建的虚拟环境中根据python -m pip install -i https://www.paddlepaddle.org.cn/packages/stable/cu118/ 安装paddlepaddle-gpu3.0.0后import paddle，虚拟环境所在服务器的cuda是11.2，安装包截图如下：
![image](https://github.com/user-attachments/assets/ae1aa8f4-f5c8-482a-bf3e-d29174752169)
import paddle报错：
![image](https://github.com/user-attachments/assets/7cd15eaa-b009-417c-aa09-abd32439b11e)
尝试按照网上方法将使用链接库libcudart.so.11.0的路径加入环境变量后仍未解决
![image](https://github.com/user-attachments/assets/a85bbee8-2a6a-4612-ab6d-0ebe322efd81)
请各位老师帮忙看看是什么原因？

**Comment by zhang-prog** [comment]
日志中有这么一句：
```Can not import paddle core while this file exists: /home/...../libpaddle.so```

试试删除这个 ```libpaddle.so``` 文件呢？感觉是环境残留导致的问题。

**Comment by zhang-prog** [comment]
很有可能是docker启动时未加 ```--gpus all ``` 参数，可以加上试试

**Comment by zhang-prog** [comment]
如果不是使用docker启动，请确保当前环境的 cuda 是可用的

**Comment by wujf147** [comment]
@zhang-prog 会不会是cuda是11.2,安装的paddle-gpu是11.8的，导致不适配

**Comment by zhang-prog** [comment]
也有可能，不过还是建议排查下cuda是否可用，感觉这个可能性会更大些

**Comment by risemeup1** [comment]
你本地的libcudart.so有问题，升级驱动就好

**Comment by XieYunshen** [comment]
看着是libpaddle.so依赖的so文件的路径不太对，打印一下`echo $LD_LIBRARY_PATH`看一下呢

**Comment by zhang-prog** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.
