### ISSUE TITLE
文档信息抽取产线服务化部署时，未来是否可以一步调用4个模型

### ISSUE THREAD

**Issue by a19970519** [PaddlePaddle/PaddleX#2461]

**Comment by zhang-prog** [comment]
可以参考 [文档场景信息抽取v3产线使用教程](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/information_extraction_pipelines/document_scene_information_extraction.md) 中 **3. 开发集成/部署** 的 **服务化部署——Python调用示例** 哈，是一个全流程的调用示例。

**Comment by a19970519** [comment]
> 可以参考 [文档场景信息抽取v3产线使用教程](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/information_extraction_pipelines/document_scene_information_extraction.md) 中 **3. 开发集成/部署** 的 **服务化部署——Python调用示例** 哈，是一个全流程的调用示例。

python示例这个，他好像也是4次web请求，未来能否可以实现1次web，调用4个模型

**Comment by zhang-prog** [comment]
我们这里实现4个api是考虑到粒度更细一些，方便调试和使用。你可以参考 Python调用示例 把全流程的调用过程自己组一个新的api，这样其实在外部来看是一样的～

**Comment by a19970519** [comment]
> 我们这里实现4个api是考虑到粒度更细一些，方便调试和使用。你可以参考 Python调用示例 把全流程的调用过程自己组一个新的api，这样其实在外部来看是一样的～

好的
