### ISSUE TITLE
印章文本检测模型二次开发

### ISSUE THREAD

**Issue by tigerdhl** [PaddlePaddle/PaddleX#2469]
paddlex列出了印章识别二次开发三个模块的链接，我要用自己的数据对文本检测模型进行微调，但是没有看到如何标注弯曲文字。
![屏幕截图 2024-11-12 230123](https://github.com/user-attachments/assets/22f9f46e-3549-43ee-a208-8ad23a8127dd)
只给出标注矩形框的实例，paddlelabel导出识别结果，只导出矩形框数据。请问对于弯曲文字，如果进行数据制作用于微调？

**Comment by wujf147** [comment]
PPOCRLabel中可以进行多边形的标注

**Comment by zhang-prog** [comment]
可以参考 [PaddleX文本检测/文本识别任务模块数据标注教程](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data_annotations/ocr_modules/text_detection_recognition.md) 进行数据标注

**Comment by tigerdhl** [comment]
> PPOCRLabel中可以进行多边形的标注

谢谢，我知道可以多点标注，比如我用14点标注弯曲文字，但是点击“导出识别结果”，crop图像会失败，只有矩形框标注的会成功crop，导出图像到crop_img。我要训练文本检测模型，应该需要每张图的标注的crop_img吧

**Comment by tigerdhl** [comment]
> 可以参考 [PaddleX文本检测/文本识别任务模块数据标注教程](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/data_annotations/ocr_modules/text_detection_recognition.md) 进行数据标注

谢谢，我知道可以多点标注，比如我用14点标注弯曲文字，但是点击“导出识别结果”，crop图像会失败，只有矩形框标注的会成功crop，导出图像到crop_img。我要训练文本检测模型，应该需要每张图的标注的crop_img吧

**Comment by zhang-prog** [comment]
可以参考这个issue https://github.com/PaddlePaddle/PaddleX/issues/2538

**Comment by tigerdhl** [comment]
> 可以参考这个issue #2538

谢啦，搞定了，不用关心crop_img
