### ISSUE TITLE
[文档]网页版文档某个链接失效

### ISSUE THREAD

**Issue by GT-ZhangAcer** [PaddlePaddle/PaddleX#247]
该页面下的语义分割->介绍->点击获取代码->DeepLabv3p-Xception65 模型的超链接有误
https://paddlex.readthedocs.io/zh_CN/develop/train/semantic_segmentation.html

原文链接为：https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/semantic_segmentation/deeplabv3p_xception65.pyy
正确链接需要更改pyy为py。

Q群里面有同学反馈了，等一波大佬们修复~

**Comment by jiangjiajun** [comment]
> 该页面下的语义分割->介绍->点击获取代码->DeepLabv3p-Xception65 模型的超链接有误
> https://paddlex.readthedocs.io/zh_CN/develop/train/semantic_segmentation.html
> 
> 原文链接为：https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/semantic_segmentation/deeplabv3p_xception65.pyy
> 正确链接需要更改pyy为py。
> 
> Q群里面有同学反馈了，等一波大佬们修复~

好的，多谢，已修改（大概5分钟左右会同步至readthedocs） ：）
