### ISSUE TITLE
在足球剪辑项目里面，自定义自己得视频训练最后一步LSTM训练，出现了

### ISSUE THREAD

**Issue by dxlei** [PaddlePaddle/PaddleX#2472]
![image](https://github.com/user-attachments/assets/ae83c42f-fe73-4d0a-beef-20c5ada922a0)
这个图片上得设置问题报错：
 if len(values) <= len(boundaries):
            raise ValueError(
                f'The values have one more element than boundaries, but received len(values) [{len(values)}] < len(boundaries) + 1 [{len(boundaries) + 1}].'
            )

但是初始设置就是这样得，是不是写错了？这是一个问题卡在这里了

**Comment by cuicheng01** [comment]
这个不是paddlex？

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
