### ISSUE TITLE
图像分类、图像目标检测当中，如何更改返回值为中文，目前返回结果是英文

### ISSUE THREAD

**Issue by ssyy398** [PaddlePaddle/PaddleX#2480]
## 描述问题
使用图像目标检测模型，识别图像，返回值和图像上标注框选都是英文的，如下：

![1731550981136](https://github.com/user-attachments/assets/1a6766fe-18ba-47d2-8977-745a26acbe20)

而paddlex文档的介绍里面，这个返回值是有中文的，如下：
![343820042-099e2b00-0bbe-4b20-9c5a-96b69e473bd2](https://github.com/user-attachments/assets/841a90b7-8b5e-4b90-b104-d760ae3ad2f7)

图像分类模型，结果也是英文的，如下:
![image](https://github.com/user-attachments/assets/fb52e998-ac7e-4399-848b-6eac6ecac704)

然后paddlex的首页文档中，返回值是中文的如下：
![image](https://github.com/user-attachments/assets/7a3026e3-fe0f-414b-9ff2-fc3003bbd1fc)

请问这个应该怎么修改，更改哪个参数还是需要更换模型？ 代码使用的都是文档中默认的代码，没有进行更改

**Comment by TingquanGao** [comment]
目前都是默认使用公开数据集的官方标签字段，所以是英文的。如果想要中文的话，需要更改下推理模型参数，如果使用的是官方模型`PP-LCNet_x0_25`，则修改：`~/.paddlex/official_models/PP-LCNet_x0_25/inference.yml`文件中的`label_list`字段，目标检测模型类似，修改对应模型配置文件即可。

**Comment by ssyy398** [comment]
嗯嗯，好的好的，非常感谢！我取尝试一下！
