### ISSUE TITLE
如何将PubTabNet数据集转换成PaddleX中需要的数据集的格式

### ISSUE THREAD

**Issue by 01sss** [PaddlePaddle/PaddleX#2489]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX数据准备文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#2-%E6%95%B0%E6%8D%AE%E5%87%86%E5%A4%87)

## 复现

1. 您使用的命令是？

2. 您使用的数据集是？

3. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是

**Comment by zhangyubo0722** [comment]
https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta2/docs/data_annotations/ocr_modules/table_recognition.md
可以参考这个文档进行数据的准备

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
