### ISSUE TITLE
Slanet_plus微调后bbox解码有错误

### ISSUE THREAD

**Issue by flow3rdown** [PaddlePaddle/PaddleX#2493]
## Checklist:

1. 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
2. 翻阅[FAQ常见问题汇总和答疑](https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/FAQ/FAQ.md)
3. 确认bug是否在新版本里还未修复
4. 翻阅[PaddleX 使用文档](https://github.com/PaddlePaddle/PaddleX/tree/develop#paddlex-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)

## 描述问题
使用原生的Slanet_plus进行推理结果是正确的，但是用自己微调的slanet_plus模型推理时需要将bbox_decode（https://github.com/PaddlePaddle/PaddleX/blob/517200d89719a93bc0cfc14ba9343d4270891beb/paddlex/inference/components/task_related/table_rec.py#L173 ）处的设置改为slanet的形式，是我哪里的配置的有问题吗？

## 复现

1. 您是否已经正常运行我们提供的[教程](https://github.com/PaddlePaddle/PaddleX/tree/develop/tutorials)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddlefsl 1.1.0
paddlenlp 2.8.0.post0
paddleocr 0.1.0.dev1+geaef336
paddlepaddle-gpu 3.0.0b1
paddlex 3.0.0b1

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Linux
3. 请问您使用的Python版本是？
3.10.6
4. . 请问您使用的CUDA/cuDNN的版本号是？
12.1

**Comment by zhangyubo0722** [comment]
训练配置使用的是SLANet_plus的config吗，SLANet_plus和SLANet两个模型在预处理部分的padding操作不一样，所以解码操作也是不一样的

**Comment by flow3rdown** [comment]
> 训练配置使用的是SLANet_plus的config吗，SLANet_plus和SLANet两个模型在预处理部分的padding操作不一样，所以解码操作也是不一样的

用的是SLANet_plus的config，启动脚本是 `python main.py -c paddlex/configs/table_recognition/SLANet_plus.yaml`，yaml里面的`model`的名字就是`SLANet_plus`

**Comment by flow3rdown** [comment]
> 训练配置使用的是SLANet_plus的config吗，SLANet_plus和SLANet两个模型在预处理部分的padding操作不一样，所以解码操作也是不一样的

从yaml文件来看，SLANet_plus和SLANet两者在数据预处理部分好像并没有不同？使用的都是`PaddingTableImage`

**Comment by flow3rdown** [comment]
@zhangyubo0722  您好，能帮忙看看吗，怀疑是框架本身的问题

**Comment by flow3rdown** [comment]
> @zhangyubo0722 您好，能帮忙看看吗，怀疑是框架本身的问题

看了一下在ResizeTableImage ops中要指定resize_bboxes为True才会进行bbox的缩放，但是SLANet_plus的配置文件中并没有指定resize_bboxes为True，请问是否要设置为True呢？这一步的作用是什么呀？ @zhangyubo0722

**Comment by flow3rdown** [comment]
@zhangyubo0722  @jzhang533  @muare 有人能帮忙看一下吗？这应该是PaddleX自身的问题，跟ACC训练一直是0一样，难道都没人发现过吗？

**Comment by liu-jiaxuan** [comment]
需要在SLANet_plus配置文件中设置resize_bboxes=True，后续我们会修复此问题

**Comment by flow3rdown** [comment]
只修改resize_bboxes=True是不起作用的，可能要排查一下整个训练逻辑，我很疑惑的是之前都没人训练过SLANet_plus吗？这么明显的错误都没人发现。

**Comment by liu-jiaxuan** [comment]
后续会排查训练逻辑

**Comment by flow3rdown** [comment]
请问大佬，这个问题是已经解决了吗？ @liu-jiaxuan
