### ISSUE TITLE
如何解决老版本from paddlex.deploy import Predictor

### ISSUE THREAD

**Issue by StrengthFirstF** [PaddlePaddle/PaddleX#2502]
`##` Checklist:
一个基于paddlex的手势识别
代码是这篇仓库里找的
[https://github.com/Sharpiless/Hand-gesture-recognition-for-game](url)
## 描述问题
在老版本的存在的Predictor，请问在新版本里面已经删除了吗，那在新版本里改如何修改这个代码，在官网的api文档里没有找到这个Predictor

## 复现
`from paddlex.deploy import Predictor
 model = Predictor('rec_inference_model', use_gpu=True)`

)
## 环境

1. paddlepaddle-gpu-3.0.0b2 paddlex 3.0.0b2

2. Windows

3. python 3.10 

5. cuda 11.8 cudnn 8.9.2

**Comment by cuicheng01** [comment]
新版和老板差异比较大，所以版本号是3.0+，以前的接口建议使用老版的paddlex。不过整体而言，推荐使用新版的，相关内容的丰富性会远超老板，部分缺失内容也在补齐中。

**Comment by StrengthFirstF** [comment]
> 新版和老板差异比较大，所以版本号是3.0+，以前的接口建议使用老版的paddlex。不过整体而言，推荐使用新版的，相关内容的丰富性会远超老板，部分缺失内容也在补齐中。

大佬，请问老版本的安装命令在哪里可以找到，我在官方好像没有找到

**Comment by StrengthFirstF** [comment]
请问大佬，在哪里可以找到老版本的paddlex的安装命令，我在官网没有找到

**Comment by StrengthFirstF** [comment]
> 新版和老板差异比较大，所以版本号是3.0+，以前的接口建议使用老版的paddlex。不过整体而言，推荐使用新版的，相关内容的丰富性会远超老板，部分缺失内容也在补齐中。

我试了在pypi的官网找到了以前发布的版本里面，用这个 pip install paddlex==1.2.2 命令装不上去

**Comment by cuicheng01** [comment]
可以切换到paddlex的早前的分支看相关的文档

**Comment by StrengthFirstF** [comment]
> 可以切换到paddlex的早前的分支看相关的文档
在早期的paddlex的分支文档没有相关老版本的安装命令，但是我在pypi的官网里找到了发布版本并安装上去，然后改了一些包的兼容版本问题，解决一下包版本冲突问题，谢谢大佬了

**Comment by cuicheng01** [comment]
好的，那该问题就close了，有问题可以reopen～
