### ISSUE TITLE
Very slow prediction [object detection]

### ISSUE THREAD

**Issue by cadpm** [PaddlePaddle/PaddleX#2503]
I am doing object detection with a pp-yolo-plus-S model.

And I'm getting prediction time of 300mS approximately.

Using a model trained by model yolov5-S I'm getting predictions of 90mS.

How can I reduce the prediction time?

I am generating my prediction with the following structure:

`
from paddlex import create_pipeline, create_model

model_deteccion = create_model("PaddleX/output01/best_model/inference", device="GPU")

frame="myimage.jpg"

myPrediction=list(model_deteccion.predict(frame)

`

**Comment by cuicheng01** [comment]
Could you provide a sample of your test image, and could you also provide the specifications of your GPU?

**Comment by cadpm** [comment]
Sure, my GPU is rtx3060 12gb

**Comment by cadpm** [comment]
The problem is not the image, it is the processing time. 

I did Testing with PP-yolov-plus-s and yolov5-s both with coco models and evaluation with coco images. The prediction performance is 3 times less in Yolov5 (with pytorch)

**Comment by cuicheng01** [comment]
Could you kindly explain how your PyTorch model makes predictions? If it’s convenient, could you share some example code?

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
