### ISSUE TITLE
How to upload a model converted by Yolov11?

### ISSUE THREAD

**Issue by cadpm** [PaddlePaddle/PaddleX#2509]
Hello everyone,

I'm just starting out with paddle, I've managed to create my models with paddle and upload them.

But I haven't been able to upload a model converted by ultralytics. I'm leaving the web page below:

https://docs.ultralytics.com/integrations/paddlepaddle/

This is because when using the conversion by Yolov11, it does not generate the YAML file in interference.

I tried to create a Yaml file with a similar configuration, but it did not work.

Could you share with me a way to deploy my converted model

**Comment by cuicheng01** [comment]
Hi, since YOLOv11’s license is AGPL-3.0 and our license is Apache 2.0, we cannot directly integrate YOLOv11. We need a more ingenious approach and expect to support it next year.

**Comment by cadpm** [comment]
Oh, it's unfortunate to read that because it doesn't make sense for Ultralytics to share a way to convert our YOLOv11-trained models to PaddlePaddle if they won't be able to work.

But still, can't they teach how to work with the inference file created by YOLO without the YAML file? That wouldn't violate any license in this case, as they wouldn't be uploading any files corresponding to Ultralytics.

**Comment by cuicheng01** [comment]
This model cannot be included in our code, but you are free to convert it to a Paddle model without any restrictions.

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
