### ISSUE TITLE
seal_recgonition中的api调用示例代码

### ISSUE THREAD

**Issue by wasd-lvlong** [PaddlePaddle/PaddleX#2514]
## Checklist:

- [ ] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [ ] 翻阅[FAQ](https://paddlep
![image](https://github.com/user-attachments/assets/0e18d41a-fe87-49d2-b692-e3b27c34c4f5)
addle.github.io/PaddleX/main/FAQ.html)
- [ ] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [ ] 确认bug是否在新版本里还未修复

## 描述问题
目前我已经实现了推理，但我做一个服务端部署，文档中的layout.png不知道是什么图片，请问能提供demo.png和layout.png这两张图片吗
## 复现

1. 您是否已经正常运行我们提供的[教程](https://paddlepaddle.github.io/PaddleX/main/index.html)？

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码

3. 您使用的数据集是？

4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是？

5. 请问您使用的CUDA/cuDNN的版本号是？

**Comment by changdazhou** [comment]
layout.png生成结果保存的图片

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
