### ISSUE TITLE
用paddlex训练实例分割，使用labelme标注数据后如何正确转成coco数据呢？

### ISSUE THREAD

**Issue by itues** [PaddlePaddle/PaddleX#2516]
## Checklist:
![微信图片_20241119172634](https://github.com/user-attachments/assets/d72669c0-a33f-4c56-bc6d-e4fee0e298d2)
查看文档之际跨越式就说使用coco格式数据，没有提到如何正确转换过去，使用什么命令。
## 复现

1. 您使用的命令是？

2. 您使用的数据集是？

3. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddleX的版本号

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS

3. 请问您使用的Python版本是

**Comment by changdazhou** [comment]
使用convert功能实现，在数据校验的时候增加相关参数即可，具体参考yaml中的相关key

**Comment by itues** [comment]
> 使用convert功能实现，在数据校验的时候增加相关参数即可，具体参考yaml中的相关key

请问在哪里找convert相关参数。我没有找到相关转换convert的资料

**Comment by changdazhou** [comment]
参考这里：https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta2/docs/practical_tutorials/instance_segmentation_remote_sensing_tutorial.md

**Comment by itues** [comment]
> 参考这里：https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta2/docs/practical_tutorials/instance_segmentation_remote_sensing_tutorial.md

你好，在你的指导下我已进入数据转换的阶段。但是由于我需要训练的是切割图片中的圆，所以lableme中制作的数据类型是circle。但是在转换的时候提示只支持多边形转换，不支持圆。请问是不是paddlex无法分割圆呢。或者有没有其他更好的方法呢。
![微信截图_20241120214542](https://github.com/user-attachments/assets/df3216a0-d833-4fb0-9be2-1e73086e0c2c)

**Comment by changdazhou** [comment]
目前仅支持多边形标柱哈

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
