### ISSUE TITLE
Python 3.12.4 安装PaddleX会报错 AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by chennest** [PaddlePaddle/PaddleX#2521]
## Checklist:

- [ ] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [ ] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [ ] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [x] 确认bug是否在新版本里还未修复

## 复现

1. 您是否已经正常运行我们提供的[教程](https://paddlepaddle.github.io/PaddleX/main/index.html)？
是的

2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
没有

3. 您使用的数据集是？
没用

4. 请提供您出现的报错信息及相关log
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
paddle2onnx                       1.2.11
paddlefsl                         1.1.0
paddlenlp                         2.8.1
paddleocr                         2.9.0
paddlepaddle-gpu                  3.0.0b1
 pip install https://paddle-model-ecology.bj.bcebos.com/paddlex/whl/paddlex-3.0.0b1-py3-none-any.whl

2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Debian GNU/Linux 12 (bookworm)

3. 请问您使用的Python版本是？
Python 3.12.4

4. 请问您使用的CUDA/cuDNN的版本号是？
CUDA Version: 12.6

**Comment by chennest** [comment]
希望能早日适配Python 3.12

**Comment by Barry-1212** [comment]
当前支持Python 3.8 ～ Python 3.10下运行

**Comment by chennest** [comment]
是的，希望能早日适配哦 哈哈哈
