### ISSUE TITLE
paddleX3.0版本调用本地模型时遇到了报错

### ISSUE THREAD

**Issue by MonLightMagic** [PaddlePaddle/PaddleX#2522]
## Checklist:

查看了文档和issue都是调用paddleX模型的方法，不知道怎么调用本地的模型

## 复现
遇到了如下的报错，说paddleX3中已经没有了load_,model这个函数，但是不知道改成了什么
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\pilaojiance.py", line 9, in <module>
    model = pdx.load_model(save_dir)
AttributeError: module 'paddlex' has no attribute 'load_model'

## 环境

1. PaddlePaddle3和PaddleX3

2. Windows

**Comment by cuicheng01** [comment]
PaddleX3.0是一次大的改版和升级，请使用3.0的使用文档哦https://paddlepaddle.github.io/PaddleX/latest/index.html

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
