### ISSUE TITLE
按路径导入本地模型时遇到了报错

### ISSUE THREAD

**Issue by MonLightMagic** [PaddlePaddle/PaddleX#2523]
## Checklist:

查看了文档和issue都是调用paddleX模型的方法，不知道怎么调用本地的模型

## 复现
遇到了如下的报错，说paddleX3中已经没有了load_,model这个函数，但是不知道改成了什么
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\pilaojiance.py", line 9, in <module>
    model = pdx.load_model(save_dir)
AttributeError: module 'paddlex' has no attribute 'load_model'

## 环境

1. PaddlePaddle3和PaddleX3

2. Windows

**Comment by Stefan3Zz** [comment]
这个怎么解决的呀

**Comment by MonLightMagic** [comment]
> 这个怎么解决的呀

没解决，换paddlex2了
