### ISSUE TITLE
印章文本识别数据

### ISSUE THREAD

**Issue by BUJIQI** [PaddlePaddle/PaddleX#2538]
## Checklist:

- [x] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [x] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [x] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [x] 确认bug是否在新版本里还未修复

PPOCRLabel不支持导出多点标注数据，只能导出矩形标注数据，请问应该如何进行印章文本识别的训练？

**Comment by Sunting78** [comment]
您好 支持的 按下快捷键Q进行4点（多点）标注  参考 https://paddlepaddle.github.io/PaddleOCR/latest/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.html#31

**Comment by BUJIQI** [comment]
> 您好 支持的 按下快捷键Q进行4点（多点）标注 参考 https://paddlepaddle.github.io/PaddleOCR/latest/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.html#31

4点是可以导出的，但是对于圆形印章，其文本是弯曲的无法使用4点标注，我这里使用的是16点标注，保存识别结果会报错：
The following images can not be saved, please check the image path and labels.
seal_train_data/a79e3fe7a377837ed1cebe3b15bd22b8.jpg
seal_train_data/a436e660fd7302450572c51943039a51.jpg
seal_train_data/a632aec44b911116bcb9359011324cfc.jpg

**Comment by Sunting78** [comment]
您好，这个中识别的结果需要自己手动调整，标注内置模型目前对弯曲识别的效果差。请参考这个文档的步骤，https://paddlepaddle.github.io/PaddleOCR/latest/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.html#31

**Comment by BUJIQI** [comment]
> 您好，这个中识别的结果需要自己手动调整，标注内置模型目前对弯曲识别的效果差。请参考这个文档的步骤，https://paddlepaddle.github.io/PaddleOCR/latest/applications/%E5%8D%B0%E7%AB%A0%E5%BC%AF%E6%9B%B2%E6%96%87%E5%AD%97%E8%AF%86%E5%88%AB.html#31

好的👌不过文档5.2.2里的代码有bug且还是针对4点标注数据的，需要自己修改挺多，建议维护一下😖

**Comment by Sunting78** [comment]
好的 收到您的宝贵建议～ 如果您愿意提一个PR，把您标注的修改过程贡献到仓库中，我们将非常感谢🙏

**Comment by BUJIQI** [comment]
> 好的 收到您的宝贵建议～ 如果您愿意提一个PR，把您标注的修改过程贡献到仓库中，我们将非常感谢🙏

👌
