### ISSUE TITLE
人脸识别产线的demo数据是不是错误的，不能进行推理

### ISSUE THREAD

**Issue by Barry-1212** [PaddlePaddle/PaddleX#2548]
https://paddlepaddle.github.io/PaddleX/main/pipeline_usage/tutorials/cv_pipelines/face_recognition.html#222-python

from paddlex import create_pipeline

pipeline = create_pipeline(pipeline="face_recognition")

pipeline.build_index(data_root="face_demo_gallery", index_dir="face_gallery_index")

output = pipeline.predict("friends1.jpg", index_dir="face_gallery_index")
for res in output:
    res.print()
    res.save_to_img("./output/")

控制台打印：
Using official model (MobileFaceNet), the model files will be be automatically downloaded and saved in C:\Users\PC\.paddlex\official_models.
Traceback (most recent call last):
  File "D:\code\PaddleX\myUtils\face_test.py", line 5, in <module>
    pipeline.build_index(data_root="face_demo_gallery", index_dir="face_gallery_index")
TypeError: ShiTuV2Pipeline.build_index() missing 2 required positional arguments: 'gallery_imgs' and 'gallery_label'

**Comment by Barry-1212** [comment]
文档的代码是不是也是错了

**Comment by leo-q8** [comment]
文档还没更新，最新的接口data_root变成了gallery_imgs， index_dir变成了gallery_label

**Comment by leo-q8** [comment]
@Barry-1212 最新文档参考https://paddlepaddle.github.io/PaddleX/main/pipeline_usage/tutorials/cv_pipelines/face_recognition.html

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
