### ISSUE TITLE
paddlex 时序分类python获取结果慢

### ISSUE THREAD

**Issue by Syorst** [PaddlePaddle/PaddleX#2592]
## Checklist:

- [ ] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [ ] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [ ] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [ ] 确认bug是否在新版本里还未修复

## 描述问题
from paddlex import create_pipeline
import time
pipeline = create_pipeline(pipeline="ts_cls")
s=time.time()
output = pipeline.predict("/home/aistudio/PaddleX-release-3.0-beta2/dataset/ts_classify_examples/test.csv")
e=time.time()
print('推理耗时：', e-s)
s=time.time()
for res in output:
    pass
    # res.print() ## 打印预测的结构化输出
    # res.save_to_csv("./output/") ## 保存csv格式结果
e=time.time()
print('获取结果耗时：', e-s)
运行以上官方python代码结果如下：
推理耗时： 3.0994415283203125e-06
获取结果耗时： 2.1785106658935547
推理很快，获取结果却很慢，有什么加速方法么？
运行环境为cpu环境

**Comment by hoobnn** [comment]
其实你的推理耗时实际上是一些初始化、加载模型操作之类的用时，获取结果的耗时才是推理耗时
