### ISSUE TITLE
方向分类模型PP-LCNet_x1_0_doc_ori重新训练发现一直报未注册

### ISSUE THREAD

**Issue by beer168** [PaddlePaddle/PaddleX#2609]
## Checklist:

- [ ] 查找[历史相关issue](https://github.com/PaddlePaddle/PaddleX/issues)寻求解答
- [ ] 翻阅[FAQ](https://paddlepaddle.github.io/PaddleX/main/FAQ.html)
- [ √] 翻阅[PaddleX 文档](https://paddlepaddle.github.io/PaddleX/main/index.html)
- [ ] 确认bug是否在新版本里还未修复

## 描述问题
调用配置文件中的mode: check_dataset，验证数据集没有问题，但是切换成train就一直提示未注册，模型推理是可以使用的
## 复现
<img width="770" alt="1111" src="https://github.com/user-attachments/assets/46db3581-be78-4e51-93c2-b8beb2b9945d">

1. 您是否已经正常运行我们提供的[教程](https://paddlepaddle.github.io/PaddleX/main/index.html)？
是
2. 您是否在教程的基础上修改代码内容？还请您提供运行的代码
否
3. 您使用的数据集是？
自定义数据集，验证已通过
4. 请提供您出现的报错信息及相关log

## 环境

1. 请提供您使用的PaddlePaddle和PaddleX的版本号
PaddleX 3.0beta2,都已验证安装成功
2. 请提供您使用的操作系统信息，如Linux/Windows/MacOS
Windows
3. 请问您使用的Python版本是？
python3.10

**Comment by cuicheng01** [comment]
参考文档，需要安装PaddleClas插件，paddlex --install PaddleClas

**Comment by beer168** [comment]
解决了，谢谢

**Comment by beer168** [comment]
装了这个插件的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月6日(周五) 晚上8:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 方向分类模型PP-LCNet_x1_0_doc_ori重新训练发现一直报未注册 (Issue #2609)




 
参考文档，需要安装PaddleClas插件，paddlex --install PaddleClas
