### ISSUE TITLE
GUI代码会开放吗

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleX#261]
PaddleX GUI: https://www.paddlepaddle.org.cn/paddle/paddleX (请在ISSUE内容中保留此行内容)

**Comment by jiangjiajun** [comment]
GUI代码暂未开源，预计会在接下来1至2个Q内开源，欢迎关注我们的Repo跟进最新的开发进展 ：）

**Comment by geoexploring** [comment]
@jiangjiajun  您好，我试用了PaddleX GUI版本，效果很不错，并且能在我的 GTX750Ti 上跑模型训练，tql！
请问GUI的代码开源了吗？谢谢！
