### ISSUE TITLE
高性能推理插件，阿里云租用的服务器没有11.8版本的cuda，有其他可以替代的版本吗

### ISSUE THREAD

**Issue by zx007nice** [PaddlePaddle/PaddleX#2610]
## 描述问题
阿里云租用的服务器没有11.8版本的cuda，只支持下面的版本.这里面有高性能推理服务器能使用的吗？

<img width="325" alt="83c608351cf31a7eb139141b470a5c2" src="https://github.com/user-attachments/assets/9d20a34b-e58e-4dc0-8c94-ce067a10bc5d">

1. 高性能推理

    * 您是否完全按照[高性能推理文档教程](https://paddlepaddle.github.io/PaddleX/main/pipeline_deploy/high_performance_inference.html)跑通了流程？
是
    * 您使用的是离线激活方式还是在线激活方式？
在线

**Comment by cuicheng01** [comment]
高性能推理目前需要获取设备的指纹，所以云服务器可能本身也不能支持，月底PaddleX会推出无需获取设备指纹的高性能推理方式，到时候可以试一下

**Comment by zx007nice** [comment]
> 高性能推理目前需要获取设备的指纹，所以云服务器可能本身也不能支持，月底PaddleX会推出无需获取设备指纹的高性能推理方式，到时候可以试一下

好的谢谢了
