### ISSUE TITLE
数据集图片中的红章问题

### ISSUE THREAD

**Issue by hoobnn** [PaddlePaddle/PaddleX#2615]
## 描述问题

请教一下数据集中的红章问题处理
我的目的是对文本检测模型进行微调，更适用于垂直领域
私有数据集会出现红章，但红章内容不是我关注的，我再进行数据标注的时候，对红章应该怎么处理？
- 考虑预处理消除红章？
- 标注的时候不标注红章的内容？但会不会影响其他文本区域的检测效果，优先需要保证其他区域的文本检测效果
- 或者是有其他更好的办法吗？

**Comment by changdazhou** [comment]
如果可以很方便的通过预处理消除掉红章是最好的解决方案，如果不方便消除不标柱也可以，适当增加数据量，影响应该比较可控

**Comment by hoobnn** [comment]
> 如果可以很方便的通过预处理消除掉红章是最好的解决方案，如果不方便消除不标柱也可以，适当增加数据量，影响应该比较可控

明白了，感谢回复

**Comment by changdazhou** [comment]
好的，我这边先close掉了，后续有问题可以reopen哈

**Comment by changdazhou** [comment]
好的，我这边先close掉了，后续有问题可以reopen哈
