### ISSUE TITLE
PP-OCRv4 推理找不到 inference.yml 

### ISSUE THREAD

**Issue by ming2681** [PaddlePaddle/PaddleX#2619]
希望通过 paddlex3，进行ocr识别，从官网下载 PP-OCRv4_server_rec_infer 模型，在代码中进行ocr识别操作，提示找不到 inference.yml 文件，我只需要进行推理，不需要训练，这个文件如何获得？

**Comment by changdazhou** [comment]
可以在这里下载哈：https://github.com/PaddlePaddle/PaddleX/blob/develop/paddlex/inference/utils/official_models.py

**Comment by changdazhou** [comment]
另外单模型推理的话，可以自动下载的，你是如何操作的呢

**Comment by ming2681** [comment]
可能是我的下载路径不对，使用提供的地址已经可以了
