### ISSUE TITLE
PaddleCls和PaddleDetection里面的模型，如果需要集成到PaddleX里面，工作量大吗

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleX#262]

**Comment by jiangjiajun** [comment]
> _No description provided._

您现在有什么模型需求吗，可以列下你的模型需求，现在模型是否能够满足你的需求，我们评估下

**Comment by deep-practice** [comment]
没有具体的模型需求，只是看目前PaddleX支持的模型还比较少
顺便问一句，导出模型之后，如何在PaddleServer里面用呢
已经迷失在Paddle的众多repo中，感觉每个repo都是自己的一套东西

**Comment by jiangjiajun** [comment]
PaddleX目前选定的模型是在工业领域广泛应用的模型集，例如检测模型中的FasterRCNN和YOLOv3，并且针对这些模型都会打通部署、压缩裁剪的所有流程。
目前部署已经打通了C++、Python等部署方式，支持在服务端，Jetson开发板以及通过PaddleLite在Android上的部署（也即将提供树莓派、EdgeBoard等设备上的部署代码和流程，以及模型通过OpenVINO部署在Intel计算棒，VPU等设备上的部署），详细可以参考 https://paddlex.readthedocs.io/zh_CN/develop/deploy/

因此如果是要直接解决业务上的问题，推荐使用PaddleX。如果是想调研当前最新最前沿的模型在自己业务线上的效果，推荐用PaddleSeg、PaddleDetection。

另外目前我们也提供了轻量级的服务化部署，可以通过http服务请求来预测结果，可查看 https://paddlex.readthedocs.io/zh_CN/develop/deploy/hub_serving.html

**Comment by deep-practice** [comment]
明白了，定位不一样，试用了一下，对于小白用户会很友好。
