### ISSUE TITLE
使用Paddlex人脸检测模块, 出现模型未注册问题

### ISSUE THREAD

**Issue by LGYYYYYY** [PaddlePaddle/PaddleX#2623]
## Checklist:

查阅官方文档https://paddlepaddle.github.io/PaddleX/latest/module_usage/tutorials/cv_modules/face_detection.html
试用人脸检测模块

## 描述问题
试用人脸检测模块, 出现模型未注册问题, 同时测试过使用"确实没注册"的模型如:yolox-s(小写), 会出现
---报错显示有哪些模型已经注册
paddlex.utils.errors.others.ClassNotFoundException: `yolox-s` is not registered on BaseTrainer.
The registied entities: [CLIP_vit_base_patch16_224,  CLIP_vit_large_patch14_224,  ConvNeXt_tiny,  ConvNeXt_small,  ConvNeXt_base_224,  ConvNeXt_base_384,  ConvNeXt_large_224,  ConvNeXt_large_384, ......
---等
途中没有修改过paddlx的代码
环境使用aistudio的云上cpu环境, 仅安装Paddlex
<img width="656" alt="error" src="https://github.com/user-attachments/assets/8949ed6c-7c04-4b64-a252-597c5dc09340">

**Comment by leo-q8** [comment]
使用paddlex进行二次开发，需要安装对应的插件，这里需要安装PaddleDetetion插件，请参考paddleX的安装说明

**Comment by LGYYYYYY** [comment]
感谢, 问题已解决
