### ISSUE TITLE
window11系统的docker平台paddleX高性能插件联网激活失败

### ISSUE THREAD

**Issue by 1756112901** [PaddlePaddle/PaddleX#2624]
## 描述问题

系统是window11
显卡cuda12.7，如下
![image](https://github.com/user-attachments/assets/5a8af5d0-4168-4a9a-9256-2c5971349db6)

docker环境是，paddlepaddle/paddle:3.0.0b2-gpu-cuda11.8-cudnn8.6-trt8.5

普通模式是已经跑通了的，如图
![image](https://github.com/user-attachments/assets/27bf9d1c-1745-4945-b3ec-c3f07f5b8c08)

然后已经安装高性能推理插件，尝试联网激活，报错如下图
提示Please ensure that you have purchased the product and set the correct serial number.
[ERROR] fastdeploy/runtime/runtime.cc(281)::Init Authentication failed. Please check the serial number.
![image](https://github.com/user-attachments/assets/1c2b53ae-d60a-4249-ba3e-3dc4fa9d12c0)

请问是我哪一个步骤错了吗 还是现在window系统docker暂不支持高性能模式？

**Comment by 1756112901** [comment]
想激活的 OCR

**Comment by Bobholamovic** [comment]
你好，windows暂时不支持高性能推理插件的鉴权。不过，我们将在近期推出免鉴权版的高性能推理插件，届时应该可以在你的环境中使用，敬请关注～
