### ISSUE TITLE
在3.0b2中无法设置权重路径，但是在3.0b中，这种方式就是可以的，请问如何在3.0b2中设置权重路径

### ISSUE THREAD

**Issue by ming2681** [PaddlePaddle/PaddleX#2639]
代码:
model = create_model(model_name="PP-YOLOE_plus-S", model_dir="D:/AI/my_models/lm/best_model")

错误提示:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by zhang-prog** [comment]
可以通过 `model_name` 来传入权重路径哈：
`model_name`：`str` 类型，模型名或是本地inference模型文件路径，如“PP-LCNet_x1_0”、“/path/to/PP-LCNet_x1_0_infer/”；

**Comment by ming2681** [comment]
当我写成
model = create_model(model_name="D:/AI/my_models/lm/best_model")
output = model.predict("lm.jpg", batch_size=1)

提示错误
 File "D:\miniconda3\envs\paddlex30b2\lib\pathlib.py", line 576, in _parse_args  a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

![image](https://github.com/user-attachments/assets/24e0ab59-3db5-419d-bfc6-6d04520d8df0)

**Comment by ming2681** [comment]
![image](https://github.com/user-attachments/assets/4c45e017-1f84-4d74-ad77-1f7dd66cf830)

**Comment by zhang-prog** [comment]
麻烦把完整代码贴一下，包括 import 那些

**Comment by ming2681** [comment]
# 目标检测
from paddlex import create_model

from flask import jsonify, Flask, request, render_template, send_file
import base64
import os
import uuid
import json

app = Flask(__name__)
basedir = os.path.abspath(os.path.dirname(__file__))

# 目标检测
@app.route('/object_detection', methods=['POST'])
def object_detection():
    # 输出路径
    output_dir = 'D:/AI/result/'
    
    model = create_model(model_name="D:/AI/my_models/lm/best_model/")
    output = model.predict("lm.jpg", batch_size=1)
    for res in output:
        res.print(json_format=False)
        res.save_to_img(output_dir)
        res.save_to_json(output_dir)

    
    return None

**Comment by zhang-prog** [comment]
windows上处理path容易出问题，你试一下这样子可以吗？
```python
from pathlib import Path
model = create_model(model_name=str(Path(r"D:/AI/my_models/lm/best_model")))
```

**Comment by ming2681** [comment]
提示这样的错误：
  File "D:\miniconda3\envs\paddlex30b2\lib\pathlib.py", line 576, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

主要是在3.0b时候，是没问题的，包括路径

**Comment by zhang-prog** [comment]
`model_name` 参数改为 `model` 参数试一下

**Comment by ming2681** [comment]
改为:
model = create_model(model=str(Path(r"D:/AI/my_models/lm/best_model")))

提示错误:
File "D:\miniconda3\envs\paddlex30b2\lib\site-packages\paddlex-3.0.0b2-py3.10.egg\paddlex\inference\models\__init__.py", line 76, in create_predictor
    model_name = config["Global"]["model_name"]
KeyError: 'Global'

**Comment by zhang-prog** [comment]
麻烦贴一下你的 `inference.yml`

**Comment by ming2681** [comment]
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 640
  - 640
  type: Resize
- mean:
  - 0.0
  - 0.0
  - 0.0
  norm_type: none
  std:
  - 1.0
  - 1.0
  - 1.0
  type: NormalizeImage
- type: Permute
label_list:
- '1'

**Comment by ming2681** [comment]
这是我通过3.0b，按照目标检查的方式训练的模型 PP-YOLOE_plus-S

**Comment by zhang-prog** [comment]
给 `inference.yml` 加上：
```
Global:
  model_name: PP-YOLOE_plus-S
```

**Comment by ming2681** [comment]
可以了，最进几个版本的修改变化比较大，大概稳定版什么时候出来呢？

**Comment by zhang-prog** [comment]
感谢您对我们的关注和支持。最近我们一直在努力进行优化以确保未来版本的质量和稳定性，具体的发布日期还没完全确定，如果您在使用当前版本时遇到任何问题或有任何反馈，请随时提issue和我们联系！

**Comment by ming2681** [comment]
还有一个问题，就是我在3.0b中修改过
PaddleX3\paddlex\modules\object_detection\predictor\transforms.py做过修改，现在这个文件在3.0b2中没有了，请问对应的功能目前在那个位置呢？我想去掉目标识别在图上的lable，保留边框

**Comment by zhang-prog** [comment]
https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta2/paddlex/inference/models/object_detection.py#L67

`labels` 改成 `labels=None` 试试

**Comment by ming2681** [comment]
应该是这个位置
build\lib\paddlex\inference\results\det.py
60-74行注释掉就行了
