### ISSUE TITLE
centos7.9下 docker容器高性能插件 离线和联网激活都失败

### ISSUE THREAD

**Issue by 1756112901** [PaddlePaddle/PaddleX#2642]
系统Centos7.9 
显卡cuda 11.8 如下
![image](https://github.com/user-attachments/assets/1100f690-b085-4812-9b13-9cd6d2c7932d)

docker环境是，paddlepaddle/paddle:3.0.0b2-gpu-cuda11.8-cudnn8.6-trt8.5

普通模式是能正常跑通的
![image](https://github.com/user-attachments/assets/d3deedd6-899d-4e35-b5dc-880a75fae330)

然后已经安装高性能推理插件，尝试联网激活，报错如下图
![image](https://github.com/user-attachments/assets/38a4a3c4-dd54-4f07-8e48-ac62eca275ef)

尝试离线激活，已经绑定设备，下载证书，并且证书在主机和docker内都放到指定位置了，还是报错如下图
![image](https://github.com/user-attachments/assets/8c0fa4a4-b7f0-4350-9ede-ed5bfb5bf614)

docker容器 是以 host模式运行的，是哪一步做错了？流程都是按照文档来的，求解，谢谢

**Comment by 1756112901** [comment]
另外获取设备指纹的程序paddlex_device_id_getter在主机上能正常获得结果，但是在docker运行后没有输出

**Comment by 1756112901** [comment]
补充 用host模式和bridge模式运行 docker容器， 获取设备指纹的程序paddlex_device_id_getter也是一样没有输出

**Comment by zhang-prog** [comment]
确认一下启动docker时有没有挂载这两个目录：
```
--volume "${HOME}/.baidu/paddlex":/root/.baidu/paddlex
--volume /dev/disk/by-uuid:/dev/disk/by-uuid
```

**Comment by 1756112901** [comment]
挂载完后 能正常使用了，十分感谢

**Comment by zhang-prog** [comment]
好的，如果还有其他问题，欢迎随时提issue
