### ISSUE TITLE
使用PaddleX进行印章检测与识别时，一张图多个印章只返回一个结果

### ISSUE THREAD

**Issue by IceHowe** [PaddlePaddle/PaddleX#2668]
## 描述问题

使用PaddleX进行印章检测与识别时，一张图多个印章只返回一个结果，如何识别一张图像的多个印章

**Comment by Sunting78** [comment]
您好，使用印章文本识别产线是可以实现多个结果的。您可以拉取最新代码，如果无法返回，麻烦您把运行的命令或代码以及测试图像贴上来，我们排查下

**Comment by IceHowe** [comment]
> 您好，使用印章文本识别产线是可以实现多个结果的。您可以拉取最新代码，如果无法返回，麻烦您把运行的命令或代码以及测试图像贴上来，我们排查下

感谢，确实能识别多个，我把同一个印章截图拼接放在了一张图片上，能识别出两个，但是这张图片有三个印章，另一个印章会被识别为图片，单独这一个印章时就会识别成印章，这个现象好像比较普遍，出现了几次印章被检测为图片的，所以才导致我认为不能识别多个印章

**Comment by liu-jiaxuan** [comment]
反馈已收到，我们复现下~

**Comment by IceHowe** [comment]
> 反馈已收到，我们复现下~

例如下面的情况
原图：
![image](https://github.com/user-attachments/assets/99bc0995-47f9-45e4-aa1b-7fef0b97fd0d)
结果：
![image](https://github.com/user-attachments/assets/818a96cf-4417-46e4-afa2-6a695bbc1a1e)
原图：
![image](https://github.com/user-attachments/assets/affb68c6-aa94-4026-8615-861ca391810a)
结果：
![image](https://github.com/user-attachments/assets/db1b4928-7554-4a2e-a8f6-013d73189390)
裁剪后：
![image](https://github.com/user-attachments/assets/c806ec56-8e86-48b8-946f-939a679ae7a8)

**Comment by Sunting78** [comment]
您好 ，这个是版面模型对灰色印章识别的结果会比较差，我们带有印章的数据集略少，您可以微调版面模型，只标注印章这一类，估计几百张即可，训练一个专用模型。后续我们的官方版面模型也会优化。
