### ISSUE TITLE
PaddleX 通用OCR产线怎么将print的结果保存到变量里，重定向后显示不可读的

### ISSUE THREAD

**Issue by zwy-0766** [PaddlePaddle/PaddleX#2671]
代码如下：
from paddlex import create_pipeline
import sys
import io

output=io.StringIO()
sys.stdout=output

pipeline = create_pipeline(pipeline="OCR",device="cpu")
output = pipeline.predict("D:/Barcode/A0001.jpg")
for res in output:
    res.print()
    sys,stdout=sys.__stdout__
    output_str=output.getvalue()
    print(output_str)

Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\Upload File\test.py", line 13, in <module>
    sys,stdout=sys.__stdout__
io.UnsupportedOperation: not readable

**Comment by cuicheng01** [comment]
`res.json`，该属性可以直接拿到结果

**Comment by zwy-0766** [comment]
> `res.json`，该属性可以直接拿到结果

![image](https://github.com/user-attachments/assets/55632152-f731-4670-88e1-d0fa89736586)

json格式保存会中文乱码

**Comment by zwy-0766** [comment]
> > `res.json`，该属性可以直接拿到结果
> 
> ![image](https://private-user-images.githubusercontent.com/191821161/396340238-55632152-f731-4670-88e1-d0fa89736586.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MDY5OTgsIm5iZiI6MTczNDQwNjY5OCwicGF0aCI6Ii8xOTE4MjExNjEvMzk2MzQwMjM4LTU1NjMyMTUyLWY3MzEtNDY3MC04OGUxLWQwZmE4OTczNjU4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QwMzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2YwYTIxMGY3MTQ2MTZmYjM1Yjg2ZWE5MDgwZjcwZjgwMzI1ZmZlMzhhZWQ5ZDIxY2Y4YWNjMTFmMDZmMWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oyF6uAY69aXj7RuH50GHcq0VK9dqW2pKbNR_Jp_73c0)
> 
> json格式保存会中文乱码

没事了  用GB 2312重新打开就行了

**Comment by cuicheng01** [comment]
好的，问题我就关闭了，有新问题可以继续打开
