### ISSUE TITLE
恢复训练模型过程阻塞

### ISSUE THREAD

**Issue by wchange** [PaddlePaddle/PaddleX#271]
> model = pdx.det.MaskRCNN(num_classes=num_classes, backbone='ResNet50')
> 
> model.train(
>     num_epochs=200,
>     train_dataset=train_dataset,
>     train_batch_size=2,
>     eval_dataset=eval_dataset,
>     learning_rate=0.00125,
>     warmup_steps=10,
>     lr_decay_epochs=[8, 11],
>     save_dir='output/mask_rcnn_r50_fpn',
>     resume_checkpoint='output/mask_rcnn_r50_fpn/epoch_200',
>     use_vdl=True)

paddlex训练maskrcnn，想从200轮接着训练

运行后一直卡在加载完参数的步骤之后，如下图：
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/15187873/89780239-9ce88f80-db43-11ea-8f2c-eecf41585efe.png">

**Comment by jiangjiajun** [comment]
经沟通，是由于模型是在200轮训练保存的，而在恢复训练时，设置的num_epochs也是200，因为加载完后即结束，需要确保设置的num_epochs > 训练保存时所在的轮数。

更建议使用pretrain_weights。
