### ISSUE TITLE
使用预加载模型进行训练，可不可以像从头训练模yaml一样，修改均值等的一些参数调整

### ISSUE THREAD

**Issue by ZhouBay-TF** [PaddlePaddle/PaddleX#2719]
当我准备使用官方预训练代码训练我的数据时，如何调整一些参数，我的训练指令是python main.py -c paddlex/configs/image_classification/SwinTransformer_large_patch4_window12_384.yaml -o Global.mode=train -o Global.dataset_dir=/media/

**Comment by TingquanGao** [comment]
是想要修改哪些参数呢？重要的参数在配置文件`paddlex/configs/image_classification/SwinTransformer_large_patch4_window12_384.yaml`中可以直接修改。更多的参数可以修改配置文件`paddlex/repo_apis/PaddleClas_api/configs/SwinTransformer_large_patch4_window12_384.yaml`

**Comment by ZhouBay-TF** [comment]
好的，谢谢。
