### ISSUE TITLE
paddlex训练出来的模型怎么查看网络结构

### ISSUE THREAD

**Issue by tuya-yu** [PaddlePaddle/PaddleX#285]

**Comment by lailuboy** [comment]
可以使用visualdl查看。
安装visuadl后使用visualdl --model ./log/model --port 8080启动visualdl，然后通过浏览器访问本机8080端口页面即可。
或者启动visualdl通过点击Graph模块，一键上传模型文件即可查看。

**Comment by tuya-yu** [comment]
import paddlehub as hub
from paddle.fluid.contrib.model_stat import summary

model = hub.Module(name="vgg16_imagenet")

input_dict, output_dict, program = model.context(trainable=True)
summary(program)

============================================run=============================


+-----+--------+-----------------+-----------------+-----------+------------+
| No. |   TYPE |           INPUT |          OUTPUT |    PARAMs |      FLOPs |
+-----+--------+-----------------+-----------------+-----------+------------+
|   0 | conv2d |   (3, 224, 224) |  (64, 224, 224) |      1728 |  173408256 |
|   1 |   relu |  (64, 224, 224) |  (64, 224, 224) |         0 |   -3211264 |
|   2 | conv2d |  (64, 224, 224) |  (64, 224, 224) |     36864 | 3699376128 |
|   3 |   relu |  (64, 224, 224) |  (64, 224, 224) |         0 |   -3211264 |
|   4 | pool2d |  (64, 224, 224) |  (64, 112, 112) |         0 |    3211264 |
|   5 | conv2d |  (64, 112, 112) | (128, 112, 112) |     73728 | 1849688064 |
|   6 |   relu | (128, 112, 112) | (128, 112, 112) |         0 |   -1605632 |
|   7 | conv2d | (128, 112, 112) | (128, 112, 112) |    147456 | 3699376128 |
|   8 |   relu | (128, 112, 112) | (128, 112, 112) |         0 |   -1605632 |
|   9 | pool2d | (128, 112, 112) |   (128, 56, 56) |         0 |    1605632 |
|  10 | conv2d |   (128, 56, 56) |   (256, 56, 56) |    294912 | 1849688064 |
|  11 |   relu |   (256, 56, 56) |   (256, 56, 56) |         0 |    -802816 |
|  12 | conv2d |   (256, 56, 56) |   (256, 56, 56) |    589824 | 3699376128 |
|  13 |   relu |   (256, 56, 56) |   (256, 56, 56) |         0 |    -802816 |
|  14 | conv2d |   (256, 56, 56) |   (256, 56, 56) |    589824 | 3699376128 |
|  15 |   relu |   (256, 56, 56) |   (256, 56, 56) |         0 |    -802816 |
|  16 | pool2d |   (256, 56, 56) |   (256, 28, 28) |         0 |     802816 |
|  17 | conv2d |   (256, 28, 28) |   (512, 28, 28) |   1179648 | 1849688064 |
|  18 |   relu |   (512, 28, 28) |   (512, 28, 28) |         0 |    -401408 |
|  19 | conv2d |   (512, 28, 28) |   (512, 28, 28) |   2359296 | 3699376128 |
|  20 |   relu |   (512, 28, 28) |   (512, 28, 28) |         0 |    -401408 |
|  21 | conv2d |   (512, 28, 28) |   (512, 28, 28) |   2359296 | 3699376128 |
|  22 |   relu |   (512, 28, 28) |   (512, 28, 28) |         0 |    -401408 |
|  23 | pool2d |   (512, 28, 28) |   (512, 14, 14) |         0 |     401408 |
|  24 | conv2d |   (512, 14, 14) |   (512, 14, 14) |   2359296 |  924844032 |
|  25 |   relu |   (512, 14, 14) |   (512, 14, 14) |         0 |    -100352 |
|  26 | conv2d |   (512, 14, 14) |   (512, 14, 14) |   2359296 |  924844032 |
|  27 |   relu |   (512, 14, 14) |   (512, 14, 14) |         0 |    -100352 |
|  28 | conv2d |   (512, 14, 14) |   (512, 14, 14) |   2359296 |  924844032 |
|  29 |   relu |   (512, 14, 14) |   (512, 14, 14) |         0 |    -100352 |
|  30 | pool2d |   (512, 14, 14) |     (512, 7, 7) |         0 |     100352 |
|  31 |    mul |     (512, 7, 7) |         (4096,) | 102760449 |  102760448 |
|  32 |   relu |         (4096,) |         (4096,) |         0 |      -4096 |
|  33 |    mul |         (4096,) |         (4096,) |  16777217 |   16777216 |
|  34 |   relu |         (4096,) |         (4096,) |         0 |      -4096 |
|  35 |    mul |         (4096,) |         (1000,) |   4096001 |    4096000 |
+-----+--------+-----------------+-----------------+-----------+------------+
Total PARAMs: 138344131(138.3441M)
Total FLOPs: 30809460736(30.81G)

这样的输出在paddlex中如何获得

**Comment by jiangjiajun** [comment]
> from paddle.fluid.contrib.model_stat import summary

参考如下示例代码, PaddleX将模型前向网络存在`test_prog`里面

```
import paddlex as pdx
from paddle.fluid.contrib.model_stat import summary
model = pdx.load_model('yolov3_mobilenetv1_coco')

summary(model.test_prog)
```
