### ISSUE TITLE
paddlex gui目标检测模型

### ISSUE THREAD

**Issue by xgyyao** [PaddlePaddle/PaddleX#296]
PaddleX GUI: https://www.paddlepaddle.org.cn/paddle/paddleX (请在ISSUE内容中保留此行内容)
目前gui的目标检测是只支持yolov3以及fasterrcnn两种模型吗？
后续会增加其他模型吗？谢谢！

**Comment by lailuboy** [comment]
本周会加上PPYOLO，后续也会根据需求集成其他的模型

**Comment by jiangjiajun** [comment]
> 本周会加上PPYOLO，后续也会根据需求集成其他的模型

目前已经集成PPYOLO，前往官网下载最新版本PaddleX GUI即可
https://www.paddlepaddle.org.cn/paddle/paddleX
