### ISSUE TITLE
树莓派部署后数据处理

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleX#321]
问题类型：模型部署
**问题描述**  
树莓派完成部署后，想对检测后输出的数据，xmin,ymin,xmax,ymax进一步传入另一个代码文件处理控制，现在只能输出到控制台，怎么处理？
========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by jiangjiajun** [comment]
@syyxsxx

**Comment by syyxsxx** [comment]
@lhy823436493 
您好，可以把数据后处理代码放在deploy/raspberry/demo/detector.cpp中88行model.predict(im, &result);的后面，Box的坐标值在result.boxes[i].coordinat；

**Comment by syyxsxx** [comment]
@lhy823436493 
您好，可以将数据后处的代码放在deploy/raspberry/demo/detector.cpp中88行'model.predict(im, &result);'的后面
另外后续会在树莓派下提供PaddleX部署的.so文件，可以通过动态库调用PaddleX的predict接口

**Comment by Monday-Leo** [comment]
能够有python的实现方式吗？

**Comment by syyxsxx** [comment]
> 能够有python的实现方式吗？

@lhy823436493 
PaddleX在树莓派下部署支持python，具体参考：https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/deploy/raspberry/python.md
代码路径：
https://github.com/PaddlePaddle/PaddleX/tree/develop/deploy/raspberry/python
