### ISSUE TITLE
batch_size问题

### ISSUE THREAD

**Issue by ZhijunLStudio** [PaddlePaddle/PaddleX#322]
GPU为1660ti，使用paddlex的yolov3模型训练，当batch_size设为4的时候可以正常运行，设置8,16,32都不能跑，这是什么原因呢
![微信图片_20200922161820](https://user-images.githubusercontent.com/60954978/93858996-a0009f00-fcef-11ea-8779-0ebea3d5d77b.png)

**Comment by jiangjiajun** [comment]
> GPU为1660ti，使用paddlex的yolov3模型训练，当batch_size设为4的时候可以正常运行，设置8,16,32都不能跑，这是什么原因呢
> ![微信图片_20200922161820](https://user-images.githubusercontent.com/60954978/93858996-a0009f00-fcef-11ea-8779-0ebea3d5d77b.png)

你的显存是多大呢，可能是显存不够的原因
