### ISSUE TITLE
检测模型怎么测量偏移角度

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleX#341]
问题类型：其它  
**问题描述**  
图片中检测出物体后，怎么测量出物体偏移的角度？检测模型能不能做到？是否需要用分割模型？
========================

请在这里描述您的问题

**Comment by jiangjiajun** [comment]
> # 问题类型：其它
> **问题描述**
> 图片中检测出物体后，怎么测量出物体偏移的角度？检测模型能不能做到？是否需要用分割模型？
> 请在这里描述您的问题

可以考虑使用分割，然后通过对分割出来的面积拟合一个矩形，从而得到角度
