### ISSUE TITLE
使用GPU预测

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleX#343]
问题类型：其它  
**问题描述**  
ppyolo训练完模型下载到本地电脑预测，显示paddlegpu已经安装成功，model.predict()过程中GPU占用率很低，每秒6帧左右，请问怎么打开GPU预测视频流。
========================

请在这里描述您的问题

**Comment by FlyingQianMM** [comment]
为追求更高的预测性能，建议使用paddlex.deploy.Predictor接口，该接口中通过use_gpu设置是否打开GPU。
可参考文档 https://paddlex.readthedocs.io/zh_CN/develop/deploy/server/python.html
