### ISSUE TITLE
resume之后，为啥学习率变成了0？

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleX#380]
[TRAIN] Epoch 34 finished, loss=0.026103, lr=0.0 .

**Comment by jiangjiajun** [comment]
> [TRAIN] Epoch 34 finished, loss=0.026103, lr=0.0 .

学习率在模型训练过程中，一般都是先从warmup开始，从很小的学习率一到增长到设定的学习率。 当训练到一定轮数后，又会开始衰减到较低的值。

当前你使用的是Resume模式，恢复训练一般用于模型在训练过程中，提前中止后，如若想恢复训练，则使用Resume

Resume会加载先前保存的模型，迭代轮数会从保存模型所在的轮数开始，同理学习率也是一样。因此在你这个示例中，应该是从恢复的那轮开始，学习率已经较低（由于太低，显示为0.0）。


如若只是想Fine-Tune，建议将此模型作为Pretrain Weights传给train函数进行训练

**Comment by deep-practice** [comment]
明白了，谢谢。
