### ISSUE TITLE
paddlex linux C++编译通过，但运行Demo报找不到so文件

### ISSUE THREAD

**Issue by zhihonglujon** [PaddlePaddle/PaddleX#392]
![图片](https://user-images.githubusercontent.com/58358103/98515116-86b6b080-22a5-11eb-9c11-ba9345620d4c.png)

**Comment by zhihonglujon** [comment]
这个so文件还是paddlex工具包里的，系统为ubuntu18.04.为什么呢？

**Comment by FlyingQianMM** [comment]
之前提供的opencv预编译包有点问题，该问题已解决，目前已经上传最新的预编译包。您将build与deps文件夹删除，再重新编译c++代码即可。

**Comment by zhihonglujon** [comment]
![Uploading 图片.png…]()
将build与deps文件夹删除，再重新编译c++代码，出这个错误。

**Comment by zhihonglujon** [comment]
![Uploading 图片.png…]()

**Comment by zhihonglujon** [comment]
/home/zzj/图片/2020-11-11 09-43-36 的屏幕截图.png

**Comment by zhihonglujon** [comment]
将build与deps文件夹删除，再重新编译c++代码，出这个错误。
![Uploading 2020-11-11 09-43-36 的屏幕截图.png…]()

**Comment by zhihonglujon** [comment]
opencv3.4.6gcc4.8ffmpeg_ubuntu_18.04/lib/libopencv_objdetect.so
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done

CMake Error at CMakeLists.txt:122 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/zzj/work3/paddle/Paddlexcode/PaddleX/deploy/cpp/build/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。

**Comment by FlyingQianMM** [comment]
g++和gcc版本是多少？我们测试是用的4.8.5的，如果是高版本，需要降低gcc和g++的版本

**Comment by zhihonglujon** [comment]
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done

CMake Error at CMakeLists.txt:122 (find_package):
  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/zzj/work3/paddle/Paddlexcode/PaddleX/deploy/cpp/build/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。
zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu8' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu8) 
zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu8' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu8)

**Comment by zhihonglujon** [comment]
之前，系统是7.5版本，为了安装Paddlex已经降级到4.8.5版本了。还是说要单独编译安装opencv?

**Comment by FlyingQianMM** [comment]
你看下deps文件夹下面有opencv的包么，看下是不是没下载下来

**Comment by zhihonglujon** [comment]
有的，/home/zzj/图片/2020-11-11 10-37-14 的屏幕截图.png

**Comment by zhihonglujon** [comment]
![Uploading 2020-11-11 10-37-14 的屏幕截图.png…]()

**Comment by zhihonglujon** [comment]
/paddle/Paddlexcode/PaddleX/deploy/cpp/deps/opencv3.4.6gcc4.8ffmpeg_ubuntu_18.04$ ls
bin  include  lib  share

**Comment by zhihonglujon** [comment]
zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp/deps/opencv3.4.6gcc4.8ffmpeg_ubuntu_18.04$ ls
bin  include  lib  share
zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp/deps/opencv3.4.6gcc4.8ffmpeg_ubuntu_18.04$ cd ..
zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp/deps$ ls
opencv3.4.6gcc4.8ffmpeg_ubuntu_18.04
zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp/deps$

**Comment by zhihonglujon** [comment]
这个OpenCVConfig.cmake文件也是有的。

zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp/deps/opencv3.4.6gcc4.8ffmpeg_ubuntu_18.04/share/OpenCV$ ls
haarcascades        OpenCVConfig-version.cmake   valgrind_3rdparty.supp
lbpcascades         OpenCVModules.cmake          valgrind.supp
OpenCVConfig.cmake  OpenCVModules-release.cmake

**Comment by FlyingQianMM** [comment]
你先把deps/opencv3.4.6gcc4.8ffmpeg_ubuntu_18.04改成deps/opencv3.4.6gcc4.8ffmpeg，我再重新上传下预编译包

**Comment by zhihonglujon** [comment]
修改后，编译过了。但执行DEMO 还是出现之前的缺少so 文件。
[ 85%] Linking CXX shared library lib/libpaddlex_inference.so
[ 87%] Linking CXX executable demo/video_segmenter
[ 90%] Linking CXX executable demo/detector
[ 92%] Linking CXX executable demo/classifier
[ 95%] Linking CXX executable demo/video_detector
[ 95%] Built target paddlex_inference
[ 95%] Built target detector
[ 95%] Built target video_segmenter
[ 95%] Built target classifier
[ 97%] Linking CXX executable demo/segmenter
[100%] Linking CXX executable demo/video_classifier
[100%] Built target video_detector
[100%] Built target segmenter
[100%] Built target video_classifier
zzj@zzj:~/work3/paddle/Paddlexcode/PaddleX/deploy/cpp$ ./build/demo/video_detector --model_dir=~/work2/paddlextrainedmodel/zzj_helmat_ppyolo_for_server  --video_path=~/work1/20200506_170555.mp4  --use_gpu=1 --save_dir=output --show_result=1 --save_result=1
./build/demo/video_detector: error while loading shared libraries: libopencv_imgcodecs.so.3.4: cannot open shared object file: No such file or directory

**Comment by FlyingQianMM** [comment]
尝试使用sudo权限进行编译，你可以在～/.bashrc里面加上export LD_LIBRARY_PATH=/path/to/deps/opencv3.4.6gcc4.8ffmpeg/lib:$LD_LIBRARY_PATH，然后souce ~/.bashrc进行生效

**Comment by zhihonglujon** [comment]
按这个方式应用了，还是不行。
之前，这个机器上安装了openvino,openvino绑定安装了opencv4.1.会不会是不同版本引起的。
编译paddlex需要哪些opencv目录结构呢？能不能和openvino共用opencv编译包呢？
