### ISSUE TITLE
目标检测能不能支持自定义anchor

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleX#419]
PaddleX非常好用，我这种电脑小白都可以轻松开发应用，支持国产，支持PaddlePaddle

那么请问目标检测能不能支持自定义anchor或者自动聚类anchor并导入

未来能不能支持PaddleSeg，PaddleDetection等的模型yaml导入，以支持更多的模型，谢谢

**Comment by jiangjiajun** [comment]
> PaddleX非常好用，我这种电脑小白都可以轻松开发应用，支持国产，支持PaddlePaddle
> 
> 那么请问目标检测能不能支持自定义anchor或者自动聚类anchor并导入
> 
> 未来能不能支持PaddleSeg，PaddleDetection等的模型yaml导入，以支持更多的模型，谢谢

目前可视化客户端还未支持anchor等参数，我们提示的Python API方式进行模型训练已经支持anchor参数的设置

- Python API方式训练YOLOv3模型示例： https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/object_detection/yolov3_mobilenetv1.py
- YOLOv3 API接口说明: https://paddlex.readthedocs.io/zh_CN/develop/apis/models/detection.html#paddlex-det-yolov3

关于客户端支持更多参数设置，以及其它模型套件的支持，我们会评估需求加入，多谢反馈

**Comment by fanweiya** [comment]
好的，谢谢
