### ISSUE TITLE
实例分割数据集导入出错

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleX#421]
非常感谢能开发出这么简单易操作的软件，支持国产，支持paddlepaddle
我的数据集在
我在导入实例分割数据集时出现了这样的错误，[数据集在这](https://cowtransfer.com/s/54fdb94054c94e)，可以帮忙看下是哪里出问题了吗？谢谢
数据校验失败！

Traceback (most recent call last):
  File "paddlexui\pms\dataset\operate.py", line 42, in _check_and_copy
  File "paddlexui\pms\dataset\ins_seg_dataset.py", line 101, in check_dataset
  File "paddlexui\pms\dataset\utils.py", line 239, in get_npy_from_coco_json
KeyError: '0.jpg'

**Comment by jiangjiajun** [comment]
感谢对飞桨的支持，此情况下，需先确认是否有0.jpg这个文件存在

**Comment by jiangjiajun** [comment]
下载了您提供的数据，发现里面的json文件中存在一点问题，请问是通过PaddleX将labelme的标注数据转换为coco格式的吗

在当前的annotation.json文件中，图像路径存储显示如下
![image](https://user-images.githubusercontent.com/19339784/100420304-2c00bf80-30c1-11eb-8012-c0400ccd7396.png)
需删除json文件中所有的JPEGImages\\字符串，改为如下
![image](https://user-images.githubusercontent.com/19339784/100420342-3cb13580-30c1-11eb-963c-0cde4870ee57.png)

**Comment by fanweiya** [comment]
不是，我是用labelme里的labelme2coco脚本，请问使用paddleX转labelme，为什么cricle标注转完之后没有显示呢

**Comment by jiangjiajun** [comment]
PaddleX在转换目标检测的标注数据时，只支持Rectangle和Poly

**Comment by fanweiya** [comment]
因为我做的对象大部分都是圆形，PaddleX能不能支持cricle标注转换，我看这个[issues](https://github.com/wkentaro/labelme/issues/537)，提到了圆形标注转换的方法，能不能加进去？谢谢
```
    # Support for circle shape by Stephan Janssen (sja@devoxx.com)
            if shape_type == "circle":
                
                # Create polygon shaped based on connecting lines from/to following degress
                bearing_angles = [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 
                180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360]
                            
                orig_x1 = points[0][0] 
                orig_y1 = points[0][1] 

                orig_x2 = points[1][0]
                orig_y2 = points[1][1]

                # Calculate radius of circle
                cx = (orig_x2 - orig_x1)**2
                cy = (orig_y2 - orig_y1)**2
                radius = math.sqrt(cx + cy)

                circle_polygon = []
            
                for i in range(0, len(bearing_angles) - 1):
                    ad1 = math.radians(bearing_angles[i])
                    x1 = radius * math.cos(ad1)
                    y1 = radius * math.sin(ad1)
                    circle_polygon.append( (orig_x1 + x1, orig_y1 + y1) )

                    ad2 = math.radians(bearing_angles[i+1])
                    x2 = radius * math.cos(ad2)  
                    y2 = radius * math.sin(ad2)
                    circle_polygon.append( (orig_x1 + x2, orig_y1 + y2) )

                points = circle_polygon

            else:
                points = np.asarray(points).flatten().tolist()
            
            segmentations[label].append(points)                
```

**Comment by jiangjiajun** [comment]
这个需求比较少见，不过当前你可以先使用这个方式将圆形转成polyline的形式。至于本issue最开始提到数据无法导入的问题，建议用文本编辑器直接打开这个annotation.json文件，然后将里面的'JPEGImages\\'字符串替换为空即可以导入了

**Comment by fanweiya** [comment]
我试了下，这种转完的数据，paddleX识别不出mask，显示不出mask标注图，您能看下是怎么回事吗？数据在这[数据](https://cowtransfer.com/s/a7c3fb3adaa143)

**Comment by SunAhong1993** [comment]
> 我试了下，这种转完的数据，paddleX识别不出mask，显示不出mask标注图，您能看下是怎么回事吗？数据在这[数据](https://cowtransfer.com/s/a7c3fb3adaa143)

你好，这边查看到所有的segmentation都是有一模一样的，都不在box中，所以画不出来
![image](https://user-images.githubusercontent.com/48579383/100567117-bb48e580-3302-11eb-9c77-dfe4635e2b9c.png)

**Comment by fanweiya** [comment]
嗯，我也发现了，是上面那个转换脚本有问题
