### ISSUE TITLE
paddle模型转openvino模型后，使用openvino重复预测同一张图结果不一致

### ISSUE THREAD

**Issue by wangyuan111** [PaddlePaddle/PaddleX#434]
问题类型：模型部署
**问题描述**  

模型 MobileNetV3_small分类模型

转openvino
![image](https://user-images.githubusercontent.com/39080886/101275318-b9d65c00-37df-11eb-9aac-626745d030b7.png)

vs2019 cmake
![image](https://user-images.githubusercontent.com/39080886/101275337-cfe41c80-37df-11eb-8bf3-f25be91000ae.png)

同一条命令同一张图，预测结果不一样。类别只有4类。
![微信图片_20201206162504](https://user-images.githubusercontent.com/39080886/101275354-f43ff900-37df-11eb-9cb4-be8f26be3855.png)

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by wangyuan111** [comment]
上图第二次预测结果是对的。重复测试，预测准确的结果大约占30%

**Comment by jiangjiajun** [comment]
@syyxsxx

**Comment by syyxsxx** [comment]
@wangyuan111 
您好，能否提供PaddleX训练出来的模型以及测试图片我这边复现下问题

**Comment by wangyuan111** [comment]
已发送到微信

**Comment by jiangjiajun** [comment]
此问题在于先前OpenVINO部署的C++代码中，在结果的后处理存在问题（Python代码无此问题），目前已通过此PR修复，拉取最新的GitHub代码即可解决。 https://github.com/PaddlePaddle/PaddleX/pull/435

**Comment by wangyuan111** [comment]
拉取最新代码，复测问题已修复。谢谢@jiangjiajun
