### ISSUE TITLE
paddleX语义分割后处理中，宽高不一致时，结果变形

### ISSUE THREAD

**Issue by wangyuan111** [PaddlePaddle/PaddleX#466]
**问题类型**：模型部署

**问题描述**  
paddleX语义分割后处理中，宽高不一致时，结果变形。

**原因**：
后处理取预处理存放的原始宽高时 拿反了。

**解决办法：**
修改..\PaddleX2\deploy\cpp\src\paddlex.cpp和..\PaddleX2\deploy\openvino\src\paddlex.cpp两个文件语义分割后处理
将宽高对调，并且修复resize里的宽高错误。

![image](https://user-images.githubusercontent.com/39080886/102686519-2fe8b300-4223-11eb-8eb1-458dc56b95ea.png)

**Comment by jiangjiajun** [comment]
请问这个ISSUE中的问题存在吗？看您那边又close掉了这个issue @wangyuan111

**Comment by wangyuan111** [comment]
我看到这个问题paddlex在6月份已经修复了，我这边用新版本已经没问题了。谢谢
