### ISSUE TITLE
为什么OpenVINO部署detection模型不支持VPU?

### ISSUE THREAD

**Issue by littlepure2333** [PaddlePaddle/PaddleX#483]
![image](https://user-images.githubusercontent.com/36270711/103291110-04857580-4a26-11eb-8e00-84549de36917.png)

**Comment by syyxsxx** [comment]
@littlepure2333 
您好，由于检测模型转完OpenVINO IR之后，VPU下不支持某些算子，导致检测模型不能在VPU下部署

**Comment by jiangjiajun** [comment]
我们正在和OpenVINO进行合作，推动更多模型算子的支持，后续会在VPU上支持更多模型 @littlepure2333

**Comment by littlepure2333** [comment]
好的，期待你们早日支持💪
