### ISSUE TITLE
PaddleX GUI可视化客户端界面显示不全，无法切分数据集

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/PaddleX#484]
问题类型：PaddleX可视化客户端  
**问题描述**  

===================================  

电脑型号：联想拯救者Y7000P

PaddleX的GUI版本在本机上显示不全，无法看到数据切分按钮，其他的一些UI和字体也显示不全，个人信息显示那儿也无法点击和修改
![I32MQL NLN}~~P `M9@@0VV](https://user-images.githubusercontent.com/71769312/103333586-5e7b4f00-4aa9-11eb-841e-f221f7facfcc.png)
![NMGV_VDM~`$2EH394V2MT~K](https://user-images.githubusercontent.com/71769312/103333590-60451280-4aa9-11eb-9013-55c72d805835.png)
![O ULG `BV1M)XYZ4Y7I$33](https://user-images.githubusercontent.com/71769312/103333591-60dda900-4aa9-11eb-8404-e4a55ac556f0.png)

**Comment by lailuboy** [comment]
在系统显示属性中，将缩放设置为100%
<img width="728" alt="image" src="https://user-images.githubusercontent.com/22521767/103334797-b5832300-4aad-11eb-8294-7a9e46b71fff.png">
