### ISSUE TITLE
macOS 运行 PaddleX 10分钟上手程序失败

### ISSUE THREAD

**Issue by snowind** [PaddlePaddle/PaddleX#545]
运行环境： macOS big sur 11.1 
Python: 3.8.5 
Conda 管理

https://paddlex.readthedocs.io/zh_CN/develop/quick_start.html  

在macOS上通过Conda创建 paddlex 包管理环境，并安装： 
paddlepaddle==1.8.5 
paddlex==1.3.4
paddle==1.0.2 
paddlehub==1.8.3 

运行示例代码： https://github.com/PaddlePaddle/PaddleX/blob/develop/tutorials/train/image_classification/mobilenetv3_small_ssld.py  失败。
请教是什么问题导致？   
同样的操作和配置，在Ubuntu16.04 运行没有问题。 

谢谢！

报错误信息： 
ttributeError: Can't pickle local object 'multiprocess_reader.<locals>._read_into_queue'
Traceback (most recent call last):
  File "paddle_train.py", line 44, in <module>
    model.train(
  File "/Users/ZhouHui/opt/anaconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/models/classifier.py", line 197, in train
    self.train_loop(
  File "/Users/ZhouHui/opt/anaconda3/envs/paddlex/lib/python3.8/site-packages/paddlex/cv/models/base.py", line 496, in train_loop
    for step, data in enumerate(self.train_data_loader()):
  File "/Users/ZhouHui/opt/anaconda3/envs/paddlex/lib/python3.8/site-packages/paddle/fluid/reader.py", line 1104, in __next__
    return self._reader.read_next()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::EnforceNotKilled()
2   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::Receive(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
4   std::__1::__packaged_task_func<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0>, std::__1::allocator<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0> >, unsigned long ()>::operator()()
5   std::__1::packaged_task<unsigned long ()>::operator()()
6   ThreadPool::ThreadPool(unsigned long)::'lambda'()::operator()() const
7   void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPool::ThreadPool(unsigned long)::'lambda'()> >(void*)

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/reader/blocking_queue.h:141)

**Comment by jiangjiajun** [comment]
Mac上无法使用GPU，尝试降低batch_size，重新训练看下

**Comment by snowind** [comment]
export CPU_NUM=4 

将 paddle_train.py 中的train_batch_size 改成 8， 还是失败。 

model.train(
    num_epochs=10,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    lr_decay_epochs=[4, 6, 8],
    learning_rate=0.025,
    save_dir='output/mobilenetv2',
    use_vdl=True)

**Comment by jiangjiajun** [comment]
> export CPU_NUM=4
> 
> 将 paddle_train.py 中的train_batch_size 改成 8， 还是失败。
> 
> model.train(
> num_epochs=10,
> train_dataset=train_dataset,
> train_batch_size=8,
> eval_dataset=eval_dataset,
> lr_decay_epochs=[4, 6, 8],
> learning_rate=0.025,
> save_dir='output/mobilenetv2',
> use_vdl=True)

你好，看这个原因是由于多进程处理数据时导致的问题，你可以参考一下这个issue，将dataset中的多进程处理改成多线程处理
https://github.com/PaddlePaddle/PaddleX/issues/257#issuecomment-667529224

**Comment by snowind** [comment]
已解决， 在macOS 下运行 paddlex 示例程序，需要将 dataset 中的多进程处理改成多线程处理： 
parallel_method='thread' 。 

parallel_method (str): Parallel processing method during the preprocessing of samples in the dataset. Two methods including ‘thread’ thread and ‘process’ process are supported. It is ‘process’ by default (Thread is mandatory in Windows and Mac and this parameter is invalid).

train_dataset = pdx.datasets.SegDataset(
  data_dir='../dataset-all/',
  file_list='../dataset-all/train_dataset/train_list.txt',
  label_list='../dataset-all/labels.txt',
  parallel_method='thread',
  transforms=train_transforms,
  shuffle=True)
eval_dataset = pdx.datasets.SegDataset(
  data_dir='../dataset-all/',
  file_list='../dataset-all/test_dataset/test_list.txt',
  label_list='../dataset-all/labels.txt',
  parallel_method='thread',
  transforms=eval_transforms)
