### ISSUE TITLE
工业仪表计数分割数据标签错误

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/PaddleX#549]
训练集和验证集数据无问题，但meter_seg\annotations标签数据解压缩后全为黑色
![微信截图_20210127105833](https://user-images.githubusercontent.com/52873355/105936536-d6c83680-608e-11eb-9471-341b4b1f4387.png)
![22123123](https://user-images.githubusercontent.com/52873355/105936551-dd56ae00-608e-11eb-9e5b-c7d58fd60fc7.png)

**Comment by FlyingQianMM** [comment]
标签数据的像素值代表了每个类别的id，这个案例里面只有3个类别，类别id分别是0、1、2，所以肉眼看上去是全黑。

**Comment by PhilCuriosity** [comment]
> 标签数据的像素值代表了每个类别的id，这个案例里面只有3个类别，类别id分别是0、1、2，所以肉眼看上去是全黑。

好的，谢谢，我去split一下试试

**Comment by Yaoxingtian** [comment]
> 标签数据的像素值代表了每个类别的id，这个案例里面只有3个类别，类别id分别是0、1、2，所以肉眼看上去是全黑。

请问这三个类别分别是什么？

**Comment by ChaocunChen** [comment]
> 标签数据的像素值代表了每个类别的id，这个案例里面只有3个类别，类别id分别是0、1、2，所以肉眼看上去是全黑。

我按照教程用labelme标注好 用paddlex 转成seg格式后annotations文件夹的数据*png是可以看到标注内容的 是不是哪里出问题了？ @FlyingQianMM

**Comment by PhilCuriosity** [comment]
> > 标签数据的像素值代表了每个类别的id，这个案例里面只有3个类别，类别id分别是0、1、2，所以肉眼看上去是全黑。
> 
> 我按照教程用labelme标注好 用paddlex 转成seg格式后annotations文件夹的数据*png是可以看到标注内容的 是不是哪里出问题了？ @FlyingQianMM

要自己转成0,1,2的单通道的标签

**Comment by PhilCuriosity** [comment]
> > 标签数据的像素值代表了每个类别的id，这个案例里面只有3个类别，类别id分别是0、1、2，所以肉眼看上去是全黑。
> 
> 请问这三个类别分别是什么？

label.txt文件中从上到下的标签。

**Comment by Leelongqi** [comment]
> 

怎么转成0,1,2的单通道的标签？

**Comment by PhilCuriosity** [comment]
> > 
> 
> 怎么转成0,1,2的单通道的标签？

依次判定每个通道每一点像素的值，再在单通道上的相同位置赋值。或者你直接读取灰度图试试
