### ISSUE TITLE
想在paddle2.0rc1版本上实现模型加密部署，其中paddle_security_load_model()的实现细节是怎样的？

### ISSUE THREAD

**Issue by kritohyh** [PaddlePaddle/PaddleX#551]
问题类型：模型部署

 ======================== 
        尝试在2.0rc1版本的paddle inference C++预测库上实现加密部署，而目前paddlex提供的paddlex-encryption工具包含的加密、解密、模型文件解析的动态库是1.8.4版本以及centos7系统下编译的，这样似乎无法直接在jetson平台上使用  
        另外， 想要自己实现模型文件解密以及在内存中加载模型的细节并且编译， 相应的接口是paddle_security_load_model()，  能提供一下这个函数的具体实现细节、源码吗？  因为不知道怎么把文件解密跟SetModelBuffer()串联起来，很难进行下去。。

jetson嵌入式平台： 型号agx xavier  arm64架构
操作系统：ubuntu 18.04   
框架： paddlepaddle 2.0rc1 以及 相应C++预测库

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/2122 参考这个issue说明
