### ISSUE TITLE
paddleX-restfule下载示例项目数据报错，无法下载

### ISSUE THREAD

**Issue by naah69** [PaddlePaddle/PaddleX#553]
paddlehub                 1.8.3                    pypi_0    pypi
paddleslim                1.1.1                    pypi_0    pypi
paddlex                   1.3.4                    pypi_0    pypi
![image](https://user-images.githubusercontent.com/25682169/106084103-9df49400-6158-11eb-96e3-84e9efa6046f.png)
![image](https://user-images.githubusercontent.com/25682169/106084127-acdb4680-6158-11eb-9874-fd5c4a8c4c30.png)

**Comment by lailuboy** [comment]
是不是没有安装paddlepaddle?需要依赖paddlepaddle飞桨框架。
可以参考这里：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/1.8/install/pip/linux-pip.html

**Comment by naah69** [comment]
3q，刚才安装上了，日志不报错了，但是好像还是下载不下来，一直卡在0%

**Comment by lailuboy** [comment]
试试这个文件能不能访问
https://paddlex.bj.bcebos.com/demos/vegetables_cls.tar.gz

**Comment by naah69** [comment]
下载下来了
