### ISSUE TITLE
如何将人体分隔模型生成android可以用的

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/PaddleX#561]
问题类型：模型部署
**问题描述**  
这里有个模型，python命令可以运行
PaddleX/examples/human_segmentation/pretrain_weights/humanseg_mobile_inference
请问怎么把这个模型搞成android可以同的？
========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by jiangjiajun** [comment]
> # 问题类型：模型部署
> **问题描述**
> 这里有个模型，python命令可以运行
> PaddleX/examples/human_segmentation/pretrain_weights/humanseg_mobile_inference
> 请问怎么把这个模型搞成android可以同的？
> 请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

参考此文档 https://paddlex.readthedocs.io/zh_CN/develop/deploy/paddlelite/android.html

**Comment by guojiahuiEmily** [comment]
谢谢
