### ISSUE TITLE
请问我的这个PR该在哪里进行操作

### ISSUE THREAD

**Issue by guojiahuiEmily** [PaddlePaddle/PaddleX#567]
问题类型：其它  
**问题描述**  

请问我发起的这个PR，还需要我签什么东西吗？
我已经同意了CLA了，但是状态好像还是显示说“Contributor License Agreement is not signed yet.”

请问我该在哪里进行操作？

状态信息：
Some checks haven’t completed yet
1 pending check

license/cla Pending — Contributor License Agreement is not signed yet.
Details

**Comment by jiangjiajun** [comment]
感谢对PaddleX文档的修改贡献，已合入：）

**Comment by guojiahuiEmily** [comment]
thanks
