### ISSUE TITLE
使用PaddleX可视化客户端导出的移动端模型部署报Fatal signal 11 (SIGSEGV), code 1

### ISSUE THREAD

**Issue by CLLIFE-henry** [PaddlePaddle/PaddleX#578]
问题类型：模型部署
**问题描述**  

========================  

使用PaddleX可视化客户端导出移动端模型并量化，OK
android studio导入project demo，OK
在资源管理器替换yml和nb，OK
连接华为手机，OK
Build and run，报warning：使用了过时的API，和Error：Fatal signal 11 (SIGSEGV), code 1。

**Comment by FlyingQianMM** [comment]
麻烦您贴一下详细的报错信息～

**Comment by CLLIFE-henry** [comment]
日志
Launching 'app' on Physical Device.
Install successfully finished in 10 s 510 ms.
$ adb shell am start -n "com.baidu.paddlex.lite.demo/com.baidu.paddlex.lite.demo.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7261 on device 'huawei-tas_an00-XPL0219B20004026'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ddlex.lite.dem: Late-enabling -Xcheck:jni
E/ddlex.lite.dem: Unknown bits set in runtime_flags: 0x8000
I/ddlex.lite.dem: Reinit property: dalvik.vm.checkjni= false
    ReInitProperties: persist.vm.debug.dumpapi= false
D/ActivityThread: Attach thread to application
I/ActivityThread: Init compatible state: true
D/HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
I/HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
D/BehaviorCollectManager: hook process for AI virus second
I/BehaviorCollectManager: bindAnalyzerService: huawei.android.security.IAppBehaviorDataAnalyzer$Stub$Proxy@96960f2 pid:7261
I/ActivityThread: finishPreloaded preloadStatus 0
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddlex.lite.demo#10294#256
    need clear apicache,because volumes changed,oldCnt=0 newCnt=1
D/OpenGLRenderer: disableOutlineDraw is true
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.baidu.paddlex.lite.demo#10294#0
    need clear apicache,because volumes changed,oldCnt=1 newCnt=1
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@f289a3e
I/HwPartIawareFactory: add android.common.HwPartIawareFactoryImpl to memory.
I/AwareBitmapCacher: init processName:com.baidu.paddlex.lite.demo pid=7261 uid=10294
V/ActivityThread: callActivityOnCreate
I/DecorView[]:  old windowMode:0 new windoMode:1
I/OverScrollerOptimization: start init SmartSlideOverScroller and get the overscroller config
    get the overscroller config
W/ddlex.lite.dem: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/ddlex.lite.dem: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/OpenCV/StaticHelper: Trying to get library list
E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper: Library list: ""
    First attempt to load libs
    Trying to init OpenCV libs
    Trying to load library opencv_java3
D/OpenCV/StaticHelper: Library opencv_java3 loaded
    First attempt to load libs is OK
I/OpenCV/StaticHelper: General configuration for OpenCV 3.4.6 =====================================
      Version control:               3.4.6
      Platform:
        Timestamp:                   2019-04-07T00:37:06Z
        Host:                        Linux 4.15.0-47-generic x86_64
        Target:                      Linux 1 aarch64
        CMake:                       2.8.12.2
        CMake generator:             Ninja
        CMake build tool:            /usr/bin/ninja
        Configuration:               Release
      CPU/HW features:
        Baseline:                    NEON
          requested:                 NEON FP16
          required:                  NEON
          disabled:                  VFPV3
      C/C++:
        Built as dynamic libs?:      NO
        C++ Compiler:                /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ (ver 4.9)
        C++ flags (Release):         -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG  -DNDEBUG
        C++ flags (Debug):           -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
        C Compiler:                  /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
        C flags (Release):           -fexceptions -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG  -DNDEBUG
        C flags (Debug):             -fexceptions -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
        Linker flags (Release):      -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
        Linker flags (Debug):        -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
        ccache:                      YES
        Precompiled headers:         NO
        Extra dependencies:          z dl m log
        3rdparty dependencies:       quirc libprotobuf tbb libcpufeatures libjpeg-turbo libwebp libpng libtiff libjasper IlmImf tegra_hal
      OpenCV modules:
        To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc java ml objdetect photo shape stitching superres video videoio videostab
        Disabled:                    world
        Disabled by dependency:      -
        Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev js python2 python3 ts viz
        Applications:                android_examples
        Documentation:               NO
        Non-free algorithms:         NO
      Android NDK:                   location: /opt/android/android-ndk-r10e
        Android ABI:                 arm64-v8a
        NDK toolchain:               aarch64-linux-android-4.9
        STL type:                    gnustl_static
        Native API level:            21
      Android SDK:                   /opt/android/android-sdk-java7 (tools: 25.2.2 build tools: 23.0.3)
        android tool:                /opt/android/android-sdk-java7/tools/android
        SDK target:                  android-21
        Projects build scripts:      Ant/Eclipse compatible
      GUI: 
      Media I/O: 
        ZLib:                        z (ver 1.2.3)
        JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
I/OpenCV/StaticHelper:     WEBP:                        build (ver encoder: 0x020e)
        PNG:                         build (ver 1.6.36)
        TIFF:                        build (ver 42 - 4.0.10)
        JPEG 2000:                   build (ver 1.900.1)
        OpenEXR:                     build (ver 1.7.1)
        HDR:                         YES
        SUNRASTER:                   YES
        PXM:                         YES
      Video I/O:
      Parallel framework:            TBB (ver 2018.0 interface 10001)
      Trace:                         YES (built-in)
      Other third-party libraries:
        Custom HAL:                  YES (carotene (ver 0.0.1))
        Protobuf:                    build (3.5.1)
      Python (for build):            /usr/bin/python2.7
      Java:                          export all functions
        ant:                         /usr/bin/ant (ver 1.9.3)
        Java wrappers:               YES
        Java tests:                  NO
      Install to:                    /build/3_4_pack-android/build/o4a/install
    -----------------------------------------------------------------
D/HwGalleryCacheManagerImpl: mIsEffect:false
D/ActivityThread: add activity client record, r= ActivityRecord{7624fb2 token=android.os.BinderProxy@a943343 {com.baidu.paddlex.lite.demo/com.baidu.paddlex.lite.demo.MainActivity}} token= android.os.BinderProxy@a943343
I/MainActivity: begin onResume
I/DecorView[]:  old windowMode:0 new windoMode:1
I/HwPartPowerOfficeFactory: add HwPartPowerOfficeFactoryImpl to memory.
D/InputEventReceiver: dispatchInputInterval 1000000
I/HwPartMagicWindowFactory: add android.common.HwPartMagicWindowFactoryImpl to memory.
D/InputEventReceiver: dispatchInputInterval 1000000
I/RmeSchedManager: init Rme, version is: v1.0
D/OpenGLRenderer: disableOutlineDraw is true
I/iGraphics: [0020080c] pn: com.baidu.paddlex.lite.demo, p: 7261
    [0030080c] no spt app: com.baidu.paddlex.lite.demo
I/FrameFlow: FrameFlowInit app is not supported by frameflow solution
I/: [CAF] out_sc_config: sc_enable=1, max_size=3670016 
    [CAF] sc_policy[0] = 0x0
    [CAF] sc_policy[1] = 0x0
    [CAF] sc_policy[2] = 0x0
    [CAF] sc_policy[3] = 0x0
D/HiTouch_PressGestureDetector: onAttached, package=com.baidu.paddlex.lite.demo, windowType=2, mHiTouchRestricted=false
I/: package[com.baidu.paddlex.lite.demo] pid[7261] game[0]
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/HwForceDark: [SetDarkThemeInfo] enable = [0], appType = [0], winWidth = [1080]
W/Gralloc3: mapper 3.x is not supported
D/OpenCV/StaticHelper: Trying to get library list
E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper: Library list: ""
    First attempt to load libs
    Trying to init OpenCV libs
    Trying to load library opencv_java3
    Library opencv_java3 loaded
    First attempt to load libs is OK
I/OpenCV/StaticHelper: General configuration for OpenCV 3.4.6 =====================================
      Version control:               3.4.6
      Platform:
        Timestamp:                   2019-04-07T00:37:06Z
        Host:                        Linux 4.15.0-47-generic x86_64
        Target:                      Linux 1 aarch64
        CMake:                       2.8.12.2
        CMake generator:             Ninja
        CMake build tool:            /usr/bin/ninja
        Configuration:               Release
      CPU/HW features:
        Baseline:                    NEON
          requested:                 NEON FP16
          required:                  NEON
          disabled:                  VFPV3
      C/C++:
        Built as dynamic libs?:      NO
        C++ Compiler:                /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ (ver 4.9)
        C++ flags (Release):         -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG  -DNDEBUG
        C++ flags (Debug):           -fexceptions -frtti -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
        C Compiler:                  /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
        C flags (Release):           -fexceptions -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -O3 -DNDEBUG  -DNDEBUG
        C flags (Debug):             -fexceptions -Wno-psabi --sysroot=/opt/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=21   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -fomit-frame-pointer   -fvisibility=hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
        Linker flags (Release):      -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
        Linker flags (Debug):        -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
        ccache:                      YES
        Precompiled headers:         NO
        Extra dependencies:          z dl m log
        3rdparty dependencies:       quirc libprotobuf tbb libcpufeatures libjpeg-turbo libwebp libpng libtiff libjasper IlmImf tegra_hal
      OpenCV modules:
        To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc java ml objdetect photo shape stitching superres video videoio videostab
        Disabled:                    world
        Disabled by dependency:      -
        Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev js python2 python3 ts viz
        Applications:                android_examples
        Documentation:               NO
        Non-free algorithms:         NO
I/OpenCV/StaticHelper:   Android NDK:                   location: /opt/android/android-ndk-r10e
        Android ABI:                 arm64-v8a
        NDK toolchain:               aarch64-linux-android-4.9
        STL type:                    gnustl_static
        Native API level:            21
      Android SDK:                   /opt/android/android-sdk-java7 (tools: 25.2.2 build tools: 23.0.3)
        android tool:                /opt/android/android-sdk-java7/tools/android
        SDK target:                  android-21
        Projects build scripts:      Ant/Eclipse compatible
      GUI: 
      Media I/O: 
        ZLib:                        z (ver 1.2.3)
        JPEG:                        build-libjpeg-turbo (ver 2.0.2-62)
        WEBP:                        build (ver encoder: 0x020e)
        PNG:                         build (ver 1.6.36)
        TIFF:                        build (ver 42 - 4.0.10)
        JPEG 2000:                   build (ver 1.900.1)
        OpenEXR:                     build (ver 1.7.1)
        HDR:                         YES
        SUNRASTER:                   YES
        PXM:                         YES
      Video I/O:
      Parallel framework:            TBB (ver 2018.0 interface 10001)
      Trace:                         YES (built-in)
      Other third-party libraries:
        Custom HAL:                  YES (carotene (ver 0.0.1))
        Protobuf:                    build (3.5.1)
      Python (for build):            /usr/bin/python2.7
      Java:                          export all functions
        ant:                         /usr/bin/ant (ver 1.9.3)
        Java wrappers:               YES
        Java tests:                  NO
      Install to:                    /build/3_4_pack-android/build/o4a/install
    -----------------------------------------------------------------
I/Predictor: ConfigParser{model='MobileNetV2', labeList=[atm, dvd, hwd, pem, pfr], numClasses=5, modelType='classifier', transformsMode='RGB', transformsList=[{ResizeByShort={max_size=-1, short_size=109}}, {CenterCrop={crop_size=96}}, {Normalize={mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]}}], modelPath='/data/user/0/com.baidu.paddlex.lite.demo/cache/model.nb', cpuThreadNum=1, cpuPowerMode='LITE_POWER_HIGH', yamlPath='/data/user/0/com.baidu.paddlex.lite.demo/cache/model.yml'}
D/HiTouch_PressGestureDetector: onAttached, package=com.baidu.paddlex.lite.demo, windowType=1, mHiTouchRestricted=false
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/HwViewRootImpl: removeInvalidNode jank list is null
D/OpenGLRenderer: disableOutlineDraw is true
W/libEGL: EGLNativeWindowType 0x75c6db2a10 disconnect failed
D/DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
W/InputMethodManager: startInputReason = 1
D/InputEventReceiver: dispatchInputInterval 1000000
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer: disableOutlineDraw is true
W/InputMethodManager: startInputReason = 5
W/System: A resource failed to call close. 
D/stylus: init stylus touchlistener.
I/Hwaps: APS: EventAnalyzed: initAPS: version is 11.0.0.4
D/Hwaps: Fpsrequest create,type:EXACTLY_IDENTIFY
    Fpsrequest create,type:EXACTLY_IDENTIFY
    Fpsrequest create,type:OPENGL_SETTING
D/Hwaps: FpsController create
D/Hwaps: APS: EventAnalyzed: reInitFpsPara :mBaseFps = 60; mMaxFps = 60
W/Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor: User setup is finished.
W/HwApsManager: HwApsManagerService, registerCallback, start !
D/Hwaps: APS: EventAnalyzed: registerCallbackInApsManagerService, mPkgName:com.baidu.paddlex.lite.demo; result = true
V/AudioManager: querySoundEffectsEnabled...
I/DecorView[]:  old windowMode:0 new windoMode:1
D/InputEventReceiver: dispatchInputInterval 1000000
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 7356 (Predictor Worke), pid 7261 (ddlex.lite.demo)
D/HiTouch_PressGestureDetector: onAttached, package=com.baidu.paddlex.lite.demo, windowType=2, mHiTouchRestricted=false
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/OpenGLRenderer: disableOutlineDraw is true
W/libEGL: EGLNativeWindowType 0x75c6db64d0 disconnect failed
D/DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true

**Comment by FlyingQianMM** [comment]
请问您的华为手机是什么芯片？

**Comment by CLLIFE-henry** [comment]
麒麟990 华为mate30

**Comment by FlyingQianMM** [comment]
@Channingss 帮忙看下这个问题～

**Comment by Channingss** [comment]
默认的demo可以run成功吗？

**Comment by CLLIFE-henry** [comment]
默认的demo可以

**Comment by Channingss** [comment]
请使用以下文档里面的2.3 使用bin文件优化模型(linux)，另外请问一下是什么模型？  https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/deploy/paddlelite/android.md
