### ISSUE TITLE
文档有一个小笔误

### ISSUE THREAD

**Issue by Sharpiless** [PaddlePaddle/PaddleX#58]
[https://paddlex.readthedocs.io/zh_CN/latest/apis/slim.html](https://paddlex.readthedocs.io/zh_CN/latest/apis/slim.html)

此处文档计算参数敏感度为：
`paddlex.slim.cal_params_sensetives(model, save_file, eval_dataset, batch_size=8)`

实际应当写作：

`paddlex.slim.cal_params_sensitivities(model, save_file, eval_dataset, batch_size=8)`

**Comment by jiangjiajun** [comment]
> cal_params_sensitivities

谢谢反馈，已修改。
