### ISSUE TITLE
使用Jetson Nano的C++ 的服务化部署

### ISSUE THREAD

**Issue by Wall-ee** [PaddlePaddle/PaddleX#580]
使用Jetson Nano的C++ 部署完成后，希望使其变成在jetson 中 执行的一项服务，别的机器可以发送HTTP请求，进行识别。

问题类型：模型部署
目前来说 ，参照https://paddlex.readthedocs.io/zh_CN/develop/deploy/jetson/nvidia-jetson.html 的部署方式，可以在jetson本地进行模型推断。  其结果会保存在output文件夹。

但是，希望将识别过程封装为 http 服务。  返回一个json的结果。 然后 客户端拿到结果后，自己根据json 内容，使用 opencv 进行可视化输出，请问该如何处理呢？

jetson 无法在其板子上安装paddlex 全部的python 服务。 

因此有没有：
1，将结果只输出为文本，然后保存
2，将C++预测模型封装成http 服务的方法？

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by FlyingQianMM** [comment]
您好～
1. 因为paddlex依赖paddle，但目前paddle还未提供jetpack下的预编译安装包，所以jetson上暂时还不能直接使用paddlex的python服务。
2. 如果要在jetson上使用paddle，辛苦自行编译生成paddle的安装包，编译过程请参考 https://github.com/PaddlePaddle/Paddle/issues/27402 。预计paddle2.0.1开始发布jetpack4.4和jetpack4.5的预编译包。
3. 目前PaddleX有提供http请求服务化部署，参考文档https://paddlex.readthedocs.io/zh_CN/develop/deploy/hub_serving.html 。服务化部署依赖paddlehub，而目前paddlehub也要依赖paddle，所以还是需要先在jetson上编译生成paddle的安装包。

**Comment by Wall-ee** [comment]
非常感谢 非常感谢！

**Comment by dongyangli-del** [comment]
> * 因为paddlex依赖paddle，但目前paddle还未提供jetpack下的预编译安装包，所以jetson上暂时还不能直接使用paddlex的python服务。

请问paddle2.0时代，现在可以直接使用paddlex的Python服务吗？
