### ISSUE TITLE
裁剪训练通过 resume_checkpoint 来恢复训练进度会报错

### ISSUE THREAD

**Issue by 1107979819** [PaddlePaddle/PaddleX#599]
进行裁剪训练的时候中断了，通过 resume_checkpoint来继续训练，但会报错报错如下。
![QQ20210221-0](https://user-images.githubusercontent.com/7136052/108627739-1584bd00-7492-11eb-8b2f-5ec22bce27c9.png)

**Comment by FlyingQianMM** [comment]
因为之前resume checkpoint只支持了正常训练中的恢复训练，因此模型剪裁过程中的训练无法正常恢复。PR #600  已经修复了该问题，当前模型剪裁支持恢复训练。

pip uninstall paddlex卸载掉原有的paddlex，更新paddlex的代码使用python setup.py install重新安装即可正常使用。
