### ISSUE TITLE
paddlex的模型如何进行多尺度+翻转预测？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#602]
问题类型：其它  
**问题描述**  
我已经训练好了模型，并且使用了model = pdx.load_model('/home/aistudio/Models/HRNet64/best_model/')加载模型，如何进行paddlseg中的多尺度+反转预测？

如
evaluate(
        model,
        val_dataset,
        _**aug_eval=True,
        scales=[0.75, 1.0, 1.25],
        flip_horizontal=True**_)

**Comment by FlyingQianMM** [comment]
出于预测性能的考虑，目前paddlex的分割还没有支持多尺度+翻转预测。后续升级我们会将该功能加入～
