### ISSUE TITLE
cyclical cosine annealing learning rate，目前paddle2.0和paddlex支持吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#605]
最近在做cv，看到了SWA Object Detection，想将这个用于训练模型，查了一下paddle的api文档，只发现了paddle.fluid.layers. cosine_decay和paddle.optimizer.lr.CosineAnnealingDecay，但这两个似乎是针对整个训练流程的，那种每个epoch都来一次的周期余弦退火有吗？

**Comment by FlyingQianMM** [comment]
目前还没有该API实现。
如果要实现12个epoch周期余弦退火学习速率，看下能否用替代解决方案：每个epoch单独训练，然后下一个epoch resume上一个epoch的参数再单独训练。
