### ISSUE TITLE
如何提高PaddleX C++推理时间

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleX#613]
问题类型：模型部署

**问题描述**  

使用resnet50_vd_ssld训练了一个模型，图片大小350*550，使用PaddleX C++推理平均时间大约需要40到55ms（毫秒）,使用hub API大约35到45ms（本机），CPU和GPU差别不大，问题是如何提高推理时间？

========================  

测试环境是ubuntu18.4，本机测试。问题是如何提高推理时间，期望在25ms以下，有什么办法？谢谢。

**Comment by jiangjiajun** [comment]
CPU下，可使用paddlex.deploy.Predictor加载模型，并指定'use_mkl=True, mkl_thread_num=8`，从而使用MKLDNN进行加速

**Comment by abanger** [comment]
> CPU下，可使用paddlex.deploy.Predictor加载模型，并指定'use_mkl=True, mkl_thread_num=8`，从而使用MKLDNN进行加速

请教下C++的“paddlex.deploy.Predictor”接口在那个文件，此接口python有，C++也有？

**Comment by jiangjiajun** [comment]
如果是C++，同理在模型Init时，如果是cpu下,use_gpu为false， 然后将`use_mkl`设为true，同时根据自己的CPU配置，设定`mkl_thread_num`值 
参考这里的代码 https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/demo/detector.cpp#L65

**Comment by abanger** [comment]
发现推理第一张时间比较长，后面的时间会变短。
