### ISSUE TITLE
预训练模型如何保留原来的标签

### ISSUE THREAD

**Issue by ChungTak** [PaddlePaddle/PaddleX#630]
问题类型：模型训练  
**问题描述**  
用安全帽数据集训练出了预测模型，效果很好。
现在想在这个模型基础上再训练反光衣，训练出来的模型能预测反光衣，但安全帽预测功能却没有了，怎样保留之前训练出来的标签？
====================  
步骤描述:
1.用paddlex脚本yolov3_darknet53.py 训练安全帽数据，得出output/yolov3_darknet53/best_model
2.使用paddlex --export_inference 导出模型，测试能识别安全帽
3.修改yolov3_darknet53.py的pretrain_weights ='output/yolov3_darknet53/best_model'指向步骤1的模型,并修改output目录
4.再训练反光衣数据得出新的模型
5.使用paddlex --export_inference 导出最终模型，测试只能识别反光衣

**Comment by jiangjiajun** [comment]
预训练模型在加载时，会直接删掉之前分类的权重，所以当前如果要两种目标都要检测到，那在第4个步骤时，数据应该需要包括反光衣和安全帽

**Comment by ChungTak** [comment]
> 预训练模型在加载时，会直接删掉之前分类的权重，所以当前如果要两种目标都要检测到，那在第4个步骤时，数据应该需要包括反光衣和安全帽

非常感谢你的回复，那就是每次新增一个类别，都要把之前的训练集全量重新训练一遍罗？

**Comment by jiangjiajun** [comment]
> > 预训练模型在加载时，会直接删掉之前分类的权重，所以当前如果要两种目标都要检测到，那在第4个步骤时，数据应该需要包括反光衣和安全帽
> 
> 非常感谢你的回复，那就是每次新增一个类别，都要把之前的训练集全量重新训练一遍罗？

对的
