### ISSUE TITLE
Only the one-channel image is supported

### ISSUE THREAD

**Issue by 60999** [PaddlePaddle/PaddleX#638]
问题类型：模型训练  
**问题描述**  
Exception: Only the one-channel image is supported in the CLAHE operator, but recieved image channel is 3

用的是 model = pdx.det.FasterRCNN(num_classes=num_classes, backbone='ResNet50',keep_top_k =1,input_channel=3)

但是[文档](https://paddlex.readthedocs.io/zh_CN/develop/apis/models/detection.html#paddlex-det-fasterrcnn)里说：input_channel (int): 输入图像的通道数量。默认为3。
====================  
文档错了，还是代码错了。

**Comment by 60999** [comment]
使用PPYOLO也出现了这种问题

**Comment by FlyingQianMM** [comment]
CLAHE增强算子只适用于灰度图，RGB图像不适用

**Comment by 60999** [comment]
这里的意思是，数据增强CLAHE只支持单通道图像，输入的图像是3通道。删除这个增强算子即可。
但是删除后会提示最少要有一个算子，可以保留 transforms.Normalize() 
感谢Jason|PddleX
