### ISSUE TITLE
paddlex slim之后继续训练，与之前的训练epoch是什么关系？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#651]
原始模型已经训练了50个epoch，经过裁剪，生成了sensi.data，加载原始模型和sensi.data进行继续训练，设置epoch为10，那这10个epoch是算新的epoch？还是说算51-60的epoch，与之相关随着epoch改变而改变的lr等参照那种情况？新开始还是原来基础上继续？
另外这个继续训练的epoch一般设置为多少？是根据训练的eval结果自行调整吗？
最后教程里面没有提到预测的细节，只是说了效果。是加载训练后的模型直接预测就可以了，还是要经过export_model之类的方式？

**Comment by jiangjiajun** [comment]
1. 10个epoch是新的epoch，但这里训练时的预训练模型变成了加载的『原始模型』
2. epoch的设置一般与原始训练模型时的参数配置一致
3. 训练后的模型做部署或预测都与之前无异

**Comment by bbbxixixixi** [comment]
> 1. 10个epoch是新的epoch，但这里训练时的预训练模型变成了加载的『原始模型』
> 2. epoch的设置一般与原始训练模型时的参数配置一致
> 3. 训练后的模型做部署或预测都与之前无异

感谢回复，关于第二点，也就是说原始模型训练了50epoch，那prune后继续训练50epoch找最优解是较为通常的做法，是这样理解吧？

**Comment by jiangjiajun** [comment]
是的

**Comment by lleesg** [comment]
请问怎么加载sensi.data进行训练呢？
貌似paddlex2.0后不用显式指定sensitivities_file了
