### ISSUE TITLE
模型转化

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleX#66]
请问用PaddleX做的目标检测的模型能不能转换成PaddleDetection的模型？

**Comment by jiangjiajun** [comment]
模型是一样的，不需要转换，您这里指的转换是什么意思呢？

> 请问用PaddleX做的目标检测的模型能不能转换成PaddleDetection的模型？

**Comment by Monday-Leo** [comment]
![D](https://user-images.githubusercontent.com/53975909/82307137-858d8080-99f2-11ea-9f31-2ba2441e05bc.png)
![X](https://user-images.githubusercontent.com/53975909/82307148-89210780-99f2-11ea-815d-fe5e7aaf1889.png)
导出的模型怎么转化呀，一个是五个文件，一个是三个文件。

**Comment by jiangjiajun** [comment]
> ![D](https://user-images.githubusercontent.com/53975909/82307137-858d8080-99f2-11ea-9f31-2ba2441e05bc.png)
> ![X](https://user-images.githubusercontent.com/53975909/82307148-89210780-99f2-11ea-815d-fe5e7aaf1889.png)
> 导出的模型怎么转化呀，一个是五个文件，一个是三个文件。

安装paddlex后，在命令行终端执行如下命令

```
pip install paddlex -i https://mirror.baidu.com/pypi/simple
paddlex --export_inference --model_dir paddlex_model --save_dir infer_model
```

**Comment by Monday-Leo** [comment]
好的，我试试
