### ISSUE TITLE
如何使加载的模型使用指定的gpu

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#660]
有4张卡，打算加载12个模型，0--2号模型在0卡，3--5号模型在1卡，以此类推
然后起多线程预测，每张卡负责3个模型的处理
要如何指定model使用特定的gpu进行计算？
语言是python

**Comment by FlyingQianMM** [comment]
可以先试下，每个模型加载之前通过os.environ['CUDA_VISIBLE_DEVICES']='x' (x为0, 1, ...)指定显卡
