### ISSUE TITLE
paddlex有使用onnx加速推理的办法吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#669]
slim感觉还是差了那么一些

**Comment by jiangjiajun** [comment]
支持转成ONNX，在CPU可使用OpenVINO进行部署。

**Comment by bbbxixixixi** [comment]
> 支持转成ONNX，在CPU可使用OpenVINO进行部署。

有例子参考吗？

**Comment by jiangjiajun** [comment]
https://paddlex.readthedocs.io/zh_CN/develop/deploy/openvino/index.html

**Comment by bbbxixixixi** [comment]
> https://paddlex.readthedocs.io/zh_CN/develop/deploy/openvino/index.html

我做了一个版本试了下，发现转了之后相比原来GPU版本慢了很多，看了下segment目前只有CPU，VPU，如果是GPU的架构，是不是就不行了?

**Comment by jiangjiajun** [comment]
CPU肯定是慢于GPU的，GPU上的话，如果想提升速度，建议分析下当前速度慢的原于是在于预处理，还是模型在GPU上的推理。
- 如若是预处理慢，建议对源数据进行一定限制，例如减小分辨率，同时修改预处理避免不必要的操作
- 如若是在GPU上推理慢，建议选择更小的模型，如DeepLab选择MobileNet backbone， 或者是FastSCNN模型
