### ISSUE TITLE
用paddlex训练出来的模型，用result结果中的bbox框出来的区域与调用pdx.det.visualize框出来的区域不一样

### ISSUE THREAD

**Issue by MartinDing-hub** [PaddlePaddle/PaddleX#691]
我想问一下，我用paddlex训练出来的模型，为什么我用result结果中的bbox框出来的区域与调用pdx.det.visualize框出来的区域不一样？

![QQ图片20210427133905](https://user-images.githubusercontent.com/70771429/116190901-00f8c580-a75e-11eb-97c4-cab448a1ee8a.png)
（图中，红色细框是我用cv2.rectangle函数根据bbox的数值框出来的，绿框是调用paddlex接口框出来的）

**Comment by lailuboy** [comment]
result中的值是x,y,w,h，cv2.rectangle中的参数是左上角（x，y），右下角（x，y）

**Comment by MartinDing-hub** [comment]
@lailuboy 原来如此，懂了，谢谢！
