### ISSUE TITLE
Cuda error(2), out of memory.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleX#702]
This log file path is /home/***/paddlex_workspace/projects/P0007/T0017/err.log

注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息

/home/hello/PaddleX/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
Process Process-1:14:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 297, in _bootstrap
  File "multiprocessing/process.py", line 99, in run
  File "paddlexui/pms/model_tasks/tasks.py", line 68, in _call_paddlex_train
  File "paddlexui/pms/model_tasks/train/classification.py", line 134, in train
  File "site-packages/paddlex/cv/models/classifier.py", line 469, in train
  File "site-packages/paddlex/cv/models/classifier.py", line 195, in train
  File "site-packages/paddlex/cv/models/base.py", line 244, in net_initialize
  File "site-packages/paddle/fluid/executor.py", line 1071, in run
  File "site-packages/six.py", line 703, in reraise
  File "site-packages/paddle/fluid/executor.py", line 1066, in run
  File "site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
  File "site-packages/paddle/fluid/executor.py", line 1229, in _run_program
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::stream::CUDAStream::Init(paddle::platform::Place const&, paddle::platform::stream::Priority const&)
3   paddle::platform::CUDAContext::CUDAContext(paddle::platform::CUDAPlace const&, paddle::platform::stream::Priority const&)
4   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
5   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
6   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
7   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
8   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
9   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
10  paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
11  paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
12  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
13  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
14  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)
15  _PyMethodDef_RawFastCallKeywords
16  _PyCFunction_FastCallKeywords
17  _PyEval_EvalFrameDefault
18  _PyEval_EvalCodeWithName
19  _PyFunction_FastCallKeywords
20  _PyEval_EvalFrameDefault
21  _PyEval_EvalCodeWithName
22  _PyFunction_FastCallKeywords
23  _PyEval_EvalFrameDefault
24  _PyEval_EvalCodeWithName
25  _PyFunction_FastCallKeywords
26  _PyEval_EvalFrameDefault
27  _PyEval_EvalCodeWithName
28  _PyFunction_FastCallKeywords
29  _PyEval_EvalFrameDefault
30  _PyEval_EvalCodeWithName
31  _PyFunction_FastCallKeywords
32  _PyEval_EvalFrameDefault
33  _PyEval_EvalCodeWithName
34  _PyFunction_FastCallKeywords
35  _PyEval_EvalFrameDefault
36  _PyEval_EvalFrameDefault
37  _PyFunction_FastCallDict
38  _PyEval_EvalFrameDefault
39  _PyEval_EvalFrameDefault
40  _PyEval_EvalFrameDefault
41  _PyEval_EvalFrameDefault
42  _PyFunction_FastCallDict
43  _PyObject_Call_Prepend
44  PyObject_Call
45  _PyEval_EvalFrameDefault
46  _PyEval_EvalCodeWithName
47  _PyFunction_FastCallDict
48  _PyObject_Call_Prepend
49  _PyObject_FastCallKeywords
50  _PyEval_EvalFrameDefault
51  _PyEval_EvalFrameDefault
52  _PyEval_EvalFrameDefault
53  _PyEval_EvalFrameDefault
54  _PyEval_EvalFrameDefault
55  _PyEval_EvalFrameDefault
56  _PyEval_EvalFrameDefault
57  _PyEval_EvalFrameDefault
58  _PyFunction_FastCallDict
59  _PyEval_EvalFrameDefault

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(2), out of memory.
  [Advise: Please search for the error code(2) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] at (/paddle/paddle/fluid/platform/stream/cuda_stream.cc:36)

-------------
This log file path is /home/*****/paddlex_workspace/projects/P0008/T0020/out.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
2021-05-04 21:59:15 [INFO]	Starting to read file list from dataset...
2021-05-04 21:59:16 [INFO]	100956 samples in file /home/hello/paddlex_workspace/datasets/D0009/train_list.txt
2021-05-04 21:59:16 [INFO]	Starting to read file list from dataset...
2021-05-04 21:59:16 [INFO]	28844 samples in file /home/hello/paddlex_workspace/datasets/D0009/val_list.txt
2021-05-04 21:59:17 [INFO]	Decompressing /home/hello/paddlex_workspace/pretrain/ResNet50_vd_pretrained.tar...
2021-05-04 21:59:17 [DEBUG]	/home/hello/paddlex_workspace/pretrain/ResNet50_vd_pretrained.tar decompressed.
----------

分类检测
批大小为 1 2 3 4 10 20
都调整过 报错误

**Comment by FlyingQianMM** [comment]
把图像大小设置的小一点试试。另外样例工程是否可以正常运行？
