### ISSUE TITLE
关于模型导出 --fixed_input_shape 参数

### ISSUE THREAD

**Issue by m657438565** [PaddlePaddle/PaddleX#704]
问题类型：其它  
**问题描述**  
部署模型导出  --fixed_input_shape 参数  只有 w,h     希望大佬 也能把batchsize批大小   也能设置上，  要不然跑出来得模型是-1 无法更改
========================

请在这里描述您的问题

**Comment by FlyingQianMM** [comment]
batchsize为-1表示可以动态设置，不会影响后续部署呢。

**Comment by m657438565** [comment]
> batchsize为-1表示可以动态设置，不会影响后续部署呢。

大佬 但是我转ONNX  然后进行优化 他不支持 动态得， 有什么办法  可以改成1呢

**Comment by jiangjiajun** [comment]
> > batchsize为-1表示可以动态设置，不会影响后续部署呢。
> 
> 大佬 但是我转ONNX 然后进行优化 他不支持 动态得， 有什么办法 可以改成1呢

你具体是什么模型呢

**Comment by m657438565** [comment]
MobileNetV2  paddlex 训练得官方例子  我用 API上得  paddlex --export_inference --model_dir=. /xiaoduxiong_epoch_12 --save_dir=. /inference_model --fixed_input_shape=[640,960] 这种命令来导出， 但是发现shape  只能设置wh   ，batchsize 无法设置 ， 导致我转ONNX  无法进行onnxsim 优化  ， 有什么方法 可以设置batchsize  设置成1嘛 不要动态得

> > > batchsize为-1表示可以动态设置，不会影响后续部署呢。
> > 
> > 
> > 大佬但是我转ONNX然后进行优化他不支持动态得，有什么办法可以改成1呢
> 
> 你具体是什么模型呢

**Comment by jiangjiajun** [comment]
当前有两个方法
## 方法1（推荐）
模型导出时，我们通过指定shape组网，你可以直接修改PaddleX的代码来达成你的目标
### Step 1.找到paddlex的安装目录
`pip show paddlex`，可以查看到安装目录，一般为`/docker/jiangjiajun/anaconda3/envs/paddlex/lib/python3.7/site-packages/`
### Step 2.修改代码
对于分类模型，修改``/docker/jiangjiajun/anaconda3/envs/paddlex/lib/python3.7/site-packages/paddlex/cv/models/classifier.py`
找到如下代码
```
        if self.fixed_input_shape is not None:
            input_shape = [
                None, self.input_channel, self.fixed_input_shape[1],
                self.fixed_input_shape[0]
            ]
            image = fluid.data(
                dtype='float32', shape=input_shape, name='image')
```
修改为(仅将其中的None改为了1)
```
        if self.fixed_input_shape is not None:
            input_shape = [
                1, self.input_channel, self.fixed_input_shape[1],
                self.fixed_input_shape[0]
            ]
            image = fluid.data(
                dtype='float32', shape=input_shape, name='image')
```
然后再重新导出模型即可。

## 方法2
方法2为直接修改先前已经导出来的动态batch的ONNX模型，使用如下代码修改导出来的onnx模型
```
import onnx
import onnx.checker
import onnx.utils
from onnx.tools import update_model_dims
model = onnx.load('model.onnx')
# 此处可以理解为获得了一个维度 “引用”，通过该 “引用“可以修改其对应的维度
new_model = update_model_dims.update_inputs_outputs_dims(model, {'image': [1, 3, 224, 224]},  {'tanh_0.tmp_0': [1, 3, 7, 7]})

onnx.save(new_model, 'new_model.onnx')
```
注意这里的'image`和'tanh_0.tmp_0`分别为模型的输入和输出节点名，可通过Netron软件可视化你的onnx模型来获得准确的输入输出名

**Comment by m657438565** [comment]
> 当前有两个方法
> 
> ## 方法1（推荐）
> 模型导出时，我们通过指定shape组网，你可以直接修改PaddleX的代码来达成你的目标
> 
> ### Step 1.找到paddlex的安装目录
> `pip show paddlex`，可以查看到安装目录，一般为`/docker/jiangjiajun/anaconda3/envs/paddlex/lib/python3.7/site-packages/`
> 
> ### Step 2.修改代码
> 对于分类模型，修改``/docker/jiangjiajun/anaconda3/envs/paddlex/lib/python3.7/site-packages/paddlex/cv/models/classifier.py`
> 找到如下代码
> 
> ```
>         if self.fixed_input_shape is not None:
>             input_shape = [
>                 None, self.input_channel, self.fixed_input_shape[1],
>                 self.fixed_input_shape[0]
>             ]
>             image = fluid.data(
>                 dtype='float32', shape=input_shape, name='image')
> ```
> 
> 修改为(仅将其中的None改为了1)
> 
> ```
>         if self.fixed_input_shape is not None:
>             input_shape = [
>                 1, self.input_channel, self.fixed_input_shape[1],
>                 self.fixed_input_shape[0]
>             ]
>             image = fluid.data(
>                 dtype='float32', shape=input_shape, name='image')
> ```
> 
> 然后再重新导出模型即可。
> 
> ## 方法2
> 方法2为直接修改先前已经导出来的动态batch的ONNX模型，使用如下代码修改导出来的onnx模型
> 
> ```
> import onnx
> import onnx.checker
> import onnx.utils
> from onnx.tools import update_model_dims
> model = onnx.load('model.onnx')
> # 此处可以理解为获得了一个维度 “引用”，通过该 “引用“可以修改其对应的维度
> new_model = update_model_dims.update_inputs_outputs_dims(model, {'image': [1, 3, 224, 224]},  {'tanh_0.tmp_0': [1, 3, 7, 7]})
> 
> onnx.save(new_model, 'new_model.onnx')
> ```
> 
> 注意这里的'image`和'tanh_0.tmp_0`分别为模型的输入和输出节点名，可通过Netron软件可视化你的onnx模型来获得准确的输入输出名

感谢感谢 完美解决    大佬万岁
