### ISSUE TITLE
python 视频流预测报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleX#712]
问题类型：模型部署
![image](https://user-images.githubusercontent.com/58030051/117305946-d1f6f800-aeb1-11eb-9c01-77bbaa98aaac.png)

代码：
import cv2
import paddlex as pdx
predictor = pdx.deploy.Predictor('D:\\project\\python\\detection\\inference_model')
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    if ret:
        result = predictor.predict(frame)
        vis_img = pdx.det.visualize(frame, result, threshold=0.6, save_dir=None)
        cv2.imshow('Xiaoduxiong', vis_img)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
cap.release()

报错：
Traceback (most recent call last):
  File "d:/project/python/detection/dataset.py", line 22, in <module>
    predictor = pdx.deploy.Predictor('D:\\project\\python\\detection\\inference_model')
  File "D:\programme\Anaconda\envs\paddle\lib\site-packages\paddlex\deploy.py", line 82, in __init__
    self.info['Transforms'], to_rgb)
  File "D:\programme\Anaconda\envs\paddle\lib\site-packages\paddlex\cv\transforms\__init__.py", line 38, in build_transforms
    transforms.append(getattr(T, op_name)(**op_attr))
TypeError: __init__() got an unexpected keyword argument 'max_val'

**Comment by FlyingQianMM** [comment]
使用的paddlex版本号是多少呢？
贴一下model.yml

**Comment by thomas-yanxin** [comment]
paddlex 版本1.3.7
paddlex  model.yml ？在哪里看？？？

**Comment by FlyingQianMM** [comment]
![image](https://user-images.githubusercontent.com/22235422/117567892-d2310680-b0f0-11eb-92bb-65dda47541fa.png)
这个文件夹里面有个model.yml

**Comment by whtwhtw** [comment]
使用cpu部署没问题，如果用显卡的cuda部署，也出现同样问题.3090+cuda11.2
model.yml文件内容为：
Model: PPYOLO
Transforms:
- Resize:
    interp: CUBIC
    target_size: 608
- Normalize:
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.229
    - 0.224
    - 0.225
TransformsMode: RGB
_Attributes:
  eval_metrics:
    bbox_map: 60.33631612800527
  fixed_input_shape: null
  labels:
  - head
  - helmet
  - person
  model_type: detector
  num_classes: 3
_ModelInputsOutputs:
  test_inputs:
  - - image
    - image
  - - im_size
    - im_size
  test_outputs:
  - - bbox
    - matrix_nms_0.tmp_0
_init_params:
  anchor_masks: null
  anchors: null
  backbone: ResNet50_vd_ssld
  ignore_threshold: 0.7
  input_channel: 3
  label_smooth: false
  nms_iou_threshold: 0.45
  nms_keep_topk: 100
  nms_score_threshold: 0.01
  nms_topk: 1000
  num_classes: 3
  scale_x_y: 1.05
  train_random_shapes:
  - 320
  - 352
  - 384
  - 416
  - 448
  - 480
  - 512
  - 544
  - 576
  - 608
  use_coord_conv: true
  use_drop_block: true
  use_iou_aware: true
  use_iou_loss: true
  use_matrix_nms: true
  use_spp: true
  with_dcn_v2: true
completed_epochs: 0
status: Infer
version: 1.3.10

**Comment by whtwhtw** [comment]
使用cpu部署没问题，如果用显卡的cuda部署，也出现同样问题
model.yml文件内容为：
Model: PPYOLO
Transforms:
- Resize:
    interp: CUBIC
    target_size: 608
- Normalize:
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.485
    - 0.456
    - 0.406
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.229
    - 0.224
    - 0.225
TransformsMode: RGB
_Attributes:
  eval_metrics:
    bbox_map: 60.33631612800527
  fixed_input_shape: null
  labels:
  - head
  - helmet
  - person
  model_type: detector
  num_classes: 3
_ModelInputsOutputs:
  test_inputs:
  - - image
    - image
  - - im_size
    - im_size
  test_outputs:
  - - bbox
    - matrix_nms_0.tmp_0
_init_params:
  anchor_masks: null
  anchors: null
  backbone: ResNet50_vd_ssld
  ignore_threshold: 0.7
  input_channel: 3
  label_smooth: false
  nms_iou_threshold: 0.45
  nms_keep_topk: 100
  nms_score_threshold: 0.01
  nms_topk: 1000
  num_classes: 3
  scale_x_y: 1.05
  train_random_shapes:
  - 320
  - 352
  - 384
  - 416
  - 448
  - 480
  - 512
  - 544
  - 576
  - 608
  use_coord_conv: true
  use_drop_block: true
  use_iou_aware: true
  use_iou_loss: true
  use_matrix_nms: true
  use_spp: true
  with_dcn_v2: true
completed_epochs: 0
status: Infer
version: 1.3.10

**Comment by kinraymon** [comment]
@thomas-yanxin 请问最后有解决方案吗？
