### ISSUE TITLE
模型可以正常训练但不能正常加载！！

### ISSUE THREAD

**Issue by ppppppppao** [PaddlePaddle/PaddleX#722]
问题类型：模型训练  
**问题描述**  

====================  
模型可以正常训练但不能正常加载
model=pdx.cls.ResNet50(num_classes=num_classes)
model.train(num_epochs=1000,
            train_dataset=train_dataset,
            train_batch_size=128,
            eval_dataset=eval_dataset,
            lr_decay_epochs=[200,400,800],
            save_interval_epochs=10,
            learning_rate=0.025,
            save_dir='output3/ResNet50',
            use_vdl=True,pretrain_weights='output2/ResNet50/best_model')
可以正常运行，正常加载模型，正常训练
训练完成后运行：model=pdx.load_model('output2/ResNet50/best_model')
报错：recent call last)<ipython-input-35-25b7181f53b0> in <module>
      3 import matplotlib.image as mpimg
      4 
----> 5 model=pdx.load_model('output2/ResNet50/best_model')
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py in load_model(model_dir, fixed_input_shape)
     45     if 'model_name' in info['_init_params']:
     46         del info['_init_params']['model_name']
---> 47     model = getattr(paddlex.cv.models, info['Model'])(**info['_init_params'])
     48 
     49     model.fixed_input_shape = fixed_input_shape
TypeError: __init__() got an unexpected keyword argument 'input_channel'

**Comment by ppppppppao** [comment]
dalao们，救救孩子

**Comment by FlyingQianMM** [comment]
更新下paddlex版本

**Comment by ppppppppao** [comment]
> 更新下paddlex版本

那个，麻烦能告诉我更新paddlex的操作吗，pip install paddlex不可以吗，我看目前的版本时1.9.4，怎样继续更新呢？

**Comment by FlyingQianMM** [comment]
你训练完的模型在output3/ResNet50，加载这个把。
pip show paddlex看下版本号，如果低于1.3.9的话，执行以下命令：
pip uninstall paddlex
pip install paddlex

**Comment by ppppppppao** [comment]
resnet系列的都是同样的报错信息，但是MobileNetV2可以正常训练然后加载，paddlex版本是1.3.9。

**Comment by FlyingQianMM** [comment]
看了下ResNet18-50漏掉了input_channel这个参数，抱歉哈，该问题已经修复，将paddlex升级至1.3.10即可。

**Comment by ppppppppao** [comment]
okok，好的，谢谢谢谢。😘😘😘
