### ISSUE TITLE
实例分割如何融合各个不同模型的结果？单个模型现在能支持multiscale预测吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#772]

**Comment by FlyingQianMM** [comment]
> 实例分割如何融合各个不同模型的结果？

这个暂时还没融合不同模型结果的API，可以自己手动取到各个模型的结果进行融合

> 单个模型现在能支持multiscale预测吗？

出于预测性能的考虑，我们还没有集成多尺度预测

**Comment by bbbxixixixi** [comment]
> > 实例分割如何融合各个不同模型的结果？
> 
> 这个暂时还没融合不同模型结果的API，可以自己手动取到各个模型的结果进行融合
> 
> > 单个模型现在能支持multiscale预测吗？
> 
> 出于预测性能的考虑，我们还没有集成多尺度预测

如果只是bbox的话，可以采用wbf，但是mask部分我就不知道了，有什么建议吗？

**Comment by FlyingQianMM** [comment]
每个bbox都有一个mask，最简单的方法是只对bbox做融合，完了取每个bbox的mask就行。

复杂一点的就是，bbox昨晚融合之后再对每个bbox预测mask，这个ppdet静态图版本有多尺度预测。
