### ISSUE TITLE
pdx.det.PPYOLO的train_random_shapes 对于长方形的图片，会不会因为图形变换造成精度下降

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#773]
pdx版本1.3
训练图片都是1920_1080和1280_720大小，train_random_shapes 似乎只会将图片转成正方形的，这样感觉图片就有些失真了。而且默认值相对原图有点偏小，小目标一缩估计就没了
另外anchors和anchor_masks以及train_random_shapes 的参数设置有什么可参考的吗？被检测目标绝大多数在100*100以内aspect_ratio集中在0.5到2.5之间

**Comment by bbbxixixixi** [comment]
另外不仅是pdx，还有paddledetection中，ppyolo系列感觉挺难调的，基本保持不动原始配置文件，loss非常容易就跑到nan了。其他的se154， r200，libra等反而很容易

**Comment by FlyingQianMM** [comment]
> pdx版本1.3
> 训练图片都是1920_1080和1280_720大小，train_random_shapes 似乎只会将图片转成正方形的，这样感觉图片就有些失真了。而且默认值相对原图有点偏小，小目标一缩估计就没了
> 另外anchors和anchor_masks以及train_random_shapes 的参数设置有什么可参考的吗？被检测目标绝大多数在100*100以内aspect_ratio集中在0.5到2.5之间

yolo系列要求输入大小都是正方形且是32的倍数。

anchors、anchor_masks、aspect_ratio基本上不需要调整。

关于train_random_shapes，设置时考虑下在该shape下最小目标能在预测特征层上占据一个点，基本上都能预测出来。

**Comment by FlyingQianMM** [comment]
> 另外不仅是pdx，还有paddledetection中，ppyolo系列感觉挺难调的，基本保持不动原始配置文件，loss非常容易就跑到nan了。其他的se154， r200，libra等反而很容易

paddledetection中的配置基本上是针对8卡的，如果用单卡跑，需要改下lr，bs。
ppyolo系列要求的epoch数较多，把预训练模型设成COCO的可以减少训练的轮数。对于容易出nan的问题，因为初期不稳定，可以把warmup_steps设的大一点。 另外主要是数据集的差异，为了能得到更好的精度，还是需要耐心的调整下参数。
