### ISSUE TITLE
paddlex 2.0.0rc0 GPU多卡训练 评估报错，单卡训练没问题

### ISSUE THREAD

**Issue by shawnLang** [PaddlePaddle/PaddleX#775]
问题类型：模型训练  
**问题描述**  
使用 paddlex 2.0.0rc0版本 训练自己的数据集 GPU多卡训练 评估报错，用单卡训练没问题。
 paddlepaddle-gpu==2.1.0

![QQ截图20210524123141](https://user-images.githubusercontent.com/22512533/119296692-06c5c600-bc8c-11eb-8fa7-441d032b79f5.png)

![QQ截图20210524122713](https://user-images.githubusercontent.com/22512533/119296481-94ed7c80-bc8b-11eb-9320-ad26d7c6b20f.png)

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by FlyingQianMM** [comment]
你好，系统是linux 18.04吗？显卡是什么系列的？

训练脚本和数据集就是tutorials里面的对吧？请问有修改哪些地方呢

**Comment by shawnLang** [comment]
> 你好，系统是linux 18.04吗？显卡是什么系列的？
> 
> 训练脚本和数据集就是tutorials里面的对吧？请问有修改哪些地方呢


系统是centos7.9 显卡是Tesla P40
使用的这个示例 https://github.com/PaddlePaddle/PaddleX/blob/release/2.0-rc/tutorials/train/object_detection/ppyolov2.py
只是数据集改成我自己的 其他没有改动

**Comment by shawnLang** [comment]
> 你好，系统是linux 18.04吗？显卡是什么系列的？
> 
> 训练脚本和数据集就是tutorials里面的对吧？请问有修改哪些地方呢



这是另外一个日志的报错信息
![QQ截图20210524163612](https://user-images.githubusercontent.com/22512533/119320516-3ede0080-bcae-11eb-931f-f1d0acbadf6c.png)

**Comment by will-jl944** [comment]
你好，已定位到问题。由于检测模型目前仅支持单卡评估，在评估阶段会自动切换为单卡，另一张卡上的eval_metrics为None，导致了该错误。我们已针对该问题作出了修复，详情见PR #778 。

请依次执行：
`$ python3 -m pip uninstall paddlex`
`$ git clone https://github.com/PaddlePaddle/PaddleX.git`
`$ cd dygraph`
`$ python3 setup.py install`

**Comment by DrugD** [comment]
paddlex 2.0.0版本，单卡至尊版，32g显存，训练时batchsize=2时，显存占20g左右，但是 调用评估api时，就会爆显存，查看资源，感觉每预测几个图片，显存就会涨一些，是否有bug还是图片/模型过大？
