### ISSUE TITLE
求gPRC方式部署的demo

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/PaddleX#777]
问题类型：模型部署
**问题描述**  

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。
B站官方视频 https://www.bilibili.com/video/BV1no4y1Z7kq 中，第三部分，使用gRPC部署paddlex，使用C#开发UI，这个demo的代码可以发一下链接吗

**Comment by heliqi** [comment]
视频下的评论有代码链接 https://github.com/LiKangyuLKY/PaddleXCsharp
有个grpc_demo的目录
