### ISSUE TITLE
C++ 编译预测，paddleDection模型mask_rcnn_x101_vd_64x4d_fpn_2x_coco

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/PaddleX#788]
问题类型：模型部署
**问题描述**  

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。
exe编译成功，是还没有适配？目标检测可以预测成功。

**Comment by heliqi** [comment]
我们支持mask_rcnn。请问你遇到什么问题？请详细描述下。 develop分支dygraph目录才支持其他套件，且是2.0以后版本导出模型

**Comment by xialei2821212670** [comment]
> 我们支持mask_rcnn。请问你遇到什么问题？请详细描述下。

我尝试了自己导出的模型，无法调用
![image](https://user-images.githubusercontent.com/57654726/119810473-a7c8b100-bf18-11eb-8973-801deda71de4.png)
，但是yolo倒是可以
![image](https://user-images.githubusercontent.com/57654726/119810583-c0d16200-bf18-11eb-88e2-74f5146581d2.png)
这是部分文件
![image](https://user-images.githubusercontent.com/57654726/119810663-d21a6e80-bf18-11eb-9515-f333cad0c4ae.png)

**Comment by heliqi** [comment]
你是哪个版本的paddledetection导出的mask模型

**Comment by xialei2821212670** [comment]
用的2.1

**Comment by xialei2821212670** [comment]
> 你是那个版本的paddledetection更新的mask模型

用的2.1版本的，导出模型paddledection在python环境下预测没问题，paddlex编译成exe预测部署运行报错

**Comment by heliqi** [comment]
不好意思，有点时间耽搁，没有及时跟进。
我们这边测试的模型是 mask_rcnn_r50_vd_fpn_1x_coco ， 导出版本为PaddleDetection 2.0， 测试是可以部署的。

我现在测试一下2.1版本模型， 以及你反馈的模型。 如果有结果，我会第一时间反馈。

**Comment by heliqi** [comment]
@xialei2821212670 经过测试，在PaddleDetection release/2.1 下导出的mask_rcnn都可以正常部署。

导出你所描述模型的代码为:
```python
python tools/export_model.py -c configs/mask_rcnn/mask_rcnn_x101_vd_64x4d_fpn_2x_coco.yml \
                             -o weights=https://paddledet.bj.bcebos.com/models/mask_rcnn_x101_vd_64x4d_fpn_2x_coco.pdparams \
                             --output_dir=./inference_model
```

1. 检查你的模型导出，  是否为 PaddleDetection release/2.1 代码导出
2. 检查c++部署代码是否为 Paddlex/dygraph/deploy/cpp
3. 检查你所使用的预测苦是否为 2.1 的推理引擎。 2.1版本预测库下载链接https://paddleinference.paddlepaddle.org.cn/v2.1/user_guides/download_lib.html


如果检查没有问题， 则需要提供模型 + 详细描述你的环境。 我们这边进行复现
