### ISSUE TITLE
实例分割训练 报错

### ISSUE THREAD

**Issue by Enn29** [PaddlePaddle/PaddleX#798]
问题类型：模型训练  
**问题描述**  
实例分割训练时报错，在导入模块时发生的报错
看报错应该是在import shapely.ops时发生的报错

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
报错信息如下
![image](https://user-images.githubusercontent.com/63645468/120608191-80776400-c483-11eb-8416-e8f17ce485c2.png)

**Comment by FlyingQianMM** [comment]
使用管理员权限打开cmd试下，另外pip show Shapely看下有没有安装Shapely，如果没有安装的话，pip install Shapely或者conda install Shapely

**Comment by Enn29** [comment]
有安装Shapely
只是Library/bin/下没有geos_c.dll，卸载Shapely后，下载whl后重新安装就好了
谢谢
