### ISSUE TITLE
使用paddleX进行C++部署PeddleSeg编译时报错：target(for copy command) ")" is model_infer not a directory

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#827]
问题类型：模型部署
**问题描述**  
参考的是官方教程https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/deploy/cpp/docs/compile/paddle/windows.md
前边一切顺利，最后用VS2019编译的时候出现target(for copy command) ")" is model_infer not a directory

**Comment by heliqi** [comment]
你需要把paddlex/dygraph/deploy/cpp/cmakelists.txt最下边的command中的tensorrt判断及里边的copy指令全删掉。 后面我们会修复这个问题。

友情提示：目前windows 提供的2.1预测库都包含tensorrt，即使没用也需要链接。 所以最好下载tensorrt并进行链接

**Comment by heliqi** [comment]
![Uploading Screenshot_20210613_222751_com.baidu.searchbox_edit_180694982874510.jpg…]()
圈里的代码需要去掉

**Comment by heliqi** [comment]
![Uploading Screenshot_20210613_222751_com.baidu.searchbox_edit_180694982874510.jpg…](圈里的照片)

**Comment by aiwenzhu** [comment]
请问是去掉隐形部分吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月13日(周日) 晚上10:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 使用paddleX进行C++部署PeddleSeg编译时报错：target(for copy command) ")" is model_infer not a directory (#827)




 
你需要把paddlex/dygraph/deploy/cpp/cmakelists.txt最下边的command中的tensorrt判断及里边的copy指令全删掉。 后面我们会修复这个问题。
 
友情提示：目前windows 提供的2.1预测库都包含tensorrt，即使没用也需要链接。 所以最好下载tensorrt并进行链接

**Comment by heliqi** [comment]
是的， 去掉这里。 主要是tensorrt导致的， 我们稍后会修复此问题
![image](https://user-images.githubusercontent.com/34152981/121991211-d0362380-cdd1-11eb-8e9d-469f73be26b9.png)

**Comment by aiwenzhu** [comment]
你好，我这里编译成功了，不过没有在demo文件夹下生成可执行文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月15日(周二) 中午12:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 使用paddleX进行C++部署PeddleSeg编译时报错：target(for copy command) ")" is model_infer not a directory (#827)




 
是的， 去掉这里。 主要是tensorrt导致的， 我们稍后会修复此问题

**Comment by heliqi** [comment]
有先清理再进行生成么？ 全流程都是用vs2019操作的吧？或者你试试先删除out文件夹再走一遍

**Comment by heliqi** [comment]
该问题已在最新的代码修复
