### ISSUE TITLE
paddlex_restful二次开发

### ISSUE THREAD

**Issue by fangxin-debug** [PaddlePaddle/PaddleX#828]
用restful二次开发时，可以部署在多机多卡的环境下吗？如果可以，相应的代码路径在哪里呀？

**Comment by lailuboy** [comment]
是想单个模型训练时可以同时在多机上并行训练吗？

**Comment by fangxin-debug** [comment]
嗯嗯，最好也能多块gpu的。

**Comment by lailuboy** [comment]
目前restful可以支持单机多卡，想了解一下具体希望什么模型在多机多卡上同时并行训练。因为对于CV模型单机多卡基本可以满足需要。

**Comment by fangxin-debug** [comment]
蟹蟹，我是想利用restful自己搭建一个深度学习平台。想问配置单机多卡的具体代码在哪个路径下面呢，在restful目录下面没有找到。

**Comment by lailuboy** [comment]
单机多卡，在训练时可以指定参数：cuda_visible_devices，在/paddlex_restful/restful/project/train/params.py
在HTML界面中也有开放填写。

**Comment by lailuboy** [comment]
如果有多台服务器的话，可以在服务器上都安装PaddleX，然后将不同任务跑在不同服务器和卡上。前提是模型不需要多机多卡并行训练。如果需要一个模型同时在多机多卡上训练，可以通过调用框架提供的分布式训练接口fleet API去实现。

**Comment by fangxin-debug** [comment]
感谢解答问题****
