### ISSUE TITLE
paddleseg部署生成dll过程中编译时出现无法打开源文件yaml-cpp/yaml.h

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#831]
paddleseg部署生成dll过程中编译时出现无法打开源文件yaml-cpp/yaml.h

**Comment by kungkook** [comment]
> paddleseg部署生成dll过程中编译时出现无法打开源文件yaml-cpp/yaml.h

你好，请问你解决了吗，我在部署PaddleX也出现了这个问题......
