### ISSUE TITLE
paddleseg 使用paddleX进行C++部署二次开发

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#832]
问题类型：其它  
paddleseg 使用paddleX进行C++部署二次开发如何编译dll可以像opencv那样方便调用，比如自己的项目想直接调用PaddleX里的init、Predict等函数该怎么把相关依赖打包

请在这里描述您的问题

**Comment by heliqi** [comment]
我们后续会出相关链接库和文档。 当前版本在使用上是可以这样操作的， 你需要稍微修改下CMakeList和代码然后进行编译即可
