### ISSUE TITLE
paddleseg使用paddleX编译生成dll报错

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#836]
错误	C2440	“=”: 无法从“const YAML::Node”转换为“bool”	model_infer	D:\PaddleSeg_projects\PaddleX_DLL\PaddleX_cpp\model_deploy\common\include\transforms.h
其他报错跟这个类似都是类型转换问题

**Comment by heliqi** [comment]
你改动的代码能贴下么？还有完整的报错

**Comment by aiwenzhu** [comment]
> 你改动的代码能贴下么？还有完整的报错

报错共有53个，全部都是“=”: 无法从“const YAML::Node”转换为“bool”

按照文章中的方式https://zhuanlan.zhihu.com/p/183875466进行生成dll，没有改动代码，紧改动了cmakelist：
改动为：ADD_library(model_infer SHARED ${PROJECT_ROOT_DIR}/demo/model_infer.cpp ${SRC} ${ENGINE_SRC} ${DETECTOR_SRC})，这里改成了ADD_library并添加了SHARED
batch_infer、multi_gpu_model_infer、tensorrt_infer改法相同

**Comment by heliqi** [comment]
应该是你的cmakelists没有链接上ext-yaml。你参照编译model_infer的三行,你只能改第一行为生成链接库，其余两行不能动。 详细原因可以网上搜索下cmake编译链接语法

**Comment by aiwenzhu** [comment]
> 应该是你的cmakelists没有链接上ext-yaml。你参照编译model_infer的三行,你只能改第一行为生成链接库，其余两行不能动。 详细原因可以网上搜索下cmake编译链接语法

谢谢您的回复，成功了不过只生成了dll不过没有lib，有一个疑问，这种方式似乎只能生成dll，然后通过C++调用dll的方式调用网络获得结果，确实不太方便，如何把model_infer.cpp放在自己创建的项目中也能跑起来，这么多包含依赖文件和lib文件怎么弄，您说当前版本可以这么操作，有点不明白

**Comment by heliqi** [comment]
1.生成dll还是lib在于你CMakeList里面的语法， 你只设置了生成动态链接库，肯定只能生成dll。
2.你另外一个问题所描述的OpenCV，不也是需要链接dll/lib进行编译才能使用么？ 现在也是在自己项目编译使用PaddleX部署，不方便在哪？
3. 你可以把model_infer.cpp里的main改成2个函数(比如init、predict)，然后编译成dll， 这样你只需要调用这两个函数即可。这种做法在你发的知乎链接文章里有写， 只是作者改成了C#的方式。

如果实在弄不懂的话，建议你等我们发布的新版本， 到时会出相关的demo和教程。（新版本大概在6月底～7月初）

**Comment by aiwenzhu** [comment]
> 1.生成dll还是lib在于你CMakeList里面的语法， 你只设置了生成动态链接库，肯定只能生成dll。
> 2.你另外一个问题所描述的OpenCV，不也是需要链接dll/lib进行编译才能使用么？ 现在也是在自己项目编译使用PaddleX部署，不方便在哪？
> 3. 你可以把model_infer.cpp里的main改成2个函数(比如init、predict)，然后编译成dll， 这样你只需要调用这两个函数即可。这种做法在你发的知乎链接文章里有写， 只是作者改成了C#的方式。
> 
> 如果实在弄不懂的话，建议你等我们发布的新版本， 到时会出相关的demo和教程。（新版本大概在6月底～7月初）

好的，明白了，谢谢解答疑惑

**Comment by aiwenzhu** [comment]
> > 1.生成dll还是lib在于你CMakeList里面的语法， 你只设置了生成动态链接库，肯定只能生成dll。
> > 2.你另外一个问题所描述的OpenCV，不也是需要链接dll/lib进行编译才能使用么？ 现在也是在自己项目编译使用PaddleX部署，不方便在哪？
> > 3. 你可以把model_infer.cpp里的main改成2个函数(比如init、predict)，然后编译成dll， 这样你只需要调用这两个函数即可。这种做法在你发的知乎链接文章里有写， 只是作者改成了C#的方式。
> > 如果实在弄不懂的话，建议你等我们发布的新版本， 到时会出相关的demo和教程。（新版本大概在6月底～7月初）
> 
> 好的，明白了，谢谢解答疑惑
请问一下，segresult中的像素标签和置信度数据(vector存储的)和图片上的像素的对应关系是什么样的，我想把分割结果显示在原图上

**Comment by aiwenzhu** [comment]
> > 1.生成dll还是lib在于你CMakeList里面的语法， 你只设置了生成动态链接库，肯定只能生成dll。
> > 2.你另外一个问题所描述的OpenCV，不也是需要链接dll/lib进行编译才能使用么？ 现在也是在自己项目编译使用PaddleX部署，不方便在哪？
> > 3. 你可以把model_infer.cpp里的main改成2个函数(比如init、predict)，然后编译成dll， 这样你只需要调用这两个函数即可。这种做法在你发的知乎链接文章里有写， 只是作者改成了C#的方式。
> > 如果实在弄不懂的话，建议你等我们发布的新版本， 到时会出相关的demo和教程。（新版本大概在6月底～7月初）
> 
> 好的，明白了，谢谢解答疑惑
请问一下，我想把分割的结果显示在图片上，在输出seg_result->label_map.data的时候，发现结果如下：
200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000000020000000200000002000
数据都是隔7个0出现一个其他数字，这正常吗，还是操作有误

**Comment by heliqi** [comment]
那issues我关闭了
