### ISSUE TITLE
cuda报错

### ISSUE THREAD

**Issue by liu2020112425** [PaddlePaddle/PaddleX#837]
no kernel image is available for execution on the device

**Comment by liu2020112425** [comment]
![5b721c3da001108d997fb778f94b6cd](https://user-images.githubusercontent.com/77332940/122210184-f0500a80-ced7-11eb-890f-879c8ba5a962.jpg)
![7065059d1c030e84049d69c85f856d5](https://user-images.githubusercontent.com/77332940/122210191-f1813780-ced7-11eb-88fd-6b2d8ea68d57.jpg)
![00a88dd2fdf48416a00a53a813ead96](https://user-images.githubusercontent.com/77332940/122210207-f80faf00-ced7-11eb-91ed-67bc8c90c768.jpg)

**Comment by liu2020112425** [comment]
ubantu 16.04系统

**Comment by liu2020112425** [comment]
ubantu18.04

**Comment by zkailinzhang** [comment]
现在安装的 paddlepaddle-gpu 2.1.0.post101 ，也不支持呢，GTX3090 ubuntu18，还是报这样的错误
gaussian_random raises an exception thrust::system::system_error, parallel_for failed: no kernel image is available for execution on the device
