### ISSUE TITLE
训练Faster RCNN实例cuDNN库报错,MobileNetV3-ssld模型正常

### ISSUE THREAD

**Issue by HairongWu** [PaddlePaddle/PaddleX#846]
报错信息如下'
Could not load library libcudnn_cnn_train.so.8. Error: /home/xxx/anaconda3/envs/py38-paddle2.1/bin/../lib/libcudnn_ops_train.so.8: symbol _Z22cudnnGenericOpTensorNdILi3EE13cudnnStatus_tP12cudnnContext16cudnnGenericOp_t21cudnnNanPropagation_tPKdPKvPK17cudnnTensorStructS8_S8_SB_S8_S8_SB_Pv version libcudnn_ops_infer.so.8 not defined in file libcudnn_ops_infer.so.8 with link time reference
Please make sure libcudnn_cnn_train.so.8 is in your library path!
Please make sure libcudnn_cnn_train.so.8 is in your library path!

**Comment by FlyingQianMM** [comment]
> Please make sure libcudnn_cnn_train.so.8 is in your library path!

尝试下把cudnn添加到LD_LIBRARY_PATH
