### ISSUE TITLE
aspect ratio是高比宽？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#848]
这个不是宽高比吗？看anchor_generator里面的注释说是 height/width ratios，是我一直理解错了还是注释有误？

**Comment by bbbxixixixi** [comment]
另外再有一点，假设aspect ratio是height/width，当anchor size取32，aspect ratio取0.5， 生成的height和width分别是16/32还是32/64?

**Comment by FlyingQianMM** [comment]
是height/width ratios，具体可以看下静态图时的实现 
https://github.com/PaddlePaddle/Paddle/blob/930ca3f4950187131aa010f3ae88006a0fbf91ad/paddle/fluid/operators/detection/anchor_generator_op.h#L75

基本上数据充足的情况下，不需要调整aspect ratio

**Comment by bbbxixixixi** [comment]
> 是height/width ratios，具体可以看下静态图时的实现
> https://github.com/PaddlePaddle/Paddle/blob/930ca3f4950187131aa010f3ae88006a0fbf91ad/paddle/fluid/operators/detection/anchor_generator_op.h#L75
> 
> 基本上数据充足的情况下，不需要调整aspect ratio

是这一部分吧？


auto anchor_size = anchor_sizes[s];            area = stride_width * stride_height;            area_ratios = area / ar;            base_w = round(sqrt(area_ratios));            base_h = round(base_w * ar);            scale_w = anchor_size / stride_width;            scale_h = anchor_size / stride_height;            anchor_width = scale_w * base_w;            anchor_height = scale_h * base_h;
训练数据宽高比比较偏，我想调节一下这部分

**Comment by will-jl944** [comment]
> 另外再有一点，假设aspect ratio是height/width，当anchor size取32，aspect ratio取0.5， 生成的height和width分别是16/32还是32/64?

生成的`height`和`width`分别为`\sqrt{anchor_size^2 / aspect_ratio} * aspect_ratio`和`\sqrt{anchor_size^2 / aspect_ratio}`。

具体的计算如下：
`area = anchor_size ** 2.0`
`w = math.sqrt(area / aspect_ratio)`
`h = aspect_ratio * w`

代码具体实现见https://github.com/PaddlePaddle/PaddleDetection/blob/6ec36068ee450df33c0038fb0cdc575b21510acd/ppdet/modeling/proposal_generator/anchor_generator.py#L67

**Comment by will-jl944** [comment]
> > 是height/width ratios，具体可以看下静态图时的实现
> > https://github.com/PaddlePaddle/Paddle/blob/930ca3f4950187131aa010f3ae88006a0fbf91ad/paddle/fluid/operators/detection/anchor_generator_op.h#L75
> > 基本上数据充足的情况下，不需要调整aspect ratio
> 
> 是这一部分吧？
> 
> auto anchor_size = anchor_sizes[s]; area = stride_width * stride_height; area_ratios = area / ar; base_w = round(sqrt(area_ratios)); base_h = round(base_w * ar); scale_w = anchor_size / stride_width; scale_h = anchor_size / stride_height; anchor_width = scale_w * base_w; anchor_height = scale_h * base_h;
> 训练数据宽高比比较偏，我想调节一下这部分

根据你的数据集的特点调节`anchor_sizes`和`aspect_ratios`，只需在初始化网络实例的时候传入相应参数，例如：
`my_model = paddlex.models.FasterRCNN(anchor_sizes=my_anchor_sizes, aspect_ratios=my_aspect_ratios)`

网络会根据是否使用了fpn结构以及`my_anchor_sizes`和`my_aspect_ratios`参数计算不同feature_maps上先验框的具体尺寸。

**Comment by bbbxixixixi** [comment]
> > 另外再有一点，假设aspect ratio是height/width，当anchor size取32，aspect ratio取0.5， 生成的height和width分别是16/32还是32/64?
> 
> 生成的`height`和`width`分别为`\sqrt{anchor_size^2 / aspect_ratio} * aspect_ratio`和`\sqrt{anchor_size^2 / aspect_ratio}`。
> 
> 具体的计算如下：
> `area = anchor_size ** 2.0`
> `w = math.sqrt(area / aspect_ratio)`
> `h = aspect_ratio * w`
> 
> 代码具体实现见https://github.com/PaddlePaddle/PaddleDetection/blob/6ec36068ee450df33c0038fb0cdc575b21510acd/ppdet/modeling/proposal_generator/anchor_generator.py#L67

感谢回复。我查了一下，这块代码是动态图的部分，我目前使用的是master分支的静态图，也是这种实现吗？似乎还涉及到stride的设置
我没查到具体的代码，所以参考了paddle master分支中test_anchor_generator_ops.py里面anchor_generator_in_python方法的生成

def anchor_generator_in_python(input_feat, anchor_sizes, aspect_ratios,
                               variances, stride, offset):
    num_anchors = len(aspect_ratios) * len(anchor_sizes)
    layer_h = input_feat.shape[2]
    layer_w = input_feat.shape[3]
    out_dim = (layer_h, layer_w, num_anchors, 4)
    out_anchors = np.zeros(out_dim).astype('float32')

    for h_idx in range(layer_h):
        for w_idx in range(layer_w):
            x_ctr = (w_idx * stride[0]) + offset * (stride[0] - 1)
            y_ctr = (h_idx * stride[1]) + offset * (stride[1] - 1)
            idx = 0
            for r in range(len(aspect_ratios)):
                ar = aspect_ratios[r]
                for s in range(len(anchor_sizes)):
                    anchor_size = anchor_sizes[s]
                    area = stride[0] * stride[1]
                    area_ratios = area / ar
                    base_w = np.round(np.sqrt(area_ratios))
                    base_h = np.round(base_w * ar)
                    scale_w = anchor_size / stride[0]
                    scale_h = anchor_size / stride[1]
                    w = scale_w * base_w
                    h = scale_h * base_h
                    out_anchors[h_idx, w_idx, idx, :] = [
                        (x_ctr - 0.5 * (w - 1)), (y_ctr - 0.5 * (h - 1)),
                        (x_ctr + 0.5 * (w - 1)), (y_ctr + 0.5 * (h - 1))
                    ]
                    idx += 1

写了一个实现
def cal_wh(ar, anchor_size, stride=[16., 16]):
    area = stride[0] * stride[1]
    area_ratios = area / ar
    base_w = np.round(np.sqrt(area_ratios))
    base_h = np.round(base_w * ar)
    scale_w = anchor_size / stride[0]
    scale_h = anchor_size / stride[1]
    w = scale_w * base_w
    h = scale_h * base_h
    return w, h

和你的不同之处就是stride的设置上，这个是否是需要考虑的？

**Comment by will-jl944** [comment]
你指的是develop分支的静态图版本PaddleX吗？我们目前在维护和更新的PaddleX在develop分支下，最新的动态图版本在develop分支的dygraph目录下。你可以通过`clone`后运行`$ python setup.py install`安装相应的的静态图或动态图版本（动态图版本需在dygraph目录下运行该安装指令），也可以通过`$ pip install paddlex==1.3.11`（静态图）或`$ pip install paddlex==2.0.0rc0`（动态图）安装。

如果你只是需要根据你的数据集的特点更改`anchor_sizes`和`aspect_ratios`的话，静态图版本下也是同样的方法，不需要去更改模型的代码实现，只需在初始化模型实例的时候传入相应参数，即：
`model = pdx.det.FasterRCNN(anchor_sizes=my_anchor_sizes, aspect_ratios=my_aspect_ratios)`

由于FasterRCNN网络结构是确定的，特征图对应的下采样步长`stride`也是确定的，在没有更改网络结构的前提下，你无需再去设置`stride`参数，网络内部会自动根据当前特征图对应的`stride`去计算实际的先验框尺寸。
