### ISSUE TITLE
根据anchor size和aspect ratio生成框时，会考虑数据增强同步进行调整吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#849]
比如生成的框 400*400，图片原始大小1000*1000，resize1.5倍成为1500*1500，框会变成600*600吗？

**Comment by FlyingQianMM** [comment]
> resize1.5倍成为1500*1500，框会变成600*600吗？

是这样子的，图像和真值框同步进行resize

**Comment by bbbxixixixi** [comment]
> > resize1.5倍成为1500_1500，框会变成600_600吗？
> 
> 是这样子的，图像和真值框同步进行resize

不是说gt框，而是去匹配真值框而生成的那个框

**Comment by will-jl944** [comment]
你指的是，在不改变网络的`anchor_sizes`和`aspect_ratios`参数的前提下，生成的先验框尺寸是否会根据数据增强进行调整，对吗？

是不会的，网络只会根据特征图尺寸以及特征图对应的下采样倍数推算相对于**实际输入网络的图片尺寸**的先验框坐标，具体代码见https://github.com/PaddlePaddle/PaddleDetection/blob/6ec36068ee450df33c0038fb0cdc575b21510acd/ppdet/modeling/proposal_generator/anchor_generator.py#L116

**Comment by bbbxixixixi** [comment]
> 你指的是，在不改变网络的`anchor_sizes`和`aspect_ratios`参数的前提下，生成的先验框尺寸是否会根据数据增强进行调整，对吗？
> 
> 是不会的，网络只会根据特征图尺寸以及特征图对应的下采样倍数推算相对于**实际输入网络的图片尺寸**的先验框坐标，具体代码见https://github.com/PaddlePaddle/PaddleDetection/blob/6ec36068ee450df33c0038fb0cdc575b21510acd/ppdet/modeling/proposal_generator/anchor_generator.py#L116

是的 了解了
