### ISSUE TITLE
预测部署编译出错

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/PaddleX#901]
问题类型：模型部署
**问题描述**  

========================  
按照PaddleX/dygraph/deploy/cpp/docs/compile/paddle/windows.md教程进行部署cmake编译，在vs2019生成是显示'C:/projects/fluid_install_dir_win_cpu_1.6/fluid_install_dir_win_cpu_1.6/paddle/lib/libpaddle_fluid.lib', needed by 'paddlex_inference/video_classifier.exe', missing and no known rule to make it	D:\paddlexpro\PaddleX\deploy\cpp\out\build\x64-Release\cpp	D:\paddlexpro\PaddleX\deploy\cpp\out\build\x64-Release\ninja	1	我电脑中没有这个路径，也不知道怎么改，windos10 paddle_inference 2.1 预测库。
请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by studiouspan** [comment]
遇到了同样的问题，请问你解决了吗？

**Comment by ChaoII** [comment]
> 遇到了同样的问题，请问你解决了吗？

用cmakegui 打开cmakelist文件 不要直接用vs打开就好了
