### ISSUE TITLE
c++编译

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/PaddleX#902]
问题类型：模型部署
**问题描述**  

==
编译时报这个错误，不知道怎么解决
![image](https://user-images.githubusercontent.com/44053467/124075240-287a5000-da77-11eb-8b2c-6c178e84a6c8.png)
======================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by heliqi** [comment]
如果不使用gpu.必须要下载cpu版本的预测库,windows上如果下了gpu版本一定要安装cuda，如果下了带tensorrt那一定要安装tensorrt
