### ISSUE TITLE
模型部署编译报错

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/PaddleX#913]
问题类型：模型部署
使用VS2019，cuda11.0，编译生成dll过程中报错如下：

3>model_infer.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl PaddleDeploy::Model::~Model(void)" (__imp_??1Model@PaddleDeploy@@QEAA@XZ)，函数 main 中引用了该符号
3>model_factory.obj : error LNK2001: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl PaddleDeploy::Model::~Model(void)" (__imp_??1Model@PaddleDeploy@@QEAA@XZ)
3>model_factory.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl PaddleDeploy::Model::Init(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Init@Model@PaddleDeploy@@UEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
3>model_factory.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl PaddleDeploy::Model::Predict(class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > const &,class std::vector<struct PaddleDeploy::Result,class std::allocator<struct PaddleDeploy::Result> > *,int)" (?Predict@Model@PaddleDeploy@@UEAA_NAEBV?$vector@VMat@cv@@V?$allocator@VMat@cv@@@std@@@std@@PEAV?$vector@UResult@PaddleDeploy@@V?$allocator@UResult@PaddleDeploy@@@std@@@4@H@Z)
3>model_factory.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl PaddleDeploy::Model::PrePrecess(class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > const &,class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > *,class std::vector<struct PaddleDeploy::ShapeInfo,class std::allocator<struct PaddleDeploy::ShapeInfo> > *,int)" (?PrePrecess@Model@PaddleDeploy@@UEAA_NAEBV?$vector@VMat@cv@@V?$allocator@VMat@cv@@@std@@@std@@PEAV?$vector@UDataBlob@PaddleDeploy@@V?$allocator@UDataBlob@PaddleDeploy@@@std@@@4@PEAV?$vector@UShapeInfo@PaddleDeploy@@V?$allocator@UShapeInfo@PaddleDeploy@@@std@@@4@H@Z)
3>model_factory.obj : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl PaddleDeploy::Model::Infer(class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > const &,class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > *)" (?Infer@Model@PaddleDeploy@@UEAAXAEBV?$vector@UDataBlob@PaddleDeploy@@V?$allocator@UDataBlob@PaddleDeploy@@@std@@@std@@PEAV34@@Z)
3>model_factory.obj : error LNK2001: 无法解析的外部符号 "public: virtual bool __cdecl PaddleDeploy::Model::PostPrecess(class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > const &,class std::vector<struct PaddleDeploy::ShapeInfo,class std::allocator<struct PaddleDeploy::ShapeInfo> > const &,class std::vector<struct PaddleDeploy::Result,class std::allocator<struct PaddleDeploy::Result> > *,int)" (?PostPrecess@Model@PaddleDeploy@@UEAA_NAEBV?$vector@UDataBlob@PaddleDeploy@@V?$allocator@UDataBlob@PaddleDeploy@@@std@@@std@@AEBV?$vector@UShapeInfo@PaddleDeploy@@V?$allocator@UShapeInfo@PaddleDeploy@@@std@@@4@PEAV?$vector@UResult@PaddleDeploy@@V?$allocator@UResult@PaddleDeploy@@@std@@@4@H@Z)
3>model_factory.obj : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: __cdecl PaddleDeploy::Model::Model(void)" (__imp_??0Model@PaddleDeploy@@QEAA@XZ)，函数 "public: static class PaddleDeploy::Model * __cdecl PaddleDeploy::ClasModelRegister::newInstance(void)" (?newInstance@ClasModelRegister@PaddleDeploy@@SAPEAVModel@2@XZ) 中引用了该符号
3>model_factory.obj : error LNK2001: 无法解析的外部符号 "public: __cdecl PaddleDeploy::Model::~Model(void)" (??1Model@PaddleDeploy@@QEAA@XZ)
3>E:\paddle_deploy\build_out\paddle_deploy\Release\model_infer.dll : fatal error LNK1120: 8 个无法解析的外部命令

**Comment by FlyingQianMM** [comment]
生成dll可以参考下我们给出的示例 https://github.com/PaddlePaddle/PaddleX/tree/develop/dygraph/examples/C%23_deploy ，按照示例的步骤，先不改dll接口运行成功之后，再修改生成dll文件

**Comment by SchrodingerLLX** [comment]
我在编译的时候也有类似的问题，cmake不勾选WITH_TENSORRT
2>------ Build started: Project: model_infer, Configuration: Release x64 ------
2>   Creating library F:/projects/PaddleX/dygraph/deploy/cpp/out/paddle_deploy/Release/model_infer.lib and object F:/projects/PaddleX/dygraph/deploy/cpp/out/paddle_deploy/Release/model_infer.exp
2>model_infer.obj : warning LNK4217: locally defined symbol ?PaddleEngineInit@Model@PaddleDeploy@@QEAA_NAEBUPaddleEngineConfig@2@@Z (public: bool __cdecl PaddleDeploy::Model::PaddleEngineInit(struct PaddleDeploy::PaddleEngineConfig const &)) imported in function main
2>model_infer.obj : warning LNK4217: locally defined symbol ?CreateModel@PaddleDeploy@@YAPEAVModel@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z (class PaddleDeploy::Model * __cdecl PaddleDeploy::CreateModel(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)) imported in function main
2>model_infer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl PaddleDeploy::Model::~Model(void)" (__imp_??1Model@PaddleDeploy@@QEAA@XZ) referenced in function main
2>model_factory.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl PaddleDeploy::Model::~Model(void)" (__imp_??1Model@PaddleDeploy@@QEAA@XZ)
2>model_factory.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl PaddleDeploy::Model::Init(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Init@Model@PaddleDeploy@@UEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
2>model_factory.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl PaddleDeploy::Model::Predict(class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > const &,class std::vector<struct PaddleDeploy::Result,class std::allocator<struct PaddleDeploy::Result> > *,int)" (?Predict@Model@PaddleDeploy@@UEAA_NAEBV?$vector@VMat@cv@@V?$allocator@VMat@cv@@@std@@@std@@PEAV?$vector@UResult@PaddleDeploy@@V?$allocator@UResult@PaddleDeploy@@@std@@@4@H@Z)
2>model_factory.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl PaddleDeploy::Model::PrePrecess(class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > const &,class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > *,class std::vector<struct PaddleDeploy::ShapeInfo,class std::allocator<struct PaddleDeploy::ShapeInfo> > *,int)" (?PrePrecess@Model@PaddleDeploy@@UEAA_NAEBV?$vector@VMat@cv@@V?$allocator@VMat@cv@@@std@@@std@@PEAV?$vector@UDataBlob@PaddleDeploy@@V?$allocator@UDataBlob@PaddleDeploy@@@std@@@4@PEAV?$vector@UShapeInfo@PaddleDeploy@@V?$allocator@UShapeInfo@PaddleDeploy@@@std@@@4@H@Z)
2>model_factory.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl PaddleDeploy::Model::Infer(class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > const &,class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > *)" (?Infer@Model@PaddleDeploy@@UEAAXAEBV?$vector@UDataBlob@PaddleDeploy@@V?$allocator@UDataBlob@PaddleDeploy@@@std@@@std@@PEAV34@@Z)
2>model_factory.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl PaddleDeploy::Model::PostPrecess(class std::vector<struct PaddleDeploy::DataBlob,class std::allocator<struct PaddleDeploy::DataBlob> > const &,class std::vector<struct PaddleDeploy::ShapeInfo,class std::allocator<struct PaddleDeploy::ShapeInfo> > const &,class std::vector<struct PaddleDeploy::Result,class std::allocator<struct PaddleDeploy::Result> > *,int)" (?PostPrecess@Model@PaddleDeploy@@UEAA_NAEBV?$vector@UDataBlob@PaddleDeploy@@V?$allocator@UDataBlob@PaddleDeploy@@@std@@@std@@AEBV?$vector@UShapeInfo@PaddleDeploy@@V?$allocator@UShapeInfo@PaddleDeploy@@@std@@@4@PEAV?$vector@UResult@PaddleDeploy@@V?$allocator@UResult@PaddleDeploy@@@std@@@4@H@Z)
2>model_factory.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl PaddleDeploy::Model::Model(void)" (__imp_??0Model@PaddleDeploy@@QEAA@XZ) referenced in function "public: static class PaddleDeploy::Model * __cdecl PaddleDeploy::ClasModelRegister::newInstance(void)" (?newInstance@ClasModelRegister@PaddleDeploy@@SAPEAVModel@2@XZ)
2>F:\projects\PaddleX\dygraph\deploy\cpp\out\paddle_deploy\Release\model_infer.exe : fatal error LNK1120: 7 unresolved externals
2>Done building project "model_infer.vcxproj" -- FAILED.

如果cmake勾选WITH_TENSORRT那么编译的时候会显示myelin64_1.lib的缺失。
3>LINK : fatal error LNK1181: cannot open input file 'C:\Program Files\NVIDIA GPU Computing Toolkit\TensorRT-6.0.1.5\lib\myelin64_1.lib'
3>Done building project "model_infer.vcxproj" -- FAILED.
似乎和预处理器定义PADDLEX_DEPLOY有关系。

**Comment by aiwenzhu** [comment]
你好，还是这个问题，我是用cuda10.2版本的没有出现这个问题，用11.0即使不用tensorrt还是有这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月5日(周一) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 模型部署编译报错 (#913)




 
生成dll可以参考下我们给出的示例 https://github.com/PaddlePaddle/PaddleX/tree/develop/dygraph/examples/C%23_deploy ，按照示例的步骤，先不改dll接口运行成功之后，再修改生成dll文件

**Comment by heliqi** [comment]
1.windows下载的预编译库是都带tensorrt,一定要开启并填写tensorrt的路径。
2.编译dll需要使用paddlex/dygraph/cpp目录下tools/build_lib/Cmake lists.txt。 可以将这个文件拷贝到cpp目录替换生成执行文件的cmakelists。

后续我们会优化下如何编译dll的文档，当前正在整理中。

**Comment by heliqi** [comment]
@SchrodingerLLx
 trt要7.0+版本，6.0版本确实缺少myelin64库 。
你下载预测库压缩包链接或者名字是？

**Comment by SchrodingerLLX** [comment]
> @SchrodingerLLX
> trt要7.0+版本，6.0版本确实缺少myelin64库 。
> 你下载预测库压缩包链接或者名字是？

用的是 cuda10.1_cudnn7_avx_mkl_trt6		paddle_inference.zip	MSVC 2017	CMake v3.17.0	7.6	10.1

**Comment by heliqi** [comment]
那这里的cmakelists有点点问题，没有支持trt6，等下我们修改测试完毕之后更新下github代码。
 你也可以手动改下，在cmakelists中搜索myelin64，将搜索到的都删掉即可。

**Comment by heliqi** [comment]
@SchrodingerLLX 
tensorrt6的报错问题已经修复， 拉最新代码即可。

如果要编译dll，可以直接使用这一份CMakelists 覆盖原来的   ：https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/deploy/cpp/tools/build_lib/CMakeLists.txt

**Comment by aiwenzhu** [comment]
hi 何同学：
&nbsp; &nbsp; 辛苦了，不过这一替换变化很大呀，直接使用cpp下的修改后的cmakelist编译后有model_infer.cpp，现在都没有了，该怎么用哪，我没找到推理函数在哪，我之前使用cuda10.2已经部署好了，现在因为需要换cuda11.0，能不能还按cuda10.2的方式(直接修改的cpp文件加下的cmakelist)生成dll，如果可以我就可以直接用了。
&nbsp; &nbsp;使用替换的cmakelist还出现一个报错：
&nbsp; &nbsp;CMake Error: File E:/paddle_deploy_cuda110/paddleX-cpp/utils/build_lib/Config.cmake.in does not exist.
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/CMakePackageConfigHelpers.cmake:330 (configure_file):
&nbsp; configure_file Problem configuring file
&nbsp;我把Config.cmake.in放在了新建的对应路径下通过了cmake，VS编译paddledeploy通过了，不过不会用


&nbsp; cmake的paddledeploy_libs我填的paddle_inference/paddle/lib对吗，另外除了YAML_BUILD_SHARED_LIBS其它选项我都勾选了是否正确





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleX] 模型部署编译报错 (#913)





 
1.windows下载的预编译库是都带tensorrt,一定要开启并填写tensorrt的路径
 2.编译dll需要使用paddlex/dygraph/cpp目录下tools/build/Cmake lists.txt。 可以将这个文件拷贝到cpp目录替换生成执行文件的cmakelists。
 
后续我们会出如何编译dll的文档，当前正在整理中。

**Comment by heliqi** [comment]
1. dll使用都是一样的，还是按model_infer.cpp里那样使用即可。 你可以参照tools下面的use_lib 编译https://github.com/PaddlePaddle/PaddleX/blob/4c4a1ba1e646687e6e7f36af7e6d89950fe1fa61/dygraph/deploy/cpp/tools/use_lib/CMakeLists.txt#L16          
 PADDLEX_DIR为你编译生成的PaddleDeploy路径
2. 如果你习惯以前的用法， 可以直接改cpp目录下的cmakelist 生成dll，不用替换。替换的好处是你可以使用find_package，不用填写一堆lib 、include目录
3. 替换后的报错修改是对的， 修改目录结构后忘记改build_lib的cmake为tools目录
4. paddledeploy_libs 不能填写， 这个是给生成的dll使用find_package 用的， 参照1里的链接使用
5. ”除了YAML_BUILD_SHARED_LIBS其它选项我都勾选“ 如果编译dll， 不要使用静态编译， 把WITH_STATIC_LIB 给关了

**Comment by aiwenzhu** [comment]
hi 何同学:
&nbsp; 我其实想先按以前的方式直接改cpp下的cmakelist生成dll，不过这种方式的报错就是我最开始提到的错误，这个错误一直不知道什么原因，你提供的方法是替换cmake list，我编译后发现变化较多，如果不替换cmakelist也可解决最开始问题的话，期待回复😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月6日(周二) 晚上11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 模型部署编译报错 (#913)




  
dll使用都是一样的，还是按model_infer.cpp里那样使用即可。 你可以参照tools下面的use_lib 使用 https://github.com/PaddlePaddle/PaddleX/blob/4c4a1ba1e646687e6e7f36af7e6d89950fe1fa61/dygraph/deploy/cpp/tools/use_lib/CMakeLists.txt#L16 

如果你习惯以前的用法， 可以直接改cpp目录下的cmakelist 生成dll，不用替换 

替换后的报错是对的， 修改目录结构忘记改build_lib的cmake了 

paddledeploy_libs 不能填写， 这个是给生成的dll使用find_package 用的， 参照1里的链接使用 

”除了YAML_BUILD_SHARED_LIBS其它选项我都勾选“ 如果编译dll， 不要使用静态编译， 把WITH_STATIC_LIB 给关了

**Comment by heliqi** [comment]
1.  可以修改，之前trt的报错已经修复了，更新下代码即可。 
2. 没有变化很多呀， 都是生成dll，只是dll所在的目录结构变了。 你是不是对dll使用错了？你实际不是想使用dll 而是直接用生成的model_infer.exe可执行文件？

**Comment by aiwenzhu** [comment]
> 1. 可以修改，之前trt的报错已经修复了，更新下代码即可。
> 2. 没有变化很多呀， 都是生成dll，只是dll所在的目录结构变了。 你是不是对dll使用错了？你实际不是想使用dll 而是直接用生成的model_infer.exe可执行文件？

感谢回复：
       不过我的问题不是trt报错，是无法解析的外部符号 "public: virtual bool __cdecl PaddleDeploy::Model::Init， PaddleDeploy::Model::Predict，PaddleDeploy::Model::PrePrecess等好几个无法解析，我按照你说的方法拉了最新的paddlex编译dll，无法解析的外部符号报错已经没了，出现了新的报错：
 LINK : fatal error LNK1104: 无法打开文件“E:\paddle_deploy_cuda110\build_out\paddle_deploy\Release\model_infer.lib”
  该如何解决那？
我到对应目录下也发现model_infer.lib是空的，同时也很好奇为什么之前会出现无法解析的外部符号？

**Comment by aiwenzhu** [comment]
> > 1. 可以修改，之前trt的报错已经修复了，更新下代码即可。
> > 2. 没有变化很多呀， 都是生成dll，只是dll所在的目录结构变了。 你是不是对dll使用错了？你实际不是想使用dll 而是直接用生成的model_infer.exe可执行文件？
> 
> 感谢回复：
> 不过我的问题不是trt报错，是无法解析的外部符号 "public: virtual bool __cdecl PaddleDeploy::Model::Init， PaddleDeploy::Model::Predict，PaddleDeploy::Model::PrePrecess等好几个无法解析，我按照你说的方法拉了最新的paddlex编译dll，无法解析的外部符号报错已经没了，出现了新的报错：
> LINK : fatal error LNK1104: 无法打开文件“E:\paddle_deploy_cuda110\build_out\paddle_deploy\Release\model_infer.lib”
> 该如何解决那？
> 我到对应目录下也发现model_infer.lib是空的，同时也很好奇为什么之前会出现无法解析的外部符号？

已成功生成，谢谢

**Comment by heliqi** [comment]
👌   在最新cmakelist上修改应该是没问题的，出现无法解析的外部符号可能是因为你拉了中间的某次代码，缺少宏。

**Comment by SchrodingerLLX** [comment]
> @SchrodingerLLX
> tensorrt6的报错问题已经修复， 拉最新代码即可。
> 
> 如果要编译dll，可以直接使用这一份CMakelists 覆盖原来的 ：https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/deploy/cpp/tools/build_lib/CMakeLists.txt

问题已经解决了，谢谢

**Comment by aiwenzhu** [comment]
hi 何同学:
&nbsp; 使用paddlex训练的fast rcnn导出权重后部署测试出现这个:fail  to find  arch in  paddledetecion   yaml  file&nbsp; 请问怎么解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月7日(周三) 中午12:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleX] 模型部署编译报错 (#913)




  
可以修改，之前trt的报错已经修复了，更新下代码即可。 

没有变化很多呀， 都是生成dll，只是dll所在的目录结构变了。 你是不是对dll使用错了？

**Comment by edacgq** [comment]
请问一下11.0的库你那边编译出来了吗？  我这边编译有问题 看到可以回复我一下吗？

**Comment by edacgq** [comment]
请问你那边编好了吗？  我这边有问题请教下  我编译没问题，但是调用的时候就报错

**Comment by heliqi** [comment]
看前面描述都编译成功了，我们自己测试也没问题。
你有啥问题的话，把你的问题描述下，重新开个issues提问。这个已经关闭了，你的回复我们可能看不到。

**Comment by qing130** [comment]
> @SchrodingerLLX tensorrt6的报错问题已经修复， 拉最新代码即可。
> 
> 如果要编译dll，可以直接使用这一份CMakelists 覆盖原来的 ：https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/deploy/cpp/tools/build_lib/CMakeLists.txt

这个链接无效了
