### ISSUE TITLE
现在支持C++版本的finetune吗

### ISSUE THREAD

**Issue by woddle** [PaddlePaddle/PaddleX#931]
问题类型：模型训练  
**问题描述**  
支持C++版本的在线finetune吗，可以方便进行客户现场的迁移学习
====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应
我们采用C++进行的部署，有时候需要在客户现场实现在线的finetune。

**Comment by heliqi** [comment]
不支持，目前只能用python进行finetune，然后用c++部署。  我们训练的部分都是python的

**Comment by woddle** [comment]
后期会有计划支持C++ 的finetune吗

**Comment by heliqi** [comment]
暂时没有计划支持。目前主流框架都不支持c++去做训练，  都是python在训练。
