### ISSUE TITLE
模型转瑞芯微rknpu报错

### ISSUE THREAD

**Issue by guoxixiao** [PaddlePaddle/PaddleX#932]
模型转瑞芯微rknpu报错
通过paddlex训练的检测模型，用的yolo3  mobilenetv1，用2.8rc的opt转换工具，转成arm的可以，但是转成rknpu的报错
报错命令：./opt_linux --model_file=__model__ --param_file=__params__ --optimize_out_type=naive_buffer   --optimize_out=./model --valid_targets=rknpu,arm
第一个报错信息：Skip lite_conv_bn_fuse_pass because the target or kernel does not match.
最后一个报错信息：op_with_same_input_output_scale_pass.cc:44 CollectInputOutputScales] Check failed: op_info->HasInputScale(in_var_name):

**Comment by heliqi** [comment]
到paddle-lite上问问，这是他们那边模型转换出问题了。  https://github.com/PaddlePaddle/Paddle-Lite/issues

**Comment by heliqi** [comment]
已转到lite的issues： https://github.com/PaddlePaddle/Paddle-Lite/issues/6425
