### ISSUE TITLE
cpp代码规范建议

### ISSUE THREAD

**Issue by jesen8** [PaddlePaddle/PaddleX#935]
您好，我浪费了一下午的时间在解决一个模型推理结果维度不正确的问题，最终发现是因为输入数据维度搞错了，但不是我的错误，是因为你们开发人员代码不太规范，size，shape  不区分导致的....0.0  所以希望你们关注改进一下...
[具体代码](https://github.com/PaddlePaddle/PaddleX/blob/efa4b2a963abe7b0cbf418b79ee7f4e5153dba8a/deploy/cpp/src/transforms.cpp#L289~L292)
因为python端推理是可以的，输入(1,3,128,256), 输出(1,128,256)，这是一个分割模型，因为cpp端数据输出维度一直是(1,256,128),一开始误以为是python代码导出模型有问题，最后才发现是cpp端输入数据被设置成(1,3,256,128)导致的分割结果也为(1,256,128)，究其原因就是上面的代码段导致的....真难, 别的库也有这个问题
**size = [w, h], shape = [h,w,c]**
这不是各种库都默认的吗....

**Comment by jiangjiajun** [comment]
Hi，很不好意思给你带来了不必要的困扰。

这里指的cpp端输入数据被设置成1, 3, 256, 128具体是指哪部分代码呢？
在你上面给的链接中，代码如下
```
  data->ori_im_size_[0] = im->rows;
  data->ori_im_size_[1] = im->cols;
  data->new_im_size_[0] = im->rows;
  data->new_im_size_[1] = im->cols;
```
记录了原图和最终图的shape信息，即(h, w)

**Comment by jesen8** [comment]
没事儿，大家习惯不一样吧，通常会认为 shape 为(h, w)， size 为(w, h)
