### ISSUE TITLE
2.0中固定随机数复现结果需要如何完成？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleX#939]
以前1.3的时候问过，说是2.0可以了，是下面这样吗？
import random
import paddle.fluid as fluid
seed = 2021
fluid.default_startup_program().random_seed = seed
fluid.default_main_program().random_seed = seed
random.seed(seed)
np.random.seed(seed)
paddle.framework.seed(seed)

**Comment by FlyingQianMM** [comment]
固定随机种子，需要固定两部分：

1. 数据增强中的随机性
例如固定random和np.random的随机种子
PaddleX的数据增强 https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/paddlex/cv/transforms/operators.py https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/paddlex/cv/transforms/batch_operators.py
2. 模型参数的初始化的随机性
这个可以看下paddle.seed https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/seed_cn.html#paddle.seed

以上两部分需要在import paddlex之前先固定好

**Comment by bbbxixixixi** [comment]
> 固定随机种子，需要固定两部分：
> 
> 1. 数据增强中的随机性
>    例如固定random和np.random的随机种子
>    PaddleX的数据增强 https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/paddlex/cv/transforms/operators.py https://github.com/PaddlePaddle/PaddleX/blob/develop/dygraph/paddlex/cv/transforms/batch_operators.py
> 2. 模型参数的初始化的随机性
>    这个可以看下paddle.seed https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/seed_cn.html#paddle.seed
> 
> 以上两部分需要在import paddlex之前先固定好

如果2.0相比1.3没有增加统一的设定api，那如果我用1.3，照上面一样的设定，是不是1.3也能复现结果了？
1.3似乎没有batch_transformer

**Comment by FlyingQianMM** [comment]
目前还没有统一的API来固定随机种子。

1.3版本在import paddlex之前手动固定随机种子也是可以的
