### ISSUE TITLE
Paddlex的dygraph版本跑example中human_segmentation C++版本分割混乱

### ISSUE THREAD

**Issue by woddle** [PaddlePaddle/PaddleX#951]
问题类型：模型部署
**问题描述**  
在paddlex的dygraph版本中，使用C++分割example中human_segmentation人会出现混乱现象。而在paddlex的python版本中没问题，使用的模型都是humanseg_mobile_inference

**Comment by FlyingQianMM** [comment]
paddlex的dygraph版本中暂未提供human_segmentation案例呢，你这是用paddlex 2.0.0跑静态图的模型？

**Comment by woddle** [comment]
是的，我需要自己改造下生成动态图模型吧
