### ISSUE TITLE
C++部署paddleseg分割模型处理速度很慢

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleX#960]
问题类型：模型部署
**问题描述**  
paddleseg2.0 训练的分割模型部署到paddlex，读取视频进行分割平均时间都是800ms左右，除开后处理和预处理，单独预测也要300ms，太慢了
同样的视频文件为什么我直接用paddleseg的静态图版本部署C++预测时间只需要30ms左右。
========================  
这是静态图里面C++部署用的配置
        USE_GPU : 1
        USE_PR : 0
        MODEL_PATH : "ladel_model"
        MODEL_FILENAME : "__model__"
        PARAMS_FILENAME : "__params__"
        EVAL_CROP_SIZE : (256, 256)
        MEAN : [0.5, 0.5, 0.5]
        STD : [0.5, 0.5, 0.5]
        IMAGE_TYPE : "rgb"
        NUM_CLASSES : 2
        CHANNELS : 3
        PRE_PROCESSOR : "SegPreProcessor"
        PREDICTOR_MODE : "ANALYSIS"
        BATCH_SIZE : 1
请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。
使用paddle 2.0

**Comment by heliqi** [comment]
可能是动态图的原因，底层推理用的是一个引擎，paddlex不会慢，反而在预处理会快。 有试过用paddlex部署静态图版本模型么？ 
动态图和静态图分别用的是什么模型？
