### ISSUE TITLE
paddlex恢复训练报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleX#962]
问题类型：模型训练  

**PaddleX版本**  
paddlex2.0.0.rc3

**问题描述**  
模型恢复训练时报如下错误：

creating index...
index created!
2021-07-17 08:48:19 [ERROR]	pretrain_weights and resume_checkpoint cannot be set simultaneously.
An exception has occurred, use %tb to see the full traceback.
SystemExit: -1
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3273: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

====================  
训练模块的代码如下：
model.train(
    num_epochs=270,
    train_dataset=train_dataset,
    train_batch_size=8,
    eval_dataset=eval_dataset,
    learning_rate=0.005 / 12,
    lr_decay_epochs=[205, 235, 250],
    save_interval_epochs=1,
    resume_checkpoint='output/ppyolov2_r50vd_dcn/epoch_133',
    save_dir='output/ppyolov2_r50vd_dcn')

**Comment by heliqi** [comment]
同时设置了pretrain_weights and resume_checkpoint参数，去掉resum.参数试试

**Comment by thomas-yanxin** [comment]
我不是想恢复训练吗？把resume_checkpoint参数去掉怎么恢复训练？
| |
左右
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年7月17日 ***@***.***> 写道：

同时设置了pretrain_weights and resume_checkpoint参数，去掉resum.参数试试

**Comment by heliqi** [comment]
恢复训练的话只设置checkpoint 即可，不需要设置预训练权重，需要把pretrain weight设置为None
