### ISSUE TITLE
python模型部署接口问题

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleX#963]
问题类型：模型部署
**问题描述**  
![image](https://user-images.githubusercontent.com/78856426/126056819-9328f417-81aa-4a7e-8dde-1d8795dd0c22.png)
python paddlex2.0.0rc3按照官方文档python部署方式部署发现报错paddlex没有deploy模块
========================

**Comment by heliqi** [comment]
1.3训的模型，安装1.3.11版本paddlex，可以使用load_model和paddlex.deploy进行加载。 2.0训练的模型，安装2.0的paddlex，使用load_model进行加载
