### ISSUE TITLE
C++部署分割模型，启动tensorRT后效率问题

### ISSUE THREAD

**Issue by sosan-nian** [PaddlePaddle/PaddleX#977]
问题类型：模型部署
**问题描述**  
demo编译好后运行同样的模型和视频
不启用tensorRT 单帧处理时间为
![图片](https://user-images.githubusercontent.com/82444943/126581300-1b943b85-e81b-4c17-8484-7ebdb3391f92.png)
启用tensorRT FP16后单帧处理时间
![图片](https://user-images.githubusercontent.com/82444943/126581544-a8b64940-e878-43ee-8f51-8cfd7cb47c50.png)
效率无明显提升
此外当使用INT8时直接报错，如下图
![图片](https://user-images.githubusercontent.com/82444943/126581720-ac59c6fa-4f0f-4032-ba7e-6ae8efd00c31.png)

========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by heliqi** [comment]
1. trt不一定会加速很多。 可能是模型不大、跑在trt上的子图很小很杂等原因， 你可以调大subgraph_size参数看看
2.使用int8是需要先对模型进行量化， 具体请参考这个文档的 int8量化预测 ： https://paddleinference.paddlepaddle.org.cn/master/optimize/paddle_trt.html
