### ISSUE TITLE
替换model_infer.cpp后编译报错

### ISSUE THREAD

**Issue by BuLuoPiaoYu** [PaddlePaddle/PaddleX#982]
错误如下：

![image](https://user-images.githubusercontent.com/54087448/126746756-1373bec8-1bf5-45d9-a7f9-45245fcad655.png)

不过如果在cpp里加上main函数就不报错，但是会在C#调用时引发“无法读取或写入受保护的内存”异常

**Comment by heliqi** [comment]
编译链接库是不加main函数的。C#调用可参考这个文档 https://github.com/PaddlePaddle/PaddleX/tree/develop/examples/C%23_deploy

**Comment by BuLuoPiaoYu** [comment]
只用Cpu运行的话，需要修改哪些东西呢

**Comment by heliqi** [comment]
只用cpu运行的话
1. 需要下载只有cpu的预测库 https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html
2. 编译时关掉gpu选项， 其它就按上面的C#编译文档即可
