### ISSUE TITLE
模型训练时GPU没有启用

### ISSUE THREAD

**Issue by libingbingdev** [PaddlePaddle/PaddleX#985]
问题类型：模型训练  

**环境版本**  
Paddlex==1.3.7
Paddlepaddle-gpu==2.1.1.post112
系统：windows10
显卡：2x GeForce RTX 3080
驱动程序版本：461.37
CUDA 版本：11.2
CUDNN 版本：8.1.1

**问题描述**  
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
代码里设置使用显卡0或者1，模型运行时，使用"nvidia-smi"查看显卡使用率都是0%，GPU没有启用
![捕获](https://user-images.githubusercontent.com/42804898/126775963-091dc6ed-f412-4650-8515-6a1ad058979c.PNG)

![捕获1](https://user-images.githubusercontent.com/42804898/126775988-d3405e10-c350-4881-995e-a0299a6146ee.PNG)

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by will-jl944** [comment]
1. 如需使用静态图版本，建议`pip install paddlex -U`升级至1.3.11（静态图最新版本），并搭配paddle 1.8或2.0版本使用。如需使用动态图版本，可以通过`pip install paddlex==2.0.0rc4`安装我们新发布的paddlex动态图版本。
2. 看到0号显卡的内存是有占用的。模型运行时数据增强以及预处理是在cpu上进行的，因此gpu利用率会受到模型大小、输入图像大小、batch size大小等因素的影响。可以查看一下`nvidia-smi`下方显示的进程中是否有你在运行的脚本，或者多运行几次`nvidia-smi`指令看一下使用率是否一直是0。
3. 如需指定显卡，请确认在`import paddlex`之前通过`os.environ['CUDA_VISIBLE_DEVICES']`指定。
