### ISSUE TITLE
C# 下调用model_infer.dll报错

### ISSUE THREAD

**Issue by BuLuoPiaoYu** [PaddlePaddle/PaddleX#987]
C++直接运行没有问题，但是编译成dll文件后，给C#调用时发生错误。
![image](https://user-images.githubusercontent.com/54087448/126938603-3424bba2-f43c-4923-879f-a1b1cf1c00ac.png)

**Comment by heliqi** [comment]
你编译dll、以及C#调用dll时都需要链接TensorRT；如果C#调用链接库时不想链接tensorrt，你需要静态编译生成链接库，而不是动态编译生成dll

**Comment by BuLuoPiaoYu** [comment]
> 你编译dll、以及C#调用dll时都需要链接TensorRT；如果C#调用链接库时不想链接tensorrt，你需要静态编译生成链接库，而不是动态编译生成dll

可是根据提示这个Tensorrt不是可以忽略的吗，难道这个错误 “Load symbol getPluginRegistry faild.” 是因为tensorrt吗？

**Comment by cjj66ccff** [comment]
楼主后面解决了吗
