### ISSUE TITLE
T0004 erro

### ISSUE THREAD

**Issue by 827346462** [PaddlePaddle/PaddleX#993]
问题类型：模型训练  

**PaddleX版本**  
2.1.1
您使用的PaddleX版本
![image](https://user-images.githubusercontent.com/50097546/127085790-776c2541-1dfc-4c9c-a7eb-654e53a473a1.png)
我电脑的版本 cuda11.2 
**问题描述**  
![image](https://user-images.githubusercontent.com/50097546/127085658-ff769dd7-ff01-4c7d-81e5-b7d52f47ae50.png)

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

**Comment by lailuboy** [comment]
看起来是你用的30系列显卡，可以使用如下最新的rc4版本看是否可以，支持30系列和最新paddle2.1.1，windows：https://bj.bcebos.com/paddlex/PaddleX_30X0/PaddleX2.0.0rc2_windows10.zip，
linux：https://bj.bcebos.com/paddlex/2.0//paddlex_gui_ubuntu1804_amd64_v2.0.0rc2.tar.gz
