### ISSUE TITLE
是不是paddleCls训练得到的模型无法使用paddlex来导出和部署？？？

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleX#994]
问题类型：模型部署
**问题描述**  
我在paddleCls代码库中，训练了一个分类模型，我部署的时候采用的是paddlex用于部署，然后需要导出模型，就按照paddlex的导出方式来导出，问题是paddlex的导出需要训练模型有3个文件（model.pdparams、model.pdopt和model.yml），问题是我用paddleCls训练出来的模型只有model.pdparams和model.pdopt，那么问题来了，是不是说paddleCls训练得到的模型无法使用paddlex来导出和部署？
========================  

请在这里描述您在使用过程中的问题，说明您的部署环境，部署需求，模型类型和应用场景等，便于开发人员快速响应。

**Comment by heliqi** [comment]
导出inference模型后可以用paddlex部署，当前只支持cpp部署，具体请参考文档： https://github.com/PaddlePaddle/PaddleX/blob/develop/deploy/cpp/docs/models/paddleclas.md
