### ISSUE TITLE
paddlex-gui 目标检测训练模型时候图像尺寸的问题

### ISSUE THREAD

**Issue by aaaaalun** [PaddlePaddle/PaddleX#996]
问题类型：模型训练  

**PaddleX版本**  
您使用的PaddleX版本

**问题描述**  

====================  
请在这里描述您在使用过程中的问题，如模型训练出错，建议贴上模型训练代码，以便开发人员分析，并快速响应

简单说一下
1. 我使用的是paddlex-gui的
2. 我使用的是目标检测模型 ppyolo+mobilev3_large出了问题，问题后面补充。
3. 我的图像是2592*1944的500w的像素图像，标注和图像已经用了其他fasterrcnn训练成功，标注等并无问题。
4. 在2点的基础上，因为图像本身不等比，但是ppyolo需要等比图像，开始用608*608的尺寸训练出来没有问题，mAP达到了96，但是想到图像已经resize了，肯定损失了精度，那我就换成1920*1920的尺寸重新训练，此时模型收敛了，但是mAP却只有20，我不明白为什么？
5. 最后一个问题，我该如何去设置这个图像尺寸？假设训练时候图像是608*608，我传入32*32或者2592*1944的时候，他都会内部直接resize到608*608是吗？我该怎么样才能保证精度又保证速度呢？

**Comment by will-jl944** [comment]
> 4\. 在2点的基础上，因为图像本身不等比，但是ppyolo需要等比图像，开始用608_608的尺寸训练出来没有问题，mAP达到了96，但是想到图像已经resize了，肯定损失了精度，那我就换成1920_1920的尺寸重新训练，此时模型收敛了，但是mAP却只有20，我不明白为什么？

ppyolo不要求图像本身等比，只需输入的长和宽都为32的倍数即可。
是否损失了精度要看数据集中目标尺寸大小。
使用1920x1920的输入训练mAP不理想的可能原因比较多。我们给出的默认anchor尺寸是coco数据集上聚类得出的，可能并不适用于你的大尺寸数据集，后期我们会提供anchor尺寸聚类脚本。另外模型收敛并不一定意味着模型已经达到了最优点，也可能是学习率衰减得很小了。

> 5\. 最后一个问题，我该如何去设置这个图像尺寸？假设训练时候图像是608_608，我传入32_32或者2592_1944的时候，他都会内部直接resize到608_608是吗？我该怎么样才能保证精度又保证速度呢？

ppyolo不含全连接层，不要求网络输入尺寸唯一，图像尺寸为32（即2^5）的倍数即可，训练和推理是都是如此，因为网络会对输入下采样5次。
训练过程中建议像我们给出的tutorial一样使用BatchRandomResize引入多尺度训练。

**Comment by aaaaalun** [comment]
感谢您的回答，我正好看到了相关的课程，我学习后再来update一下这里
