### ISSUE TITLE
“立即切分”按钮显示不正常

### ISSUE THREAD

**Issue by ucsk** [PaddlePaddle/PaddleX#997]
问题类型：PaddleX可视化客户端  

**PaddleX GUI版本**  
1.1.7

**问题描述**  
Windows10 下高分屏，界面显示比较模糊。
对PaddleX进行【兼容性】->【更改高DPI设置】后，数据集导入界面的显示出现异常。

===================================  
【新建数据集】->【数据分析】中的 **立即切分** 按钮显示不正常。

![image](https://user-images.githubusercontent.com/53417456/127330833-7eb91771-153d-40dd-bbe0-2793dd5efcd7.png)

![image](https://user-images.githubusercontent.com/53417456/127330954-4469a107-9564-4e96-8e75-b30c69f59cfd.png)

**Comment by lailuboy** [comment]
在系统显示属性中把放大选项设置为100%即可
